Repository celeritas-project/celeritas, pull requests merged in 2020-11, with the labels that each got.

#63 Add element selection sampler
  scripts/build/vostok.cmake
  scripts/build/vostok.sh
  scripts/build/yuri.cmake
  scripts/dev/celeritas-gen.py
  scripts/dev/env/celeritas-darwin.yaml
  scripts/dev/install-spack.sh
  src/base/Span.hh
  src/physics/material/ElementSelector.hh
  src/physics/material/ElementSelector.i.hh
  src/physics/material/MaterialParams.cc
  src/physics/material/MaterialParams.hh
  test/CMakeLists.txt
  test/gtest/detail/Macros.hh
  test/physics/material/ElementSelector.test.cc
  test/physics/material/Material.test.cc
Labels: physics

#65 Fix designation of ElementSelector test as a host test
  test/CMakeLists.txt
Labels: bug, infrastructure

#78 Add "not reachable" macros
  app/geant-exporter/GeantPhysicsTableWriterHelper.hh
  app/geant-exporter/geant-exporter.cc
  src/base/Assert.hh
  src/base/DeviceAllocation.nocuda.cc
  src/base/Macros.hh
  src/base/Memory.nocuda.cc
  src/geometry/detail/VGNavStateStore.nocuda.cc
Labels: infrastructure

#80 Add quick and dirty raytrace visualization script
  app/demo-rasterizer/simple-driver.py
  app/demo-rasterizer/visualize.py
Labels: geometry

#79 Extend non-numeric quantity, enable tests and tweak annihilation process
  app/demo-interactor/demo-interactor.cc
  app/demo-interactor/host-demo-interactor.cc
  scripts/dev/celeritas-gen-hackathon.py
  src/base/Quantity.hh
  src/physics/base/Interaction.hh
  src/physics/em/EPlusGGInteractor.hh
  src/physics/em/EPlusGGInteractor.i.hh
  test/CMakeLists.txt
  test/base/Quantity.test.cc
  test/physics/InteractorHostTestBase.cc
  test/physics/base/Particle.test.cc
  test/physics/em/BetheBlochInteractor.test.cc
  test/physics/em/BremRelInteractor.test.cc
  test/physics/em/EPlusGGInteractor.test.cc
  test/physics/em/KleinNishinaInteractor.test.cc
  test/physics/em/LivermoreInteractor.test.cc
  test/physics/em/MollerBhabhaInteractor.test.cc
  test/physics/em/RayleighInteractor.test.cc
  test/physics/em/UrbanInteractor.test.cc
  test/physics/em/WentzelInteractor.test.cc
Labels: physics

#76 Add logger
  app/demo-interactor/demo-interactor.cc
  app/demo-interactor/host-demo-interactor.cc
  app/demo-rasterizer/RDemoRunner.cc
  app/demo-rasterizer/demo-rasterizer.cc
  app/geant-exporter/geant-exporter.cc
  src/CMakeLists.txt
  src/base/Assert.hh
  src/base/ColorUtils.cc
  src/comm/Communicator.hh
  src/comm/Communicator.mpi.cc
  src/comm/Communicator.nompi.cc
  src/comm/Logger.cc
  src/comm/Logger.hh
  src/comm/LoggerTypes.cc
  src/comm/LoggerTypes.hh
  src/comm/MpiTypes.hh
  src/comm/detail/LoggerMessage.cc
  src/comm/detail/LoggerMessage.hh
  src/geometry/GeoParams.cc
  test/CMakeLists.txt
  test/comm/Communicator.test.cc
  test/comm/Logger.test.cc
  test/gtest/detail/ParallelHandler.cc
Labels: infrastructure

#73 Add element scratch space and add to interactor test
  src/CMakeLists.txt
  src/physics/material/MaterialParams.cc
  src/physics/material/MaterialParamsPointers.hh
  src/physics/material/MaterialStatePointers.hh
  src/physics/material/MaterialStateStore.cc
  src/physics/material/MaterialStateStore.hh
  src/physics/material/MaterialTrackView.hh
  src/physics/material/MaterialTrackView.i.hh
  test/physics/InteractorHostTestBase.cc
  test/physics/InteractorHostTestBase.hh
  test/physics/em/BremRelInteractor.test.cc
  test/physics/material/Material.test.cc
  test/physics/material/Material.test.cu
Labels: material
