Repository celeritas-project/celeritas, pull requests merged in 2020-09, with the labels that each got.

#40 Add geometry raytrace test app
  CMakeLists.txt
  app/CMakeLists.txt
  app/demo-rasterizer/ImageIO.cc
  app/demo-rasterizer/ImageIO.hh
  app/demo-rasterizer/ImagePointers.hh
  app/demo-rasterizer/ImageStore.cc
  app/demo-rasterizer/ImageStore.hh
  app/demo-rasterizer/ImageTrackView.hh
  app/demo-rasterizer/ImageTrackView.i.hh
  app/demo-rasterizer/RDemoKernel.cu
  app/demo-rasterizer/RDemoKernel.hh
  app/demo-rasterizer/RDemoRunner.cc
  app/demo-rasterizer/RDemoRunner.hh
  app/demo-rasterizer/demo-rasterizer.cc
  app/demo-rasterizer/simple-driver.py
  scripts/build/emmet.cmake
  src/base/Assert.hh
  src/base/ColorUtils.cc
  src/base/DeviceVector.hh
  src/geometry/GeoParams.cc
  src/geometry/GeoParams.hh
  src/geometry/GeoParamsPointers.hh
  test/geometry/data/lariat.gdml
  test/geometry/data/slabsGeometry.gdml
Labels: enhancement, geometry

#45 Fix missing JSON target and update formatting from old code
  app/CMakeLists.txt
  scripts/dev/celeritas-gen.py
  src/base/Interpolator.hh
  src/base/Interpolator.i.hh
  src/base/SoftEqual.hh
  src/base/Types.hh
  src/base/detail/InterpolatorTraits.hh
  src/random/distributions/BernoulliDistribution.hh
  src/random/distributions/GenerateCanonical.hh
  src/random/distributions/IsotropicDistribution.hh
  src/random/distributions/RadialDistribution.hh
  src/random/distributions/UniformRealDistribution.hh
  test/base/Interpolator.test.cc
Labels: infrastructure

#41 Add host/device compatible RNG
  src/random/cuda/RngEngine.cuh
  src/random/cuda/RngEngine.i.cuh
  src/random/cuda/RngStatePointers.hh
  test/random/cuda/RngEngine.test.cu
Labels: infrastructure

#47 Event reader
  CMakeLists.txt
  scripts/build/emmet.cmake
  src/CMakeLists.txt
  src/io/EventReader.cc
  src/io/EventReader.hh
  src/physics/base/ParticleParams.i.hh
  src/physics/base/Primary.hh
  src/physics/base/Units.hh
  src/sim/Types.hh
  test/CMakeLists.txt
  test/io/EventReader.test.cc
  test/io/data/event-record.hepevt
  test/io/data/event-record.hepmc2
  test/io/data/event-record.hepmc3
Labels: simulation
