Repository celeritas-project/celeritas, pull requests merged in 2021-05, with the labels that each got.

#224 Update dependencies and copyright info
  README.md
Labels: documentation

#225 Document and improve failure mode for collections in cu code
  src/base/Collection.hh
  src/base/CollectionStateStore.hh
  src/base/detail/CollectionImpl.hh
Labels: infrastructure

#226 Remove device-only exclusions
  app/demo-interactor/KNDemoKernel.hh
  src/base/Assert.hh
  src/base/Collection.hh
  src/base/CollectionStateStore.hh
  src/base/KernelParamCalculator.cuda.hh
  src/base/NumericLimits.hh
  src/base/OpaqueId.hh
  src/base/StackAllocatorInterface.hh
  src/base/TypeDemangler.cc
  src/base/detail/CollectionImpl.hh
  src/field/FieldDriver.i.hh
  src/field/RungeKuttaStepper.i.hh
  src/geometry/GeoInterface.hh
  src/geometry/GeoParams.cc
  src/geometry/detail/VGNavCollection.cc
  src/geometry/detail/VGNavCollection.hh
  src/io/RootImporter.hh
  src/io/RootImporter.noroot.cc
  src/physics/base/CutoffView.hh
  src/physics/base/Interaction.hh
  src/physics/base/PDGNumber.hh
  src/physics/base/ParticleInterface.hh
  src/physics/base/ParticleTrackView.i.hh
  src/physics/base/PhysicsInterface.hh
  src/physics/em/AtomicRelaxationParams.cc
  src/physics/em/RayleighModel.hh
  src/physics/em/detail/BetheHeitlerInteractor.i.hh
  src/physics/em/detail/RayleighInteractor.hh
  src/physics/em/detail/SBEnergyDistribution.hh
  src/physics/em/detail/SBPositronXsCorrector.i.hh
  src/physics/material/MaterialInterface.hh
  src/random/distributions/GenerateCanonical.i.hh
  src/random/distributions/ReciprocalDistribution.hh
  src/random/distributions/ReciprocalDistribution.i.hh
  src/random/distributions/UniformRealDistribution.hh
  src/random/distributions/UniformRealDistribution.i.hh
  src/sim/TrackInitializerInterface.hh
  test/base/Collection.test.cc
  test/io/RootImporter.test.cc
  test/random/distributions/ReciprocalDistribution.test.cc
Labels: infrastructure

#227 Demo loop updates
  app/CMakeLists.txt
  app/demo-loop/KernelUtils.hh
  app/demo-loop/KernelUtils.i.hh
  app/demo-loop/LDemoInterface.hh
  app/demo-loop/LDemoKernel.cu
  app/demo-loop/LDemoKernel.hh
  app/demo-loop/LDemoParams.cc
  app/demo-loop/LDemoParams.hh
  app/demo-loop/LDemoRun.cc
  app/demo-loop/simple-driver.py
  app/geant-exporter/geant-exporter-cat.cc
  src/CMakeLists.txt
  src/base/Collection.hh
  src/base/Collection.i.hh
  src/base/NumericLimits.hh
  src/base/TypeDemangler.cc
  src/field/FieldDriver.i.hh
  src/geometry/GeoMaterialView.hh
  src/physics/base/PhysicsParams.cc
  src/physics/grid/ValueGridBuilder.cc
  src/random/RngParams.hh
  src/sim/SimInterface.hh
  src/sim/SimStateStore.cc
  src/sim/SimStateStore.hh
  src/sim/SimTrackView.hh
  src/sim/SimTrackView.i.hh
  src/sim/StateStore.cc
  src/sim/StateStore.hh
  src/sim/TrackInitializerInterface.hh
  src/sim/TrackInterface.hh
  src/sim/detail/SimStateInit.cu
  src/sim/detail/SimStateInit.hh
  src/sim/detail/SimStateInit.nocuda.cc
  test/geometry/GeoMaterial.test.cc
  test/physics/grid/ValueGridBuilder.test.cc
  test/sim/TrackInitializerStore.test.cu
Labels: integration

#221 Magnetic Field Propagator (#49)
  src/field/FieldDriver.hh
  src/field/FieldDriver.i.hh
  src/field/FieldInterface.hh
  src/field/FieldParamsPointers.hh
  src/field/FieldPropagator.hh
  src/field/FieldPropagator.i.hh
  src/field/FieldUtils.i.hh
  src/field/MagField.i.hh
  src/field/MagFieldEquation.hh
  src/field/MagFieldEquation.i.hh
  src/field/RungeKuttaStepper.hh
  src/field/RungeKuttaStepper.i.hh
  src/geometry/GeoTrackView.hh
  src/geometry/GeoTrackView.i.hh
  test/CMakeLists.txt
  test/field/FieldDriver.test.cc
  test/field/FieldDriver.test.hh
  test/field/FieldPropagator.test.cc
  test/field/FieldPropagator.test.cu
  test/field/FieldPropagator.test.hh
  test/field/FieldTestBase.hh
  test/field/data/fieldTest.gdml
Labels: propagation

#228 Clang and documentation fixes
  app/CMakeLists.txt
  app/demo-loop/LDemoParams.cc
  interface/celeritas.i
  src/io/ImportParticle.hh
  src/physics/base/PhysicsTrackView.i.hh
  test/geometry/GeoMaterial.test.cc
  test/io/RootImporter.test.cc
  test/physics/em/ImportedProcesses.test.cc
Labels: infrastructure

#231 Add single-material cms mock-up geometry to the demo-loop
  app/CMakeLists.txt
  app/demo-loop/simple-driver.py
  app/demo-loop/simple_cms.gdml
Labels: geometry, integration

#237 Propagate GTEST_COLOR environment to ColorUtils setting
  src/base/ColorUtils.cc
Labels: enhancement, infrastructure

#236 Complete positron annihilation and gamma conversion processes
  src/base/DeviceAllocation.cc
  src/physics/base/PhysicsParams.cc
  src/physics/em/ComptonProcess.hh
  src/physics/em/EPlusAnnihilationProcess.cc
  src/physics/em/EPlusAnnihilationProcess.hh
  src/physics/em/EPlusGGModel.cc
  src/physics/em/GammaConversionProcess.cc
  src/physics/em/GammaConversionProcess.hh
  src/physics/grid/ValueGridBuilder.cc
  src/physics/grid/ValueGridBuilder.hh
  test/CMakeLists.txt
  test/base/DeviceAllocation.test.cc
  test/physics/base/Physics.test.cc
  test/physics/em/BetheHeitler.test.cc
  test/physics/em/ImportedProcesses.test.cc
Labels: physics

#240 Refactor track initialization code
  app/demo-loop/LDemoInterface.hh
  src/CMakeLists.txt
  src/random/RngParams.hh
  src/sim/ParamStore.cc
  src/sim/ParamStore.hh
  src/sim/SimInterface.hh
  src/sim/StateStore.cc
  src/sim/StateStore.hh
  src/sim/TrackInitInterface.cc
  src/sim/TrackInitInterface.hh
  src/sim/TrackInitParams.cc
  src/sim/TrackInitParams.hh
  src/sim/TrackInitUtils.cc
  src/sim/TrackInitUtils.hh
  src/sim/TrackInitializerInterface.hh
  src/sim/TrackInitializerStore.hh
  src/sim/TrackInterface.hh
  src/sim/detail/InitializeTracks.cu
  src/sim/detail/InitializeTracks.hh
  src/sim/detail/InitializeTracks.nocuda.cc
  test/CMakeLists.txt
  test/sim/TrackInit.test.cc
  test/sim/TrackInit.test.cu
  test/sim/TrackInit.test.hh
Labels: simulation

#239 Fix CUDA relocatable device code linking
  CMakeLists.txt
  app/CMakeLists.txt
  cmake/CeleritasAddTest.cmake
  cmake/CeleritasUtils.cmake
  interface/CMakeLists.txt
  src/CMakeLists.txt
  test/CMakeLists.txt
Labels: bug, infrastructure

#238 Use static libs for CI ndebug build
  scripts/build/docker-cuda-ndebug.sh
  src/field/FieldDriver.hh
  src/field/FieldPropagator.hh
  src/field/RungeKuttaStepper.hh
  src/physics/em/detail/BetheHeitlerInteractor.hh
  src/physics/em/detail/BhabhaEnergyDistribution.hh
  src/physics/em/detail/LivermorePEInteractor.hh
  src/physics/em/detail/MollerEnergyDistribution.hh
  src/physics/em/detail/RayleighInteractor.hh
  src/physics/em/detail/RayleighInteractor.i.hh
  src/physics/em/detail/SBPositronXsCorrector.hh
Labels: infrastructure

#245 Moller-Bhabha fix
  src/physics/em/detail/MollerBhabhaInteractor.i.hh
  test/physics/em/MollerBhabha.test.cc
Labels: bug, physics
