Repository celeritas-project/celeritas, pull requests merged in 2021-11, with the labels that each got.

#303 Allow multiple VecGeom navigation states on host
  app/demo-loop/simple-driver.py
  src/base/CollectionBuilder.hh
  src/base/CollectionBuilder.i.hh
  src/geometry/detail/VGNavCollection.cc
  src/geometry/detail/VGNavCollection.hh
  src/physics/em/detail/SeltzerBergerInteractor.i.hh
Labels: geometry

#302 Update `geant-exporter` physics list
  app/CMakeLists.txt
  app/geant-exporter/BremsstrahlungProcess.cc
  app/geant-exporter/BremsstrahlungProcess.hh
  app/geant-exporter/ImportProcessConverter.cc
  app/geant-exporter/PhysicsList.cc
  app/geant-exporter/PhysicsList.hh
  app/geant-exporter/geant-exporter.cc
  scripts/build/stognini.cmake
  src/io/ImportProcess.cc
  src/io/ImportProcess.hh
  test/io/RootImporter.test.cc
  test/io/data/geant-exporter-data.root
  test/physics/base/CutoffParams.test.cc
  test/physics/base/Particle.test.cc
Labels: physics

#304 Fix secondary cutoffs
  app/demo-interactor/HostKNDemoRunner.cc
  app/demo-interactor/KNDemoKernel.cu
  app/demo-loop/KernelUtils.hh
  app/demo-loop/KernelUtils.i.hh
  app/demo-loop/LDemoKernel.cc
  app/demo-loop/LDemoKernel.cu
  src/physics/base/CutoffData.hh
  src/physics/base/CutoffParams.cc
  src/physics/base/CutoffParams.hh
  src/physics/base/CutoffView.hh
  src/physics/base/CutoffView.i.hh
  src/physics/em/detail/KleinNishinaInteractor.hh
  src/physics/em/detail/KleinNishinaInteractor.i.hh
  test/physics/InteractorHostTestBase.cc
  test/physics/base/CutoffParams.test.cc
  test/physics/em/EnergyLossDistribution.test.cc
  test/physics/em/KleinNishina.test.cc
  test/physics/em/MollerBhabha.test.cc
Labels: physics

#306 Add static surface actions for ORANGE
  src/base/Array.hh
  src/orange/surfaces/SurfaceAction.hh
  src/orange/surfaces/detail/SurfaceAction.hh
  test/orange/surfaces/GeneralQuadric.test.cc
  test/orange/surfaces/Sphere.test.cc
  test/orange/surfaces/SurfaceAction.test.cc
Labels: infrastructure, geometry

#301 Improve CI stability with larger TMPDIR and reduced parallelism
  .jenkins
  app/CMakeLists.txt
  scripts/build/docker-cuda-ndebug.sh
  scripts/build/docker-cuda.sh
Labels: infrastructure

#308 Allow arbitrary number of tracks on CPU
  app/demo-loop/simple-driver.py
  src/physics/em/detail/BetheHeitlerLauncher.hh
  src/physics/em/detail/LivermorePELauncher.hh
  src/physics/em/detail/MollerBhabhaLauncher.hh
Labels: integration

#307 Orange: add volume definition and JSON I/O for surface/volume
  app/demo-loop/simple-cms.json
  app/demo-loop/simple-cms.org.omn
  scripts/dev/celeritas-gen.py
  src/CMakeLists.txt
  src/base/Collection.hh
  src/io/EventReader.cc
  src/orange/Data.hh
  src/orange/Types.hh
  src/orange/construct/SurfaceInput.hh
  src/orange/construct/SurfaceInputIO.json.cc
  src/orange/construct/SurfaceInputIO.json.hh
  src/orange/construct/SurfaceInserter.cc
  src/orange/construct/SurfaceInserter.hh
  src/orange/construct/VolumeInput.hh
  src/orange/construct/VolumeInputIO.json.cc
  src/orange/construct/VolumeInputIO.json.hh
  src/orange/construct/VolumeInserter.cc
  src/orange/construct/VolumeInserter.hh
  test/CMakeLists.txt
  test/orange/construct/SurfaceInserter.test.cc
  test/orange/construct/VolumeInserter.test.cc
  test/orange/data/.gitignore
  test/orange/data/five-volumes.ipynb
  test/orange/data/five-volumes.org.json
  test/orange/data/five-volumes.org.omn
Labels: geometry

#309 Diagnostic for distribution of number of steps per track
  app/CMakeLists.txt
  app/demo-loop/KernelUtils.hh
  app/demo-loop/KernelUtils.i.hh
  app/demo-loop/LDemoIO.cc
  app/demo-loop/LDemoIO.hh
  app/demo-loop/LDemoKernel.cc
  app/demo-loop/LDemoKernel.cu
  app/demo-loop/LDemoRun.i.hh
  app/demo-loop/diagnostic/Diagnostic.hh
  app/demo-loop/diagnostic/EnergyDiagnostic.cc
  app/demo-loop/diagnostic/EnergyDiagnostic.cu
  app/demo-loop/diagnostic/EnergyDiagnostic.hh
  app/demo-loop/diagnostic/EnergyDiagnostic.i.hh
  app/demo-loop/diagnostic/ParticleProcessDiagnostic.cc
  app/demo-loop/diagnostic/ParticleProcessDiagnostic.cu
  app/demo-loop/diagnostic/ParticleProcessDiagnostic.hh
  app/demo-loop/diagnostic/ParticleProcessDiagnostic.i.hh
  app/demo-loop/diagnostic/StepDiagnostic.cc
  app/demo-loop/diagnostic/StepDiagnostic.cu
  app/demo-loop/diagnostic/StepDiagnostic.hh
  app/demo-loop/diagnostic/StepDiagnostic.i.hh
  app/demo-loop/diagnostic/TrackDiagnostic.cc
  app/demo-loop/diagnostic/TrackDiagnostic.cu
  app/demo-loop/diagnostic/TrackDiagnostic.hh
Labels: detectors

#311 Improve gtest macros and internals
  src/CMakeLists.txt
  src/base/Repr.hh
  src/base/TypeDemangler.hh
  src/base/detail/ReprImpl.cc
  src/base/detail/ReprImpl.hh
  test/CMakeLists.txt
  test/base/Repr.test.cc
  test/gtest/Test.cc
  test/gtest/detail/Macros.cc
  test/gtest/detail/Macros.hh
  test/gtest/detail/Macros.i.hh
  test/gtest/detail/NonMasterResultPrinter.cc
  test/gtest/detail/ParallelHandler.cc
  test/gtest/detail/PrintableValueTraits.hh
  test/gtest/detail/TestMain.cc
  test/gtest/detail/Utils.hh
  test/gtest/detail/test/Macros.test.cc
  test/physics/em/ImportedProcesses.test.cc
Labels: infrastructure

#313 Fix collection warning
  scripts/build/emmet.cmake
  scripts/build/emmet.sh
  src/base/Collection.hh
  src/base/Collection.i.hh
  src/geometry/detail/VGNavCollection.cc
  src/geometry/detail/VGNavCollection.hh
  src/physics/grid/ValueGridBuilder.cc
  src/physics/grid/ValueGridBuilder.hh
Labels: bug, infrastructure, geometry

#315 Refactor demo loop as a reusable class
  app/CMakeLists.txt
  app/demo-loop/LDemoIO.cc
  app/demo-loop/LDemoIO.hh
  app/demo-loop/LDemoKernel.hh
  app/demo-loop/LDemoParams.cc
  app/demo-loop/LDemoParams.hh
  app/demo-loop/Transporter.cc
  app/demo-loop/Transporter.hh
  app/demo-loop/Transporter.json.hh
  app/demo-loop/demo-loop.cc
  app/demo-loop/simple-driver.py
  scripts/build/emmet.cmake
  scripts/build/emmet.sh
  src/sim/TrackData.hh
  src/sim/TrackInitParams.hh
  test/sim/TrackInit.test.cc
Labels: integration

#316 Relativistic Bremsstrahlung Model/Interactor
  app/geant-exporter/BremsstrahlungProcess.cc
  src/CMakeLists.txt
  src/physics/em/RelativisticBremModel.cc
  src/physics/em/RelativisticBremModel.hh
  src/physics/em/detail/RelativisticBremDXsection.hh
  src/physics/em/detail/RelativisticBremDXsection.i.hh
  src/physics/em/detail/RelativisticBremData.hh
  src/physics/em/detail/RelativisticBremInteractor.hh
  src/physics/em/detail/RelativisticBremInteractor.i.hh
  src/physics/em/detail/RelativisticBremLauncher.hh
  src/physics/em/generated/RelativisticBremInteract.cc
  src/physics/em/generated/RelativisticBremInteract.cu
  src/physics/em/generated/RelativisticBremInteract.hh
  test/CMakeLists.txt
  test/physics/em/RelativisticBrem.test.cc
Labels: physics

#312 ORANGE: implement volumes and on-device track initialization
  app/demo-rasterizer/ImageIO.cc
  app/demo-rasterizer/ImageIO.hh
  src/base/Algorithms.hh
  src/base/Array.json.hh
  src/base/Assert.hh
  src/base/Span.hh
  src/orange/Data.hh
  src/orange/Types.hh
  src/orange/surfaces/SurfaceAction.hh
  src/orange/surfaces/detail/SurfaceAction.hh
  src/orange/universes/SimpleUnitTracker.hh
  src/orange/universes/VolumeView.hh
  src/orange/universes/detail/LogicEvaluator.hh
  src/orange/universes/detail/LogicStack.hh
  src/orange/universes/detail/SenseCalculator.hh
  src/orange/universes/detail/SurfaceFunctors.hh
  src/orange/universes/detail/Types.hh
  src/orange/universes/detail/Utils.hh
  test/CMakeLists.txt
  test/base/Algorithms.test.cc
  test/base/Span.test.cc
  test/gtest/detail/Macros.hh
  test/orange/OrangeGeoTestBase.cc
  test/orange/OrangeGeoTestBase.hh
  test/orange/data/five-volumes.org.json
  test/orange/surfaces/SurfaceAction.test.cc
  test/orange/universes/SimpleUnitTracker.test.cc
  test/orange/universes/SimpleUnitTracker.test.cu
  test/orange/universes/SimpleUnitTracker.test.hh
  test/orange/universes/VolumeView.test.cc
  test/orange/universes/detail/LogicEvaluator.test.cc
  test/orange/universes/detail/LogicStack.test.cc
  test/orange/universes/detail/SenseCalculator.test.cc
  test/orange/universes/detail/SurfaceFunctors.test.cc
Labels: geometry
