Repository celeritas-project/celeritas, pull requests merged in 2021-08, with the labels that each got.

#271 Add Geant4 v11 compatibility to geant-exporter
  app/geant-exporter/CeleritasG4Version.hh
  app/geant-exporter/ImportProcessConverter.cc
  app/geant-exporter/geant-exporter.cc
Labels: enhancement

#274 A few more demo loop fixes
  app/demo-loop/KernelUtils.hh
  app/demo-loop/KernelUtils.i.hh
  app/demo-loop/LDemoKernel.cu
  src/geometry/GeoMaterialView.hh
  src/physics/base/Interaction.hh
  src/sim/Action.hh
  src/sim/detail/InitializeTracks.cu
  test/geometry/GeoMaterial.test.cc
Labels: bug, simulation, integration

#269 Add energy loss fluctuations
  app/demo-loop/KernelUtils.hh
  app/demo-loop/KernelUtils.i.hh
  app/demo-loop/LDemoKernel.cu
  src/physics/base/PhysicsInterface.hh
  src/physics/base/PhysicsParams.cc
  src/physics/base/PhysicsParams.hh
  src/physics/base/PhysicsStepUtils.hh
  src/physics/base/PhysicsStepUtils.i.hh
  src/physics/base/PhysicsTrackView.hh
  src/physics/base/PhysicsTrackView.i.hh
  src/physics/em/EnergyLossDistribution.hh
  src/physics/em/EnergyLossDistribution.i.hh
  src/physics/em/FluctuationInterface.hh
  src/physics/material/MaterialInterface.hh
  src/physics/material/MaterialParams.cc
  src/physics/material/MaterialView.hh
  src/physics/material/MaterialView.i.hh
  src/physics/material/detail/Utils.cc
  src/physics/material/detail/Utils.hh
  test/CMakeLists.txt
  test/physics/base/Physics.test.cc
  test/physics/base/PhysicsStepUtils.test.cc
  test/physics/em/EnergyLossDistribution.test.cc
  test/physics/material/Material.test.cc
Labels: physics
