Repository celeritas-project/celeritas, pull requests merged in 2021-12, with the labels that each got.

#319 Fix energy deposition in atomic relaxation + a couple other little things
  app/demo-loop/LDemoIO.cc
  app/demo-loop/LDemoIO.hh
  app/demo-loop/LDemoKernel.cc
  app/demo-loop/Transporter.cc
  app/demo-loop/Transporter.hh
  app/demo-loop/simple-driver.py
  src/base/CollectionBuilder.i.hh
  src/physics/base/PhysicsParams.hh
  src/physics/em/AtomicRelaxation.i.hh
  src/physics/em/AtomicRelaxationParams.cc
  src/physics/em/RayleighModel.cc
  src/physics/em/RelativisticBremModel.cc
  src/sim/TrackData.hh
  src/sim/TrackInitData.hh
  src/sim/TrackInitInterface.i.hh
Labels: bug, documentation, physics, integration

#321 Define CUDA assertion that still fails when NDEBUG
  src/base/Assert.hh
Labels: infrastructure

#322 Improve Quantity with value_as, native_value_from, native_value_to
  app/demo-interactor/KernelUtils.hh
  app/demo-loop/KernelUtils.i.hh
  scripts/build/docker-cuda-ndebug.sh
  scripts/build/docker-cuda.sh
  scripts/build/docker-minimal.sh
  scripts/build/docker-setup.sh
  scripts/build/emmet.cmake
  scripts/build/yuri.cmake
  src/base/Macros.hh
  src/base/Quantity.hh
  src/field/FieldPropagator.hh
  src/field/FieldPropagator.i.hh
  src/field/MagFieldEquation.i.hh
  src/physics/base/Interaction.hh
  src/physics/base/PhysicsData.hh
  src/physics/base/PhysicsParams.cc
  src/physics/em/detail/EPlusGGData.hh
  src/physics/em/detail/EPlusGGInteractor.hh
  src/physics/em/detail/EPlusGGInteractor.i.hh
  src/physics/em/detail/KleinNishinaData.hh
  src/physics/em/detail/KleinNishinaInteractor.i.hh
  src/physics/em/detail/LivermorePEInteractor.i.hh
  src/physics/em/detail/MuBremsstrahlungData.hh
  src/physics/em/detail/RelativisticBremData.hh
  src/physics/em/detail/RelativisticBremInteractor.i.hh
  src/physics/em/detail/SeltzerBergerData.hh
  src/physics/em/detail/SeltzerBergerInteractor.i.hh
  src/physics/material/MaterialParams.cc
  src/physics/material/detail/Utils.cc
  test/base/Quantity.test.cc
  test/physics/base/MockProcess.cc
  test/physics/base/Particle.test.cc
Labels: infrastructure

#323 Reduce code duplication
  app/CMakeLists.txt
  app/demo-loop/LDemoKernel.cc
  app/demo-loop/LDemoKernel.cu
  app/demo-loop/LDemoKernel.hh
  app/demo-loop/LDemoLauncher.hh
  app/demo-loop/Transporter.cc
  app/demo-loop/generated/.clang-format
  app/demo-loop/generated/AlongAndPostStepKernel.cc
  app/demo-loop/generated/AlongAndPostStepKernel.cu
  app/demo-loop/generated/AlongAndPostStepKernel.hh
  app/demo-loop/generated/CleanupKernel.cc
  app/demo-loop/generated/CleanupKernel.cu
  app/demo-loop/generated/CleanupKernel.hh
  app/demo-loop/generated/PreStepKernel.cc
  app/demo-loop/generated/PreStepKernel.cu
  app/demo-loop/generated/PreStepKernel.hh
  app/demo-loop/generated/ProcessInteractionsKernel.cc
  app/demo-loop/generated/ProcessInteractionsKernel.cu
  app/demo-loop/generated/ProcessInteractionsKernel.hh
  cmake/CeleritasGenDemoLoopKernel.cmake
  scripts/dev/gen-demo-loop-kernel.py
  src/CMakeLists.txt
  src/base/CollectionAlgorithms.hh
  src/base/CollectionBuilder.i.hh
  src/base/Copier.cc
  src/base/Copier.hh
  src/base/DeviceVector.hh
  src/base/DeviceVector.i.hh
  src/sim/SimData.hh
  src/sim/TrackInitUtils.cc
  src/sim/TrackInitUtils.hh
  src/sim/detail/InitTracksLauncher.hh
  src/sim/detail/InitializeTracks.cc
  src/sim/detail/InitializeTracks.cu
  src/sim/detail/InitializeTracks.hh
  src/sim/detail/InitializeTracks.nocuda.cc
  src/sim/detail/LocateAliveLauncher.hh
  src/sim/detail/ProcessPrimariesLauncher.hh
  src/sim/detail/ProcessSecondariesLauncher.hh
  src/sim/detail/SimStateInit.cu
  src/sim/detail/SimStateInit.hh
  src/sim/detail/Utils.hh
  test/CMakeLists.txt
  test/base/Copier.test.cc
  test/base/DeviceVector.test.cc
Labels: infrastructure

#324 Integration of multiple bremsstrahlung models
  app/demo-loop/LDemoIO.cc
  app/demo-loop/LDemoIO.hh
  src/physics/em/BremsstrahlungProcess.cc
  src/physics/em/BremsstrahlungProcess.hh
  src/physics/em/CombinedBremModel.cc
  src/physics/em/RelativisticBremModel.cc
  src/physics/em/SeltzerBergerModel.cc
  src/physics/em/detail/CombinedBremInteractor.i.hh
  src/physics/em/detail/PhysicsConstants.hh
  src/physics/em/detail/RBEnergySampler.i.hh
  src/physics/em/detail/RelativisticBremData.hh
  src/physics/em/detail/RelativisticBremInteractor.i.hh
  test/physics/em/ImportedProcesses.test.cc
Labels: physics

#325 Add algorithms for geometry tracking
  src/base/Algorithms.hh
  src/base/DeviceAllocation.i.hh
  src/base/Stopwatch.hh
  src/base/Stopwatch.i.hh
  src/base/detail/AlgorithmsImpl.hh
  src/base/detail/InitializedValue.hh
  src/orange/surfaces/SurfaceAction.hh
  src/orange/surfaces/detail/SurfaceAction.hh
  src/physics/em/detail/BetheHeitlerInteractor.i.hh
  src/physics/em/detail/SBEnergyDistribution.i.hh
  test/base/Algorithms.test.cc
  test/base/Quantity.test.cc
  test/orange/universes/SimpleUnitTracker.test.cc
Labels: infrastructure

#329 Update CI to use vecgeom 1.1.18 and CUDA 11.4
  .jenkins
  scripts/docker/README.md
  scripts/docker/build.sh
  scripts/docker/dev/Dockerfile
  scripts/docker/dev/bionic-minimal.yaml
  scripts/docker/dev/focal-cuda11.yaml
  src/physics/em/detail/BetheHeitlerInteractor.hh
  src/physics/em/detail/BetheHeitlerInteractor.i.hh
  src/physics/em/detail/BetheHeitlerLauncher.hh
  src/physics/em/detail/CombinedBremInteractor.hh
  src/physics/em/detail/CombinedBremInteractor.i.hh
  src/physics/em/detail/CombinedBremLauncher.hh
  src/physics/em/detail/EPlusGGInteractor.hh
  src/physics/em/detail/EPlusGGInteractor.i.hh
  src/physics/em/detail/EPlusGGLauncher.hh
  src/physics/em/detail/KleinNishinaInteractor.hh
  src/physics/em/detail/KleinNishinaInteractor.i.hh
  src/physics/em/detail/KleinNishinaLauncher.hh
  src/physics/em/detail/LivermorePEInteractor.hh
  src/physics/em/detail/LivermorePEInteractor.i.hh
  src/physics/em/detail/LivermorePELauncher.hh
  src/physics/em/detail/LivermorePEMicroXsCalculator.hh
  src/physics/em/detail/LivermorePEMicroXsCalculator.i.hh
  src/physics/em/detail/MuBremsstrahlungInteractor.hh
  src/physics/em/detail/MuBremsstrahlungInteractor.i.hh
  src/physics/em/detail/MuBremsstrahlungLauncher.hh
  src/physics/em/detail/PhysicsConstants.hh
  src/physics/em/detail/RBDiffXsCalculator.hh
  src/physics/em/detail/RBDiffXsCalculator.i.hh
  src/physics/em/detail/RBEnergySampler.hh
  src/physics/em/detail/RBEnergySampler.i.hh
  src/physics/em/detail/RayleighInteractor.hh
  src/physics/em/detail/RayleighInteractor.i.hh
  src/physics/em/detail/RayleighLauncher.hh
  src/physics/em/detail/RelativisticBremInteractor.hh
  src/physics/em/detail/RelativisticBremInteractor.i.hh
  src/physics/em/detail/RelativisticBremLauncher.hh
  src/physics/em/detail/SeltzerBergerInteractor.hh
  src/physics/em/detail/SeltzerBergerInteractor.i.hh
  src/physics/em/detail/SeltzerBergerLauncher.hh
  src/physics/em/detail/TsaiUrbanDistribution.hh
  src/physics/em/detail/Utils.cc
  src/physics/em/detail/Utils.hh
  test/physics/em/CombinedBrem.test.cc
  test/physics/em/RelativisticBrem.test.cc
Labels: physics, infrastructure

#328 Use BVH navigator by default
  app/demo-rasterizer/RDemoKernel.cu
  app/demo-rasterizer/RDemoRunner.cc
  app/demo-rasterizer/RDemoRunner.hh
  app/demo-rasterizer/demo-rasterizer.cc
  src/geometry/GeoParams.cc
  src/geometry/GeoTrackView.hh
  src/geometry/GeoTrackView.i.hh
  src/geometry/detail/BVHNavigator.hh
  test/geometry/Geo.test.cc
  test/geometry/Geo.test.cu
  test/geometry/LinearPropagator.test.cc
Labels: geometry

#330 Fix indexing in step diagnostic
  app/demo-loop/diagnostic/StepDiagnostic.hh
  app/demo-loop/diagnostic/StepDiagnostic.i.hh
Labels: bug

#331 Fix tolerance and missing move
  src/base/Algorithms.hh
  test/physics/em/RelativisticBrem.test.cc
Labels: infrastructure

#332 Fix configure/build errors when +vecgeom~cuda
  CMakeLists.txt
  app/demo-loop/diagnostic/EnergyDiagnostic.hh
  app/demo-loop/diagnostic/EnergyDiagnostic.i.hh
  app/demo-loop/diagnostic/ParticleProcessDiagnostic.hh
  app/demo-loop/diagnostic/ParticleProcessDiagnostic.i.hh
  app/demo-loop/diagnostic/StepDiagnostic.hh
  app/demo-loop/diagnostic/StepDiagnostic.i.hh
  app/demo-loop/diagnostic/TrackDiagnostic.cc
  app/demo-loop/diagnostic/TrackDiagnostic.cu
  app/demo-loop/diagnostic/TrackDiagnostic.hh
  scripts/build/emmet.cmake
  scripts/build/emmet.sh
  scripts/build/wildstyle.sh
  scripts/build/yuri.cmake
  src/geometry/GeoTrackView.i.hh
  src/geometry/detail/BVHNavigator.hh
  src/sim/detail/InitializeTracks.hh
  src/sim/detail/LocateAliveLauncher.hh
  src/sim/detail/ProcessSecondariesLauncher.hh
  test/physics/em/RelativisticBrem.test.cc
Labels: bug, infrastructure, geometry, integration
