Repository celeritas-project/celeritas, pull requests merged in 2021-07, with the labels that each got.

#251 Add track initialization to demo loop
  app/demo-loop/KernelUtils.hh
  app/demo-loop/KernelUtils.i.hh
  app/demo-loop/LDemoIO.cc
  app/demo-loop/LDemoIO.hh
  app/demo-loop/LDemoInterface.hh
  app/demo-loop/LDemoKernel.cu
  app/demo-loop/LDemoKernel.hh
  app/demo-loop/LDemoParams.cc
  app/demo-loop/LDemoParams.hh
  app/demo-loop/LDemoRun.cc
  app/demo-loop/demo-loop.cc
  app/demo-loop/simple-driver.py
  app/demo-rasterizer/demo-rasterizer.cc
  src/comm/Device.cc
  src/comm/Device.hh
  src/geometry/GeoParams.cc
  src/geometry/GeoParams.hh
  src/geometry/GeoTrackView.i.hh
  src/physics/base/Interaction.hh
  src/physics/base/ModelInterface.hh
  src/physics/base/PhysicsParams.cc
  src/physics/base/PhysicsStepUtils.hh
  src/physics/base/PhysicsStepUtils.i.hh
  src/physics/base/PhysicsTrackView.i.hh
  src/physics/em/BetheHeitlerModel.cc
  src/physics/em/KleinNishinaModel.cc
  src/physics/em/MollerBhabhaModel.cc
  src/physics/em/RayleighModel.cc
  src/physics/em/SeltzerBergerModel.cc
  src/physics/em/detail/KleinNishinaInteractor.i.hh
  src/physics/em/detail/LivermorePE.cu
  src/physics/em/detail/SBPositronXsCorrector.i.hh
  src/physics/em/detail/SeltzerBerger.cu
  src/physics/em/detail/SeltzerBergerInteractor.i.hh
  src/random/distributions/UniformRealDistribution.i.hh
  src/sim/Action.hh
  src/sim/TrackInitInterface.cc
  src/sim/TrackInitParams.hh
  src/sim/TrackInterface.hh
  src/sim/detail/InitializeTracks.cu
  test/physics/base/Physics.test.cc
  test/physics/base/PhysicsStepUtils.test.cc
  test/sim/TrackInit.test.cc
  test/sim/TrackInit.test.cu
  test/sim/TrackInit.test.hh
Labels: integration, physics, simulation

#259 MagField Traits
  src/field/FieldDriver.hh
  src/field/FieldDriver.i.hh
  src/field/FieldPropagator.hh
  src/field/FieldPropagator.i.hh
  src/field/MagFieldTraits.hh
  src/field/RungeKuttaStepper.hh
  src/field/RungeKuttaStepper.i.hh
  test/field/FieldDriver.test.cc
  test/field/FieldDriver.test.cu
  test/field/FieldPropagator.test.cc
  test/field/FieldPropagator.test.cu
  test/field/RungeKutta.test.cc
  test/field/RungeKutta.test.cu
  test/field/detail/MagTestTraits.hh
Labels: propagation

#258 Computing performance tests of curand generators
  test/CMakeLists.txt
  test/random/curand/CurandPerformance.test.cc
  test/random/curand/CurandPerformance.test.cu
  test/random/curand/CurandPerformance.test.hh
Labels: infrastructure

#257 Add MuBremsstrahlungInteractor
  src/CMakeLists.txt
  src/base/Constants.hh
  src/physics/base/Secondary.hh
  src/physics/em/MuBremsstrahlungModel.cc
  src/physics/em/MuBremsstrahlungModel.hh
  src/physics/em/detail/MuBremsstrahlung.cu
  src/physics/em/detail/MuBremsstrahlung.hh
  src/physics/em/detail/MuBremsstrahlungInteractor.hh
  src/physics/em/detail/MuBremsstrahlungInteractor.i.hh
  test/CMakeLists.txt
  test/physics/em/MuBremsstrahlung.test.cc
Labels: physics

#264 Add a few distributions
  src/random/distributions/GammaDistribution.hh
  src/random/distributions/GammaDistribution.i.hh
  src/random/distributions/NormalDistribution.hh
  src/random/distributions/NormalDistribution.i.hh
  src/random/distributions/PoissonDistribution.hh
  src/random/distributions/PoissonDistribution.i.hh
  test/CMakeLists.txt
  test/random/distributions/GammaDistribution.test.cc
  test/random/distributions/NormalDistribution.test.cc
  test/random/distributions/PoissonDistribution.test.cc
Labels: infrastructure, physics

#265 Fix a few missing includes and typos
  app/demo-loop/simple-driver.py
  src/base/Span.hh
  src/comm/Device.hh
  test/base/StackAllocator.test.cu
  test/geometry/Geo.test.cu
  test/geometry/LinearPropagator.test.cu
Labels: infrastructure
