Repository celeritas-project/celeritas, pull requests merged in 2022-01, with the labels that each got.

#335 ORANGE: implement distance-to-boundary calculation
  src/orange/Data.hh
  src/orange/universes/SimpleUnitTracker.hh
  src/orange/universes/detail/SurfaceFunctors.hh
  src/orange/universes/detail/Types.hh
  src/orange/universes/detail/Utils.hh
  test/orange/OrangeGeoTestBase.cc
  test/orange/OrangeGeoTestBase.hh
  test/orange/universes/SimpleUnitTracker.test.cc
  test/orange/universes/SimpleUnitTracker.test.cu
  test/orange/universes/SimpleUnitTracker.test.hh
Labels: enhancement, geometry

#333 Refactor geometry stepping and field propagation
  app/demo-loop/KernelUtils.i.hh
  app/demo-rasterizer/RDemoKernel.cu
  scripts/build/yuri.cmake
  src/base/ArrayUtils.hh
  src/base/ArrayUtils.i.hh
  src/field/FieldDriver.hh
  src/field/FieldDriver.i.hh
  src/field/FieldPropagator.hh
  src/field/FieldPropagator.i.hh
  src/field/MagFieldEquation.hh
  src/field/RungeKuttaStepper.hh
  src/field/RungeKuttaStepper.i.hh
  src/field/Types.hh
  src/field/detail/FieldUtils.hh
  src/field/detail/FieldUtils.i.hh
  src/geometry/GeoData.hh
  src/geometry/GeoParams.hh
  src/geometry/GeoTrackView.hh
  src/geometry/GeoTrackView.i.hh
  src/geometry/LinearPropagator.hh
  src/geometry/LinearPropagator.i.hh
  src/geometry/Types.hh
  src/physics/base/Interaction.hh
  src/sim/TrackInitData.hh
  test/base/ArrayUtils.test.cc
  test/field/FieldDriver.test.cc
  test/field/FieldDriver.test.cu
  test/field/FieldPropagator.test.cc
  test/field/FieldPropagator.test.cu
  test/field/FieldPropagator.test.hh
  test/field/FieldTestBase.hh
  test/field/RungeKutta.test.cc
  test/field/RungeKutta.test.cu
  test/field/data/field-test.gdml
  test/geometry/Geo.test.cc
  test/geometry/Geo.test.cu
  test/geometry/LinearPropagator.test.cc
  test/geometry/LinearPropagator.test.cu
Labels: geometry, propagation, integration

#336 ORANGE params
  app/demo-rasterizer/ImageStore.cc
  scripts/build/yuri.sh
  src/CMakeLists.txt
  src/base/ArrayUtils.hh
  src/base/ArrayUtils.i.hh
  src/base/CollectionMirror.hh
  src/base/StringUtils.cc
  src/base/StringUtils.hh
  src/geometry/BoundingBox.hh
  src/geometry/GeoData.hh
  src/geometry/GeoParams.cc
  src/geometry/GeoParams.hh
  src/geometry/GeoTrackView.i.hh
  src/geometry/Types.hh
  src/orange/OrangeParams.cc
  src/orange/OrangeParams.hh
  src/orange/OrangeTrackView.hh
  src/orange/Types.hh
  src/orange/universes/SimpleUnitTracker.hh
  src/orange/universes/detail/Types.hh
  src/physics/base/Interaction.hh
  src/physics/material/MaterialTrackView.i.hh
  test/CMakeLists.txt
  test/base/ArrayUtils.test.cc
  test/geometry/BoundingBox.test.cc
  test/gtest/detail/Macros.hh
  test/orange/Orange.test.cc
  test/orange/OrangeGeoTestBase.cc
  test/orange/OrangeGeoTestBase.hh
  test/orange/universes/SimpleUnitTracker.test.cc
  test/orange/universes/VolumeView.test.cc
  test/orange/universes/detail/SenseCalculator.test.cc
  test/random/distributions/IsotropicDistribution.test.cc
Labels: geometry

#337 Rename VecGeom classes and enable building code with ORANGE
  app/CMakeLists.txt
  app/demo-loop/Transporter.hh
  app/demo-loop/simple-cms.json
  app/demo-rasterizer/two-boxes.gdml
  src/CMakeLists.txt
  src/geometry/GeoData.hh
  src/geometry/GeoParams.hh
  src/geometry/GeoTrackView.hh
  src/sim/detail/InitializeTracks.cc
  src/vecgeom/VecgeomData.hh
  src/vecgeom/VecgeomParams.cc
  src/vecgeom/VecgeomParams.hh
  src/vecgeom/VecgeomTrackView.hh
  src/vecgeom/VecgeomTrackView.i.hh
  src/vecgeom/detail/BVHNavigator.hh
  src/vecgeom/detail/ScopedTimeAndRedirect.cc
  src/vecgeom/detail/ScopedTimeAndRedirect.hh
  src/vecgeom/detail/VecgeomCompatibility.hh
  src/vecgeom/detail/VecgeomNavCollection.cc
  src/vecgeom/detail/VecgeomNavCollection.hh
  src/vecgeom/detail/VecgeomTraits.hh
  test/CMakeLists.txt
  test/field/FieldPropagator.test.cc
  test/geometry/Geo.test.cc
  test/geometry/Geo.test.cu
  test/geometry/Geo.test.hh
  test/geometry/GeoMaterial.test.cc
  test/geometry/GeoTestBase.cc
  test/geometry/GeoTestBase.hh
  test/geometry/LinearPropagator.test.cc
  test/geometry/data/four-steel-slabs.gdml
  test/geometry/data/simple-cms.gdml
  test/gtest/Test.cc
  test/sim/TrackInit.test.cc
  test/sim/data/two-boxes.gdml
  test/vecgeom/Vecgeom.test.cc
  test/vecgeom/Vecgeom.test.cu
  test/vecgeom/Vecgeom.test.hh
  test/vecgeom/data/four-levels.gdml
Labels: infrastructure, geometry

#339 Enable ORANGE for unit tests
  .gitignore
  app/demo-loop/LDemoIO.cc
  src/geometry/GeoMaterialParams.cc
  src/geometry/GeoMaterialParams.hh
  src/io/ImportData.hh
  src/vecgeom/VecgeomParams.cc
  src/vecgeom/VecgeomParams.hh
  test/CMakeLists.txt
  test/geometry/GeoMaterial.test.cc
  test/geometry/LinearPropagator.test.cc
  test/geometry/data/four-steel-slabs.gdml
  test/geometry/data/simple-cms.gdml
  test/geometry/data/simple-cms.org.json
  test/geometry/data/simple-cms.org.omn
  test/geometry/data/simple-cms.root
  test/sim/TrackInit.test.cc
  test/sim/data/two-boxes.org.json
  test/sim/data/two-boxes.org.omn
  test/vecgeom/Vecgeom.test.cc
  test/vecgeom/data/four-levels.gdml
Labels: geometry, integration

#343 Enable ORANGE demo loop
  app/CMakeLists.txt
  app/demo-loop/KernelUtils.i.hh
  app/demo-loop/LDemoIO.cc
  app/demo-loop/simple-cms.gdml
  app/demo-loop/simple-cms.org.json
  app/demo-loop/simple-cms.org.omn
  app/demo-loop/simple-driver.py
  src/geometry/GeoMaterialParams.cc
  src/orange/OrangeTrackView.hh
  test/orange/Orange.test.cc
Labels: geometry, integration

#341 Update geant-exporter to include multiple scattering tables
  app/geant-exporter/ImportProcessConverter.cc
  app/geant-exporter/PhysicsList.cc
  app/geant-exporter/geant-exporter-cat.cc
  src/io/ImportPhysicsTable.hh
  src/io/ImportProcess.hh
  test/io/RootImporter.test.cc
  test/io/data/geant-exporter-data.root
  test/physics/base/Particle.test.cc
Labels: enhancement

#344 Add abstraction for environment variables to support JSON I/O
  app/demo-loop/demo-loop.cc
  src/CMakeLists.txt
  src/base/Assert.cc
  src/base/ColorUtils.cc
  src/comm/Device.cc
  src/comm/Environment.cc
  src/comm/Environment.hh
  src/comm/EnvironmentIO.json.hh
  src/comm/Logger.cc
  src/comm/ScopedMpiInit.cc
  src/io/AtomicRelaxationReader.cc
  src/io/LivermorePEReader.cc
  src/io/SeltzerBergerReader.cc
  test/CMakeLists.txt
  test/comm/Environment.test.cc
  test/comm/Logger.test.cc
  test/field/detail/CMSFieldMapReader.cc
  test/field/detail/CMSFieldMapReader.hh
  test/gtest/detail/TestMain.cc
Labels: infrastructure

#346 Add timers to demo loop
  app/demo-loop/LDemoIO.cc
  app/demo-loop/LDemoIO.hh
  app/demo-loop/Transporter.cc
  app/demo-loop/Transporter.hh
  app/demo-loop/Transporter.json.hh
  app/demo-loop/demo-loop.cc
  app/demo-loop/diagnostic/Diagnostic.hh
  app/demo-loop/diagnostic/EnergyDiagnostic.hh
  app/demo-loop/diagnostic/EnergyDiagnostic.i.hh
  app/demo-loop/diagnostic/ParticleProcessDiagnostic.hh
  app/demo-loop/diagnostic/ParticleProcessDiagnostic.i.hh
  app/demo-loop/diagnostic/StepDiagnostic.hh
  app/demo-loop/diagnostic/StepDiagnostic.i.hh
  app/demo-loop/diagnostic/TrackDiagnostic.hh
  app/demo-loop/simple-driver.py
Labels: integration

#345 Enable ORANGE field test
  src/base/Collection.hh
  src/base/Range.hh
  src/base/Span.hh
  src/base/detail/RangeImpl.hh
  src/orange/surfaces/Surfaces.hh
  test/CMakeLists.txt
  test/field/data/field-test.org.json
  test/field/data/field-test.org.py
Labels: propagation

#347 Fix rasterizer
  app/demo-rasterizer/RDemoKernel.cu
  app/demo-rasterizer/demo-rasterizer.cc
Labels: geometry

#348 Un-lfs last file and remove attributes
  .gitattributes
  doc/_static/celeritas-thumbnail.png
Labels: documentation

#349 Enhance demo loop application
  CMakePresets.json
  app/demo-loop/LDemoIO.cc
  app/demo-loop/LDemoIO.hh
  app/demo-loop/Transporter.cc
  app/demo-loop/demo-loop.cc
  app/demo-loop/diagnostic/Diagnostic.hh
  app/demo-loop/simple-driver.py
  scripts/cmake-presets/ci.json
  scripts/cmake-presets/emmet.cmake
  scripts/cmake-presets/emmet.json
  scripts/cmake-presets/wildstyle.json
  scripts/cmake-presets/yuri.json
  src/base/ArrayUtils.i.hh
  src/base/ScopedTimeLog.hh
  src/io/AtomicRelaxationReader.cc
  src/io/LivermorePEReader.cc
  src/io/RootImporter.cc
  src/io/SeltzerBergerReader.cc
  src/orange/OrangeParams.cc
  src/physics/em/AtomicRelaxationParams.cc
  src/physics/em/LivermorePEModel.cc
  src/physics/em/SeltzerBergerModel.cc
  src/sim/TrackInitData.hh
  src/sim/TrackInitParams.cc
  src/sim/TrackInitParams.hh
  src/vecgeom/detail/ScopedTimeAndRedirect.cc
  src/vecgeom/detail/ScopedTimeAndRedirect.hh
  test/sim/TrackInit.test.cc
Labels: integration

#351 Add status messages and improve diagnostics to demo loop
  app/demo-loop/LDemoIO.cc
  app/demo-loop/LDemoIO.hh
  app/demo-loop/Transporter.cc
  app/demo-loop/Transporter.hh
  app/demo-loop/Transporter.json.hh
  app/demo-loop/demo-loop.cc
  app/demo-loop/simple-driver.py
  app/demo-rasterizer/demo-rasterizer.cc
  scripts/docker/ci/run-ci.sh
  src/orange/OrangeTrackView.hh
Labels: integration

#360 Change Def to Record
  app/demo-interactor/demo-interactor.cc
  app/demo-interactor/host-demo-interactor.cc
  src/orange/Data.hh
  src/orange/OrangeParams.cc
  src/orange/construct/VolumeInput.hh
  src/orange/construct/VolumeInserter.cc
  src/orange/universes/VolumeView.hh
  src/physics/base/ParticleData.hh
  src/physics/base/ParticleParams.cc
  src/physics/base/Types.hh
  src/physics/material/ElementView.hh
  src/physics/material/MaterialData.hh
  src/physics/material/MaterialParams.cc
  src/physics/material/MaterialView.hh
  src/physics/material/MaterialView.i.hh
  src/physics/material/Types.hh
  src/physics/material/detail/Utils.cc
  src/physics/material/detail/Utils.hh
  test/field/FieldPropagator.test.cc
  test/io/EventReader.test.cc
  test/physics/base/CutoffParams.test.cc
  test/physics/base/Particle.test.cc
  test/physics/base/Physics.test.cc
  test/physics/base/PhysicsTestBase.cc
  test/physics/em/BetheHeitler.test.cc
  test/physics/em/CombinedBrem.test.cc
  test/physics/em/EPlusGG.test.cc
  test/physics/em/EnergyLossDistribution.test.cc
  test/physics/em/KleinNishina.test.cc
  test/physics/em/LivermorePE.test.cc
  test/physics/em/MollerBhabha.test.cc
  test/physics/em/MuBremsstrahlung.test.cc
  test/physics/em/Rayleigh.test.cc
  test/physics/em/RelativisticBrem.test.cc
  test/physics/em/SeltzerBerger.test.cc
  test/physics/material/Material.test.cc
  test/sim/TrackInit.test.cc
Labels: infrastructure

#362 Fix parent ID assignment
  src/base/detail/CollectionImpl.hh
  src/physics/base/Interaction.hh
  src/sim/detail/LocateAliveLauncher.hh
  src/sim/detail/ProcessSecondariesLauncher.hh
  test/sim/TrackInit.test.cc
  test/sim/TrackInit.test.cu
  test/sim/TrackInit.test.hh
Labels: bug, simulation

#364 Fix forceinline usage, docker script, and demo-loop test disable
  app/CMakeLists.txt
  scripts/docker/ci/launch-local-test.sh
  src/orange/universes/detail/LogicEvaluator.hh
  src/orange/universes/detail/LogicStack.hh
  src/physics/material/MaterialTrackView.hh
  src/physics/material/MaterialTrackView.i.hh
Labels: infrastructure

#365 Split movement-to-boundary from boundary-crossing
  app/demo-loop/KernelUtils.hh
  app/demo-loop/KernelUtils.i.hh
  app/demo-loop/LDemoLauncher.hh
  app/demo-loop/simple-cms.org.json
  app/demo-rasterizer/RDemoKernel.cu
  scripts/cmake-presets/emmet.json
  src/comm/KernelDiagnostics.hh
  src/field/FieldPropagator.i.hh
  src/geometry/LinearPropagator.hh
  src/geometry/Types.hh
  src/orange/OrangeTrackView.hh
  src/orange/universes/SimpleUnitTracker.hh
  src/orange/universes/detail/Types.hh
  src/sim/detail/ProcessSecondariesLauncher.hh
  src/vecgeom/VecgeomTrackView.hh
  src/vecgeom/VecgeomTrackView.i.hh
  test/field/FieldPropagator.test.cc
  test/field/FieldPropagator.test.cu
  test/geometry/GeoMaterial.test.cc
  test/geometry/LinearPropagator.test.cc
  test/orange/Orange.test.cc
  test/orange/universes/SimpleUnitTracker.test.cc
  test/orange/universes/SimpleUnitTracker.test.hh
  test/vecgeom/Vecgeom.test.cc
  test/vecgeom/Vecgeom.test.cu
Labels: bug, physics, geometry, propagation, integration
