Repository celeritas-project/celeritas, pull requests merged in 2022-07, with the labels that each got.

#443 Fix HIP/Crusher build
  app/demo-loop/Transporter.cc
  src/CMakeLists.txt
  src/celeritas/ext/detail/DetectorConstruction.cc
  src/celeritas/field/RungeKuttaStepper.hh
  src/celeritas/global/ActionManagerOutput.cc
  src/celeritas/global/CoreTrackData.hh
  src/celeritas/phys/PhysicsParams.cc
  src/celeritas/phys/PhysicsParams.hh
  src/celeritas/phys/PhysicsStepView.hh
  src/celeritas/phys/PhysicsTrackView.hh
  src/celeritas/random/CuHipRngData.hh
  src/celeritas/random/Selector.hh
  src/celeritas/track/detail/ProcessSecondariesLauncher.hh
  test/celeritas/em/SeltzerBerger.test.cc
  test/celeritas/field/FieldDriver.test.cc
  test/celeritas/field/FieldPropagator.test.cc
  test/celeritas/field/FieldPropagator.test.cu
  test/celeritas/field/FieldPropagator.test.hh
  test/celeritas/field/Steppers.test.cc
  test/celeritas/field/UserMapField.test.cc
Labels: infrastructure

#444 Use the integral approach for all processes with particles that can lose energy over the step
  app/demo-loop/LDemoIO.cc
  src/celeritas/em/process/BremsstrahlungProcess.cc
  src/celeritas/em/process/BremsstrahlungProcess.hh
  src/celeritas/em/process/ComptonProcess.cc
  src/celeritas/em/process/ComptonProcess.hh
  src/celeritas/em/process/EIonizationProcess.cc
  src/celeritas/em/process/EIonizationProcess.hh
  src/celeritas/em/process/EPlusAnnihilationProcess.cc
  src/celeritas/em/process/EPlusAnnihilationProcess.hh
  src/celeritas/em/process/GammaConversionProcess.cc
  src/celeritas/em/process/GammaConversionProcess.hh
  src/celeritas/em/process/MultipleScatteringProcess.cc
  src/celeritas/em/process/MultipleScatteringProcess.hh
  src/celeritas/em/process/PhotoelectricProcess.cc
  src/celeritas/em/process/PhotoelectricProcess.hh
  src/celeritas/em/process/RayleighProcess.cc
  src/celeritas/em/process/RayleighProcess.hh
  src/celeritas/phys/PhysicsData.hh
  src/celeritas/phys/PhysicsParams.cc
  src/celeritas/phys/PhysicsParams.hh
  src/celeritas/phys/PhysicsStepUtils.hh
  src/celeritas/phys/PhysicsTrackView.hh
  src/celeritas/phys/Process.hh
  test/celeritas/MockTestBase.cc
  test/celeritas/TestEm3Base.cc
  test/celeritas/em/ImportedProcesses.test.cc
  test/celeritas/em/UrbanMsc.test.cc
  test/celeritas/phys/MockProcess.cc
  test/celeritas/phys/MockProcess.hh
  test/celeritas/phys/Physics.test.cc
  test/celeritas/phys/PhysicsStepUtils.test.cc
Labels: bug, physics

#448 Make energy fluctuation setup independent of physics params
  app/demo-loop/LDemoIO.cc
  scripts/cmake-presets/yuri.json
  scripts/dev/iwyu-apple-clang.imp
  scripts/dev/iwyu-celeritas.imp
  src/CMakeLists.txt
  src/celeritas/em/FluctuationParams.cc
  src/celeritas/em/FluctuationParams.hh
  src/celeritas/global/CoreParams.hh
  src/celeritas/phys/ParticleTrackView.hh
  src/celeritas/phys/PhysicsData.hh
  src/celeritas/phys/PhysicsParams.cc
  src/celeritas/phys/PhysicsParams.hh
  src/corecel/Types.hh
  src/corecel/data/CollectionMirror.hh
  test/CMakeLists.txt
  test/celeritas/MockTestBase.cc
  test/celeritas/TestEm3Base.cc
  test/celeritas/em/Fluctuation.test.cc
  test/celeritas/global/Stepper.test.cc
  test/celeritas/phys/Physics.test.cc
Labels: physics, housekeeping

#450 Add simulation time
  src/celeritas/global/detail/AlongStepActionImpl.hh
  src/celeritas/io/EventReader.cc
  src/celeritas/phys/Primary.hh
  src/celeritas/track/SimData.hh
  src/celeritas/track/SimTrackView.hh
  src/celeritas/track/detail/ProcessPrimariesLauncher.hh
  src/celeritas/track/detail/ProcessSecondariesLauncher.hh
  test/celeritas/em/UrbanMsc.test.cc
  test/celeritas/ext/EventReader.test.cc
  test/celeritas/global/Stepper.test.cc
  test/celeritas/track/TrackInit.test.cc
Labels: simulation

#453 Revert accidental change to Assert.hh
  src/corecel/Assert.hh
Labels: bug, housekeeping

#452 Avoid double transfer from device (see PR #446)
  app/geo-check/GCheckKernel.cu
Labels: geometry, housekeeping

#456 Improve support for building as a "vendored" dependency
  CMakeLists.txt
  src/CMakeLists.txt
  test/CMakeLists.txt
Labels: infrastructure

#455 Refactor stepper test and add "action result" for MSC interaction
  scripts/cmake-presets/wildstyle.json
  scripts/docker/ci/run-ci.sh
  src/celeritas/em/distribution/UrbanMscScatter.hh
  src/celeritas/global/Stepper.hh
  src/celeritas/global/detail/AlongStepActionImpl.hh
  src/celeritas/phys/Interaction.hh
  src/corecel/sys/KernelDiagnostics.cc
  src/corecel/sys/KernelDiagnostics.hh
  test/CMakeLists.txt
  test/Test.cc
  test/Test.hh
  test/celeritas/TestEm3Base.cc
  test/celeritas/TestEm3Base.hh
  test/celeritas/em/UrbanMsc.test.cc
  test/celeritas/global/DummyAction.hh
  test/celeritas/global/Stepper.test.cc
  test/celeritas/global/StepperTestBase.cc
  test/celeritas/global/StepperTestBase.hh
  test/detail/Macros.hh
  test/detail/TestMain.cc
Labels: integration

#458 Add granular along-step tests
  src/celeritas/io/EventReader.hh
  src/celeritas/phys/Primary.hh
  test/CMakeLists.txt
  test/celeritas/TestEm3Base.cc
  test/celeritas/TestEm3Base.hh
  test/celeritas/global/AlongStep.test.cc
  test/celeritas/global/AlongStepTestBase.cc
  test/celeritas/global/AlongStepTestBase.hh
  test/celeritas/global/StepperTestBase.cc
  test/celeritas/global/StepperTestBase.hh
Labels: physics

#454 Fix an issue of too many small steps when msc is enabled
  src/celeritas/em/distribution/UrbanMscScatter.hh
  src/celeritas/em/distribution/UrbanMscStepLimit.hh
  src/celeritas/global/detail/AlongStepActionImpl.hh
  src/celeritas/phys/PhysicsData.hh
  src/celeritas/phys/PhysicsParams.cc
  src/celeritas/phys/PhysicsParams.hh
  src/celeritas/phys/PhysicsParamsOutput.cc
  src/celeritas/phys/PhysicsStepUtils.hh
  test/celeritas/em/UrbanMsc.test.cc
  test/celeritas/global/AlongStep.test.cc
  test/celeritas/global/AlongStepTestBase.cc
  test/celeritas/global/Stepper.test.cc
  test/celeritas/phys/Physics.test.cc
Labels: bug, physics

#457 Refactor along-step for extensibility
  app/demo-loop/LDemoIO.cc
  app/demo-loop/Transporter.cc
  app/demo-loop/Transporter.hh
  scripts/cmake-presets/voskhod.json
  src/CMakeLists.txt
  src/celeritas/Types.hh
  src/celeritas/em/FluctuationParams.cc
  src/celeritas/em/FluctuationParams.hh
  src/celeritas/em/distribution/EnergyLossDistribution.hh
  src/celeritas/em/distribution/EnergyLossHelper.hh
  src/celeritas/global/CoreParams.cc
  src/celeritas/global/CoreParams.hh
  src/celeritas/global/Stepper.cc
  src/celeritas/global/alongstep/AlongStep.hh
  src/celeritas/global/alongstep/AlongStepGeneralLinearAction.cc
  src/celeritas/global/alongstep/AlongStepGeneralLinearAction.cu
  src/celeritas/global/alongstep/AlongStepGeneralLinearAction.hh
  src/celeritas/global/alongstep/AlongStepLauncher.hh
  src/celeritas/global/alongstep/AlongStepNeutralAction.cc
  src/celeritas/global/alongstep/AlongStepNeutralAction.cu
  src/celeritas/global/alongstep/AlongStepNeutralAction.hh
  src/celeritas/global/alongstep/detail/AlongStepGeneralLinear.hh
  src/celeritas/global/alongstep/detail/AlongStepLauncherImpl.hh
  src/celeritas/global/alongstep/detail/AlongStepNeutral.hh
  src/celeritas/global/alongstep/detail/EnergyLossApplier.hh
  src/celeritas/global/alongstep/detail/EnergyLossFluctApplier.hh
  src/celeritas/global/alongstep/detail/UrbanMsc.hh
  src/celeritas/global/detail/AlongStepActionImpl.hh
  src/celeritas/global/generated/.clang-format
  src/celeritas/global/generated/AlongStepAction.cc
  src/celeritas/global/generated/AlongStepAction.hh
  src/celeritas/phys/PhysicsData.hh
  src/celeritas/phys/PhysicsParams.cc
  src/celeritas/phys/PhysicsParams.hh
  src/celeritas/phys/PhysicsParamsOutput.cc
  src/celeritas/phys/PhysicsStepUtils.hh
  src/celeritas/phys/PhysicsTrackView.hh
  test/celeritas/GlobalTestBase.cc
  test/celeritas/GlobalTestBase.hh
  test/celeritas/MockTestBase.cc
  test/celeritas/MockTestBase.hh
  test/celeritas/SimpleTestBase.cc
  test/celeritas/SimpleTestBase.hh
  test/celeritas/TestEm3Base.cc
  test/celeritas/TestEm3Base.hh
  test/celeritas/em/Fluctuation.test.cc
  test/celeritas/em/UrbanMsc.test.cc
  test/celeritas/ext/Vecgeom.test.cc
  test/celeritas/field/FieldPropagatorTestBase.hh
  test/celeritas/field/LinearPropagator.test.cc
  test/celeritas/geo/GeoMaterial.test.cc
  test/celeritas/global/AlongStepTestBase.cc
  test/celeritas/phys/Physics.test.cc
  test/celeritas/phys/PhysicsStepUtils.test.cc
Labels: physics, integration

#463 Optionally generate primaries without a HepMC3 input file in the demo loop
  app/demo-loop/LDemoIO.cc
  app/demo-loop/LDemoIO.hh
  app/demo-loop/demo-loop.cc
  src/CMakeLists.txt
  src/celeritas/phys/PrimaryGenerator.cc
  src/celeritas/phys/PrimaryGenerator.hh
  src/celeritas/phys/PrimaryGeneratorOptionsIO.json.cc
  src/celeritas/phys/PrimaryGeneratorOptionsIO.json.hh
Labels: enhancement

#464 Fix generation error when building static+vecgeom
  cmake/CeleritasLibrary.cmake
Labels: bug, infrastructure

#467 Cache the energy loss range as a physics state data
  src/celeritas/em/distribution/UrbanMscHelper.hh
  src/celeritas/em/distribution/UrbanMscScatter.hh
  src/celeritas/em/distribution/UrbanMscStepLimit.hh
  src/celeritas/phys/PhysicsData.hh
  src/celeritas/phys/PhysicsStepUtils.hh
  src/celeritas/phys/PhysicsTrackView.hh
  test/celeritas/em/UrbanMsc.test.cc
  test/celeritas/phys/PhysicsStepUtils.test.cc
Labels: physics

#468 Add release notes and final doc tweaks for v0.1.0
  .jenkins
  CMakeLists.txt
  CMakePresets.json
  README.md
  doc/CMakeLists.txt
  doc/_python/monkeysphinx.py
  doc/_static/ornltm-extract.sty
  doc/_static/ornltm-footer.tex
  doc/_static/ornltm-header-celeritas.tex
  doc/_static/references.bib
  doc/_static/sphinxcustom.sty
  doc/api.rst
  doc/api/celeritas.rst
  doc/api/corecel.rst
  doc/api/orange.rst
  doc/appendices/release-history.rst
  doc/conf.py
  doc/index.rst
  scripts/cmake-presets/ci.json
  scripts/cmake-presets/crusher.json
  scripts/cmake-presets/emmet.json
  scripts/cmake-presets/goldfinger.json
  scripts/cmake-presets/stognini.json
  scripts/cmake-presets/summit.json
  scripts/cmake-presets/wildstyle.json
  scripts/cmake-presets/yuri.json
  scripts/spack.yaml
  src/celeritas/ext/GeantSetup.cc
  src/celeritas/mat/MaterialParams.hh
  src/corecel/Assert.hh
  src/corecel/Macros.hh
  src/corecel/OpaqueId.hh
  src/corecel/math/Algorithms.hh
  src/corecel/math/ArrayUtils.hh
  src/corecel/math/NumericLimits.hh
  src/corecel/sys/Device.cc
  src/corecel/sys/Device.hh
Labels: documentation
