Repository celeritas-project/celeritas, pull requests merged in 2022-03, with the labels that each got.

#382 Store the number of steps per track
  app/demo-loop/LDemoLauncher.hh
  app/demo-loop/Transporter.cc
  app/demo-loop/diagnostic/ParticleProcessDiagnostic.hh
  app/demo-loop/diagnostic/StepDiagnostic.hh
  src/sim/SimData.hh
  src/sim/SimTrackView.hh
  src/sim/detail/ProcessSecondariesLauncher.hh
Labels: simulation

#381 Add ctest labels, minor tweaks
  CMakePresets.json
  app/CMakeLists.txt
  cmake/CeleritasAddTest.cmake
  scripts/cmake-presets/ci.json
  scripts/cmake-presets/crusher.json
  scripts/dev/run-cloc.sh
  scripts/docker/README.md
  scripts/docker/ci/launch-local-test.sh
  scripts/docker/ci/run-ci.sh
  src/base/Assert.hh
  src/base/KernelParamCalculator.device.hh
  test/CMakeLists.txt
Labels: infrastructure

#375 Add an initial version of the Urban multiple scattering model
  src/CMakeLists.txt
  src/physics/base/PhysicsData.hh
  src/physics/base/PhysicsParams.cc
  src/physics/base/PhysicsTrackView.hh
  src/physics/em/MultipleScatteringProcess.cc
  src/physics/em/MultipleScatteringProcess.hh
  src/physics/em/UrbanMscModel.cc
  src/physics/em/UrbanMscModel.hh
  src/physics/em/detail/UrbanMscData.hh
  src/physics/em/detail/UrbanMscHelper.hh
  src/physics/em/detail/UrbanMscScatter.hh
  src/physics/em/detail/UrbanMscStepLimit.hh
  src/physics/material/MaterialView.hh
  test/CMakeLists.txt
  test/io/data/geant-exporter-data.gdml
  test/physics/em/ImportedProcesses.test.cc
  test/physics/em/UrbanMsc.test.cc
Labels: physics

#384 Add features and fixes for testem3 comparison
  app/demo-loop/LDemoIO.cc
  app/demo-loop/LDemoIO.hh
  app/demo-loop/LDemoLauncher.hh
  app/demo-loop/Transporter.cc
  app/demo-loop/Transporter.hh
  app/demo-loop/diagnostic/EnergyDiagnostic.hh
  app/demo-loop/simple-driver.py
  src/sim/detail/InitTracksLauncher.hh
Labels: physics

#385 Add relativistic pair production
  app/demo-loop/LDemoIO.cc
  app/demo-loop/LDemoIO.hh
  src/comm/Device.cc
  src/physics/em/BetheHeitlerModel.cc
  src/physics/em/BetheHeitlerModel.hh
  src/physics/em/CombinedBremModel.hh
  src/physics/em/GammaConversionProcess.cc
  src/physics/em/GammaConversionProcess.hh
  src/physics/em/RelativisticBremModel.cc
  src/physics/em/RelativisticBremModel.hh
  src/physics/em/detail/BetheHeitlerData.hh
  src/physics/em/detail/BetheHeitlerInteractor.hh
  src/physics/em/detail/BetheHeitlerLauncher.hh
  src/physics/em/detail/LPMCalculator.hh
  src/physics/em/detail/PhysicsConstants.hh
  src/physics/em/detail/RBDiffXsCalculator.hh
  src/physics/em/detail/RelativisticBremData.hh
  test/physics/em/BetheHeitler.test.cc
  test/physics/em/CombinedBrem.test.cc
  test/physics/em/ImportedProcesses.test.cc
  test/physics/em/RelativisticBrem.test.cc
Labels: physics

#394 Fix doxygen documentation
  doc/CMakeLists.txt
  src/base/KernelParamCalculator.device.cc
  src/comm/EnvironmentIO.json.hh
  src/io/detail/TFileUniquePtr.root.cc
  src/physics/em/detail/UrbanMscHelper.hh
  src/physics/em/detail/UrbanMscScatter.hh
  src/physics/em/detail/UrbanMscStepLimit.hh
  src/sim/CoreTrackData.hh
Labels: documentation
