Repository celeritas-project/celeritas, pull requests merged in 2022-09, with the labels that each got.

#506 Format code base (clang-format version 14.0.6)
  app/demo-loop/Transporter.hh
  src/celeritas/field/FieldDriver.hh
  src/celeritas/field/FieldPropagator.hh
  src/celeritas/global/Stepper.hh
  src/celeritas/global/alongstep/detail/EnergyLossApplier.hh
  src/celeritas/grid/ValueGridBuilder.hh
  src/celeritas/phys/PDGNumber.hh
  src/celeritas/phys/ParticleParams.cc
  src/celeritas/phys/PhysicsParams.hh
  src/celeritas/phys/Primary.hh
  src/celeritas/phys/PrimaryGenerator.hh
  src/corecel/data/Collection.hh
  src/corecel/data/CollectionStateStore.hh
  src/corecel/data/DeviceVector.hh
  src/corecel/data/detail/InitializedValue.hh
  src/corecel/io/detail/LoggerMessage.hh
  src/corecel/sys/ScopedSignalHandler.hh
  src/orange/Data.hh
  src/orange/OrangeTrackView.hh
  test/celeritas/MockTestBase.cc
  test/celeritas/SimpleTestBase.cc
  test/celeritas/em/EPlusGG.test.cc
  test/celeritas/em/MollerBhabha.test.cc
  test/celeritas/em/Rayleigh.test.cc
  test/celeritas/em/UrbanMsc.test.cc
  test/celeritas/ext/RootImporter.test.cc
  test/celeritas/field/FieldPropagator.test.cc
  test/celeritas/geo/Geometry.test.cc
  test/celeritas/global/AlongStepTestBase.cc
  test/celeritas/global/Stepper.test.cc
  test/celeritas/phys/InteractorHostTestBase.cc
  test/celeritas/phys/PrimaryGenerator.test.cc
  test/corecel/OpaqueId.test.cc
  test/corecel/io/Join.test.cc
Labels: housekeeping

#507 Save JSON exception output if demo loop fails
  app/demo-loop/demo-loop.cc
  src/CMakeLists.txt
  src/celeritas/ext/ScopedMpiInit.cc
  src/celeritas/ext/detail/GeantExceptionHandler.cc
  src/corecel/Assert.cc
  src/corecel/Assert.hh
  src/corecel/io/ExceptionOutput.cc
  src/corecel/io/ExceptionOutput.hh
  test/celeritas/random/SequenceEngine.hh
  test/corecel/data/Collection.test.cu
  test/corecel/io/OutputManager.test.cc
Labels: infrastructure

#508 Fix no-ROOT demo loop for 0.1.x and other summit changes
  CMakePresets.json
  app/CMakeLists.txt
  app/demo-loop/LDemoIO.cc
  app/geo-check/GCheckKernel.cc
  app/geo-check/GCheckKernel.hh
  app/geo-check/GCheckRunner.cc
  app/geo-check/gcheck-four-levels.json.in
  app/geo-check/geo-check.cc
  cmake/CgvFindVersion.cmake
  scripts/cmake-presets/summit.json
  scripts/env/summit.sh
  src/celeritas/phys/ProcessBuilder.cc
  src/celeritas/phys/ProcessBuilder.hh
  src/celeritas/random/CuHipRngData.hh
  test/celeritas/GeantTestBase.cc
  test/celeritas/GeantTestBase.hh
  test/celeritas/field/FieldPropagator.test.cc
  test/celeritas/global/Stepper.test.cc
Labels: bug, integration

#509 Fixes and infrastructure improvements for summit
  CMakePresets.json
  app/CMakeLists.txt
  app/geo-check/GCheckKernel.cc
  app/geo-check/GCheckKernel.hh
  app/geo-check/GCheckRunner.cc
  app/geo-check/gcheck-four-levels.json.in
  app/geo-check/geo-check.cc
  cmake/CeleritasAddTest.cmake
  cmake/CgvFindVersion.cmake
  scripts/cmake-presets/summit.json
  scripts/env/summit.sh
  src/celeritas/phys/ProcessBuilder.cc
  src/celeritas/phys/ProcessBuilder.hh
  src/celeritas/random/CuHipRngData.hh
  src/corecel/io/ExceptionOutput.cc
  test/TestMain.hh
  test/celeritas/GeantTestBase.cc
  test/celeritas/GeantTestBase.hh
  test/celeritas/field/FieldPropagator.test.cc
  test/celeritas/global/Stepper.test.cc
  test/testdetail/TestMainImpl.cc
Labels: bug, infrastructure

#504 Fix class name conflict, remove default initializers, and add other tweaks
  scripts/cmake-presets/goldfinger.json
  src/celeritas/em/distribution/UrbanMscScatter.hh
  src/celeritas/em/interactor/MollerBhabhaInteractor.hh
  src/celeritas/em/interactor/MuBremsstrahlungInteractor.hh
  src/celeritas/em/interactor/RayleighInteractor.hh
  src/celeritas/em/interactor/detail/BremFinalStateHelper.hh
  src/celeritas/field/DormandPrinceStepper.hh
  src/celeritas/field/FieldDriver.hh
  src/celeritas/field/MagFieldEquation.hh
  src/celeritas/field/RungeKuttaStepper.hh
  src/celeritas/field/Types.hh
  src/celeritas/field/ZHelixStepper.hh
  src/celeritas/field/detail/FieldUtils.hh
  src/celeritas/global/alongstep/detail/UrbanMsc.hh
  src/celeritas/random/distribution/GammaDistribution.hh
  src/corecel/math/Algorithms.hh
  test/CMakeLists.txt
  test/celeritas/field/FieldDriver.test.cc
  test/celeritas/field/MagFieldEquation.test.cc
  test/celeritas/field/Steppers.test.cc
  test/corecel/math/Algorithms.test.cc
Labels: bug, propagation, housekeeping

#510 Refactor ORANGE input to be more extensible
  src/CMakeLists.txt
  src/celeritas/grid/NonuniformGrid.hh
  src/orange/Data.hh
  src/orange/OrangeParams.cc
  src/orange/OrangeParams.hh
  src/orange/construct/OrangeInput.hh
  src/orange/construct/OrangeInputIO.json.cc
  src/orange/construct/OrangeInputIO.json.hh
  src/orange/construct/SurfaceInputBuilder.cc
  src/orange/construct/SurfaceInputBuilder.hh
  src/orange/construct/SurfaceInputIO.json.cc
  src/orange/construct/SurfaceInputIO.json.hh
  src/orange/construct/VolumeInputIO.json.cc
  src/orange/construct/VolumeInputIO.json.hh
  src/orange/detail/SurfaceInserter.cc
  src/orange/detail/SurfaceInserter.hh
  src/orange/detail/VolumeInserter.cc
  src/orange/detail/VolumeInserter.hh
  src/orange/surf/Surfaces.hh
  src/orange/univ/SimpleUnitTracker.hh
  test/CMakeLists.txt
  test/orange/Orange.test.cc
  test/orange/OrangeGeoTestBase.cc
  test/orange/OrangeGeoTestBase.hh
  test/orange/construct/SurfaceInserter.test.cc
  test/orange/construct/VolumeInserter.test.cc
  test/orange/surf/SurfaceAction.test.cc
  test/orange/surf/SurfaceAction.test.hh
  test/orange/univ/detail/SenseCalculator.test.cc
  test/orange/univ/detail/SurfaceFunctors.test.cc
Labels: geometry

#511 Fix edge cases in field propagation
  src/celeritas/field/FieldDriver.hh
  src/celeritas/field/FieldPropagator.hh
  src/celeritas/field/MakeMagFieldPropagator.hh
  test/celeritas/field/DiagnosticStepper.hh
  test/celeritas/field/FieldDriver.test.cc
  test/celeritas/field/FieldPropagator.test.cc
  test/celeritas/field/LinearPropagator.test.cc
Labels: bug, propagation

#512 Fix indexing of imported micro xs
  src/celeritas/ext/GeantImporter.cc
  src/celeritas/io/ImportProcess.cc
  src/celeritas/phys/ImportedModelAdapter.cc
  src/celeritas/phys/Model.hh
  src/celeritas/phys/PhysicsParams.cc
  test/celeritas/data/four-steel-slabs.root
  test/celeritas/em/ImportedProcesses.test.cc
  test/celeritas/ext/GeantImporter.test.cc
  test/celeritas/phys/MockModel.cc
Labels: bug

#513 Allow tracks taking small steps to propagate in field
  src/celeritas/field/FieldDriver.hh
  src/celeritas/field/FieldPropagator.hh
  test/celeritas/field/FieldPropagator.test.cc
Labels: bug, propagation

#515 Fix failure when changing direction on boundary immediately after crossing
  src/celeritas/ext/VecgeomTrackView.hh
  src/celeritas/field/FieldPropagator.hh
  src/orange/OrangeTrackView.hh
  test/celeritas/field/FieldPropagator.test.cc
  test/orange/Orange.test.cc
Labels: bug, geometry, propagation

#516 Escape rather than segfault on geometry error in release mode
  src/orange/OrangeTrackView.hh
Labels: geometry

#514 Make primary generator more general
  app/demo-loop/LDemoIO.hh
  app/demo-loop/demo-loop.cc
  src/CMakeLists.txt
  src/celeritas/phys/PrimaryGenerator.cc
  src/celeritas/phys/PrimaryGenerator.hh
  src/celeritas/phys/PrimaryGeneratorOptions.hh
  src/celeritas/phys/PrimaryGeneratorOptionsIO.json.cc
  src/celeritas/phys/PrimaryGeneratorOptionsIO.json.hh
  src/celeritas/random/distribution/DeltaDistribution.hh
  test/celeritas/phys/PrimaryGenerator.test.cc
Labels: enhancement

#517 Fix additional failures resulting from direction change on a boundary after crossing
  src/celeritas/field/FieldPropagator.hh
  src/orange/OrangeTrackView.hh
  test/orange/Orange.test.cc
Labels: bug, geometry, propagation
