Repository celeritas-project/celeritas, pull requests merged in 2022-02, with the labels that each got.

#367 Move .i.hh contents into .hh for remainder of base, comm, random, and sim
  src/base/ArrayUtils.hh
  src/base/ArrayUtils.i.hh
  src/base/Collection.hh
  src/base/Collection.i.hh
  src/base/CollectionBuilder.hh
  src/base/CollectionBuilder.i.hh
  src/base/DeviceVector.hh
  src/base/DeviceVector.i.hh
  src/base/SoftEqual.hh
  src/base/SoftEqual.i.hh
  src/base/StackAllocator.hh
  src/base/StackAllocator.i.hh
  src/base/detail/ArrayUtilsImpl.hh
  src/comm/Operations.hh
  src/comm/Operations.i.hh
  src/random/Selector.hh
  src/random/Selector.i.hh
  src/sim/SimTrackView.hh
  src/sim/SimTrackView.i.hh
Labels: infrastructure

#368 Use size_t in DeviceAllocation
  src/base/DeviceAllocation.hh
Labels: bug, infrastructure

#372 Fix TrackInit test
  test/sim/TrackInit.test.cc
  test/sim/TrackInit.test.cu
  test/sim/TrackInit.test.hh
Labels: bug, simulation

#376 Initialize interactions on device
  src/sim/TrackData.hh
  src/sim/detail/InitTracksLauncher.hh
Labels: bug, integration

#378 Rename safety to find_safety and add not-implemented ORANGE interface
  src/orange/OrangeTrackView.hh
  src/vecgeom/VecgeomTrackView.hh
  test/orange/Orange.test.cc
  test/vecgeom/Vecgeom.test.cc
Labels: geometry

#379 Optimize geometry tracking
  app/demo-rasterizer/RDemoKernel.cu
  scripts/cmake-presets/yuri.json
  src/field/FieldPropagator.hh
  src/geometry/LinearPropagator.hh
  src/orange/Data.hh
  src/orange/OrangeParams.cc
  src/orange/OrangeTrackView.hh
  src/orange/construct/VolumeInput.hh
  src/orange/construct/VolumeInputIO.json.cc
  src/orange/construct/VolumeInserter.cc
  src/orange/surfaces/detail/QuadraticSolver.hh
  src/orange/universes/SimpleUnitTracker.hh
  src/orange/universes/VolumeView.hh
  src/orange/universes/detail/SurfaceFunctors.hh
  src/orange/universes/detail/Types.hh
  src/orange/universes/detail/Utils.hh
  src/vecgeom/VecgeomTrackView.hh
  test/field/FieldPropagator.test.cc
  test/orange/Orange.test.cc
  test/orange/OrangeGeoTestBase.cc
  test/orange/universes/SimpleUnitTracker.test.cc
  test/vecgeom/Vecgeom.test.cc
  test/vecgeom/Vecgeom.test.cu
Labels: enhancement, geometry
