Repository celeritas-project/celeritas, pull requests merged in 2022-11, with the labels that each got.

#534 Load and build multiple universes in ORANGE
  src/celeritas/geo/GeoMaterialParams.cc
  src/orange/CMakeLists.txt
  src/orange/Data.hh
  src/orange/OrangeParams.cc
  src/orange/OrangeParams.hh
  src/orange/Translator.hh
  src/orange/Types.hh
  src/orange/construct/OrangeInput.hh
  src/orange/detail/UnitIndexer.cc
  src/orange/detail/UnitIndexer.hh
  src/orange/detail/UnitInserter.cc
  src/orange/detail/UnitInserter.hh
  test/CMakeLists.txt
  test/celeritas/field/FieldPropagator.test.cc
  test/orange/Orange.test.cc
  test/orange/OrangeGeoTestBase.cc
  test/orange/Translator.test.cc
  test/orange/data/universes.org.json
  test/orange/data/universes.org.omn
  test/orange/detail/UnitIndexer.test.cc
Labels: enhancement, geometry

#532 Fix thread safety issues in Celeritas
  app/demo-interactor/demo-interactor.cc
  app/demo-interactor/host-demo-interactor.cc
  app/demo-interactor/simple-driver.py
  app/demo-loop/demo-loop.cc
  app/demo-loop/diagnostic/EnergyDiagnostic.cu
  app/demo-loop/diagnostic/ParticleProcessDiagnostic.cu
  app/demo-loop/diagnostic/StepDiagnostic.cu
  app/demo-rasterizer/RDemoKernel.cu
  app/demo-rasterizer/demo-rasterizer.cc
  src/celeritas/global/ActionRegistry.hh
  src/corecel/CMakeLists.txt
  src/corecel/io/Logger.cc
  src/corecel/math/Algorithms.hh
  src/corecel/math/Atomics.hh
  src/corecel/sys/Device.cc
  src/corecel/sys/Device.hh
  src/corecel/sys/DeviceIO.json.cc
  src/corecel/sys/Environment.cc
  src/corecel/sys/Environment.hh
  src/corecel/sys/KernelAttributes.hh
  src/corecel/sys/KernelDiagnostics.cc
  src/corecel/sys/KernelDiagnostics.hh
  src/corecel/sys/KernelDiagnosticsIO.json.cc
  src/corecel/sys/KernelParamCalculator.device.cc
  src/corecel/sys/KernelParamCalculator.device.hh
  src/corecel/sys/KernelRegistry.cc
  src/corecel/sys/KernelRegistry.hh
  src/corecel/sys/KernelRegistryIO.json.cc
  src/corecel/sys/KernelRegistryIO.json.hh
  test/celeritas/ext/Vecgeom.test.cu
  test/celeritas/random/RngEngine.test.cu
  test/corecel/math/Algorithms.test.cc
  test/corecel/math/NumericLimits.test.cu
  test/testdetail/TestMainImpl.cc
Labels: bug, integration

#541 Split orange/Types and add Orange prefix to Data
  app/demo-loop/LDemoIO.cc
  app/demo-loop/Transporter.cc
  app/geo-check/GCheckKernel.cc
  scripts/dev/iwyu-apple-clang.imp
  scripts/dev/iwyu-dependencies.imp
  src/celeritas/Types.hh
  src/celeritas/ext/GeantImporter.hh
  src/celeritas/ext/VecgeomParams.hh
  src/celeritas/geo/GeoData.hh
  src/celeritas/io/EventReader.cc
  src/corecel/Assert.cc
  src/corecel/io/Logger.cc
  src/corecel/io/Logger.hh
  src/corecel/io/OutputManager.cc
  src/corecel/sys/Device.cc
  src/corecel/sys/Device.hh
  src/corecel/sys/KernelRegistry.cc
  src/corecel/sys/KernelRegistry.hh
  src/corecel/sys/MpiCommunicator.hh
  src/orange/BoundingBox.hh
  src/orange/CMakeLists.txt
  src/orange/OrangeData.hh
  src/orange/OrangeParams.cc
  src/orange/OrangeParams.hh
  src/orange/OrangeTrackView.hh
  src/orange/OrangeTypes.cc
  src/orange/OrangeTypes.hh
  src/orange/Translator.hh
  src/orange/Types.hh
  src/orange/construct/OrangeInput.hh
  src/orange/construct/SurfaceInputBuilder.hh
  src/orange/detail/UnitIndexer.hh
  src/orange/detail/UnitInserter.hh
  src/orange/surf/CylCentered.hh
  src/orange/surf/GeneralQuadric.hh
  src/orange/surf/PlaneAligned.hh
  src/orange/surf/SurfaceIO.hh
  src/orange/surf/SurfaceTypeTraits.hh
  src/orange/surf/Surfaces.hh
  src/orange/surf/detail/QuadraticSolver.hh
  src/orange/surf/detail/SurfaceAction.hh
  src/orange/univ/SimpleUnitTracker.hh
  src/orange/univ/UniverseTypeTraits.hh
  src/orange/univ/VolumeView.hh
  src/orange/univ/detail/LogicEvaluator.hh
  src/orange/univ/detail/Types.hh
  test/orange/OrangeGeoTestBase.hh
  test/orange/surf/SurfaceAction.test.cc
  test/orange/surf/SurfaceAction.test.hh
  test/orange/univ/SimpleUnitTracker.test.hh
  test/orange/univ/detail/SurfaceFunctors.test.cc
Labels: infrastructure, housekeeping

#542 Support adding primaries at any step in the transport loop
  app/demo-loop/LDemoIO.cc
  app/demo-loop/LDemoIO.hh
  app/demo-loop/Transporter.cc
  app/demo-loop/Transporter.hh
  app/demo-loop/demo-loop.cc
  app/demo-loop/simple-driver.py
  cmake/CeleritasGen/gen-trackinit.py
  src/celeritas/global/CoreParams.cc
  src/celeritas/global/CoreParams.hh
  src/celeritas/global/CoreTrackData.hh
  src/celeritas/global/Stepper.cc
  src/celeritas/global/Stepper.hh
  src/celeritas/track/TrackInitData.hh
  src/celeritas/track/TrackInitParams.cc
  src/celeritas/track/TrackInitParams.hh
  src/celeritas/track/TrackInitUtils.hh
  src/celeritas/track/detail/InitTracksLauncher.hh
  src/celeritas/track/detail/LocateAliveLauncher.hh
  src/celeritas/track/detail/ProcessPrimariesLauncher.hh
  src/celeritas/track/detail/ProcessSecondariesLauncher.hh
  src/celeritas/track/detail/TrackInitAlgorithms.cc
  src/celeritas/track/detail/TrackInitAlgorithms.cu
  src/celeritas/track/detail/Utils.hh
  src/celeritas/track/generated/InitTracks.cc
  src/celeritas/track/generated/InitTracks.cu
  src/celeritas/track/generated/InitTracks.hh
  src/celeritas/track/generated/LocateAlive.cc
  src/celeritas/track/generated/LocateAlive.cu
  src/celeritas/track/generated/LocateAlive.hh
  src/celeritas/track/generated/ProcessPrimaries.cc
  src/celeritas/track/generated/ProcessPrimaries.cu
  src/celeritas/track/generated/ProcessPrimaries.hh
  src/celeritas/track/generated/ProcessSecondaries.cc
  src/celeritas/track/generated/ProcessSecondaries.cu
  src/celeritas/track/generated/ProcessSecondaries.hh
  test/celeritas/GeantTestBase.cc
  test/celeritas/GeantTestBase.hh
  test/celeritas/GlobalTestBase.cc
  test/celeritas/GlobalTestBase.hh
  test/celeritas/MockTestBase.hh
  test/celeritas/SimpleTestBase.cc
  test/celeritas/SimpleTestBase.hh
  test/celeritas/em/UrbanMsc.test.cc
  test/celeritas/ext/Vecgeom.test.cc
  test/celeritas/field/FieldPropagator.test.cc
  test/celeritas/field/LinearPropagator.test.cc
  test/celeritas/geo/GeoMaterial.test.cc
  test/celeritas/geo/HeuristicGeoTestBase.hh
  test/celeritas/geo/OnlyGeoTestBase.hh
  test/celeritas/global/AlongStepTestBase.cc
  test/celeritas/global/Stepper.test.cc
  test/celeritas/global/StepperTestBase.cc
  test/celeritas/global/StepperTestBase.hh
  test/celeritas/phys/Physics.test.hh
  test/celeritas/track/TrackInit.test.cc
Labels: simulation, interface

#544 Add basic step collector
  src/celeritas/CMakeLists.txt
  src/celeritas/Types.hh
  src/celeritas/global/ActionInterface.hh
  src/celeritas/global/alongstep/AlongStepGeneralLinearAction.hh
  src/celeritas/global/alongstep/AlongStepNeutralAction.cc
  src/celeritas/global/alongstep/AlongStepNeutralAction.hh
  src/celeritas/global/alongstep/AlongStepUniformMscAction.hh
  src/celeritas/phys/detail/PreStepActionImpl.hh
  src/celeritas/user/StepCollector.cc
  src/celeritas/user/StepCollector.hh
  src/celeritas/user/StepData.hh
  src/celeritas/user/StepInterface.hh
  src/celeritas/user/detail/StepGatherAction.cc
  src/celeritas/user/detail/StepGatherAction.cu
  src/celeritas/user/detail/StepGatherAction.hh
  src/celeritas/user/detail/StepGatherLauncher.hh
  src/celeritas/user/detail/StepStorage.hh
  src/corecel/Macros.hh
  src/corecel/data/Collection.hh
  test/CMakeLists.txt
  test/celeritas/SimpleTestBase.cc
  test/celeritas/global/AlongStep.test.cc
  test/celeritas/user/ExampleStepCallback.cc
  test/celeritas/user/ExampleStepCallback.hh
  test/celeritas/user/StepCollector.test.cc
  test/celeritas/user/StepCollectorTestBase.cc
  test/celeritas/user/StepCollectorTestBase.hh
Labels: enhancement, interface

#549 Add finer granularity to step collector
  src/celeritas/user/StepCollector.cc
  src/celeritas/user/StepCollector.hh
  src/celeritas/user/StepData.hh
  src/celeritas/user/StepInterface.hh
  src/celeritas/user/detail/StepGatherAction.cc
  src/celeritas/user/detail/StepGatherAction.hh
  src/celeritas/user/detail/StepGatherLauncher.hh
  test/celeritas/user/ExampleStepCallback.cc
  test/celeritas/user/ExampleStepCallback.hh
  test/celeritas/user/StepCollectorTestBase.cc
Labels: interface

#554 Enable resizing of CUDA malloc heap to fix VecGeom failures
  app/demo-loop/demo-loop.cc
  app/demo-rasterizer/demo-rasterizer.cc
  src/corecel/sys/Device.cc
  src/corecel/sys/Device.hh
Labels: enhancement, infrastructure

#555 Add detector mapping and filtering to hit collector
  doc/appendices/development.rst
  src/celeritas/Types.hh
  src/celeritas/user/StepCollector.cc
  src/celeritas/user/StepCollector.hh
  src/celeritas/user/StepData.hh
  src/celeritas/user/StepInterface.hh
  src/celeritas/user/detail/StepGatherLauncher.hh
  src/corecel/data/CollectionBuilder.hh
  test/CMakeLists.txt
  test/celeritas/user/CaloTestBase.cc
  test/celeritas/user/CaloTestBase.hh
  test/celeritas/user/ExampleCalorimeters.cc
  test/celeritas/user/ExampleCalorimeters.hh
  test/celeritas/user/ExampleMctruth.cc
  test/celeritas/user/ExampleMctruth.hh
  test/celeritas/user/MctruthTestBase.cc
  test/celeritas/user/MctruthTestBase.hh
  test/celeritas/user/StepCollector.test.cc
  test/celeritas/user/StepCollectorTestBase.hh
Labels: enhancement, interface

#547 Remove calls to host code from host-device Collection
  src/corecel/data/detail/CollectionImpl.hh
  src/corecel/data/detail/DisabledStorage.hh
Labels: bug, infrastructure

#562 Fix celeritas-gen when run from root directory
  scripts/dev/celeritas-gen.py
Labels: bug, infrastructure

#546 Add initialization of particles in multi-universe ORANGE geometries
  src/orange/BoundingBox.hh
  src/orange/CMakeLists.txt
  src/orange/OrangeData.hh
  src/orange/OrangeParams.cc
  src/orange/OrangeParams.hh
  src/orange/OrangeTrackView.hh
  src/orange/OrangeTypes.hh
  src/orange/construct/OrangeInputIO.json.cc
  src/orange/detail/UnitIndexer.cc
  src/orange/detail/UnitIndexer.hh
  src/orange/univ/VolumeView.hh
  test/orange/Orange.test.cc
  test/orange/data/universes.org.json
  test/orange/data/universes.org.omn
  test/orange/detail/UnitIndexer.test.cc
Labels: enhancement, geometry
