Repository celeritas-project/celeritas, pull requests merged in 2022-05, with the labels that each got.

#417 Pre-rename IWYU and minor class changes
  app/demo-loop/diagnostic/ParticleProcessDiagnostic.hh
  app/demo-loop/diagnostic/StepDiagnostic.hh
  cmake/CeleritasUtils/gen-interactor.py
  src/CMakeLists.txt
  src/base/ArrayUtils.hh
  src/base/Quantity.hh
  src/field/ZHelixStepper.hh
  src/io/EventReader.cc
  src/io/EventReader.hh
  src/io/EventReader.nohepmc.cc
  src/io/ImportProcess.hh
  src/io/detail/ImportProcessConverter.cc
  src/physics/base/PhysicsData.hh
  src/physics/base/PhysicsTrackView.hh
  src/physics/base/detail/AlongStepActionImpl.hh
  src/physics/em/EPlusGGMacroXsCalculator.hh
  src/physics/em/detail/KleinNishinaData.hh
  src/physics/em/detail/RBDiffXsCalculator.hh
  src/physics/em/detail/RBEnergySampler.hh
  src/physics/em/detail/RelativisticBremData.hh
  src/physics/em/detail/UrbanMscHelper.hh
  src/physics/em/detail/UrbanMscScatter.hh
  src/physics/em/detail/UrbanMscStepLimit.hh
  src/physics/em/generated/BetheHeitlerInteract.hh
  src/physics/em/generated/CombinedBremInteract.hh
  src/physics/em/generated/EPlusGGInteract.hh
  src/physics/em/generated/KleinNishinaInteract.hh
  src/physics/em/generated/LivermorePEInteract.hh
  src/physics/em/generated/MollerBhabhaInteract.hh
  src/physics/em/generated/MuBremsstrahlungInteract.hh
  src/physics/em/generated/RayleighInteract.hh
  src/physics/em/generated/RelativisticBremInteract.hh
  src/physics/em/generated/SeltzerBergerInteract.hh
  src/sim/detail/ProcessSecondariesLauncher.hh
  test/field/FieldPropagatorTestBase.hh
  test/geometry/GeoTestBase.hh
  test/io/EventReader.test.cc
  test/physics/em/CombinedBrem.test.cc
  test/physics/em/RelativisticBrem.test.cc
  test/physics/em/UrbanMsc.test.cc
  test/random/DiagnosticRngEngine.hh
Labels: infrastructure

#423 Add capability to import Geant4 EM parameters
  app/celer-dump-data.cc
  src/CMakeLists.txt
  src/celeritas/em/process/BremsstrahlungProcess.hh
  src/celeritas/ext/GeantImporter.cc
  src/celeritas/ext/GeantImporter.hh
  src/celeritas/ext/GeantSetup.cc
  src/celeritas/ext/GeantSetup.hh
  src/celeritas/ext/RootExporter.cc
  src/celeritas/ext/RootImporter.cc
  src/celeritas/io/ImportData.cc
  src/celeritas/io/ImportData.hh
  test/celeritas/data/four-steel-slabs.root
  test/celeritas/data/simple-cms.root
  test/celeritas/ext/RootImporter.test.cc
  test/celeritas/geo/GeoMaterial.test.cc
Labels: interface

#426 Initialize states with garbage on host in debug mode
  app/demo-interactor/DetectorData.hh
  app/demo-loop/LDemoIO.cc
  src/celeritas/em/data/AtomicRelaxationData.hh
  src/celeritas/em/xs/EPlusGGMacroXsCalculator.hh
  src/celeritas/ext/VecgeomData.hh
  src/celeritas/ext/VecgeomParams.hh
  src/celeritas/ext/VecgeomTrackView.hh
  src/celeritas/global/CoreParams.hh
  src/celeritas/mat/MaterialData.hh
  src/celeritas/phys/ParticleData.hh
  src/celeritas/phys/PhysicsData.hh
  src/celeritas/phys/PhysicsParams.cc
  src/celeritas/random/CuHipRngData.cc
  src/celeritas/random/XorwowRngData.cc
  src/celeritas/track/TrackInitData.hh
  src/celeritas/track/TrackInitUtils.hh
  src/corecel/data/CollectionBuilder.hh
  src/corecel/data/CollectionMirror.hh
  src/corecel/data/CollectionStateStore.hh
  src/corecel/data/StackAllocatorData.hh
  src/corecel/data/detail/FillInvalid.hh
  src/corecel/io/OutputManager.cc
  src/corecel/io/OutputManager.hh
  src/orange/Data.hh
  src/orange/OrangeParams.cc
  src/orange/OrangeParams.hh
  test/celeritas/GlobalTestBase.cc
  test/celeritas/em/LivermorePE.test.cc
  test/celeritas/phys/Physics.test.cc
  test/celeritas/track/TrackInit.test.cc
  test/corecel/data/Collection.test.cc
  test/orange/surf/SurfaceAction.test.hh
  test/orange/univ/SimpleUnitTracker.test.cc
Labels: housekeeping

#428 Minor changes to magnetic field in preparation for AlongStep integration
  doc/CMakeLists.txt
  src/celeritas/field/DormandPrinceStepper.hh
  src/celeritas/field/FieldDriver.hh
  src/celeritas/field/FieldDriverOptions.hh
  src/celeritas/field/FieldPropagator.hh
  src/celeritas/field/MagFieldEquation.hh
  src/celeritas/field/MagFieldTraits.hh
  src/celeritas/field/MakeMagFieldPropagator.hh
  src/celeritas/field/RungeKuttaStepper.hh
  src/celeritas/field/UniformField.hh
  src/celeritas/field/UniformZField.hh
  src/celeritas/field/ZHelixStepper.hh
  src/corecel/data/detail/FillInvalid.hh
  test/celeritas/field/FieldDriver.test.cc
  test/celeritas/field/FieldDriver.test.cu
  test/celeritas/field/FieldDriver.test.hh
  test/celeritas/field/FieldPropagator.test.cc
  test/celeritas/field/FieldPropagator.test.cu
  test/celeritas/field/FieldPropagator.test.hh
  test/celeritas/field/FieldPropagatorTestBase.hh
  test/celeritas/field/MagFieldTraits.hh
  test/celeritas/field/Steppers.test.cc
  test/celeritas/field/Steppers.test.cu
  test/celeritas/field/Steppers.test.hh
  test/celeritas/field/UserMapField.test.cc
  test/celeritas/field/UserMapField.test.cu
  test/celeritas/field/UserParamField.test.cc
  test/celeritas/field/UserParamField.test.cu
  test/celeritas/field/detail/MagTestTraits.hh
Labels: propagation, housekeeping

#433 Noexcept/cxx17 fixes
  src/celeritas/random/Selector.hh
  test/corecel/sys/ScopedSignalHandler.test.cc
Labels: bug, infrastructure

#432 Support external installation
  .gitignore
  CMakeLists.txt
  app/CMakeLists.txt
  cmake/CeleritasConfig.cmake.in
  cmake/CeleritasGen.cmake
  cmake/CeleritasGen/gen-action.py
  cmake/CeleritasGen/gen-interactor.py
  cmake/CeleritasGen/gen-trackinit.py
  cmake/CeleritasGen/launch-bounds.json
  cmake/CeleritasGen/launchbounds.py
  cmake/CeleritasLibrary.cmake
  cmake/CeleritasUtils.cmake
  interface/CMakeLists.txt
  scripts/cmake-presets/wildstyle.json
  scripts/cmake-presets/yuri.json
  src/CMakeLists.txt
  test/CMakeLists.txt
Labels: infrastructure
