Repository celeritas-project/celeritas, pull requests merged in 2022-04, with the labels that each got.

#395 Tweak MSC implementation
  app/demo-loop/LDemoLauncher.hh
  src/base/Algorithms.hh
  src/physics/base/Interaction.hh
  src/physics/base/PhysicsData.hh
  src/physics/base/PhysicsTrackView.hh
  src/physics/em/detail/UrbanMscData.hh
  src/physics/em/detail/UrbanMscHelper.hh
  src/physics/em/detail/UrbanMscScatter.hh
  src/physics/em/detail/UrbanMscStepLimit.hh
  test/CMakeLists.txt
  test/base/Algorithms.test.cc
  test/gtest/detail/Macros.hh
  test/physics/em/UrbanMsc.test.cc
Labels: physics

#396 Add a Dormand-Prince stepper
  src/field/DormandPrinceStepper.hh
  src/field/RungeKuttaStepper.hh
  test/CMakeLists.txt
  test/field/Steppers.test.cc
  test/field/Steppers.test.cu
  test/field/Steppers.test.hh
Labels: propagation

#397 Work around Geant4 include propagation
  CMakeLists.txt
  scripts/cmake-presets/wildstyle.json
Labels: infrastructure

#399 Fix error in FieldDriver
  src/field/FieldDriver.hh
Labels: propagation

#400 Add polynomial evaluator
  src/physics/em/UrbanMscModel.cc
  src/physics/em/detail/LPMCalculator.hh
  src/physics/em/detail/LivermorePEInteractor.hh
  src/physics/em/detail/LivermorePEMicroXsCalculator.hh
  src/physics/em/detail/UrbanMscScatter.hh
  src/physics/em/detail/UrbanMscStepLimit.hh
  src/physics/grid/PolyEvaluator.hh
  test/CMakeLists.txt
  test/physics/em/UrbanMsc.test.cc
  test/physics/grid/PolyEvaluator.test.cc
Labels: physics

#401 Seltzer-Berger positron correction fix
  src/io/detail/GeantPhysicsList.cc
  src/physics/em/SeltzerBergerModel.cc
  src/physics/em/SeltzerBergerModel.hh
  src/physics/em/detail/CombinedBremInteractor.hh
  src/physics/em/detail/SBEnergyDistHelper.hh
  src/physics/em/detail/SBEnergyDistribution.hh
  src/physics/em/detail/SBPositronXsCorrector.hh
  src/physics/em/detail/SeltzerBergerInteractor.hh
  test/physics/em/CombinedBrem.test.cc
  test/physics/em/SeltzerBerger.test.cc
Labels: bug, physics

#404 Add a simple in-house XORWOW implementation
  CMakeLists.txt
  app/CMakeLists.txt
  app/demo-interactor/KNDemoRunner.cc
  app/demo-loop/Transporter.cc
  app/demo-loop/Transporter.hh
  scripts/cmake-presets/wildstyle.json
  src/CMakeLists.txt
  src/base/Macros.hh
  src/celeritas_config.h.in
  src/physics/base/PhysicsParams.hh
  src/physics/base/detail/AlongStepActionImpl.hh
  src/physics/base/detail/PreStepActionImpl.hh
  src/random/CuHipRngData.cc
  src/random/CuHipRngData.hh
  src/random/CuHipRngEngine.hh
  src/random/CuHipRngParams.hh
  src/random/RngData.hh
  src/random/RngEngine.hh
  src/random/RngParams.hh
  src/random/XorwowRngData.cc
  src/random/XorwowRngData.hh
  src/random/XorwowRngEngine.hh
  src/random/XorwowRngParams.cc
  src/random/XorwowRngParams.hh
  src/random/detail/CuHipRngStateInit.cc
  src/random/detail/CuHipRngStateInit.cu
  src/random/detail/CuHipRngStateInit.hh
  src/random/detail/GenerateCanonical32.hh
  src/random/detail/RngStateInit.cc
  src/random/detail/RngStateInit.nocuda.cc
  src/random/detail/mockrand.hh
  src/sim/ActionInterface.cc
  test/CMakeLists.txt
  test/physics/base/Physics.test.cc
  test/physics/base/PhysicsStepUtils.test.cc
  test/physics/base/PhysicsTestBase.cc
  test/physics/base/PhysicsTestBase.hh
  test/random/RngEngine.test.cc
  test/random/SequenceEngine.hh
  test/random/XorwowRngEngine.test.cc
  test/random/curand/CurandPerformance.test.cc
  test/sim/TrackInit.test.hh
Labels: infrastructure

#408 Update "interact" as "execute"
  src/CMakeLists.txt
  src/physics/base/Model.cc
  src/physics/base/Model.hh
  src/physics/em/BetheHeitlerModel.cc
  src/physics/em/BetheHeitlerModel.hh
  src/physics/em/CombinedBremModel.cc
  src/physics/em/CombinedBremModel.hh
  src/physics/em/EPlusGGModel.cc
  src/physics/em/EPlusGGModel.hh
  src/physics/em/KleinNishinaModel.cc
  src/physics/em/KleinNishinaModel.hh
  src/physics/em/LivermorePEModel.cc
  src/physics/em/LivermorePEModel.hh
  src/physics/em/MollerBhabhaModel.cc
  src/physics/em/MollerBhabhaModel.hh
  src/physics/em/MuBremsstrahlungModel.cc
  src/physics/em/MuBremsstrahlungModel.hh
  src/physics/em/RayleighModel.cc
  src/physics/em/RayleighModel.hh
  src/physics/em/RelativisticBremModel.cc
  src/physics/em/RelativisticBremModel.hh
  src/physics/em/SeltzerBergerModel.cc
  src/physics/em/SeltzerBergerModel.hh
  src/physics/em/UrbanMscModel.cc
  src/physics/em/UrbanMscModel.hh
  src/physics/material/MaterialData.hh
  src/physics/material/MaterialParams.hh
  src/physics/material/detail/Utils.cc
  src/random/CuHipRngData.hh
  src/random/XorwowRngData.hh
  test/physics/base/MockModel.cc
  test/physics/base/MockModel.hh
  test/physics/base/Physics.test.cc
  test/physics/em/ImportedProcesses.test.cc
Labels: infrastructure

#406 Add demonstration-use ORANGE safety distance
  src/orange/Data.hh
  src/orange/OrangeParams.cc
  src/orange/OrangeTrackView.hh
  src/orange/construct/VolumeInserter.cc
  src/orange/construct/VolumeInserter.hh
  src/orange/surfaces/CylCentered.hh
  src/orange/surfaces/GeneralQuadric.hh
  src/orange/surfaces/PlaneAligned.hh
  src/orange/surfaces/Sphere.hh
  src/orange/surfaces/SphereCentered.hh
  src/orange/universes/SimpleUnitTracker.hh
  src/orange/universes/VolumeView.hh
  src/orange/universes/detail/LogicStack.hh
  src/orange/universes/detail/SurfaceFunctors.hh
  test/CMakeLists.txt
  test/io/RootImporter.test.cc
  test/io/data/four-steel-slabs.gdml
  test/io/data/four-steel-slabs.org.json
  test/io/data/four-steel-slabs.org.omn
  test/io/data/four-steel-slabs.root
  test/orange/Orange.test.cc
  test/orange/OrangeGeoTestBase.cc
  test/orange/construct/VolumeInserter.test.cc
  test/orange/universes/SimpleUnitTracker.test.cc
  test/physics/base/CutoffParams.test.cc
  test/physics/base/Particle.test.cc
  test/physics/em/ImportedProcesses.test.cc
  test/physics/em/UrbanMsc.test.cc
  test/physics/material/Material.test.cc
Labels: geometry

#411 Add output manager
  app/demo-loop/Transporter.hh
  app/demo-loop/Transporter.json.hh
  app/demo-loop/demo-loop.cc
  app/demo-loop/simple-driver.py
  src/CMakeLists.txt
  src/base/EnumArray.hh
  src/celeritas_cmake_strings.h.in
  src/comm/BuildOutput.cc
  src/comm/BuildOutput.hh
  src/physics/base/PhysicsParams.cc
  src/physics/base/PhysicsParamsOutput.cc
  src/physics/base/PhysicsParamsOutput.hh
  src/sim/ActionManager.cc
  src/sim/ActionManager.hh
  src/sim/ActionManagerOutput.cc
  src/sim/ActionManagerOutput.hh
  src/sim/JsonPimpl.hh
  src/sim/OutputInterface.cc
  src/sim/OutputInterface.hh
  src/sim/OutputInterfaceAdapter.hh
  src/sim/OutputManager.cc
  src/sim/OutputManager.hh
  test/CMakeLists.txt
  test/physics/base/Physics.test.cc
  test/sim/ActionManager.test.cc
  test/sim/OutputManager.test.cc
Labels: interface

#402 Add CLHEP/Celeritas constant conversion tests
  src/base/Constants.hh
  test/CMakeLists.txt
  test/base/Constants.test.cc
Labels: physics

#414 Add geant setup options to configure bins per decade
  app/celer-export-geant.cc
  app/demo-loop/LDemoIO.cc
  app/demo-loop/LDemoIO.hh
  src/CMakeLists.txt
  src/base/Assert.hh
  src/io/GeantSetup.cc
  src/io/GeantSetup.hh
  src/io/GeantSetupOptionsIO.json.cc
  src/io/GeantSetupOptionsIO.json.hh
  src/io/detail/GeantPhysicsList.cc
  test/CMakeLists.txt
  test/sim/OutputManager.test.cc
Labels: physics, integration

#415 Support multiple signals for a single handler
  app/demo-loop/Transporter.cc
  scripts/cmake-presets/summit.json
  scripts/dev/run-cloc.sh
  src/CMakeLists.txt
  src/celeritas_config.h.in
  src/comm/BuildOutput.cc
  src/comm/Device.cc
  src/comm/ScopedSignalHandler.cc
  src/comm/ScopedSignalHandler.hh
  test/comm/ScopedSignalHandler.test.cc
Labels: infrastructure
