Repository celeritas-project/celeritas, pull requests merged in 2022-12, with the labels that each got.

#564 Add ROOT MC truth output
  app/CMakeLists.txt
  app/demo-loop/LDemoIO.cc
  app/demo-loop/LDemoIO.hh
  app/demo-loop/LDemoIO.root.cc
  app/demo-loop/demo-loop.cc
  app/demo-loop/simple-driver.py
  src/celeritas/CMakeLists.txt
  src/celeritas/ext/RootExporter.hh
  src/celeritas/ext/RootImporter.hh
  src/celeritas/ext/ScopedRootErrorHandler.hh
  src/celeritas/ext/detail/RootUniquePtr.hh
  src/celeritas/ext/detail/RootUniquePtr.root.cc
  src/celeritas/io/RootFileManager.cc
  src/celeritas/io/RootFileManager.hh
  src/celeritas/io/RootStepWriter.cc
  src/celeritas/io/RootStepWriter.hh
  src/celeritas/user/DetectorSteps.cc
  src/celeritas/user/DetectorSteps.cu
  src/celeritas/user/DetectorSteps.hh
  src/celeritas/user/StepData.hh
  src/celeritas/user/detail/StepGatherLauncher.hh
  test/celeritas/user/DetectorSteps.test.cc
  test/celeritas/user/ExampleCalorimeters.cc
  test/celeritas/user/ExampleMctruth.cc
Labels: enhancement, interface

#558 Fix and work around some issues on HIP/Crusher
  cmake/CeleritasUtils.cmake
  scripts/cmake-presets/crusher.json
  scripts/cmake-presets/summit.json
  scripts/env/crusher.sh
  src/celeritas/ext/RootImporter.cc
  src/celeritas/ext/ScopedRootErrorHandler.cc
  src/corecel/Assert.hh
  src/corecel/Macros.hh
Labels: infrastructure

#568 Fix git-clang-format hook and code documentation
  app/celer-dump-data.cc
  app/celer-export-geant.cc
  app/demo-loop/demo-loop.cc
  scripts/dev/post-commit.git-clang-format
  src/celeritas/ext/detail/GeantLoggerAdapter.cc
  src/corecel/io/Logger.cc
  src/corecel/sys/Device.cc
  src/corecel/sys/Device.hh
Labels: infrastructure, housekeeping

#571 Fix build documentation and issues with newer toolchains
  CMakeLists.txt
  README.md
  doc/appendices/development.rst
  doc/infrastructure.rst
  interface/CMakeLists.txt
  scripts/README.md
  scripts/cmake-presets/goldfinger.json
  scripts/dev/iwyu-apple-clang.imp
  scripts/dev/run-iwyu.sh
  scripts/spack.yaml
  src/corecel/Types.hh
Labels: bug, documentation, infrastructure

#572 Change Transport/Stepper interfaces to take span of `Primary` instead of vector
  app/demo-loop/Transporter.cc
  app/demo-loop/Transporter.hh
  app/demo-loop/demo-loop.cc
  src/celeritas/global/Stepper.cc
  src/celeritas/global/Stepper.hh
  src/celeritas/track/TrackInitUtils.hh
  test/celeritas/global/AlongStepTestBase.cc
  test/celeritas/global/Stepper.test.cc
  test/celeritas/global/StepperTestBase.cc
  test/celeritas/track/TrackInit.test.cc
  test/celeritas/user/CaloTestBase.cc
  test/celeritas/user/MctruthTestBase.cc
  test/celeritas/user/StepCollector.test.cc
Labels: infrastructure, housekeeping

#567 Add skeleton classes for Celeritas/Geant4 integration
  .clang-format
  app/CMakeLists.txt
  app/celer-export-geant.cc
  app/demo-geant-integration/ActionInitialization.cc
  app/demo-geant-integration/ActionInitialization.hh
  app/demo-geant-integration/DetectorConstruction.cc
  app/demo-geant-integration/DetectorConstruction.hh
  app/demo-geant-integration/GlobalSetup.cc
  app/demo-geant-integration/GlobalSetup.hh
  app/demo-geant-integration/PrimaryGeneratorAction.cc
  app/demo-geant-integration/PrimaryGeneratorAction.hh
  app/demo-geant-integration/SensitiveDetector.cc
  app/demo-geant-integration/SensitiveDetector.hh
  app/demo-geant-integration/demo-geant-integration.cc
  app/demo-geant-integration/simple-cms-test.mac.in
  doc/appendices/development.rst
  scripts/dev/iwyu-apple-clang.imp
  scripts/dev/run-iwyu.sh
  src/CMakeLists.txt
  src/accel/CMakeLists.txt
  src/accel/EventAction.cc
  src/accel/EventAction.hh
  src/accel/InitializeActions.cc
  src/accel/InitializeActions.hh
  src/accel/Logger.cc
  src/accel/Logger.hh
  src/accel/RunAction.cc
  src/accel/RunAction.hh
  src/accel/SetupOptions.hh
  src/accel/SharedParams.hh
  src/accel/TrackingAction.cc
  src/accel/TrackingAction.hh
  src/celeritas/ext/GeantImporter.cc
  src/celeritas/ext/GeantSetup.cc
  src/celeritas/ext/GeantSetup.hh
  src/celeritas/ext/GeantVersion.hh
  src/celeritas/ext/detail/ImportProcessConverter.cc
Labels: enhancement, integration

#566 CI: use Geant4 11, C++17, VecGeom 1.2, CUDA 11.8, GCC 11
  .jenkins
  scripts/cmake-presets/ci.json
  scripts/cmake-presets/wildstyle.json
  scripts/docker/build.sh
  scripts/docker/ci/Dockerfile
  scripts/docker/ci/launch-local-test.sh
  scripts/docker/dev/bionic-minimal.yaml
  scripts/docker/dev/jammy-cuda11.yaml
  scripts/spack.yaml
  test/celeritas/GeantTestBase.cc
  test/celeritas/global/Stepper.test.cc
  test/celeritas/user/StepCollector.test.cc
Labels: infrastructure

#569 CI: add no-debug HIP (ROCM 5.4) build
  .jenkins
  CMakePresets.json
  scripts/ci/run-ci.sh
  scripts/cmake-presets/ci-bionic-minimal.json
  scripts/cmake-presets/ci-centos-rocm.json
  scripts/cmake-presets/ci-jammy-cuda.json
  scripts/docker/build.sh
  scripts/docker/ci/Dockerfile
  scripts/docker/dev/Dockerfile
  scripts/docker/dev/centos7-rocm5.yaml
  src/corecel/Assert.hh
  src/corecel/data/detail/Filler.cu
  src/corecel/data/detail/Filler.hh
  src/corecel/sys/KernelParamCalculator.device.hh
  test/celeritas/random/SequenceEngine.hh
Labels: infrastructure

#575 Add thread-local transporter and Celeritas shared params setup to Acceleritas
  src/accel/CMakeLists.txt
  src/accel/EventAction.cc
  src/accel/EventAction.hh
  src/accel/InitializeActions.cc
  src/accel/RunAction.cc
  src/accel/RunAction.hh
  src/accel/TrackingAction.cc
  src/accel/TrackingAction.hh
  src/accel/detail/LocalTransporter.cc
  src/accel/detail/LocalTransporter.hh
Labels: integration

#577 Refactor geant demo app and `accel` code
  app/CMakeLists.txt
  app/demo-geant-integration/ActionInitialization.cc
  app/demo-geant-integration/EventAction.cc
  app/demo-geant-integration/EventAction.hh
  app/demo-geant-integration/GlobalSetup.cc
  app/demo-geant-integration/GlobalSetup.hh
  app/demo-geant-integration/RunAction.cc
  app/demo-geant-integration/RunAction.hh
  app/demo-geant-integration/TrackingAction.cc
  app/demo-geant-integration/TrackingAction.hh
  src/accel/CMakeLists.txt
  src/accel/InitializeActions.cc
  src/accel/InitializeActions.hh
  src/accel/LocalTransporter.cc
  src/accel/LocalTransporter.hh
  src/accel/SetupOptions.hh
  src/accel/SharedParams.cc
  src/accel/SharedParams.hh
  src/accel/detail/LocalTransporter.cc
  src/accel/detail/LocalTransporter.hh
  src/corecel/sys/Device.cc
Labels: integration, housekeeping

#580 Add Geant4 Exception converter
  app/demo-geant-integration/DetectorConstruction.cc
  app/demo-geant-integration/EventAction.cc
  app/demo-geant-integration/RunAction.cc
  app/demo-geant-integration/TrackingAction.cc
  src/accel/CMakeLists.txt
  src/accel/ExceptionConverter.cc
  src/accel/ExceptionConverter.hh
  src/corecel/Assert.hh
  src/corecel/Macros.hh
  src/corecel/sys/MultiExceptionHandler.hh
  test/CMakeLists.txt
  test/accel/ExceptionConverter.test.cc
Labels: integration

#582 Convert Thrust exceptions to Geant4
  src/accel/CMakeLists.txt
  src/accel/ExceptionConverter.cc
  src/accel/ExceptionConverter.cu
  src/accel/ExceptionConverter.hh
Labels: enhancement, infrastructure

#584 Add clang address sanitizer to CI
  .jenkins
  scripts/ci/run-ci.sh
  scripts/cmake-presets/ci-centos-rocm.json
  scripts/cmake-presets/ci-ubuntu-cuda.json
  scripts/cmake-presets/ci-ubuntu-minimal.json
  scripts/docker/ci/launch-local-test.sh
  scripts/env/ci-centos-rocm.sh
Labels: infrastructure

#585 Auto-export GDML from Geant4 geometry
  app/demo-geant-integration/DetectorConstruction.cc
  app/demo-geant-integration/GlobalSetup.cc
  app/demo-geant-integration/GlobalSetup.hh
  app/demo-geant-integration/MasterRunAction.cc
  app/demo-geant-integration/RunAction.cc
  src/accel/SetupOptions.hh
  src/accel/SharedParams.cc
  src/accel/SharedParams.hh
  src/celeritas/CMakeLists.txt
  src/celeritas/ext/GeantImporter.cc
  src/celeritas/ext/GeantImporter.hh
  src/celeritas/ext/VecgeomParams.cc
  src/celeritas/ext/VecgeomParams.hh
  src/celeritas/ext/detail/GeantGeoExporter.cc
  src/celeritas/ext/detail/GeantGeoExporter.hh
  src/orange/OrangeParams.cc
  src/orange/OrangeParams.hh
  test/celeritas/GeantTestBase.cc
  test/celeritas/GeantTestBase.hh
  test/celeritas/GlobalGeoTestBase.cc
  test/celeritas/GlobalGeoTestBase.hh
  test/celeritas/OnlyGeoTestBase.hh
  test/celeritas/data/solids.gdml
  test/celeritas/ext/Vecgeom.test.cc
  test/celeritas/field/FieldPropagator.test.cc
  test/celeritas/field/LinearPropagator.test.cc
  test/celeritas/geo/GeoMaterial.test.cc
  test/celeritas/geo/HeuristicGeoTestBase.hh
Labels: geometry, integration
