Repository celeritas-project/celeritas, pull requests merged in 2022-10, with the labels that each got.

#521 Fix the true path length limit of UrbanMsc
  src/celeritas/em/data/UrbanMscData.hh
  src/celeritas/em/distribution/UrbanMscStepLimit.hh
  src/celeritas/em/model/UrbanMscModel.cc
  src/celeritas/global/alongstep/detail/UrbanMsc.hh
  test/celeritas/em/UrbanMsc.test.cc
  test/celeritas/global/Stepper.test.cc
Labels: bug, physics

#520 Refactor ORANGE data and simple tracker to support nested universes
  src/CMakeLists.txt
  src/celeritas/track/TrackInitUtils.hh
  src/corecel/OpaqueId.hh
  src/orange/Data.hh
  src/orange/OrangeParams.cc
  src/orange/OrangeTrackView.hh
  src/orange/Types.hh
  src/orange/construct/OrangeInput.hh
  src/orange/construct/OrangeInputIO.json.cc
  src/orange/detail/SurfaceInserter.cc
  src/orange/detail/SurfaceInserter.hh
  src/orange/detail/UnitInserter.cc
  src/orange/detail/UnitInserter.hh
  src/orange/detail/VolumeInserter.cc
  src/orange/detail/VolumeInserter.hh
  src/orange/surf/SurfaceTypeTraits.hh
  src/orange/surf/Surfaces.hh
  src/orange/univ/SimpleUnitTracker.hh
  src/orange/univ/UniverseTypeTraits.hh
  src/orange/univ/VolumeView.hh
  test/corecel/OpaqueId.test.cc
  test/orange/Orange.test.cc
  test/orange/OrangeGeoTestBase.cc
  test/orange/surf/SurfaceAction.test.cc
  test/orange/surf/SurfaceAction.test.hh
  test/orange/univ/SimpleUnitTracker.test.cc
  test/orange/univ/SimpleUnitTracker.test.hh
  test/orange/univ/VolumeView.test.cc
  test/orange/univ/detail/SenseCalculator.test.cc
  test/orange/univ/detail/SurfaceFunctors.test.cc
Labels: geometry

#522 Define gauss as internal field strength and use tesla for input
  app/demo-loop/LDemoIO.cc
  app/demo-loop/LDemoIO.hh
  doc/api/celeritas.rst
  doc/api/corecel.rst
  src/celeritas/Constants.hh
  src/celeritas/Quantities.hh
  src/celeritas/Units.hh
  test/celeritas/Constants.test.cc
  test/celeritas/field/FieldPropagator.test.cc
  test/celeritas/field/Fields.test.cc
  test/celeritas/field/MagFieldEquation.test.cc
  test/celeritas/global/Stepper.test.cc
Labels: physics, housekeeping

#525 Support arbitrary user/internal kernels as part of stepping loop
  app/demo-loop/LDemoIO.cc
  app/demo-loop/Transporter.cc
  app/demo-loop/Transporter.hh
  app/demo-loop/Transporter.json.hh
  app/demo-loop/demo-loop.cc
  cmake/CeleritasGen/gen-action.py
  src/CMakeLists.txt
  src/celeritas/Types.cc
  src/celeritas/Types.hh
  src/celeritas/geo/generated/BoundaryAction.hh
  src/celeritas/global/ActionInterface.hh
  src/celeritas/global/ActionManager.cc
  src/celeritas/global/ActionRegistry.cc
  src/celeritas/global/ActionRegistry.hh
  src/celeritas/global/ActionRegistryOutput.cc
  src/celeritas/global/ActionRegistryOutput.hh
  src/celeritas/global/CoreParams.cc
  src/celeritas/global/CoreParams.hh
  src/celeritas/global/Stepper.cc
  src/celeritas/global/Stepper.hh
  src/celeritas/global/alongstep/AlongStepGeneralLinearAction.cc
  src/celeritas/global/alongstep/AlongStepGeneralLinearAction.hh
  src/celeritas/global/alongstep/AlongStepNeutralAction.hh
  src/celeritas/global/alongstep/AlongStepUniformMscAction.cc
  src/celeritas/global/alongstep/AlongStepUniformMscAction.hh
  src/celeritas/global/detail/ActionSequence.cc
  src/celeritas/global/detail/ActionSequence.hh
  src/celeritas/phys/Model.hh
  src/celeritas/phys/PhysicsParams.cc
  src/celeritas/phys/PhysicsParams.hh
  src/celeritas/phys/generated/DiscreteSelectAction.hh
  src/celeritas/phys/generated/PreStepAction.hh
  test/CMakeLists.txt
  test/celeritas/GeantTestBase.cc
  test/celeritas/GlobalTestBase.cc
  test/celeritas/GlobalTestBase.hh
  test/celeritas/MockTestBase.cc
  test/celeritas/SimpleTestBase.cc
  test/celeritas/em/UrbanMsc.test.cc
  test/celeritas/global/ActionRegistry.test.cc
  test/celeritas/global/AlongStepTestBase.cc
  test/celeritas/global/DummyAction.hh
  test/celeritas/global/Stepper.test.cc
  test/celeritas/global/StepperTestBase.cc
  test/celeritas/global/StepperTestBase.hh
  test/celeritas/phys/MockProcess.cc
  test/celeritas/phys/Physics.test.cc
Labels: integration

#527 Calculate range properties of multiple scattering at the first step in every tracking step
  src/celeritas/em/distribution/UrbanMscScatter.hh
  src/celeritas/em/distribution/UrbanMscStepLimit.hh
  src/celeritas/global/alongstep/detail/UrbanMsc.hh
  src/celeritas/phys/Interaction.hh
  src/celeritas/phys/PhysicsData.hh
  src/celeritas/phys/PhysicsTrackView.hh
  test/celeritas/em/UrbanMsc.test.cc
  test/celeritas/global/Stepper.test.cc
Labels: physics

#528 Reset physics state when a secondary is initialized in the parent's track slot
  src/celeritas/track/detail/ProcessSecondariesLauncher.hh
Labels: bug, physics

#529 Improve CMake version/host metadata
  CMakeLists.txt
  cmake/CgvFindVersion.cmake
  doc/CMakeLists.txt
  doc/appendices/administration.rst
  doc/config.json.in
  scripts/docker/ci/run-ci.sh
  src/CMakeLists.txt
  src/corecel/io/BuildOutput.cc
Labels: infrastructure

#531 Baby steps toward Geant4 integration
  app/CMakeLists.txt
  app/celer-dump-data.cc
  app/demo-loop/LDemoIO.cc
  cmake/CeleritasAddTest.cmake
  src/CMakeLists.txt
  src/celeritas/ext/GeantImporter.cc
  src/celeritas/ext/GeantSetup.cc
  src/celeritas/ext/LoadGdml.cc
  src/celeritas/ext/RootInterfaceLinkDef.h
  src/celeritas/ext/VecgeomParams.cc
  src/celeritas/geo/GeoMaterialParams.cc
  src/celeritas/geo/GeoMaterialParams.hh
  src/celeritas/global/CoreParams.cc
  src/celeritas/global/CoreParams.hh
  src/celeritas/global/alongstep/AlongStepGeneralLinearAction.cc
  src/celeritas/global/alongstep/AlongStepGeneralLinearAction.hh
  src/celeritas/global/alongstep/AlongStepUniformMscAction.cc
  src/celeritas/global/alongstep/AlongStepUniformMscAction.hh
  src/celeritas/global/detail/ActionSequence.cc
  src/celeritas/io/ImportData.cc
  src/celeritas/io/ImportData.hh
  src/celeritas/phys/CutoffParams.hh
  src/celeritas/phys/PhysicsData.hh
  src/celeritas/phys/PhysicsParams.cc
  src/celeritas/phys/PhysicsParams.hh
  src/celeritas/phys/PhysicsParamsOutput.cc
  src/celeritas/phys/PhysicsTrackView.hh
  src/celeritas/phys/ProcessBuilder.cc
  src/corecel/sys/Device.cc
  src/corecel/sys/Device.hh
  src/corecel/sys/KernelDiagnostics.hh
  src/corecel/sys/KernelParamCalculator.device.cc
  test/CMakeLists.txt
  test/celeritas/GeantTestBase.cc
  test/celeritas/GlobalTestBase.cc
  test/celeritas/MockTestBase.cc
  test/celeritas/data/four-steel-slabs.root
  test/celeritas/ext/GeantImporter.test.cc
  test/celeritas/global/Stepper.test.cc
  test/celeritas/phys/Physics.test.cc
Labels: integration

#526 Break library into multiple parts and mirror install tree
  .clang-format
  CMakeLists.txt
  app/CMakeLists.txt
  app/celer-dump-data.cc
  app/celer-export-geant.cc
  app/demo-interactor/demo-interactor.cc
  app/demo-interactor/host-demo-interactor.cc
  app/demo-loop/demo-loop.cc
  app/demo-rasterizer/demo-rasterizer.cc
  cmake/CeleritasAddTest.cmake
  cmake/CeleritasConfig.cmake.in
  cmake/CeleritasGen/gen-action.py
  cmake/CeleritasGen/gen-interactor.py
  cmake/CeleritasGen/gen-trackinit.py
  cmake/CeleritasLibrary.cmake
  cmake/CeleritasUtils.cmake
  doc/CMakeLists.txt
  interface/CMakeLists.txt
  src/CMakeLists.txt
  src/celeritas/CMakeLists.txt
  src/celeritas_version.cc.in
  src/celeritas_version.h.in
  src/corecel/CMakeLists.txt
  src/corecel/io/BuildOutput.cc
  src/corecel/io/Logger.cc
  src/corecel/sys/Device.cc
  src/corecel/sys/MpiCommunicator.cc
  src/corecel/sys/MpiCommunicator.hh
  src/corecel/sys/MpiOperations.hh
  src/corecel/sys/ScopedMpiInit.cc
  src/corecel/sys/ScopedMpiInit.hh
  src/corecel/sys/detail/MpiTypes.hh
  src/corecel/sys/detail/MpiTypes.mpi.hh
  src/corecel/sys/detail/MpiTypes.nompi.hh
  src/orange/CMakeLists.txt
  test/CMakeLists.txt
  test/celeritas/GeantTestBase.cc
  test/corecel/io/Logger.test.cc
  test/corecel/sys/MpiCommunicator.test.cc
  test/testdetail/ParallelHandler.cc
  test/testdetail/TestConfig.cc.in
  test/testdetail/TestMainImpl.cc
Labels: infrastructure, housekeeping

#533 Add DOE DOI and improve PR process documentation
  CONTRIBUTING.rst
  README.md
  doc/_static/celeritas.bib
  doc/_static/references.bib
  doc/appendices/administration.rst
  doc/appendices/development.rst
  doc/conf.py
Labels: documentation

#536 Fix JSON build issues
  app/CMakeLists.txt
  src/celeritas/phys/PhysicsParamsOutput.cc
  test/CMakeLists.txt
  test/celeritas/phys/PrimaryGenerator.test.cc
Labels: bug, infrastructure

#537 Fix library location and configure issues from #526
  .jenkins
  CMakeLists.txt
  cmake/CeleritasConfig.cmake.in
  cmake/CeleritasUtils.cmake
  cmake/CgvFindVersion.cmake
  scripts/ci/run-ci.sh
  scripts/ci/test-installation.sh
  scripts/ci/test-installation/.gitignore
  scripts/ci/test-installation/CMakeLists.txt
  scripts/ci/test-installation/cmake/FindCeleritas.cmake
  scripts/ci/test-installation/example.cc
  scripts/cmake-presets/ci.json
  scripts/docker/ci/launch-local-test.sh
  scripts/docker/ci/run-ci.sh
  src/celeritas/CMakeLists.txt
  src/corecel/CMakeLists.txt
  test/CMakeLists.txt
Labels: bug, infrastructure
