Repository celeritas-project/celeritas, pull requests merged in 2022-08, with the labels that each got.

#472 Fix uninitialized data access in primary generator
  src/celeritas/phys/PDGNumber.hh
  src/celeritas/phys/Primary.hh
  src/celeritas/phys/PrimaryGenerator.cc
  src/celeritas/phys/PrimaryGenerator.hh
  src/celeritas/phys/PrimaryGeneratorOptionsIO.json.cc
  test/CMakeLists.txt
  test/celeritas/phys/PrimaryGenerator.test.cc
Labels: bug

#471 Rewrite field tests including two failing ones
  scripts/cmake-presets/goldfinger.json
  src/celeritas/field/FieldDriver.hh
  src/celeritas/field/FieldPropagator.hh
  src/celeritas/global/alongstep/AlongStep.hh
  test/CMakeLists.txt
  test/celeritas/SimpleTestBase.cc
  test/celeritas/data/field-test.org.py
  test/celeritas/data/two-boxes.gdml
  test/celeritas/data/two-boxes.org.json
  test/celeritas/data/two-boxes.org.omn
  test/celeritas/field/FieldDriver.test.cc
  test/celeritas/field/FieldDriver.test.cu
  test/celeritas/field/FieldDriver.test.hh
  test/celeritas/field/FieldPropagator.test.cc
  test/celeritas/field/FieldPropagator.test.cu
  test/celeritas/field/FieldPropagator.test.hh
  test/celeritas/field/FieldPropagatorTestBase.hh
  test/celeritas/field/FieldTestParams.hh
  test/celeritas/field/Fields.test.cc
  test/celeritas/field/Steppers.test.cc
  test/celeritas/field/Steppers.test.cu
  test/celeritas/field/UserField.test.hh
  test/celeritas/field/UserMapField.test.cc
  test/celeritas/field/UserMapField.test.cu
  test/celeritas/field/UserParamField.test.cc
  test/celeritas/field/UserParamField.test.cu
  test/celeritas/field/detail/CMSMapField.hh
  test/celeritas/field/detail/CMSParameterizedField.hh
  test/celeritas/field/detail/FieldMapData.hh
  test/celeritas/field/detail/MagFieldMap.hh
Labels: bug, propagation

#479 Add range-to-step tests and remove min
  src/celeritas/phys/PhysicsTrackView.hh
  test/celeritas/phys/Physics.test.cc
Labels: physics, housekeeping

#478 Add unit tests and make minor changes to FieldDriver
  src/celeritas/field/FieldDriver.hh
  src/celeritas/field/FieldDriverOptions.hh
  src/celeritas/field/Types.hh
  test/celeritas/field/FieldPropagator.test.cc
Labels: propagation, housekeeping

#477 Unify units in EM interactors/data
  src/celeritas/em/AtomicRelaxationParams.cc
  src/celeritas/em/FluctuationParams.cc
  src/celeritas/em/data/AtomicRelaxationData.hh
  src/celeritas/em/data/BetheHeitlerData.hh
  src/celeritas/em/data/EPlusGGData.hh
  src/celeritas/em/data/FluctuationData.hh
  src/celeritas/em/data/LivermorePEData.hh
  src/celeritas/em/data/MollerBhabhaData.hh
  src/celeritas/em/detail/Utils.cc
  src/celeritas/em/detail/Utils.hh
  src/celeritas/em/distribution/EnergyLossHelper.hh
  src/celeritas/em/distribution/EnergyLossUrbanDistribution.hh
  src/celeritas/em/distribution/TsaiUrbanDistribution.hh
  src/celeritas/em/distribution/UrbanMscHelper.hh
  src/celeritas/em/distribution/UrbanMscScatter.hh
  src/celeritas/em/distribution/UrbanMscStepLimit.hh
  src/celeritas/em/interactor/AtomicRelaxation.hh
  src/celeritas/em/interactor/BetheHeitlerInteractor.hh
  src/celeritas/em/interactor/EPlusGGInteractor.hh
  src/celeritas/em/interactor/LivermorePEInteractor.hh
  src/celeritas/em/interactor/MollerBhabhaInteractor.hh
  src/celeritas/em/interactor/MuBremsstrahlungInteractor.hh
  src/celeritas/em/interactor/RayleighInteractor.hh
  src/celeritas/em/interactor/SeltzerBergerInteractor.hh
  src/celeritas/em/model/BetheHeitlerModel.cc
  src/celeritas/em/model/EPlusGGModel.cc
  src/celeritas/em/model/KleinNishinaModel.cc
  src/celeritas/em/model/LivermorePEModel.cc
  src/celeritas/em/model/MollerBhabhaModel.cc
  src/celeritas/em/model/UrbanMscModel.cc
  src/celeritas/em/xs/EPlusGGMacroXsCalculator.hh
  src/celeritas/io/ImportAtomicRelaxation.hh
  src/celeritas/random/distribution/GammaDistribution.hh
  test/celeritas/em/BetheHeitler.test.cc
  test/celeritas/em/EPlusGG.test.cc
  test/celeritas/em/LivermorePE.test.cc
  test/celeritas/em/MollerBhabha.test.cc
  test/celeritas/em/SeltzerBerger.test.cc
Labels: physics, housekeeping

#480 Fix field propagator at boundary crossings
  src/celeritas/ext/VecgeomParams.hh
  src/orange/OrangeParams.hh
  test/celeritas/field/FieldPropagator.test.cc
Labels: propagation

#482 Filter imported data from Geant4 based on user options
  src/celeritas/ext/GeantImporter.cc
  src/celeritas/ext/GeantImporter.hh
  src/celeritas/ext/detail/ImportProcessConverter.cc
  src/celeritas/io/ImportData.hh
  test/CMakeLists.txt
  test/celeritas/ext/GeantImporter.test.cc
  test/celeritas/ext/RootImporter.test.cc
Labels: interface

#483 Build processes based on exported data
  app/demo-loop/LDemoIO.cc
  src/CMakeLists.txt
  src/celeritas/phys/ProcessBuilder.cc
  src/celeritas/phys/ProcessBuilder.hh
Labels: interface

#486 NVHPC: silence warnings
  app/CMakeLists.txt
  src/CMakeLists.txt
  src/corecel/Assert.hh
  src/corecel/Macros.hh
  src/corecel/cont/LabelIdMultiMap.hh
  src/corecel/cont/Span.hh
  src/orange/surf/detail/SurfaceAction.hh
  test/celeritas/grid/PolyEvaluator.test.cc
  test/celeritas/phys/Physics.test.cc
  test/celeritas/phys/PhysicsStepUtils.test.cc
  test/celeritas/random/curand/CurandPerformance.test.cu
  test/corecel/OpaqueId.test.cc
  test/corecel/sys/TypeDemangler.test.cc
Labels: infrastructure

#488 Return one event at a time from EventReader and PrimaryGenerator
  app/demo-loop/demo-loop.cc
  src/celeritas/io/EventReader.cc
  src/celeritas/io/EventReader.hh
  src/celeritas/io/EventReader.nohepmc.cc
  src/celeritas/phys/PrimaryGenerator.cc
  src/celeritas/phys/PrimaryGenerator.hh
  test/celeritas/data/event-record.hepevt
  test/celeritas/data/event-record.hepmc2
  test/celeritas/data/event-record.hepmc3
  test/celeritas/ext/EventReader.test.cc
  test/celeritas/phys/PrimaryGenerator.test.cc
Labels: integration, housekeeping

#489 Force disabling of shared libs for VecGeom 1.2.0+
  CMakeLists.txt
Labels: bug, infrastructure

#492 Add minor fixes for UrbanMsc
  src/celeritas/em/data/UrbanMscData.hh
  src/celeritas/em/distribution/UrbanMscScatter.hh
Labels: bug, physics

#490 Set remaining model lower limits to zero and make sure demo loop runs with integral approach off
  src/celeritas/em/data/MollerBhabhaData.hh
  src/celeritas/em/distribution/BhabhaEnergyDistribution.hh
  src/celeritas/em/interactor/MollerBhabhaInteractor.hh
  src/celeritas/em/model/MollerBhabhaModel.cc
  src/celeritas/em/model/MuBremsstrahlungModel.cc
  src/celeritas/em/model/SeltzerBergerModel.cc
  src/celeritas/phys/ParticleTrackView.hh
Labels: physics

#496 Fix clang-14/ROCM build with JSON enabled
  src/celeritas/phys/PDGNumber.hh
Labels: bug, infrastructure

#495 Better workaround for VecGeom 1.2 crashes
  CMakeLists.txt
  app/CMakeLists.txt
  app/geo-check/gcheck-four-levels.json
  app/geo-check/gcheck-simplecms.json
  src/CMakeLists.txt
  test/CMakeLists.txt
  test/celeritas/global/Stepper.test.cc
Labels: bug, infrastructure

#487 Fix imported model microscopic cross sections
  src/celeritas/ext/GeantImporter.cc
  src/celeritas/ext/detail/GeantPhysicsList.cc
  src/celeritas/ext/detail/ImportProcessConverter.cc
  src/celeritas/ext/detail/ImportProcessConverter.hh
  src/celeritas/io/ImportProcess.hh
  test/celeritas/SimpleTestBase.cc
  test/celeritas/data/four-steel-slabs.root
  test/celeritas/data/simple-cms.root
  test/celeritas/em/CombinedBrem.test.cc
  test/celeritas/em/Rayleigh.test.cc
  test/celeritas/em/RelativisticBrem.test.cc
  test/celeritas/em/SeltzerBerger.test.cc
  test/celeritas/em/UrbanMsc.test.cc
  test/celeritas/ext/GeantImporter.test.cc
  test/celeritas/ext/RootImporter.test.cc
  test/celeritas/phys/Particle.test.cc
Labels: bug, physics

#500 Fix unintentional MSC enable and some displacement logic
  app/demo-loop/LDemoIO.cc
  src/celeritas/em/distribution/UrbanMscScatter.hh
  src/celeritas/global/alongstep/AlongStepUniformMscAction.hh
Labels: bug, physics, integration

#499 Fix unusual errors in field propagation
  src/celeritas/field/FieldDriverOptions.hh
  src/celeritas/field/FieldPropagator.hh
  src/celeritas/field/detail/FieldUtils.hh
  test/celeritas/field/FieldPropagator.test.cc
Labels: bug, propagation

#497 Improve static/shared CUDA library choice when linking VecGeom
  CMakeLists.txt
  cmake/CeleritasLibrary.cmake
Labels: bug, infrastructure

#501 Fix ORANGE reentrant boundary crossings
  src/orange/Data.hh
  src/orange/OrangeTrackView.hh
  src/orange/Types.hh
  src/orange/univ/SimpleUnitTracker.hh
  test/celeritas/data/three-spheres.gdml
  test/celeritas/geo/Geometry.test.cc
  test/orange/Orange.test.cc
  test/orange/univ/SimpleUnitTracker.test.cc
Labels: bug, geometry
