Repository celeritas-project/celeritas, pull requests merged in 2023-03, with the labels that each got.

#669 Differentiate between local and global Volume and Surface Ids within ORANGE
  src/corecel/data/Collection.hh
  src/corecel/data/detail/CollectionImpl.hh
  src/orange/OrangeData.hh
  src/orange/OrangeTrackView.hh
  src/orange/Types.hh
  src/orange/construct/OrangeInput.hh
  src/orange/construct/OrangeInputIO.json.cc
  src/orange/construct/SurfaceInputBuilder.cc
  src/orange/construct/SurfaceInputBuilder.hh
  src/orange/detail/LevelStateAccessor.hh
  src/orange/detail/UnitIndexer.hh
  src/orange/detail/UnitInserter.cc
  src/orange/surf/Surfaces.hh
  src/orange/surf/detail/SurfaceAction.hh
  src/orange/univ/SimpleUnitTracker.hh
  src/orange/univ/VolumeView.hh
  src/orange/univ/detail/Types.hh
  src/orange/univ/detail/Utils.hh
  test/corecel/data/Collection.test.cc
  test/orange/OrangeGeoTestBase.cc
  test/orange/OrangeGeoTestBase.hh
  test/orange/detail/UnitIndexer.test.cc
  test/orange/surf/SurfaceAction.test.cc
  test/orange/surf/SurfaceAction.test.hh
  test/orange/univ/SimpleUnitTracker.test.cc
  test/orange/univ/VolumeView.test.cc
  test/orange/univ/detail/SenseCalculator.test.cc
  test/orange/univ/detail/SurfaceFunctors.test.cc
Labels: minor, orange

#674 Fix small bugs and remove special cases in Urban MSC
  CMakeLists.txt
  app/CMakeLists.txt
  cmake/CeleritasAddTest.cmake
  src/celeritas/em/UrbanMscParams.cc
  src/celeritas/em/data/UrbanMscData.hh
  src/celeritas/em/msc/UrbanMsc.hh
  src/celeritas/em/msc/detail/MscStepFromGeo.hh
  src/celeritas/em/msc/detail/MscStepToGeo.hh
  src/celeritas/em/msc/detail/UrbanMscScatter.hh
  src/celeritas/phys/Interaction.hh
  test/CMakeLists.txt
  test/celeritas/em/UrbanMsc.test.cc
  test/celeritas/global/AlongStep.test.cc
  test/celeritas/global/Stepper.test.cc
  test/celeritas/user/StepCollector.test.cc
Labels: bug, physics

#682 Update CI VecGeom to 1.2.2
  .jenkins
  scripts/cmake-presets/wildstyle.json
  scripts/docker/build.sh
  scripts/docker/ci/Dockerfile
  scripts/docker/dev/Dockerfile
  test/celeritas/GeantTestBase.cc
  test/celeritas/ext/Vecgeom.test.cc
Labels: minor

#679 Fix imported micro xs when lower energy grid bound is higher than upper bound
  src/celeritas/ext/detail/GeantModelImporter.cc
  test/CMakeLists.txt
  test/celeritas/OneSteelSphereBase.hh
  test/celeritas/data/one-steel-sphere.gdml
  test/celeritas/data/one-steel-sphere.org.json
  test/celeritas/data/one-steel-sphere.org.omn
  test/celeritas/ext/GeantImporter.test.cc
  test/celeritas/global/Stepper.test.cc
Labels: bug, external

#681 Loosen test tolerances for VecGeom
  src/corecel/CMakeLists.txt
  src/corecel/sys/Version.cc
  src/corecel/sys/Version.hh
  test/CMakeLists.txt
  test/celeritas/ext/GeantImporter.test.cc
  test/celeritas/ext/Vecgeom.test.cc
  test/celeritas/field/FieldPropagator.test.cc
  test/celeritas/geo/Geometry.test.cc
  test/celeritas/global/AlongStep.test.cc
  test/celeritas/global/Stepper.test.cc
  test/corecel/sys/Version.test.cc
Labels: minor, external

#686 Fix documentation links and update celeritas logo
  doc/CMakeLists.txt
  doc/_static/celeritas-square.svg
  doc/_static/celeritas-thumbnail.png
  doc/_static/doxygen-custom.css
  doc/api/celeritas.rst
  doc/appendices/administration.rst
  doc/conf.py
  doc/installation.rst
  src/celeritas/em/msc/detail/MscStepFromGeo.hh
  src/celeritas/em/msc/detail/MscStepToGeo.hh
  src/celeritas/em/msc/detail/UrbanMscHelper.hh
  src/celeritas/em/msc/detail/UrbanMscScatter.hh
  src/celeritas/em/msc/detail/UrbanMscStepLimit.hh
Labels: documentation

#689 Update the CMakePreset and env script for building on Zeus
  scripts/cmake-presets/zeus.json
  scripts/env/zeus.sh
Labels: minor

#688 Fix Collection usage from inside .cu files
  src/corecel/Assert.hh
  src/corecel/data/detail/CollectionImpl.hh
  src/corecel/data/detail/DisabledStorage.hh
  test/corecel/data/Collection.test.cc
  test/corecel/data/Collection.test.cu
  test/corecel/data/Collection.test.hh
Labels: bug, core

#690 Read EM processes from G4GammaGeneral
  CMakeLists.txt
  app/demo-geant-integration/demo-geant-integration.cc
  scripts/spack.yaml
  src/celeritas/ext/GeantConfig.hh
  src/celeritas/ext/GeantImporter.cc
  src/celeritas/ext/GeantImporter.hh
  src/celeritas/ext/GeantPhysicsOptions.hh
  src/celeritas/ext/GeantPhysicsOptionsIO.json.cc
  src/celeritas/ext/GeantSetup.cc
  src/celeritas/ext/detail/GeantModelImporter.cc
  src/celeritas/ext/detail/GeantPhysicsList.cc
  src/celeritas/ext/detail/GeantProcessImporter.cc
  src/celeritas/ext/detail/GeantProcessImporter.hh
  src/celeritas/io/ImportModel.cc
  src/celeritas/io/ImportModel.hh
  src/celeritas/io/ImportProcess.cc
  src/celeritas/io/ImportProcess.hh
  src/corecel/io/StringEnumMapper.hh
  test/CMakeLists.txt
  test/celeritas/ext/GeantImporter.test.cc
  test/corecel/io/StringEnumMapper.test.cc
Labels: enhancement, external

#685 Identify and kill looping tracks
  app/celer-dump-data.cc
  app/demo-loop/LDemoIO.cc
  app/demo-loop/LDemoIO.hh
  app/demo-loop/Transporter.cc
  app/demo-loop/demo-loop.cc
  app/demo-loop/diagnostic/Diagnostic.hh
  app/demo-loop/diagnostic/EnergyDiagnostic.cc
  app/demo-loop/diagnostic/EnergyDiagnostic.cu
  app/demo-loop/diagnostic/EnergyDiagnostic.hh
  app/demo-loop/diagnostic/ParticleProcessDiagnostic.hh
  app/demo-loop/diagnostic/StepDiagnostic.hh
  src/accel/SharedParams.cc
  src/celeritas/CMakeLists.txt
  src/celeritas/em/msc/UrbanMsc.hh
  src/celeritas/ext/GeantImporter.cc
  src/celeritas/ext/RootInterfaceLinkDef.h
  src/celeritas/ext/detail/GeantModelImporter.cc
  src/celeritas/field/FieldPropagator.hh
  src/celeritas/field/LinearPropagator.hh
  src/celeritas/global/CoreParams.cc
  src/celeritas/global/CoreParams.hh
  src/celeritas/global/CoreTrackData.hh
  src/celeritas/global/CoreTrackView.hh
  src/celeritas/global/alongstep/AlongStep.hh
  src/celeritas/io/ImportData.hh
  src/celeritas/io/ImportParameters.hh
  src/celeritas/io/ImportProcess.hh
  src/celeritas/phys/ParticleTrackView.hh
  src/celeritas/track/SimData.hh
  src/celeritas/track/SimParams.cc
  src/celeritas/track/SimParams.hh
  src/celeritas/track/SimTrackView.hh
  src/celeritas/track/detail/InitTracksLauncher.hh
  src/celeritas/track/detail/LocateAliveLauncher.hh
  src/celeritas/track/detail/ProcessPrimariesLauncher.hh
  src/celeritas/track/detail/ProcessSecondariesLauncher.hh
  src/orange/Types.hh
  test/CMakeLists.txt
  test/celeritas/GlobalTestBase.cc
  test/celeritas/GlobalTestBase.hh
  test/celeritas/ImportedDataTestBase.cc
  test/celeritas/ImportedDataTestBase.hh
  test/celeritas/MockTestBase.cc
  test/celeritas/MockTestBase.hh
  test/celeritas/OnlyGeoTestBase.hh
  test/celeritas/SimpleTestBase.cc
  test/celeritas/SimpleTestBase.hh
  test/celeritas/data/four-steel-slabs.root
  test/celeritas/em/UrbanMsc.test.cc
  test/celeritas/ext/GeantImporter.test.cc
  test/celeritas/field/FieldPropagator.test.cc
  test/celeritas/global/AlongStep.test.cc
  test/celeritas/global/AlongStepTestBase.cc
  test/celeritas/global/AlongStepTestBase.hh
  test/celeritas/phys/Particle.test.cc
  test/celeritas/track/Sim.test.cc
  test/celeritas/track/TrackInit.test.cc
  test/celeritas/track/TrackInit.test.cu
  test/celeritas/track/TrackInit.test.hh
Labels: enhancement, field

#691 Fail fast instead of giving wrong answers for multithreading
  app/CMakeLists.txt
  src/accel/detail/HitManager.cc
  src/accel/detail/HitProcessor.cc
  src/celeritas/user/DetectorSteps.cc
  src/celeritas/user/detail/StepGatherAction.cc
  src/celeritas/user/detail/StepStorage.hh
Labels: bug

#697 Fix HIP test failure in field propagation
  test/celeritas/field/FieldPropagator.test.cc
  test/celeritas/global/AlongStep.test.cc
  test/celeritas/global/AlongStepTestBase.cc
  test/celeritas/global/Stepper.test.cc
Labels: field, minor

#693 Add StreamId to allow thread-safe data access in Actions
  app/CMakeLists.txt
  app/demo-loop/Transporter.cc
  example/accel/accel.cc
  src/accel/LocalTransporter.cc
  src/accel/SharedParams.cc
  src/celeritas/CMakeLists.txt
  src/celeritas/global/CoreParams.cc
  src/celeritas/global/CoreParams.hh
  src/celeritas/global/CoreTrackData.cc
  src/celeritas/global/CoreTrackData.hh
  src/celeritas/global/Stepper.cc
  src/celeritas/global/Stepper.hh
  src/celeritas/user/detail/StepGatherAction.cc
  src/celeritas/user/detail/StepGatherAction.hh
  src/celeritas/user/detail/StepStorage.hh
  src/corecel/data/CollectionStateStore.hh
  src/corecel/sys/ThreadId.hh
  test/celeritas/global/AlongStepTestBase.cc
  test/celeritas/global/StepperTestBase.cc
  test/celeritas/track/TrackInit.test.cc
  test/celeritas/user/CaloTestBase.cc
  test/celeritas/user/MctruthTestBase.cc
  test/celeritas/user/StepCollector.test.cc
Labels: enhancement, core

#700 Fix a few edge cases in field propagation
  src/celeritas/field/FieldPropagator.hh
Labels: bug, field

#684 Cross universe boundaries in ORANGE
  src/orange/OrangeData.hh
  src/orange/OrangeTrackView.hh
  src/orange/OrangeTypes.hh
  src/orange/Types.hh
  src/orange/construct/OrangeInputIO.json.cc
  src/orange/detail/UnitInserter.cc
  src/orange/detail/UnitInserter.hh
  src/orange/univ/SimpleUnitTracker.hh
  test/orange/Orange.test.cc
  test/orange/data/universes.org.json
  test/orange/data/universes.org.omn
Labels: enhancement, orange

#699 Use more IIFE, constexpr inline, string_view
  app/demo-loop/LDemoIO.cc
  cmake/CgvFindVersion.cmake
  src/accel/SharedParams.cc
  src/celeritas/Constants.hh
  src/celeritas/Quantities.hh
  src/celeritas/Units.hh
  src/celeritas/field/FieldDriverOptions.hh
  src/corecel/io/ColorUtils.cc
  src/corecel/io/EnumStringMapper.hh
  src/corecel/io/LoggerTypes.cc
  src/corecel/io/OutputInterface.cc
  src/corecel/math/Quantity.hh
  src/corecel/sys/KernelParamCalculator.device.cc
  src/corecel/sys/KernelParamCalculator.device.hh
  src/corecel/sys/KernelRegistry.cc
  src/corecel/sys/KernelRegistry.hh
  src/orange/OrangeTypes.cc
  src/orange/OrangeTypes.hh
  src/orange/Types.hh
  test/celeritas/global/Stepper.test.cc
Labels: core, minor

#694 Fix multithreading in Geant4 and HitManager
  app/CMakeLists.txt
  src/accel/LocalTransporter.cc
  src/accel/LocalTransporter.hh
  src/accel/SharedParams.cc
  src/accel/SharedParams.hh
  src/accel/detail/HitManager.cc
  src/accel/detail/HitManager.hh
  src/accel/detail/HitProcessor.cc
  src/accel/detail/HitProcessor.hh
  src/celeritas/ext/GeantSetup.cc
  src/celeritas/user/detail/StepGatherAction.cc
  src/celeritas/user/detail/StepGatherAction.hh
  src/celeritas/user/detail/StepStorage.hh
  src/corecel/cont/InitializedValue.hh
  src/corecel/data/DeviceAllocation.hh
  src/corecel/data/DeviceVector.hh
  src/corecel/data/detail/InitializedValue.hh
  test/CMakeLists.txt
  test/accel/detail/HitProcessor.test.cc
  test/corecel/cont/InitializedValue.test.cc
  test/corecel/data/DeviceAllocation.test.cc
Labels: bug, external

#703 Import a few more EM parameters from Geant4
  app/celer-dump-data.cc
  app/demo-loop/LDemoIO.cc
  src/accel/SharedParams.cc
  src/celeritas/em/UrbanMscParams.cc
  src/celeritas/em/UrbanMscParams.hh
  src/celeritas/ext/GeantImporter.cc
  src/celeritas/ext/GeantPhysicsOptions.hh
  src/celeritas/ext/GeantPhysicsOptionsIO.json.cc
  src/celeritas/ext/detail/GeantPhysicsList.cc
  src/celeritas/global/alongstep/AlongStep.hh
  src/celeritas/global/alongstep/detail/FluctELoss.hh
  src/celeritas/global/alongstep/detail/MeanELoss.hh
  src/celeritas/io/ImportParameters.hh
  src/celeritas/phys/PhysicsData.hh
  src/celeritas/phys/PhysicsParams.cc
  src/celeritas/phys/PhysicsParams.hh
  src/celeritas/phys/PhysicsParamsOutput.cc
  test/celeritas/data/four-steel-slabs.geant.json
  test/celeritas/data/four-steel-slabs.root
  test/celeritas/ext/GeantImporter.test.cc
  test/celeritas/phys/Physics.test.cc
Labels: minor, external

#702 Add UniformAlongStepFactory for Geant4 integration
  app/CMakeLists.txt
  app/demo-geant-integration/GlobalSetup.cc
  app/demo-geant-integration/GlobalSetup.hh
  app/demo-geant-integration/HitRootIO.cc
  app/demo-geant-integration/NoFieldAlongStepFactory.cc
  app/demo-geant-integration/NoFieldAlongStepFactory.hh
  app/demo-geant-integration/RunAction.cc
  app/demo-geant-integration/demo-geant-integration.cc
  doc/api/accel.rst
  doc/examples/geant4-full.rst
  example/accel/accel.cc
  src/accel/AlongStepFactory.cc
  src/accel/AlongStepFactory.hh
  src/accel/CMakeLists.txt
  src/accel/LocalTransporter.cc
  src/accel/Logger.cc
  src/accel/Logger.hh
  src/accel/detail/Convert.hh
  src/accel/detail/HitProcessor.cc
  src/celeritas/io/ImportModel.hh
Labels: enhancement, external

#701 Add config options for ordering of trackslots
  app/demo-loop/LDemoIO.cc
  app/demo-loop/LDemoIO.hh
  src/accel/SetupOptions.hh
  src/accel/SharedParams.cc
  src/celeritas/Types.hh
  src/celeritas/global/CoreTrackData.cc
  src/celeritas/track/TrackInitData.hh
  src/celeritas/track/TrackInitParams.cc
  src/celeritas/track/TrackInitParams.hh
  src/celeritas/track/detail/TrackSortUtils.cc
  src/celeritas/track/detail/TrackSortUtils.cu
  src/celeritas/track/detail/TrackSortUtils.hh
Labels: enhancement, core

#706 Fix SWIG and mac builds
  interface/celeritas.i
  src/celeritas/track/detail/TrackSortUtils.cc
Labels: bug, core

#704 Define SimpleOffload for dead-simple Geant4 integration
  doc/api/accel.rst
  doc/examples/geant4-minimal.rst
  example/accel/accel.cc
  src/accel/CMakeLists.txt
  src/accel/LocalTransporter.cc
  src/accel/LocalTransporter.hh
  src/accel/Logger.cc
  src/accel/SetupOptions.hh
  src/accel/SharedParams.cc
  src/accel/SharedParams.hh
  src/accel/SimpleOffload.cc
  src/accel/SimpleOffload.hh
  src/corecel/io/Logger.hh
Labels: enhancement, external

#708 Fix energy deposition for killed looping positrons
  src/celeritas/global/alongstep/AlongStep.hh
  src/celeritas/phys/ParticleData.hh
  src/celeritas/phys/ParticleParams.cc
  src/celeritas/phys/ParticleTrackView.hh
  src/celeritas/phys/ParticleView.hh
  test/celeritas/phys/Particle.test.cc
Labels: bug, physics

#705 Extend Urban MSC to high energy by default
  doc/_static/ornltm-header-celeritas.tex
  doc/api/celeritas.rst
  doc/appendices/development.rst
  doc/conf.py
  doc/overview.rst
  src/celeritas/CMakeLists.txt
  src/celeritas/em/UrbanMscParams.cc
  src/celeritas/em/data/UrbanMscData.hh
  src/celeritas/ext/GeantPhysicsOptions.cc
  src/celeritas/ext/GeantPhysicsOptions.hh
  src/celeritas/ext/GeantPhysicsOptionsIO.json.cc
  src/celeritas/ext/detail/GeantExceptionHandler.cc
  src/celeritas/ext/detail/GeantPhysicsList.cc
  src/celeritas/io/ImportData.hh
  src/celeritas/io/ImportElement.hh
  src/celeritas/io/ImportMaterial.hh
  src/celeritas/io/ImportModel.cc
  src/celeritas/io/ImportModel.hh
  src/celeritas/io/ImportParticle.hh
  src/celeritas/io/ImportProcess.hh
  src/celeritas/io/ImportVolume.hh
  src/celeritas/track/detail/TrackSortUtils.hh
  test/celeritas/em/UrbanMsc.test.cc
  test/celeritas/ext/GeantImporter.test.cc
Labels: enhancement, physics

#709 Add an option to apply cuts to all secondaries
  app/celer-dump-data.cc
  src/celeritas/ext/GeantImporter.cc
  src/celeritas/ext/GeantPhysicsOptions.hh
  src/celeritas/ext/GeantPhysicsOptionsIO.json.cc
  src/celeritas/ext/detail/GeantPhysicsList.cc
  src/celeritas/io/ImportParameters.hh
  src/celeritas/phys/CutoffData.hh
  src/celeritas/phys/CutoffParams.cc
  src/celeritas/phys/CutoffParams.hh
  src/celeritas/phys/CutoffView.hh
  src/celeritas/phys/detail/InteractionLauncherImpl.hh
  test/celeritas/data/four-steel-slabs.geant.json
  test/celeritas/ext/GeantImporter.test.cc
  test/celeritas/phys/CutoffParams.test.cc
Labels: enhancement
