Repository celeritas-project/celeritas, pull requests merged in 2023-02, with the labels that each got.

#624 Refine ImportProcess enums and importing code
  src/celeritas/ext/GeantImporter.cc
  src/celeritas/ext/detail/GeantBremsstrahlungProcess.cc
  src/celeritas/ext/detail/GeantPhysicsList.cc
  src/celeritas/ext/detail/ImportProcessConverter.cc
  src/celeritas/ext/detail/ImportProcessConverter.hh
  src/celeritas/io/ImportElement.hh
  src/celeritas/io/ImportMaterial.hh
  src/celeritas/io/ImportParticle.hh
  src/celeritas/io/ImportPhysicsTable.hh
  src/celeritas/io/ImportProcess.cc
  src/celeritas/io/ImportProcess.hh
  src/celeritas/io/ImportVolume.hh
  src/celeritas/io/SeltzerBergerReader.hh
  src/celeritas/mat/MaterialParams.cc
  src/corecel/Macros.hh
  test/CMakeLists.txt
Labels: interface, housekeeping

#625 Fix missing positron annihilation process and process diagnostic
  app/demo-loop/diagnostic/ParticleProcessDiagnostic.hh
  src/celeritas/ext/detail/ImportProcessConverter.cc
  src/celeritas/io/ImportProcess.hh
  test/celeritas/data/four-steel-slabs.root
  test/celeritas/em/UrbanMsc.test.cc
  test/celeritas/ext/GeantImporter.test.cc
  test/celeritas/ext/RootImporter.test.cc
  test/celeritas/phys/CutoffParams.test.cc
Labels: bug

#626 Add enum string mapper
  src/celeritas/Types.cc
  src/celeritas/ext/GeantPhysicsOptionsIO.json.cc
  src/celeritas/io/ImportPhysicsTable.cc
  src/celeritas/io/ImportProcess.cc
  src/celeritas/phys/PrimaryGeneratorOptions.hh
  src/celeritas/phys/PrimaryGeneratorOptionsIO.json.cc
  src/corecel/io/EnumStringMapper.hh
  src/corecel/io/OutputInterface.cc
  src/corecel/io/StringEnumMapper.hh
  src/orange/OrangeTypes.cc
  src/orange/construct/OrangeInputIO.json.cc
  test/CMakeLists.txt
  test/corecel/cont/Range.test.cc
  test/corecel/io/EnumStringMapper.test.cc
  test/corecel/io/StringEnumMapper.test.cc
Labels: enhancement, infrastructure

#628 Fix NaN/assertion when taking extremely small steps in a field
  src/celeritas/field/FieldPropagator.hh
  src/celeritas/field/detail/FieldUtils.hh
  test/celeritas/field/FieldPropagator.test.cc
Labels: bug, propagation

#627 Fix ORANGE intersection along cylinder axis
  src/orange/surf/CylCentered.hh
  test/orange/surf/CylCentered.test.cc
Labels: bug, geometry

#631 Remove multiple scattering from Processes
  app/demo-geant-integration/NoFieldAlongStepFactory.cc
  app/demo-loop/LDemoIO.cc
  example/accel/accel.cc
  src/celeritas/CMakeLists.txt
  src/celeritas/Types.hh
  src/celeritas/em/UrbanMscParams.cc
  src/celeritas/em/UrbanMscParams.hh
  src/celeritas/em/data/UrbanMscData.hh
  src/celeritas/em/model/UrbanMscModel.hh
  src/celeritas/em/msc/UrbanMsc.hh
  src/celeritas/em/msc/UrbanMscHelper.hh
  src/celeritas/em/msc/UrbanMscScatter.hh
  src/celeritas/em/msc/UrbanMscStepLimit.hh
  src/celeritas/em/process/MultipleScatteringProcess.cc
  src/celeritas/em/process/MultipleScatteringProcess.hh
  src/celeritas/ext/GeantImporter.cc
  src/celeritas/ext/GeantPhysicsOptions.hh
  src/celeritas/ext/GeantPhysicsOptionsIO.json.cc
  src/celeritas/ext/RootInterfaceLinkDef.h
  src/celeritas/ext/detail/GeantPhysicsList.cc
  src/celeritas/ext/detail/ImportProcessConverter.cc
  src/celeritas/global/alongstep/AlongStep.hh
  src/celeritas/global/alongstep/AlongStepGeneralLinearAction.cc
  src/celeritas/global/alongstep/AlongStepGeneralLinearAction.hh
  src/celeritas/global/alongstep/AlongStepUniformMscAction.cc
  src/celeritas/global/alongstep/AlongStepUniformMscAction.hh
  src/celeritas/global/alongstep/detail/AlongStepGeneralLinear.hh
  src/celeritas/global/alongstep/detail/AlongStepUniformMsc.hh
  src/celeritas/io/ImportData.hh
  src/celeritas/io/ImportPhysicsTable.cc
  src/celeritas/io/ImportPhysicsTable.hh
  src/celeritas/io/ImportProcess.hh
  src/celeritas/phys/Model.hh
  src/celeritas/phys/PhysicsData.hh
  src/celeritas/phys/PhysicsParams.cc
  src/celeritas/phys/PhysicsParams.hh
  src/celeritas/phys/ProcessBuilder.cc
  test/celeritas/GeantTestBase.cc
  test/celeritas/MockTestBase.cc
  test/celeritas/data/four-steel-slabs.root
  test/celeritas/em/UrbanMsc.test.cc
  test/celeritas/ext/GeantImporter.test.cc
  test/celeritas/ext/RootImporter.test.cc
  test/celeritas/global/AlongStep.test.cc
  test/celeritas/global/Stepper.test.cc
  test/celeritas/phys/MockModel.cc
  test/celeritas/phys/Physics.test.cc
  test/celeritas/phys/ProcessBuilder.test.cc
  test/celeritas/user/StepCollector.test.cc
Labels: physics, housekeeping

#610 Update ROOT Unique Pointers
  app/demo-loop/LDemoIO.hh
  app/demo-loop/LDemoIO.root.cc
  app/demo-loop/demo-loop.cc
  src/celeritas/CMakeLists.txt
  src/celeritas/ext/RootExporter.cc
  src/celeritas/ext/RootExporter.hh
  src/celeritas/ext/RootImporter.hh
  src/celeritas/ext/RootUniquePtr.hh
  src/celeritas/ext/RootUniquePtr.root.cc
  src/celeritas/io/RootFileManager.cc
  src/celeritas/io/RootFileManager.hh
  src/celeritas/io/RootStepWriter.hh
Labels: infrastructure, interface, housekeeping

#634 Refactor import process into multiple import models
  app/celer-dump-data.cc
  app/demo-loop/Transporter.cc
  src/celeritas/CMakeLists.txt
  src/celeritas/em/UrbanMscParams.cc
  src/celeritas/ext/GeantImporter.cc
  src/celeritas/ext/GeantImporter.hh
  src/celeritas/ext/RootInterfaceLinkDef.h
  src/celeritas/ext/detail/GeantMicroXsCalculator.cc
  src/celeritas/ext/detail/GeantMicroXsCalculator.hh
  src/celeritas/ext/detail/GeantModelImporter.cc
  src/celeritas/ext/detail/GeantModelImporter.hh
  src/celeritas/ext/detail/GeantProcessImporter.cc
  src/celeritas/ext/detail/GeantProcessImporter.hh
  src/celeritas/grid/VectorUtils.cc
  src/celeritas/grid/VectorUtils.hh
  src/celeritas/io/ImportModel.cc
  src/celeritas/io/ImportModel.hh
  src/celeritas/io/ImportPhysicsTable.cc
  src/celeritas/io/ImportPhysicsTable.hh
  src/celeritas/io/ImportProcess.cc
  src/celeritas/io/ImportProcess.hh
  src/celeritas/phys/ImportedModelAdapter.cc
  src/corecel/CMakeLists.txt
  src/corecel/math/VectorUtils.cc
  test/CMakeLists.txt
  test/celeritas/SimpleTestBase.cc
  test/celeritas/data/four-steel-slabs.root
  test/celeritas/em/CombinedBrem.test.cc
  test/celeritas/em/Rayleigh.test.cc
  test/celeritas/em/RelativisticBrem.test.cc
  test/celeritas/em/SeltzerBerger.test.cc
  test/celeritas/ext/GeantImporter.test.cc
  test/celeritas/ext/RootImporter.test.cc
  test/celeritas/grid/VectorUtils.test.cc
  test/celeritas/phys/InteractorHostTestBase.cc
  test/celeritas/phys/InteractorHostTestBase.hh
  test/corecel/math/VectorUtils.test.cc
Labels: physics, interface

#630 Add filtering to `RootStepWriter`
  app/demo-loop/LDemoIO.cc
  app/demo-loop/LDemoIO.hh
  app/demo-loop/demo-loop.cc
  app/demo-loop/simple-driver.py
  src/celeritas/io/RootStepWriter.cc
  src/celeritas/io/RootStepWriter.hh
  src/celeritas/user/StepInterface.hh
Labels: enhancement

#638 VecGeom/Cuda: set the stack limit to 16K when CELERITAS_DEBUG=ON
  src/celeritas/ext/VecgeomParams.cc
Labels: bug, infrastructure, geometry

#642 Fix incorrect Urban MSC path length correction due to discontinuity in positron cross section
  src/celeritas/em/msc/UrbanMscScatter.hh
  src/celeritas/em/msc/UrbanMscStepLimit.hh
  src/celeritas/phys/Interaction.hh
  test/celeritas/global/AlongStep.test.cc
Labels: bug, physics

#636 Switch from genreflex/xml to rootcling/LinkDef for demo-geant-integration
  app/CMakeLists.txt
  app/demo-geant-integration/HitClasses.hh
  app/demo-geant-integration/HitClassesLinkDef.h
  app/demo-geant-integration/selection.xml
  src/celeritas/ext/RootInterfaceLinkDef.h
Labels: infrastructure, housekeeping

#644 Fix MSC cross section units
  app/celer-dump-data.cc
  src/celeritas/em/UrbanMscParams.cc
  src/celeritas/em/msc/UrbanMscHelper.hh
  src/celeritas/ext/GeantImporter.cc
  src/celeritas/ext/detail/GeantPhysicsList.cc
  src/celeritas/ext/detail/GeantProcessImporter.cc
  src/celeritas/io/ImportModel.hh
  src/celeritas/io/ImportPhysicsTable.cc
  src/celeritas/io/ImportPhysicsTable.hh
  src/celeritas/io/ImportProcess.hh
  src/celeritas/phys/ImportedModelAdapter.cc
  test/celeritas/data/four-steel-slabs.geant.json
  test/celeritas/data/four-steel-slabs.root
Labels: bug, physics

#645 Activate fine-grid MSC test and make GeantImporter less verbose
  app/celer-export-geant.cc
  src/celeritas/ext/GeantPhysicsOptions.hh
  src/celeritas/ext/GeantPhysicsOptionsIO.json.cc
  src/celeritas/ext/detail/GeantPhysicsList.cc
  test/CMakeLists.txt
  test/celeritas/GeantTestBase.cc
  test/celeritas/ext/GeantImporter.test.cc
Labels: integration, housekeeping

#646 Check for unlikely "zero speed" condition
  src/celeritas/global/alongstep/AlongStep.hh
  test/CMakeLists.txt
  test/celeritas/MockTestBase.cc
  test/celeritas/MockTestBase.hh
  test/celeritas/global/AlongStep.test.cc
  test/celeritas/phys/Physics.test.cc
Labels: bug, physics

#649 Avoid XS scaling factor > 1 in `SBPositronXSCorrector`.
  src/celeritas/em/interactor/detail/SBPositronXsCorrector.hh
  test/celeritas/em/SeltzerBerger.test.cc
Labels: bug

#637 Fix volume mapping and navigation issues found with HGCal prototype
  app/demo-geant-integration/EventAction.cc
  scripts/cmake-presets/goldfinger.json
  src/accel/HepMC3PrimaryGenerator.cc
  src/accel/LocalTransporter.cc
  src/accel/detail/HitManager.cc
  src/accel/detail/HitProcessor.cc
  src/accel/detail/HitProcessor.hh
  src/celeritas/ext/GeantImporter.cc
  src/celeritas/geo/GeoMaterialParams.cc
  src/celeritas/io/ImportVolume.hh
  test/CMakeLists.txt
  test/accel/detail/HitProcessor.test.cc
  test/celeritas/SimpleCmsTestBase.hh
Labels: bug, geometry, interface

#657 Fix SWIG and update requirements
  interface/celeritas.i
  scripts/docker/dev/centos7-rocm5.yaml
  scripts/docker/dev/jammy-cuda11.yaml
  scripts/spack.yaml
Labels: bug, infrastructure

#654 Fix coincident boundary/step created by field propagator
  CMakePresets.json
  scripts/cmake-presets/goldfinger.json
  scripts/cmake-presets/wildstyle.json
  src/celeritas/field/FieldDriver.hh
  src/celeritas/field/FieldDriverOptions.hh
  src/celeritas/field/FieldPropagator.hh
  src/celeritas/field/detail/FieldUtils.hh
  test/celeritas/field/FieldPropagator.test.cc
Labels: propagation

#650 Characterize and remove field driver convergence assertions
  src/celeritas/field/FieldDriver.hh
  src/corecel/io/Repr.hh
  test/CMakeLists.txt
  test/TestMacros.test.cc
  test/celeritas/field/DiagnosticStepper.hh
  test/celeritas/field/FieldDriver.test.cc
  test/testdetail/TestMacrosImpl.hh
Labels: documentation, propagation

#658 Add math operators to Quantity
  src/celeritas/global/alongstep/detail/FluctELoss.hh
  src/celeritas/global/alongstep/detail/MeanELoss.hh
  src/celeritas/phys/PhysicsData.hh
  src/celeritas/phys/PhysicsStepUtils.hh
  src/corecel/math/Quantity.hh
  test/corecel/math/Quantity.test.cc
Labels: infrastructure

#656 Disable Geant4+ROOT system signal hooks
  src/celeritas/ext/GeantSetup.cc
  src/celeritas/ext/ScopedRootErrorHandler.cc
  test/CMakeLists.txt
Labels: infrastructure

#660 Fix duplicate CMake presets
  CMakePresets.json
  scripts/cmake-presets/perlmutter.json
  scripts/cmake-presets/summit.json
Labels: infrastructure, housekeeping

#661 Only capture kernel context if corresponding track is alive
  src/celeritas/global/KernelContextException.cc
  test/celeritas/global/KernelContextException.test.cc
Labels: bug

#607 Find next step across multiple universes
  app/demo-loop/diagnostic/EnergyDiagnostic.hh
  src/orange/OrangeData.hh
  src/orange/OrangeParams.cc
  src/orange/OrangeTrackView.hh
  src/orange/OrangeTypes.hh
  src/orange/construct/OrangeInput.hh
  src/orange/detail/LevelStateAccessor.hh
  test/orange/Orange.test.cc
  test/orange/univ/SimpleUnitTracker.test.cc
  test/orange/univ/SimpleUnitTracker.test.hh
Labels: enhancement, geometry

#653 Document available physics processes and models
  doc/CMakeLists.txt
  doc/_static/references.bib
  doc/api/celeritas.rst
  doc/conf.py
  doc/overview.rst
  src/celeritas/em/interactor/RayleighInteractor.hh
  src/celeritas/em/msc/UrbanMscScatter.hh
  src/celeritas/random/distribution/GammaDistribution.hh
Labels: documentation

#663 Release v0.1.5
  doc/CMakeLists.txt
  doc/appendices/release-history.rst
  src/orange/detail/LevelStateAccessor.hh
Labels: documentation

#666 Fix Geant4/GDML volume names to get TileCal working
  app/celer-dump-data.cc
  src/accel/SharedParams.cc
  src/accel/detail/HitProcessor.cc
  src/accel/detail/HitProcessor.hh
  src/celeritas/CMakeLists.txt
  src/celeritas/ext/GeantImporter.cc
  src/celeritas/ext/GeantImporter.hh
  src/celeritas/ext/detail/GeantVolumeVisitor.cc
  src/celeritas/ext/detail/GeantVolumeVisitor.hh
  src/celeritas/global/Stepper.cc
  src/celeritas/track/TrackInitParams.hh
  test/CMakeLists.txt
  test/celeritas/GeantTestBase.cc
  test/celeritas/GeantTestBase.hh
  test/celeritas/ext/GeantImporter.test.cc
Labels: bug, external

#667 Ignore Geant4 muons and muon processes by default in accel
  app/demo-geant-integration/demo-geant-integration.cc
  example/accel/accel.cc
  src/accel/SharedParams.cc
  src/celeritas/ext/GeantImporter.cc
  src/celeritas/ext/GeantImporter.hh
Labels: bug, external

#668 Release v0.2.1
  doc/appendices/release-history.rst
  doc/appendices/release-history/v0.1.rst
  doc/appendices/release-history/v0.2.rst
Labels: documentation

#672 Fix hit mapping when using GDML geometry with pointers
  src/accel/detail/HitManager.cc
  src/celeritas/phys/ImportedModelAdapter.cc
Labels: bug, external

#673 Fix hit mapping when using GDML geometry with pointers
  src/accel/detail/HitManager.cc
Labels: bug, external
