Repository celeritas-project/celeritas, pull requests merged in 2023-07, with the labels that each got.

#839 Gather and set more Step/Track attributes when calling sensitive detectors
  app/celer-g4/DetectorConstruction.cc
  src/accel/SetupOptions.hh
  src/accel/SharedParams.cc
  src/accel/detail/HitManager.cc
  src/accel/detail/HitManager.hh
  src/accel/detail/HitProcessor.cc
  src/accel/detail/HitProcessor.hh
  src/celeritas/user/StepData.hh
  test/accel/SimpleSensitiveDetector.cc
  test/accel/SimpleSensitiveDetector.hh
  test/accel/detail/HitManager.test.cc
  test/accel/detail/HitProcessor.test.cc
Labels: enhancement, external

#829 Unify convergence criteria in field driver
  src/celeritas/field/FieldDriver.hh
  src/celeritas/field/FieldDriverOptions.hh
  src/celeritas/field/FieldPropagator.hh
  src/celeritas/field/MagFieldEquation.hh
  src/celeritas/field/detail/FieldUtils.hh
  test/celeritas/field/DiagnosticStepper.hh
  test/celeritas/field/FieldDriver.test.cc
  test/celeritas/field/FieldPropagator.test.cc
  test/celeritas/field/Steppers.test.cc
  test/celeritas/global/AlongStep.test.cc
  test/celeritas/user/StepCollector.test.cc
Labels: bug, field

#843 Add isotope selector
  src/celeritas/mat/IsotopeSelector.hh
  test/CMakeLists.txt
  test/celeritas/mat/IsotopeSelector.test.cc
  test/celeritas/mat/Material.test.cc
  test/celeritas/mat/MaterialTestBase.hh
Labels: enhancement, physics

#846 Fix minor issues with exceptions
  src/celeritas/phys/ImportedProcessAdapter.cc
  src/celeritas/phys/ImportedProcessAdapter.hh
  src/corecel/Assert.hh
  src/corecel/sys/ScopedMem.cc
  src/corecel/sys/ScopedProfiling.cuda.cc
Labels: bug

#847 Add some quality-of-life CMake defaults
  CMakeLists.txt
  cmake/CeleritasUtils.cmake
Labels: core, minor

#851 Add a HepMC3 writer
  CMakeLists.txt
  src/accel/HepMC3PrimaryGenerator.cc
  src/celeritas/CMakeLists.txt
  src/celeritas/io/EventReader.cc
  src/celeritas/io/EventReader.hh
  src/celeritas/io/EventReader.nohepmc.cc
  src/celeritas/io/EventWriter.cc
  src/celeritas/io/EventWriter.hh
  src/corecel/io/ScopedTimeAndRedirect.hh
  test/CMakeLists.txt
  test/celeritas/ext/EventReader.test.cc
  test/celeritas/io/EventIO.test.cc
Labels: enhancement, external

#855 Require semicolon for statement-like CELER_X_COPY_MOVE macros
  src/accel/AlongStepFactory.hh
  src/celeritas/ext/ScopedGeantExceptionHandler.hh
  src/celeritas/ext/ScopedGeantLogger.hh
  src/celeritas/ext/ScopedRootErrorHandler.hh
  src/celeritas/global/ActionInterface.hh
  src/celeritas/io/EventReader.hh
  src/celeritas/io/EventWriter.hh
  src/celeritas/phys/Process.hh
  src/corecel/Macros.hh
  src/corecel/io/ScopedStreamFormat.hh
  src/corecel/io/ScopedStreamRedirect.hh
  src/corecel/io/ScopedTimeAndRedirect.hh
  src/corecel/io/ScopedTimeLog.hh
  src/corecel/sys/ScopedMpiInit.hh
  src/corecel/sys/ScopedProfiling.hh
Labels: core, minor

#856 Fix linking errors with CUDA+VecGeom
  cmake/CeleritasLibrary.cmake
Labels: bug, core

#857 Fix inconsistencies in Geant4-to-VecGeom boolean conversion
  cmake/CeleritasUtils.cmake
  scripts/dev/celeritas-gen.py
  src/celeritas/ext/g4vg/SolidConverter.cc
  test/celeritas/ext/GeantGeo.test.cc
  test/celeritas/ext/Vecgeom.test.cc
Labels: bug, external

#860 Add option to disable Celeritas offloading in celer-g4
  app/celer-g4/ActionInitialization.cc
  app/celer-g4/EventAction.cc
  app/celer-g4/EventAction.hh
  app/celer-g4/GlobalSetup.cc
  app/celer-g4/GlobalSetup.hh
  app/celer-g4/RunAction.cc
  app/celer-g4/RunAction.hh
  app/celer-g4/TrackingAction.cc
  app/celer-g4/TrackingAction.hh
  app/celer-g4/celer-g4.cc
Labels: enhancement, app

#859 Expose SDSetupOptions "enabled" flag in SetupOptionsMessenger
  src/accel/SetupOptionsMessenger.cc
  src/accel/SetupOptionsMessenger.hh
Labels: enhancement, external

#862 Add track step counter to celer-g4
  app/celer-g4/ActionInitialization.cc
  app/celer-g4/ActionInitialization.hh
  app/celer-g4/CMakeLists.txt
  app/celer-g4/GeantDiagnostics.cc
  app/celer-g4/GeantDiagnostics.hh
  app/celer-g4/GlobalSetup.cc
  app/celer-g4/GlobalSetup.hh
  app/celer-g4/RunAction.cc
  app/celer-g4/RunAction.hh
  app/celer-g4/TrackingAction.cc
  app/celer-g4/TrackingAction.hh
  src/accel/CMakeLists.txt
  src/accel/GeantStepDiagnostic.cc
  src/accel/GeantStepDiagnostic.hh
Labels: enhancement, app

#866 Fix large function warnings by disabling device debug code by default
  cmake/CeleritasMakeRulesOverride.cmake
  scripts/cmake-presets/ci-ubuntu-cuda.json
  src/celeritas/user/DetectorSteps.cu
Labels: core, minor

#868 Define arithmetic operators for Array
  src/celeritas/em/interactor/EPlusGGInteractor.hh
  src/celeritas/em/msc/UrbanMsc.hh
  src/celeritas/em/msc/detail/UrbanMscScatter.hh
  src/celeritas/field/FieldPropagator.hh
  src/celeritas/field/MagFieldEquation.hh
  src/celeritas/field/ZHelixStepper.hh
  src/celeritas/field/detail/FieldUtils.hh
  src/corecel/cont/Array.hh
  src/corecel/math/ArrayOperators.hh
  src/corecel/math/ArrayUtils.hh
  test/CMakeLists.txt
  test/celeritas/field/FieldDriver.test.cc
  test/corecel/math/ArrayOperators.test.cc
Labels: enhancement, core
