Repository celeritas-project/celeritas, pull requests merged in 2023-05, with the labels that each got.

#736 Add an along step action with a RZMapField
  src/accel/AlongStepFactory.cc
  src/accel/AlongStepFactory.hh
  src/celeritas/CMakeLists.txt
  src/celeritas/field/RZMapFieldData.hh
  src/celeritas/field/RZMapFieldInput.hh
  src/celeritas/global/alongstep/AlongStepRZMapFieldMscAction.cc
  src/celeritas/global/alongstep/AlongStepRZMapFieldMscAction.cu
  src/celeritas/global/alongstep/AlongStepRZMapFieldMscAction.hh
  src/celeritas/global/alongstep/detail/AlongStepRZMapFieldMsc.hh
Labels: enhancement, field

#739 Add G4LogicalVolume* to VolumeId mapping
  src/celeritas/ext/GeantVolumeMapper.cc
  src/celeritas/ext/VecgeomParams.cc
  src/celeritas/ext/VecgeomParams.hh
  src/celeritas/ext/detail/GeantGeoConverter.cc
  src/celeritas/ext/detail/GeantGeoConverter.hh
  src/orange/OrangeParams.cc
  src/orange/OrangeParams.hh
Labels: external

#737 Decompose along-step GPU kernel for 10% performance boost
  cmake/CeleritasGen/gen-action.py
  scripts/dev/iwyu-celeritas.imp
  src/accel/AlongStepFactory.cc
  src/celeritas/Types.hh
  src/celeritas/em/msc/UrbanMsc.hh
  src/celeritas/geo/generated/BoundaryAction.cc
  src/celeritas/geo/generated/BoundaryAction.cu
  src/celeritas/global/TrackLauncher.hh
  src/celeritas/global/alongstep/AlongStep.hh
  src/celeritas/global/alongstep/AlongStepGeneralLinearAction.cc
  src/celeritas/global/alongstep/AlongStepGeneralLinearAction.cu
  src/celeritas/global/alongstep/AlongStepLauncher.hh
  src/celeritas/global/alongstep/AlongStepNeutralAction.cc
  src/celeritas/global/alongstep/AlongStepNeutralAction.cu
  src/celeritas/global/alongstep/AlongStepRZMapFieldMscAction.cc
  src/celeritas/global/alongstep/AlongStepRZMapFieldMscAction.cu
  src/celeritas/global/alongstep/AlongStepRZMapFieldMscAction.hh
  src/celeritas/global/alongstep/AlongStepUniformMscAction.cc
  src/celeritas/global/alongstep/AlongStepUniformMscAction.cu
  src/celeritas/global/alongstep/detail/AlongStepGeneralLinear.hh
  src/celeritas/global/alongstep/detail/AlongStepImpl.hh
  src/celeritas/global/alongstep/detail/AlongStepLauncherImpl.hh
  src/celeritas/global/alongstep/detail/AlongStepNeutral.hh
  src/celeritas/global/alongstep/detail/AlongStepRZMapFieldMsc.hh
  src/celeritas/global/alongstep/detail/AlongStepUniformMsc.hh
  src/celeritas/global/detail/TrackLauncherImpl.hh
  src/celeritas/phys/Interaction.hh
  src/celeritas/phys/PhysicsStepView.hh
  src/celeritas/phys/generated/DiscreteSelectAction.cc
  src/celeritas/phys/generated/DiscreteSelectAction.cu
  src/celeritas/phys/generated/PreStepAction.cc
  src/celeritas/phys/generated/PreStepAction.cu
  src/celeritas/track/SimTrackView.hh
  test/celeritas/global/Stepper.test.cc
Labels: internal, minor

#723 Add documentation about deprecation
  doc/appendices/administration.rst
  scripts/dev/celeritas-gen.py
  src/celeritas/io/ImportMaterial.hh
  src/celeritas/io/ImportModel.hh
  src/celeritas/io/ImportProcess.hh
  src/corecel/grid/Interpolator.hh
  src/corecel/math/Quantity.hh
Labels: documentation

#740 Add ActionDiagnostic, replacing ParticleProcessDiagnostic
  app/CMakeLists.txt
  app/demo-loop/Runner.cc
  app/demo-loop/Runner.hh
  app/demo-loop/RunnerInput.hh
  app/demo-loop/RunnerInputIO.json.cc
  app/demo-loop/Transporter.cc
  app/demo-loop/demo-loop.cc
  app/demo-loop/diagnostic/ParticleProcessDiagnostic.cc
  app/demo-loop/diagnostic/ParticleProcessDiagnostic.cu
  app/demo-loop/diagnostic/ParticleProcessDiagnostic.hh
  app/demo-loop/simple-driver.py
  src/celeritas/CMakeLists.txt
  src/celeritas/user/ActionDiagnostic.cc
  src/celeritas/user/ActionDiagnostic.cu
  src/celeritas/user/ActionDiagnostic.hh
  src/celeritas/user/ActionDiagnosticData.cc
  src/celeritas/user/ActionDiagnosticData.hh
  src/celeritas/user/SimpleCalo.cc
  src/celeritas/user/SimpleCalo.hh
  src/celeritas/user/detail/ActionDiagnosticImpl.hh
  src/corecel/data/StreamStore.hh
  test/CMakeLists.txt
  test/celeritas/user/Diagnostic.test.cc
  test/celeritas/user/DiagnosticTestBase.cc
  test/celeritas/user/DiagnosticTestBase.hh
Labels: enhancement, io

#742 Improve and add internal utilities before refactoring action interface
  src/celeritas/CMakeLists.txt
  src/celeritas/ext/GeantGeoUtils.cc
  src/celeritas/ext/detail/GeantLoggerAdapter.cc
  src/celeritas/global/CoreParams.hh
  src/celeritas/global/CoreState.cc
  src/celeritas/global/CoreState.hh
  src/celeritas/global/CoreTrackData.hh
  src/celeritas/global/CoreTrackDataFwd.hh
  src/celeritas/global/KernelContextException.cc
  src/celeritas/global/KernelContextException.hh
  src/celeritas/global/Stepper.cc
  src/celeritas/global/Stepper.hh
  src/celeritas/track/detail/LocateAliveLauncher.hh
  src/corecel/data/DeviceVector.hh
  src/corecel/data/ObserverPtr.device.hh
  src/corecel/data/ObserverPtr.hh
  src/corecel/io/LogContextException.cc
  src/corecel/io/LogContextException.hh
  src/corecel/io/ScopedStreamRedirect.cc
  src/corecel/io/StringUtils.cc
  src/corecel/io/StringUtils.hh
  src/corecel/math/Algorithms.hh
  src/corecel/sys/TypeDemangler.hh
  test/CMakeLists.txt
  test/celeritas/GlobalTestBase.cc
  test/celeritas/global/ActionRegistry.test.cc
  test/celeritas/global/AlongStepTestBase.cc
  test/celeritas/global/KernelContextException.test.cc
  test/celeritas/global/StepperTestBase.cc
  test/celeritas/track/MockInteractAction.cc
  test/celeritas/track/MockInteractAction.cu
  test/celeritas/track/MockInteractAction.hh
  test/celeritas/track/MockInteractData.hh
  test/celeritas/track/MockInteractImpl.hh
  test/celeritas/track/TrackInit.test.cc
  test/celeritas/track/TrackInit.test.cu
  test/celeritas/track/TrackInit.test.hh
  test/celeritas/track/TrackSort.test.cc
  test/corecel/data/DeviceVector.test.cc
  test/corecel/data/ObserverPtr.test.cc
  test/corecel/data/ObserverPtr.test.cu
  test/corecel/data/ObserverPtr.test.hh
  test/corecel/io/StringUtils.test.cc
  test/corecel/math/Algorithms.test.cc
  test/corecel/sys/TypeDemangler.test.cc
Labels: enhancement, core

#747 Add tests for AlongStepAction with RZMapField
  test/CMakeLists.txt
  test/celeritas/global/AlongStep.test.cc
Labels: documentation, field

#748 Use weak_ptr to fix ActionDiagnostic shared cycle
  src/celeritas/user/ActionDiagnostic.cc
  src/celeritas/user/ActionDiagnostic.hh
  src/celeritas/user/StepDiagnostic.hh
Labels: bug, io, minor

#744 Expand `GeantPhysicsOptions` to encompass all physics processes
  app/demo-loop/RootOutput.cc
  app/demo-loop/Runner.cc
  app/demo-loop/Runner.hh
  app/demo-loop/simple-driver.py
  src/celeritas/ext/GeantPhysicsOptions.cc
  src/celeritas/ext/GeantPhysicsOptions.hh
  src/celeritas/ext/GeantPhysicsOptionsIO.json.cc
  src/celeritas/ext/RootFileManager.cc
  src/celeritas/ext/RootFileManager.hh
  src/celeritas/ext/detail/GeantBremsstrahlungProcess.cc
  src/celeritas/ext/detail/GeantPhysicsList.cc
  src/celeritas/user/ActionDiagnostic.cc
  src/celeritas/user/StepDiagnostic.cc
  test/celeritas/ext/GeantImporter.test.cc
Labels: enhancement, io

#752 Output descriptive state on CPU when an offloaded track dies
  app/demo-geant-integration/ActionInitialization.cc
  app/demo-geant-integration/EventAction.cc
  app/demo-geant-integration/EventAction.hh
  app/demo-geant-integration/TrackingAction.cc
  src/accel/ExceptionConverter.cc
  src/accel/ExceptionConverter.hh
  src/accel/SimpleOffload.cc
  src/celeritas/global/KernelContextException.cc
  src/corecel/OpaqueIdIO.hh
  src/corecel/math/QuantityIO.hh
Labels: enhancement, external

#751 Fail consistently when trying to track in unsupported volumes
  src/celeritas/ext/detail/GeantGeoConverter.cc
  src/celeritas/ext/detail/GenericPlacedVolume.hh
  src/celeritas/ext/detail/GenericSolid.hh
Labels: bug, external

#749 Improve documentation and action descriptions
  src/celeritas/em/model/BetheHeitlerModel.hh
  src/celeritas/em/model/CombinedBremModel.hh
  src/celeritas/em/model/EPlusGGModel.hh
  src/celeritas/em/model/KleinNishinaModel.hh
  src/celeritas/em/model/LivermorePEModel.hh
  src/celeritas/em/model/MollerBhabhaModel.hh
  src/celeritas/em/model/MuBremsstrahlungModel.hh
  src/celeritas/em/model/RayleighModel.hh
  src/celeritas/em/model/RelativisticBremModel.hh
  src/celeritas/em/model/SeltzerBergerModel.hh
  src/celeritas/global/ActionInterface.hh
  src/celeritas/global/CoreParams.cc
  src/celeritas/global/alongstep/AlongStepGeneralLinearAction.hh
  src/celeritas/global/alongstep/AlongStepNeutralAction.hh
  src/celeritas/global/alongstep/AlongStepRZMapFieldMscAction.hh
  src/celeritas/global/alongstep/AlongStepUniformMscAction.hh
  src/celeritas/phys/PhysicsParams.cc
  src/celeritas/user/ActionDiagnostic.cc
  src/celeritas/user/ActionDiagnostic.hh
  src/celeritas/user/StepDiagnostic.cc
  src/celeritas/user/StepDiagnostic.hh
  src/celeritas/user/detail/StepGatherAction.cc
  test/celeritas/GeantTestBase.cc
  test/celeritas/global/Stepper.test.cc
  test/celeritas/global/StepperTestBase.cc
  test/celeritas/global/StepperTestBase.hh
Labels: documentation

#715 Add a VecGeom+RelWithDebInfo+debug build to the CI
  .jenkins
  scripts/cmake-presets/ci-ubuntu-cuda.json
  src/accel/detail/HitProcessor.cc
  src/celeritas/ext/detail/GenericPlacedVolume.hh
  src/celeritas/ext/detail/GenericSolid.hh
  src/celeritas/user/SimpleCaloData.cc
  src/corecel/data/CollectionAlgorithms.hh
Labels: minor

#745 Use separate along-step kernel for neutral particles for 25% performance boost
  app/demo-loop/RunnerInputIO.json.cc
  src/celeritas/Types.cc
  src/celeritas/Types.hh
  src/celeritas/global/CoreParams.cc
  src/celeritas/global/CoreTrackData.hh
  src/celeritas/global/CoreTrackView.hh
  src/celeritas/global/TrackLauncher.hh
  src/celeritas/global/alongstep/AlongStepGeneralLinearAction.cc
  src/celeritas/global/alongstep/AlongStepGeneralLinearAction.cu
  src/celeritas/global/alongstep/AlongStepNeutralAction.cc
  src/celeritas/global/alongstep/AlongStepNeutralAction.cu
  src/celeritas/global/alongstep/AlongStepRZMapFieldMscAction.cc
  src/celeritas/global/alongstep/AlongStepRZMapFieldMscAction.cu
  src/celeritas/global/alongstep/AlongStepUniformMscAction.cc
  src/celeritas/global/alongstep/AlongStepUniformMscAction.cu
  src/celeritas/global/detail/ActionSequence.cc
  src/celeritas/global/detail/TrackLauncherImpl.hh
  src/celeritas/phys/detail/PreStepActionImpl.hh
  src/celeritas/track/SimData.hh
  src/celeritas/track/SimTrackView.hh
  src/celeritas/track/SortTracksAction.cc
  src/celeritas/track/SortTracksAction.hh
  src/celeritas/track/detail/TrackSortUtils.cc
  src/celeritas/track/detail/TrackSortUtils.cu
  src/celeritas/track/detail/TrackSortUtils.hh
  test/celeritas/global/Stepper.test.cc
  test/celeritas/track/TrackSort.test.cc
  test/celeritas/user/Diagnostic.test.cc
Labels: enhancement, core

#755 Use UniformGrid for RZMapField
  src/celeritas/field/RZMapField.hh
  src/celeritas/field/RZMapFieldData.hh
  src/celeritas/field/RZMapFieldInput.hh
  src/celeritas/field/RZMapFieldInputIO.json.cc
  src/celeritas/field/RZMapFieldParams.cc
  src/corecel/grid/FindInterp.hh
  src/corecel/grid/TwodGridCalculator.hh
  src/corecel/grid/TwodSubgridCalculator.hh
  test/celeritas/data/cms-tiny.field.json
  test/celeritas/global/AlongStep.test.cc
  test/corecel/grid/TwodGridCalculator.test.cc
Labels: field

#753 Fix duplicate volume warnings and missing material IDs
  app/demo-geant-integration/DetectorConstruction.cc
  app/demo-geant-integration/GlobalSetup.cc
  app/demo-geant-integration/GlobalSetup.hh
  src/celeritas/ext/GeantVolumeMapper.cc
  src/celeritas/ext/VecgeomParams.cc
  src/celeritas/ext/detail/GeantGeoConverter.cc
  src/celeritas/ext/detail/GeantVolumeVisitor.cc
  src/corecel/cont/LabelIdMultiMap.hh
  src/corecel/io/Label.hh
  test/celeritas/ext/GeantVolumeMapper.test.cc
  test/celeritas/ext/Vecgeom.test.cc
  test/corecel/cont/LabelIdMultiMap.test.cc
Labels: bug, external

#763 Release v0.2.2
  doc/appendices/release-history/v0.2.rst
  src/celeritas/ext/VecgeomParams.hh
  src/orange/OrangeParams.hh
Labels: documentation

#761 Fix conversion of Geant4 reflected shapes
  src/celeritas/ext/detail/GeantGeoConverter.cc
  src/celeritas/ext/detail/GeantGeoConverter.hh
  test/celeritas/data/solids.gdml
  test/celeritas/ext/Vecgeom.test.cc
Labels: bug, external

#767 Extend and update SWIG wrappers
  interface/celeritas.i
  interface/detail/macros.i
  scripts/cmake-presets/goldfinger.json
  src/celeritas/ext/RootUniquePtr.root.cc
Labels: enhancement, io

#760 Add option to throw an exception when ROOT encountered an "error"
  app/celer-export-geant.cc
  src/celeritas/ext/ScopedRootErrorHandler.cc
  src/celeritas/ext/ScopedRootErrorHandler.hh
  src/corecel/AssertIO.json.cc
  src/corecel/sys/Device.cc
  src/corecel/sys/ScopedMem.cc
  src/corecel/sys/ScopedSignalHandler.cc
  test/CMakeLists.txt
  test/celeritas/RootTestBase.cc
  test/celeritas/data/simple-cms.geant.json
  test/celeritas/data/simple-cms.root
Labels: enhancement, external

#768 Support Geant4 11.1+
  app/demo-geant-integration/demo-geant-integration.cc
  src/celeritas/ext/GeantImporter.cc
  src/celeritas/ext/detail/GeantLoggerAdapter.cc
  src/celeritas/ext/detail/GeantLoggerAdapter.hh
  src/celeritas/ext/detail/GeantPhysicsList.cc
  src/celeritas/grid/ValueGridBuilder.cc
  src/celeritas/phys/ImportedProcessAdapter.cc
  src/celeritas/phys/ImportedProcessAdapter.hh
  test/celeritas/global/AlongStep.test.cc
Labels: enhancement, external

#771 Consolidate Geant4 geometry conversion utilities
  src/accel/AlongStepFactory.cc
  src/accel/LocalTransporter.cc
  src/accel/detail/HitProcessor.cc
  src/celeritas/ext/Convert.geant.hh
  src/celeritas/ext/GeantGeoUtils.cc
  src/celeritas/ext/GeantGeoUtils.hh
  src/celeritas/ext/GeantSetup.cc
Labels: minor, external

#770 Improve VecGeom testing
  src/celeritas/ext/VecgeomTrackView.hh
  src/celeritas/ext/detail/GeantGeoConverter.cc
  src/celeritas/ext/detail/VecgeomNavCollection.cc
  src/celeritas/ext/detail/VecgeomNavCollection.hh
  src/celeritas/geo/GeoParamsOutput.cc
  src/celeritas/geo/GeoParamsOutput.hh
  src/orange/OrangeTrackView.hh
  test/celeritas/GenericGeoTestBase.cc
  test/celeritas/GenericGeoTestBase.hh
  test/celeritas/ext/Vecgeom.test.cc
Labels: minor, external

#769 Add begin-of-run interface to initialize states and actions
  app/demo-loop/Runner.cc
  src/celeritas/global/ActionInterface.hh
  src/celeritas/global/ActionRegistry.cc
  src/celeritas/global/ActionRegistry.hh
  src/celeritas/global/CoreParams.cc
  src/celeritas/global/Stepper.cc
  src/celeritas/global/detail/ActionRegistryImpl.hh
  src/celeritas/global/detail/ActionSequence.cc
  src/celeritas/global/detail/ActionSequence.hh
  src/celeritas/phys/PhysicsParams.cc
  src/celeritas/user/ActionDiagnostic.cc
  src/celeritas/user/ActionDiagnostic.cu
  src/celeritas/user/ActionDiagnostic.hh
  test/celeritas/global/ActionRegistry.test.cc
  test/celeritas/user/DiagnosticTestBase.cc
Labels: enhancement, core

#766 Refactor track initialization kernels and initialization scalars
  cmake/CeleritasGen/gen-action.py
  cmake/CeleritasGen/gen-trackinit.py
  src/celeritas/CMakeLists.txt
  src/celeritas/geo/generated/BoundaryAction.cc
  src/celeritas/global/CoreParams.cc
  src/celeritas/global/CoreState.cc
  src/celeritas/global/CoreState.hh
  src/celeritas/global/ExecuteAction.hh
  src/celeritas/global/Stepper.cc
  src/celeritas/global/TrackLauncher.hh
  src/celeritas/global/alongstep/AlongStepUniformMscAction.cc
  src/celeritas/global/alongstep/AlongStepUniformMscAction.hh
  src/celeritas/phys/generated/DiscreteSelectAction.cc
  src/celeritas/phys/generated/PreStepAction.cc
  src/celeritas/track/CoreStateCounters.hh
  src/celeritas/track/ExtendFromPrimariesAction.cc
  src/celeritas/track/ExtendFromPrimariesAction.cu
  src/celeritas/track/ExtendFromPrimariesAction.hh
  src/celeritas/track/ExtendFromSecondariesAction.cc
  src/celeritas/track/ExtendFromSecondariesAction.cu
  src/celeritas/track/ExtendFromSecondariesAction.hh
  src/celeritas/track/InitializeTracksAction.cc
  src/celeritas/track/InitializeTracksAction.cu
  src/celeritas/track/InitializeTracksAction.hh
  src/celeritas/track/TrackInitData.hh
  src/celeritas/track/detail/InitTracksLauncher.hh
  src/celeritas/track/detail/LocateAliveLauncher.hh
  src/celeritas/track/detail/ProcessPrimariesLauncher.hh
  src/celeritas/track/detail/ProcessSecondariesLauncher.hh
  src/celeritas/track/generated/.clang-format
  src/celeritas/track/generated/InitTracks.cc
  src/celeritas/track/generated/InitTracks.cu
  src/celeritas/track/generated/InitTracks.hh
  src/celeritas/track/generated/LocateAlive.cc
  src/celeritas/track/generated/LocateAlive.cu
  src/celeritas/track/generated/LocateAlive.hh
  src/celeritas/track/generated/ProcessPrimaries.cc
  src/celeritas/track/generated/ProcessPrimaries.cu
  src/celeritas/track/generated/ProcessPrimaries.hh
  src/celeritas/track/generated/ProcessSecondaries.cc
  src/celeritas/track/generated/ProcessSecondaries.cu
  src/celeritas/track/generated/ProcessSecondaries.hh
  src/celeritas/user/ActionDiagnostic.cc
  src/corecel/data/DeviceAllocation.cc
  test/celeritas/track/TrackInit.test.cc
  test/celeritas/user/Diagnostic.test.cc
Labels: core, minor

#774 Support multithreaded CPU using single GPU in demo loop
  app/CMakeLists.txt
  app/demo-loop/Runner.cc
  app/demo-loop/Runner.hh
  app/demo-loop/RunnerInput.hh
  app/demo-loop/RunnerInputIO.json.cc
  app/demo-loop/RunnerOutput.cc
  app/demo-loop/RunnerOutput.hh
  app/demo-loop/Transporter.cc
  app/demo-loop/Transporter.hh
  app/demo-loop/demo-loop.cc
  app/demo-loop/simple-driver.py
  src/celeritas/user/ActionDiagnostic.cc
Labels: enhancement, core

#775 Separate app CMakeLists and install executables
  CMakeLists.txt
  app/CMakeLists.txt
  app/demo-geant-integration/CMakeLists.txt
  app/demo-interactor/CMakeLists.txt
  app/demo-interactor/demo-interactor.cc
  app/demo-loop/CMakeLists.txt
  app/demo-loop/demo-loop.cc
  app/demo-rasterizer/CMakeLists.txt
  app/demo-rasterizer/demo-rasterizer.cc
  app/geo-check/CMakeLists.txt
  app/geo-check/GCheckKernel.hh
  app/geo-check/GCheckRunner.cc
  app/geo-check/GCheckRunner.hh
  app/geo-check/gcheck-cms2018.json
  app/geo-check/gcheck-four-levels.json.in
  app/geo-check/gcheck-simplecms.json
  app/geo-check/geo-check.cc
  cmake/CeleritasUtils.cmake
  example/minimal/minimal.cc
  src/corecel/sys/Device.cc
  src/corecel/sys/Device.hh
  src/corecel/sys/MpiCommunicator.cc
  src/corecel/sys/MpiCommunicator.hh
  test/testdetail/TestMainImpl.cc
Labels: core, minor

#776 Remove next-distance caching from geometry and add limited-distance safety search
  src/accel/ExceptionConverter.cc
  src/celeritas/em/msc/UrbanMsc.hh
  src/celeritas/em/msc/detail/UrbanMscScatter.hh
  src/celeritas/em/msc/detail/UrbanMscStepLimit.hh
  src/celeritas/ext/VecgeomData.hh
  src/celeritas/ext/VecgeomTrackView.hh
  src/celeritas/ext/detail/BVHNavigator.hh
  src/celeritas/global/KernelContextException.cc
  src/celeritas/global/KernelContextException.hh
  src/celeritas/track/detail/InitTracksLauncher.hh
  src/celeritas/track/detail/ProcessSecondariesLauncher.hh
  src/orange/OrangeData.hh
  src/orange/OrangeTrackView.hh
  test/celeritas/ext/Vecgeom.test.cc
  test/celeritas/geo/HeuristicGeoLauncher.hh
  test/celeritas/global/KernelContextException.test.cc
  test/celeritas/user/Diagnostic.test.cc
  test/orange/Orange.test.cc
Labels: bug, field

#759 Implement a Geant4 geometry tracker for comparing with VecGeom
  .jenkins
  CMakeLists.txt
  app/celer-sim/CMakeLists.txt
  app/celer-sim/simple-driver.py
  app/demo-rasterizer/CMakeLists.txt
  cmake/CeleritasUtils.cmake
  example/accel/CMakeLists.txt
  scripts/cmake-presets/ci-centos-rocm.json
  scripts/cmake-presets/goldfinger.json
  scripts/cmake-presets/wildstyle.json
  src/CMakeLists.txt
  src/accel/detail/HitProcessor.cc
  src/celeritas/CMakeLists.txt
  src/celeritas/em/model/LivermorePEModel.cc
  src/celeritas/em/model/SeltzerBergerModel.cc
  src/celeritas/ext/Convert.geant.hh
  src/celeritas/ext/GeantGeoData.hh
  src/celeritas/ext/GeantGeoParams.cc
  src/celeritas/ext/GeantGeoParams.hh
  src/celeritas/ext/GeantGeoTrackView.hh
  src/celeritas/ext/detail/GeantGeoNavCollection.cc
  src/celeritas/ext/detail/GeantGeoNavCollection.hh
  src/celeritas/ext/detail/GeantVolumeVisitor.cc
  src/celeritas/ext/detail/GeantVolumeVisitor.hh
  src/celeritas/geo/GeoData.hh
  src/celeritas/geo/GeoFwd.hh
  src/celeritas/geo/GeoMaterialParams.cc
  src/celeritas/geo/GeoParams.hh
  src/celeritas/geo/GeoTrackView.hh
  src/celeritas/global/CoreParams.cc
  src/celeritas/global/CoreState.cc
  src/celeritas/global/CoreTrackData.cc
  src/celeritas/track/detail/InitTracksExecutor.hh
  test/CMakeLists.txt
  test/Test.cc
  test/celeritas/GeantTestBase.cc
  test/celeritas/GenericGeoTestBase.cc
  test/celeritas/GenericGeoTestBase.hh
  test/celeritas/GlobalGeoTestBase.cc
  test/celeritas/em/UrbanMsc.test.cc
  test/celeritas/ext/GeantGeo.test.cc
  test/celeritas/ext/GeantVolumeMapper.test.cc
  test/celeritas/ext/Vecgeom.test.cc
  test/celeritas/field/FieldPropagator.test.cc
  test/celeritas/geo/Geometry.test.cc
  test/celeritas/global/KernelContextException.test.cc
  test/celeritas/user/StepCollector.test.cc
Labels: enhancement, external
