Repository celeritas-project/celeritas, pull requests merged in 2023-01, with the labels that each got.

#587 Minor fixes for older Geant4/VecGeom releases
  README.md
  scripts/spack.yaml
  src/corecel/cont/Label.cc
  test/celeritas/ext/Vecgeom.test.cc
Labels: bug, documentation

#586 Support user-defined along-step kernels in accel+demo
  app/CMakeLists.txt
  app/demo-geant-integration/GlobalSetup.cc
  app/demo-geant-integration/GlobalSetup.hh
  app/demo-geant-integration/MasterRunAction.cc
  app/demo-geant-integration/NoFieldAlongStepFactory.cc
  app/demo-geant-integration/NoFieldAlongStepFactory.hh
  src/accel/AlongStepFactory.hh
  src/accel/SetupOptions.hh
  src/accel/SharedParams.cc
Labels: enhancement, integration

#581 Add hit processor to convert Celeritas detector hits to Geant4
  CMakeLists.txt
  app/demo-geant-integration/DetectorConstruction.cc
  app/demo-geant-integration/DetectorConstruction.hh
  app/demo-geant-integration/GlobalSetup.hh
  app/demo-geant-integration/RunAction.cc
  app/demo-geant-integration/SensitiveDetector.cc
  app/demo-geant-integration/SensitiveDetector.hh
  app/demo-geant-integration/SensitiveHit.cc
  app/demo-geant-integration/SensitiveHit.hh
  app/demo-geant-integration/demo-geant-integration.cc
  cmake/FindGeant4.cmake
  src/CMakeLists.txt
  src/accel/CMakeLists.txt
  src/accel/LocalTransporter.cc
  src/accel/LocalTransporter.hh
  src/accel/Logger.cc
  src/accel/SetupOptions.hh
  src/accel/SharedParams.cc
  src/accel/SharedParams.hh
  src/accel/detail/HitManager.cc
  src/accel/detail/HitManager.hh
  src/accel/detail/HitProcessor.cc
  src/accel/detail/HitProcessor.hh
  src/celeritas/ext/VecgeomParams.cc
  src/celeritas/ext/VecgeomParams.hh
  src/celeritas/global/CoreParams.hh
  src/celeritas/user/DetectorSteps.cc
  src/celeritas/user/DetectorSteps.cu
  src/celeritas/user/DetectorSteps.hh
  src/celeritas/user/detail/StepGatherAction.cc
  src/celeritas/user/detail/StepGatherAction.hh
  src/celeritas/user/detail/StepStorage.hh
  src/corecel/CMakeLists.txt
  src/corecel/cont/Label.hh
  src/orange/OrangeParams.cc
  src/orange/OrangeParams.hh
  test/celeritas/ext/Vecgeom.test.cc
  test/celeritas/user/DetectorSteps.test.cc
Labels: enhancement, integration

#589 Use Geant4 environment variables to choose run manager and threads
  app/CMakeLists.txt
  app/demo-geant-integration/ActionInitialization.cc
  app/demo-geant-integration/ActionInitialization.hh
  app/demo-geant-integration/MasterRunAction.cc
  app/demo-geant-integration/MasterRunAction.hh
  app/demo-geant-integration/RunAction.cc
  app/demo-geant-integration/RunAction.hh
  app/demo-geant-integration/demo-geant-integration.cc
  src/accel/LocalTransporter.hh
  src/accel/Logger.cc
  src/accel/SharedParams.cc
  src/accel/SharedParams.hh
  src/accel/detail/HitProcessor.cc
  src/celeritas/ext/GeantConfig.hh
  src/celeritas/ext/GeantSetup.cc
  src/celeritas/ext/detail/ImportProcessConverter.cc
Labels: bug, documentation, integration

#590 Add track parent id information to step data
  src/celeritas/io/RootFileManager.cc
  src/celeritas/io/RootStepWriter.cc
  src/celeritas/io/RootStepWriter.hh
  src/celeritas/user/DetectorSteps.cc
  src/celeritas/user/DetectorSteps.cu
  src/celeritas/user/DetectorSteps.hh
  src/celeritas/user/StepData.hh
  src/celeritas/user/detail/StepGatherLauncher.hh
Labels: enhancement

#594 Rename `CELER_TRY_ELSE` to `CELER_TRY_HANDLE`
  app/demo-geant-integration/EventAction.cc
  app/demo-geant-integration/PrimaryGeneratorAction.cc
  app/demo-geant-integration/RunAction.cc
  app/demo-geant-integration/TrackingAction.cc
  app/demo-geant-integration/demo-geant-integration.cc
  cmake/CeleritasGen/gen-action.py
  cmake/CeleritasGen/gen-interactor.py
  cmake/CeleritasGen/gen-trackinit.py
  src/accel/ExceptionConverter.hh
  src/celeritas/em/generated/BetheHeitlerInteract.cc
  src/celeritas/em/generated/CombinedBremInteract.cc
  src/celeritas/em/generated/EPlusGGInteract.cc
  src/celeritas/em/generated/KleinNishinaInteract.cc
  src/celeritas/em/generated/LivermorePEInteract.cc
  src/celeritas/em/generated/MollerBhabhaInteract.cc
  src/celeritas/em/generated/MuBremsstrahlungInteract.cc
  src/celeritas/em/generated/RayleighInteract.cc
  src/celeritas/em/generated/RelativisticBremInteract.cc
  src/celeritas/em/generated/SeltzerBergerInteract.cc
  src/celeritas/geo/generated/BoundaryAction.cc
  src/celeritas/global/alongstep/AlongStepGeneralLinearAction.cc
  src/celeritas/global/alongstep/AlongStepNeutralAction.cc
  src/celeritas/global/alongstep/AlongStepUniformMscAction.cc
  src/celeritas/phys/generated/DiscreteSelectAction.cc
  src/celeritas/phys/generated/PreStepAction.cc
  src/celeritas/track/generated/InitTracks.cc
  src/celeritas/track/generated/LocateAlive.cc
  src/celeritas/track/generated/ProcessPrimaries.cc
  src/celeritas/track/generated/ProcessSecondaries.cc
  src/celeritas/user/detail/StepGatherAction.cc
  src/corecel/Macros.hh
  src/corecel/sys/MultiExceptionHandler.hh
  test/accel/ExceptionConverter.test.cc
  test/corecel/sys/MultiExceptionHandler.test.cc
Labels: infrastructure, housekeeping

#595 Add Acceleritas documentation
  README.md
  app/demo-geant-integration/DetectorConstruction.cc
  app/demo-geant-integration/EventAction.cc
  app/demo-geant-integration/EventAction.hh
  app/demo-geant-integration/RunAction.hh
  app/demo-geant-integration/TrackingAction.cc
  app/demo-geant-integration/TrackingAction.hh
  doc/CMakeLists.txt
  doc/api.rst
  doc/api/accel.rst
  doc/conf.py
  doc/examples.rst
  doc/index.rst
  src/accel/ExceptionConverter.hh
  src/accel/Logger.cc
  src/accel/SetupOptions.hh
  src/celeritas/Types.hh
  src/celeritas/ext/GeantConfig.hh
  src/celeritas/ext/RootInterfaceLinkDef.h
  src/celeritas/ext/ScopedRootErrorHandler.cc
  src/celeritas/ext/ScopedRootErrorHandler.hh
  src/corecel/Assert.cc
  src/corecel/Macros.hh
  src/corecel/Types.hh
  src/corecel/data/Ref.hh
  src/corecel/io/LoggerTypes.hh
  src/corecel/sys/detail/MpiCommunicatorImpl.hh
  src/orange/OrangeTypes.hh
Labels: documentation

#599 Add backward compatibility for primary generators
  src/celeritas/phys/PrimaryGeneratorOptionsIO.json.cc
Labels: bug

#597 Refactor assertion macros
  src/celeritas/phys/PrimaryGeneratorOptionsIO.json.cc
  src/corecel/Assert.hh
  src/corecel/Macros.hh
Labels: infrastructure, housekeeping

#601 Add action labels to the ROOT MC truth output file
  app/demo-loop/LDemoIO.hh
  app/demo-loop/LDemoIO.root.cc
  app/demo-loop/demo-loop.cc
Labels: enhancement

#600 Release v0.2.0
  .git-blame-ignore-revs
  doc/CMakeLists.txt
  doc/appendices/administration.rst
  doc/appendices/release-history.rst
  scripts/cmake-presets/summit.json
  src/accel/detail/HitProcessor.cc
Labels: documentation

#603 Allow invalid volume IDs in ROOT MC truth output
  src/celeritas/io/RootStepWriter.cc
Labels: bug

#604 Remove MSC data from core physics class
  src/celeritas/CMakeLists.txt
  src/celeritas/em/data/UrbanMscData.hh
  src/celeritas/em/distribution/UrbanMscHelper.hh
  src/celeritas/em/distribution/UrbanMscScatter.hh
  src/celeritas/em/distribution/UrbanMscStepLimit.hh
  src/celeritas/em/model/UrbanMscModel.cc
  src/celeritas/em/model/UrbanMscModel.hh
  src/celeritas/em/process/MultipleScatteringProcess.cc
  src/celeritas/global/alongstep/detail/UrbanMsc.hh
  src/celeritas/grid/ValueGridData.cc
  src/celeritas/grid/ValueGridData.hh
  src/celeritas/io/ImportProcess.hh
  src/celeritas/mat/MaterialData.hh
  src/celeritas/mat/MaterialParams.cc
  src/celeritas/mat/MaterialView.hh
  src/celeritas/phys/ImportedProcessAdapter.cc
  src/celeritas/phys/ImportedProcessAdapter.hh
  src/celeritas/phys/PhysicsData.hh
  src/celeritas/phys/PhysicsParams.cc
  src/celeritas/phys/PhysicsTrackView.hh
  test/celeritas/em/UrbanMsc.test.cc
  test/celeritas/mat/Material.test.cc
  test/celeritas/phys/Physics.test.cc
  test/celeritas/phys/ProcessBuilder.test.cc
Labels: physics, housekeeping

#612 Write particle params to diagnostic output
  app/demo-loop/LDemoIO.cc
  app/demo-loop/demo-loop.cc
  app/demo-rasterizer/ImageIO.cc
  src/accel/SharedParams.cc
  src/celeritas/CMakeLists.txt
  src/celeritas/phys/ParticleParamsOutput.cc
  src/celeritas/phys/ParticleParamsOutput.hh
  src/celeritas/phys/PhysicsParamsOutput.cc
  src/celeritas/phys/PrimaryGeneratorOptionsIO.json.cc
  src/corecel/cont/ArrayIO.json.hh
  src/corecel/cont/LabelIO.json.hh
  src/orange/construct/OrangeInputIO.json.cc
  test/celeritas/phys/Particle.test.cc
Labels: enhancement, interface

#609 Update crusher environment to use AMD LLVM compilers
  scripts/cmake-presets/crusher.json
  scripts/env/crusher.sh
Labels: infrastructure, housekeeping

#611 Provide detailed track and kernel information when CPU exceptions are thrown
  app/demo-loop/simple-driver.py
  cmake/CeleritasGen/gen-action.py
  cmake/CeleritasGen/gen-interactor.py
  cmake/CeleritasGen/gen-trackinit.py
  src/accel/ExceptionConverter.cc
  src/celeritas/CMakeLists.txt
  src/celeritas/em/generated/BetheHeitlerInteract.cc
  src/celeritas/em/generated/CombinedBremInteract.cc
  src/celeritas/em/generated/EPlusGGInteract.cc
  src/celeritas/em/generated/KleinNishinaInteract.cc
  src/celeritas/em/generated/LivermorePEInteract.cc
  src/celeritas/em/generated/MollerBhabhaInteract.cc
  src/celeritas/em/generated/MuBremsstrahlungInteract.cc
  src/celeritas/em/generated/RayleighInteract.cc
  src/celeritas/em/generated/RelativisticBremInteract.cc
  src/celeritas/em/generated/SeltzerBergerInteract.cc
  src/celeritas/geo/generated/BoundaryAction.cc
  src/celeritas/global/KernelContextException.cc
  src/celeritas/global/KernelContextException.hh
  src/celeritas/global/Stepper.hh
  src/celeritas/global/alongstep/AlongStepGeneralLinearAction.cc
  src/celeritas/global/alongstep/AlongStepNeutralAction.cc
  src/celeritas/global/alongstep/AlongStepUniformMscAction.cc
  src/celeritas/phys/generated/DiscreteSelectAction.cc
  src/celeritas/phys/generated/PreStepAction.cc
  src/celeritas/track/generated/InitTracks.cc
  src/celeritas/track/generated/LocateAlive.cc
  src/celeritas/track/generated/ProcessPrimaries.cc
  src/celeritas/track/generated/ProcessSecondaries.cc
  src/corecel/Assert.hh
  src/corecel/AssertIO.json.cc
  src/corecel/AssertIO.json.hh
  src/corecel/CMakeLists.txt
  src/corecel/Macros.hh
  src/corecel/io/ExceptionOutput.cc
  src/corecel/io/Logger.hh
  src/corecel/io/detail/LoggerMessage.hh
  src/corecel/sys/MultiExceptionHandler.cc
  test/CMakeLists.txt
  test/celeritas/global/KernelContextException.test.cc
  test/corecel/io/OutputManager.test.cc
  test/corecel/sys/MultiExceptionHandler.test.cc
Labels: enhancement, infrastructure
