Repository celeritas-project/celeritas, pull requests merged in 2023-06, with the labels that each got.

#758 Add RectArrayTracker class
  src/corecel/data/HyperslabIndexer.hh
  src/corecel/data/detail/HyperslabIndexerImpl.hh
  src/corecel/math/Algorithms.hh
  src/corecel/math/detail/AlgorithmsImpl.hh
  src/orange/OrangeData.hh
  src/orange/OrangeParams.cc
  src/orange/detail/RectArrayInserter.cc
  src/orange/univ/RectArrayTracker.hh
  src/orange/univ/detail/RaggedRightIndexer.hh
  test/CMakeLists.txt
  test/corecel/data/HyperslabIndexer.test.cc
  test/corecel/math/Algorithms.test.cc
  test/orange/univ/RectArrayTracker.test.cc
  test/orange/univ/detail/RaggedRightIndexer.test.cc
Labels: enhancement, orange

#787 Use ActionLauncher for Klein-Nishina model
  src/celeritas/CMakeLists.txt
  src/celeritas/em/executor/KleinNishinaExecutor.hh
  src/celeritas/em/generated/KleinNishinaInteract.cc
  src/celeritas/em/generated/KleinNishinaInteract.cu
  src/celeritas/em/generated/KleinNishinaInteract.hh
  src/celeritas/em/model/KleinNishinaModel.cc
  src/celeritas/em/model/KleinNishinaModel.cu
Labels: minor

#788 Use ActionLauncher for boundary action
  CMakeLists.txt
  cmake/CeleritasGen/gen-action.py
  src/celeritas/CMakeLists.txt
  src/celeritas/geo/detail/BoundaryAction.cc
  src/celeritas/geo/detail/BoundaryAction.cu
  src/celeritas/geo/detail/BoundaryAction.hh
  src/celeritas/geo/detail/BoundaryExecutor.hh
  src/celeritas/geo/generated/.clang-format
  src/celeritas/geo/generated/BoundaryAction.cu
  src/celeritas/global/CoreParams.cc
Labels: core, minor

#786 Use ActionLauncher for positron annihilation, Rayleigh scattering, and Seltzer-Berger models
  src/celeritas/CMakeLists.txt
  src/celeritas/em/executor/EPlusGGExecutor.hh
  src/celeritas/em/executor/RayleighExecutor.hh
  src/celeritas/em/executor/SeltzerBergerExecutor.hh
  src/celeritas/em/generated/EPlusGGInteract.cc
  src/celeritas/em/generated/EPlusGGInteract.cu
  src/celeritas/em/generated/EPlusGGInteract.hh
  src/celeritas/em/generated/RayleighInteract.cc
  src/celeritas/em/generated/RayleighInteract.cu
  src/celeritas/em/generated/RayleighInteract.hh
  src/celeritas/em/generated/SeltzerBergerInteract.cc
  src/celeritas/em/generated/SeltzerBergerInteract.cu
  src/celeritas/em/generated/SeltzerBergerInteract.hh
  src/celeritas/em/model/EPlusGGModel.cc
  src/celeritas/em/model/EPlusGGModel.cu
  src/celeritas/em/model/EPlusGGModel.hh
  src/celeritas/em/model/RayleighModel.cc
  src/celeritas/em/model/RayleighModel.cu
  src/celeritas/em/model/RayleighModel.hh
  src/celeritas/em/model/SeltzerBergerModel.cc
  src/celeritas/em/model/SeltzerBergerModel.cu
Labels: minor

#785 Rename `max_num_tracks` to `num_track_slots` and divide by `num_streams`
  app/celer-sim/Runner.cc
  app/celer-sim/Runner.hh
  app/celer-sim/RunnerInput.hh
  app/celer-sim/RunnerInputIO.json.cc
  app/celer-sim/RunnerOutput.cc
  app/celer-sim/RunnerOutput.hh
  app/celer-sim/Transporter.cc
  app/celer-sim/Transporter.hh
  app/celer-sim/celer-sim.cc
  app/celer-sim/simple-driver.py
  src/celeritas/global/CoreState.hh
  src/celeritas/global/Stepper.hh
  src/corecel/sys/Device.cc
  src/corecel/sys/Device.hh
  src/corecel/sys/ScopedMem.hh
Labels: enhancement, internal

#792 Remove CelerGen and associated scripts
  CMakeLists.txt
  cmake/CeleritasGen.cmake
  cmake/CeleritasGen/gen-interactor.py
  cmake/CeleritasGen/launch-bounds.json
  cmake/CeleritasGen/launchbounds.py
  scripts/cmake-presets/ci-ubuntu-cuda.json
  scripts/cmake-presets/wildstyle.json
  scripts/dev/process-kernel-stats.py
  src/CMakeLists.txt
  src/celeritas_config.h.in
  src/corecel/io/BuildOutput.cc
Labels: core, minor

#793 Refactor TrackInitTest and fix when JSON is unavailable
  test/CMakeLists.txt
  test/celeritas/field/Fields.test.cc
  test/celeritas/global/Stepper.test.cc
  test/celeritas/global/Stepper.test.hh
  test/celeritas/track/TrackSort.test.cc
  test/corecel/io/OutputRegistry.test.cc
Labels: documentation, minor

#791 Use ActionLauncher for along-step methods
  src/celeritas/CMakeLists.txt
  src/celeritas/em/msc/UrbanMsc.hh
  src/celeritas/em/msc/detail/MscStepFromGeo.hh
  src/celeritas/em/msc/detail/MscStepToGeo.hh
  src/celeritas/em/msc/detail/UrbanMscHelper.hh
  src/celeritas/em/msc/detail/UrbanMscScatter.hh
  src/celeritas/field/DormandPrinceStepper.hh
  src/celeritas/field/MakeMagFieldPropagator.hh
  src/celeritas/field/RZMapField.hh
  src/celeritas/field/RZMapFieldInputIO.json.cc
  src/celeritas/field/RZMapFieldParams.cc
  src/celeritas/global/ActionLauncher.device.hh
  src/celeritas/global/alongstep/AlongStep.hh
  src/celeritas/global/alongstep/AlongStepGeneralLinearAction.cc
  src/celeritas/global/alongstep/AlongStepGeneralLinearAction.cu
  src/celeritas/global/alongstep/AlongStepGeneralLinearAction.hh
  src/celeritas/global/alongstep/AlongStepNeutralAction.cc
  src/celeritas/global/alongstep/AlongStepNeutralAction.cu
  src/celeritas/global/alongstep/AlongStepRZMapFieldMscAction.cc
  src/celeritas/global/alongstep/AlongStepRZMapFieldMscAction.cu
  src/celeritas/global/alongstep/AlongStepRZMapFieldMscAction.hh
  src/celeritas/global/alongstep/AlongStepUniformMscAction.cc
  src/celeritas/global/alongstep/AlongStepUniformMscAction.cu
  src/celeritas/global/alongstep/detail/AlongStepGeneralLinear.hh
  src/celeritas/global/alongstep/detail/AlongStepImpl.hh
  src/celeritas/global/alongstep/detail/AlongStepKernels.cu
  src/celeritas/global/alongstep/detail/AlongStepKernels.hh
  src/celeritas/global/alongstep/detail/AlongStepNeutralImpl.hh
  src/celeritas/global/alongstep/detail/AlongStepRZMapFieldMsc.hh
  src/celeritas/global/alongstep/detail/AlongStepUniformMsc.hh
  src/celeritas/global/alongstep/detail/ElossApplier.hh
  src/celeritas/global/alongstep/detail/FluctELoss.hh
  src/celeritas/global/alongstep/detail/LinearTrackPropagator.hh
  src/celeritas/global/alongstep/detail/MscApplier.hh
  src/celeritas/global/alongstep/detail/MscStepLimitApplier.hh
  src/celeritas/global/alongstep/detail/PropagationApplier.hh
  src/celeritas/global/alongstep/detail/RZMapFieldTrackPropagator.hh
  src/celeritas/global/alongstep/detail/TimeUpdater.hh
  src/celeritas/global/alongstep/detail/TrackUpdater.hh
  src/celeritas/global/alongstep/detail/UniformFieldTrackPropagator.hh
Labels: minor

#782 Simulate zero cross section for particles without processes
  app/celer-sim/RootOutput.cc
  src/celeritas/global/alongstep/detail/TrackUpdater.hh
  src/celeritas/io/ImportModel.hh
  src/celeritas/phys/detail/PreStepExecutor.hh
  test/CMakeLists.txt
  test/celeritas/global/Stepper.test.cc
  test/celeritas/user/Diagnostic.test.cc
Labels: enhancement, physics

#784 Use constrained safety distance for MSC step limit and scattering
  src/celeritas/em/msc/UrbanMsc.hh
  src/celeritas/em/msc/detail/UrbanMscScatter.hh
  src/celeritas/em/msc/detail/UrbanMscStepLimit.hh
  test/celeritas/em/UrbanMsc.test.cc
Labels: physics, minor

#795 Account for zero-processes only in pre-step action
  src/celeritas/global/alongstep/detail/TrackUpdater.hh
  src/celeritas/phys/PhysicsParams.cc
  src/celeritas/phys/PhysicsStepUtils.hh
  src/celeritas/phys/detail/PreStepExecutor.hh
  test/celeritas/MockTestBase.cc
  test/celeritas/phys/Physics.test.cc
  test/celeritas/phys/PhysicsStepUtils.test.cc
Labels: physics, minor

#796 Finalize launch simplification
  src/celeritas/em/generated/.clang-format
  src/celeritas/geo/detail/BoundaryAction.cc
  src/celeritas/geo/detail/BoundaryAction.cu
  src/celeritas/geo/detail/BoundaryAction.hh
  src/celeritas/geo/detail/BoundaryExecutor.hh
  src/celeritas/global/TrackExecutor.hh
  src/celeritas/phys/InteractionExecutor.hh
  src/celeritas/phys/detail/InteractionExecutorImpl.hh
  src/celeritas/track/detail/InitTracksExecutor.hh
  src/celeritas/track/detail/LocateAliveExecutor.hh
  src/celeritas/track/detail/ProcessPrimariesExecutor.hh
  src/celeritas/track/detail/ProcessSecondariesExecutor.hh
Labels: minor

#798 Only use ROOT in celer-g4 when Celeritas uses Geant4
  app/celer-g4/CMakeLists.txt
Labels: bug, core

#799 Fix celer-g4 ROOT PCM load error
  app/celer-g4/CMakeLists.txt
  app/celer-g4/celer-g4.cc
  src/celeritas/ext/ScopedRootErrorHandler.cc
Labels: bug, external

#803 Fix UrbanMsc safety edge case
  src/celeritas/em/msc/UrbanMsc.hh
Labels: bug, physics

#805 Create CUDA streams when integrating with Geant4
  app/celer-g4/GlobalSetup.cc
  src/accel/SetupOptions.hh
  src/accel/SharedParams.cc
Labels: minor

#806 Fix build on Summit
  src/celeritas/global/CoreParams.hh
  src/celeritas/global/CoreState.cc
  src/celeritas/global/CoreState.hh
  src/corecel/data/ParamsDataInterface.hh
  src/corecel/data/StreamStore.hh
  test/CMakeLists.txt
Labels: bug, core

#807 Fix along-step with uniform field on CPU when no MSC
  src/celeritas/global/alongstep/AlongStepUniformMscAction.cc
  src/celeritas/global/alongstep/AlongStepUniformMscAction.cu
  src/celeritas/global/alongstep/AlongStepUniformMscAction.hh
  test/CMakeLists.txt
  test/celeritas/global/AlongStep.test.cc
  test/celeritas/global/Stepper.test.cc
Labels: bug, core

#804 Improve logger interaction with Geant4
  src/celeritas/CMakeLists.txt
  src/celeritas/ext/GeantGeoParams.cc
  src/celeritas/ext/GeantGeoParams.hh
  src/celeritas/ext/GeantGeoUtils.cc
  src/celeritas/ext/GeantSetup.cc
  src/celeritas/ext/GeantSetup.hh
  src/celeritas/ext/ScopedGeantLogger.cc
  src/celeritas/ext/ScopedGeantLogger.hh
  src/celeritas/ext/detail/GeantLoggerAdapter.cc
  src/celeritas/ext/detail/GeantLoggerAdapter.hh
  src/corecel/io/Logger.cc
  src/corecel/io/ScopedStreamRedirect.cc
  src/corecel/io/ScopedStreamRedirect.hh
  src/corecel/io/ScopedTimeAndRedirect.cc
  src/corecel/io/ScopedTimeAndRedirect.hh
Labels: enhancement, external

#810 Fix G4 version check for `G4Step::Reset[Pre|Post]StepPoint`
  src/accel/detail/HitProcessor.cc
Labels: minor

#800 Add new vecgeom tests to emulate CMS run 3 issues
  src/accel/SharedParams.cc
  src/celeritas/ext/GeantGeoUtils.cc
  src/celeritas/ext/GeantGeoUtils.hh
  src/celeritas/ext/GeantImporter.cc
  src/celeritas/ext/GeantImporter.hh
  src/celeritas/ext/detail/GeantGeoConverter.cc
  src/celeritas/io/ImportData.hh
  src/celeritas/mat/MaterialParams.cc
  src/celeritas/phys/CutoffParams.cc
  src/celeritas/phys/ParticleParams.cc
  src/celeritas/track/SimParams.cc
  test/CMakeLists.txt
  test/accel/detail/HitProcessor.test.cc
  test/celeritas/GeantTestBase.cc
  test/celeritas/GenericGeoTestBase.cc
  test/celeritas/GenericGeoTestBase.hh
  test/celeritas/RootTestBase.cc
  test/celeritas/data/solids.gdml
  test/celeritas/ext/GeantGeo.test.cc
  test/celeritas/ext/GeantImporter.test.cc
  test/celeritas/ext/RootImporter.test.cc
  test/celeritas/ext/Vecgeom.test.cc
Labels: documentation, external

#811 Fix Bremsstrahlung process construction based on `Geant4PhysicsOptions`
  app/celer-sim/Runner.cc
  src/celeritas/em/process/BremsstrahlungProcess.cc
  src/celeritas/em/process/BremsstrahlungProcess.hh
  src/celeritas/phys/ProcessBuilder.cc
  src/celeritas/phys/ProcessBuilder.hh
Labels: bug, physics

#797 Fix some VecGeom CMS Run 3 issues
  src/accel/detail/HitManager.cc
  src/celeritas/ext/GeantGeoUtils.cc
  src/celeritas/ext/GeantGeoUtils.hh
  src/celeritas/ext/VecgeomParams.cc
  src/celeritas/ext/detail/GeantGeoConverter.cc
  src/celeritas/ext/detail/GeantGeoConverter.hh
  src/celeritas/ext/detail/GeantVolumeVisitor.cc
  src/celeritas/ext/detail/GeantVolumeVisitor.hh
  src/corecel/sys/Device.cc
  test/celeritas/ext/GeantImporter.test.cc
  test/celeritas/ext/Vecgeom.test.cc
Labels: bug, external

#815 Improve stream redirection behavior and logger destination
  src/corecel/io/ScopedStreamRedirect.cc
  src/corecel/io/ScopedStreamRedirect.hh
  src/corecel/io/ScopedTimeLog.hh
  src/corecel/sys/Device.cc
  src/corecel/sys/ScopedSignalHandler.hh
Labels: enhancement, core

#812 Rewrite VecGeom converter to fix mapping issues with reflecting volumes
  app/celer-g4/DetectorConstruction.cc
  doc/appendices/license.rst
  src/celeritas/CMakeLists.txt
  src/celeritas/ext/GeantGeoUtils.cc
  src/celeritas/ext/GeantVolumeMapper.cc
  src/celeritas/ext/GeantVolumeMapper.hh
  src/celeritas/ext/VecgeomParams.cc
  src/celeritas/ext/VecgeomParams.hh
  src/celeritas/ext/detail/GeantGeoConverter.cc
  src/celeritas/ext/detail/GeantGeoConverter.hh
  src/celeritas/ext/detail/GeantVolumeVisitor.cc
  src/celeritas/ext/detail/GenericPlacedVolume.hh
  src/celeritas/ext/detail/GenericSolid.hh
  src/celeritas/ext/g4vg/Converter.cc
  src/celeritas/ext/g4vg/Converter.hh
  src/celeritas/ext/g4vg/LogicalVolumeConverter.cc
  src/celeritas/ext/g4vg/LogicalVolumeConverter.hh
  src/celeritas/ext/g4vg/Scaler.hh
  src/celeritas/ext/g4vg/SolidConverter.cc
  src/celeritas/ext/g4vg/SolidConverter.hh
  src/celeritas/ext/g4vg/Transformer.hh
  test/celeritas/ext/Vecgeom.test.cc
Labels: bug, external

#813 Add G4ExtrudedSolid conversion
  src/celeritas/ext/g4vg/SolidConverter.cc
  src/celeritas/ext/g4vg/SolidConverter.hh
  test/celeritas/data/solids.gdml
  test/celeritas/ext/GeantGeo.test.cc
  test/celeritas/ext/GeantImporter.test.cc
  test/celeritas/ext/Vecgeom.test.cc
Labels: enhancement, external

#816 Extend user-facing app/environment options
  app/celer-dump-data.cc
  app/celer-export-geant.cc
  app/celer-g4/CMakeLists.txt
  app/celer-g4/GlobalSetup.cc
  app/celer-g4/celer-g4.cc
  app/celer-g4/simple-cms-test.mac.in
  app/celer-sim/Runner.cc
  app/celer-sim/RunnerInput.hh
  app/celer-sim/RunnerInputIO.json.cc
  app/celer-sim/celer-sim.cc
  doc/api/accel.rst
  src/accel/CMakeLists.txt
  src/accel/SetupOptions.hh
  src/accel/SetupOptionsMessenger.cc
  src/accel/SetupOptionsMessenger.hh
  src/celeritas/ext/GeantGeoUtils.hh
  src/celeritas/ext/RootImporter.hh
  src/celeritas/user/RootStepWriterIO.json.cc
  src/corecel/CMakeLists.txt
  src/corecel/io/ColorUtils.cc
  src/corecel/io/EnumStringMapper.hh
  src/corecel/io/detail/EnumStringMapperImpl.cc
  src/corecel/io/detail/EnumStringMapperImpl.hh
  test/corecel/io/EnumStringMapper.test.cc
Labels: enhancement, app

#817 Pre-release clang format
  src/accel/HepMC3PrimaryGenerator.cc
  src/accel/LocalTransporter.cc
  src/celeritas/em/msc/detail/UrbanPositronCorrector.hh
  src/celeritas/ext/detail/GeantPhysicsList.cc
  src/celeritas/ext/g4vg/SolidConverter.cc
  src/celeritas/global/CoreParams.hh
  src/celeritas/phys/CutoffView.hh
  src/celeritas/random/detail/CuHipRngStateInit.cu
  src/corecel/AssertIO.json.cc
  src/corecel/AssertIO.json.hh
  src/corecel/Macros.hh
  src/corecel/data/ParamsDataInterface.hh
  src/corecel/data/StreamStore.hh
  src/corecel/io/ExceptionOutput.cc
  src/orange/OrangeTypes.cc
  test/celeritas/ext/Vecgeom.test.cc
  test/celeritas/global/AlongStepTestBase.cc
  test/corecel/data/Collection.test.cu
Labels: minor

#772 Support manual addition/exclusion of volumes in HitManager
  CMakeLists.txt
  app/celer-g4/DetectorConstruction.cc
  src/accel/LocalTransporter.cc
  src/accel/LocalTransporter.hh
  src/accel/SetupOptions.hh
  src/accel/SharedParams.cc
  src/accel/detail/HitManager.cc
  src/accel/detail/HitManager.hh
  src/accel/detail/HitProcessor.cc
  src/accel/detail/HitProcessor.hh
  src/corecel/cont/InitializedValue.hh
  test/CMakeLists.txt
  test/accel/SDTestBase.cc
  test/accel/SDTestBase.hh
  test/accel/SimpleSensitiveDetector.cc
  test/accel/SimpleSensitiveDetector.hh
  test/accel/detail/HitManager.test.cc
  test/accel/detail/HitProcessor.test.cc
  test/celeritas/OneSteelSphereBase.hh
  test/celeritas/SimpleCmsTestBase.hh
  test/celeritas/TestEm15Base.hh
  test/celeritas/TestEm3Base.hh
Labels: enhancement, external

#818 Release v0.3.0
  .git-blame-ignore-revs
  CMakeLists.txt
  CMakePresets.json
  app/celer-g4/GlobalSetup.cc
  doc/CMakeLists.txt
  doc/api.rst
  doc/api/accel.rst
  doc/api/celeritas.rst
  doc/api/corecel.rst
  doc/appendices/administration.rst
  doc/appendices/release-history.rst
  doc/appendices/release-history/v0.3.rst
  doc/examples.rst
  doc/examples/geant4-full.rst
  doc/examples/geant4.rst
  doc/index.rst
  doc/installation.rst
  doc/introduction.rst
  doc/overview.rst
  doc/usage.rst
  scripts/cmake-presets/ci-centos-rocm.json
  scripts/cmake-presets/ci-ubuntu-cuda.json
  src/accel/SetupOptionsMessenger.hh
  src/accel/detail/HitManager.hh
  src/celeritas/em/model/RelativisticBremModel.cc
  src/celeritas/ext/GeantGeoParams.hh
  src/celeritas/ext/GeantPhysicsOptions.hh
  src/celeritas/ext/ScopedGeantLogger.cc
  src/corecel/sys/Device.cc
  src/corecel/sys/detail/StreamStorage.hh
Labels: documentation

#820 Add field template deduction and parameterized test
  app/demo-geo-check/GCheckKernel.cc
  app/demo-geo-check/GCheckKernel.cu
  src/celeritas/field/DormandPrinceStepper.hh
  src/celeritas/field/FieldDriver.hh
  src/celeritas/field/FieldPropagator.hh
  src/celeritas/field/LinearPropagator.hh
  src/celeritas/field/MagFieldEquation.hh
  src/celeritas/field/MakeMagFieldPropagator.hh
  src/celeritas/field/RungeKuttaStepper.hh
  src/celeritas/field/ZHelixStepper.hh
  src/celeritas/global/alongstep/AlongStepGeneralLinearAction.cc
  src/celeritas/global/alongstep/AlongStepNeutralAction.cc
  src/celeritas/global/alongstep/AlongStepNeutralAction.cu
  src/celeritas/global/alongstep/AlongStepRZMapFieldMscAction.cc
  src/celeritas/global/alongstep/AlongStepRZMapFieldMscAction.cu
  src/celeritas/global/alongstep/AlongStepUniformMscAction.cc
  src/celeritas/global/alongstep/AlongStepUniformMscAction.cu
  src/celeritas/global/alongstep/detail/AlongStepKernels.cu
  src/celeritas/global/alongstep/detail/LinearPropagatorFactory.hh
  src/celeritas/global/alongstep/detail/PropagationApplier.hh
  src/celeritas/global/alongstep/detail/RZMapFieldPropagatorFactory.hh
  src/celeritas/global/alongstep/detail/UniformFieldPropagatorFactory.hh
  test/CMakeLists.txt
  test/celeritas/AllGeoTypedTestBase.hh
  test/celeritas/GenericGeoTestBase.cc
  test/celeritas/GenericGeoTestBase.hh
  test/celeritas/ext/GeantGeo.test.cc
  test/celeritas/field/DiagnosticStepper.hh
  test/celeritas/field/FieldPropagator.test.cc
  test/celeritas/field/LinearPropagator.test.cc
Labels: field, minor

#819 Update CI to VecGeom 1.2.3
  .jenkins
  doc/installation.rst
  scripts/docker/build.sh
  scripts/spack.yaml
  test/CMakeLists.txt
  test/celeritas/ext/Vecgeom.test.cc
Labels: documentation, core

#824 Divide initializer capacity by number of streams in celer-sim
  app/celer-sim/Runner.cc
  app/celer-sim/RunnerInput.hh
Labels: bug, app

#765 Launch kernels only with active tracks using "action range"
  scripts/cmake-presets/esseivaj.json
  src/celeritas/Types.cc
  src/celeritas/Types.hh
  src/celeritas/em/model/BetheHeitlerModel.cu
  src/celeritas/em/model/CombinedBremModel.cu
  src/celeritas/em/model/EPlusGGModel.cu
  src/celeritas/em/model/KleinNishinaModel.cu
  src/celeritas/em/model/LivermorePEModel.cu
  src/celeritas/em/model/MollerBhabhaModel.cu
  src/celeritas/em/model/MuBremsstrahlungModel.cu
  src/celeritas/em/model/RayleighModel.cu
  src/celeritas/em/model/RelativisticBremModel.cu
  src/celeritas/em/model/SeltzerBergerModel.cu
  src/celeritas/geo/detail/BoundaryAction.cu
  src/celeritas/global/ActionLauncher.device.hh
  src/celeritas/global/CoreState.cc
  src/celeritas/global/CoreState.hh
  src/celeritas/global/alongstep/AlongStepNeutralAction.cu
  src/celeritas/global/alongstep/AlongStepRZMapFieldMscAction.cu
  src/celeritas/global/alongstep/AlongStepUniformMscAction.cu
  src/celeritas/global/alongstep/detail/AlongStepKernels.cu
  src/celeritas/track/SortTracksAction.cc
  src/celeritas/track/SortTracksAction.hh
  src/celeritas/track/detail/TrackSortUtils.cc
  src/celeritas/track/detail/TrackSortUtils.cu
  src/celeritas/track/detail/TrackSortUtils.hh
  src/corecel/sys/KernelParamCalculator.device.hh
  test/celeritas/track/TrackSort.test.cc
Labels: enhancement, core

#825 Add utility for constructing SD "force_volumes" option
  src/accel/CMakeLists.txt
  src/accel/SetupOptions.cc
  src/accel/SetupOptions.hh
  src/accel/SharedParams.cc
  src/accel/SharedParams.hh
  src/celeritas/ext/GeantGeoUtils.cc
  src/celeritas/ext/GeantGeoUtils.hh
  test/CMakeLists.txt
  test/celeritas/ext/GeantGeoUtils.test.cc
Labels: enhancement, external

#826 Improve logger construction and add test helper class
  src/accel/Logger.cc
  src/corecel/io/Logger.cc
  src/corecel/io/Logger.hh
  src/corecel/io/detail/LoggerMessage.hh
  src/corecel/sys/MpiCommunicator.cc
  src/corecel/sys/MpiCommunicator.hh
  test/CMakeLists.txt
  test/accel/SimpleSensitiveDetector.cc
  test/celeritas/ext/GeantVolumeMapper.test.cc
  test/corecel/ScopedLogStorer.cc
  test/corecel/ScopedLogStorer.hh
  test/corecel/io/Logger.test.cc
  test/corecel/sys/MultiExceptionHandler.test.cc
  test/testdetail/TestMainImpl.cc
Labels: internal, minor

#833 Hotfix: fix warning when building with Geant4@11
  src/celeritas/ext/g4vg/SolidConverter.cc
Labels: minor

#832 Remove variadic templating from track executor
  src/celeritas/global/TrackExecutor.hh
  src/celeritas/global/detail/TrackExecutorImpl.hh
Labels: core, minor

#827 Add scoped NVTX ranges for improved profiling
  app/celer-sim/celer-sim.cc
  src/corecel/CMakeLists.txt
  src/corecel/sys/ScopedDeviceProfiling.cuda.cc
  src/corecel/sys/ScopedDeviceProfiling.hh
  src/corecel/sys/ScopedProfiling.cuda.cc
  src/corecel/sys/ScopedProfiling.hh
Labels: enhancement, core

#835 Refactor hit manager SD mapping
  src/accel/CMakeLists.txt
  src/accel/detail/HitManager.cc
  src/accel/detail/HitManager.hh
  src/accel/detail/SensDetInserter.cc
  src/accel/detail/SensDetInserter.hh
  src/celeritas/ext/GeantGeoParams.cc
  src/corecel/io/Repr.hh
  test/CMakeLists.txt
  test/accel/detail/HitManager.test.cc
  test/corecel/ScopedLogStorer.cc
  test/corecel/ScopedLogStorer.hh
Labels: minor, external

#831 Add isotope data to `MaterialParams`
  app/celer-dump-data.cc
  src/celeritas/Types.hh
  src/celeritas/ext/GeantImporter.cc
  src/celeritas/ext/RootInterfaceLinkDef.h
  src/celeritas/io/ImportData.hh
  src/celeritas/io/ImportElement.hh
  src/celeritas/mat/ElementView.hh
  src/celeritas/mat/IsotopeView.hh
  src/celeritas/mat/MaterialData.hh
  src/celeritas/mat/MaterialParams.cc
  src/celeritas/mat/MaterialParams.hh
  src/celeritas/mat/MaterialParamsOutput.cc
  src/celeritas/phys/AtomicNumber.hh
  test/celeritas/MockTestBase.cc
  test/celeritas/SimpleTestBase.cc
  test/celeritas/em/CombinedBrem.test.cc
  test/celeritas/em/Fluctuation.test.cc
  test/celeritas/em/LivermorePE.test.cc
  test/celeritas/em/MollerBhabha.test.cc
  test/celeritas/em/Rayleigh.test.cc
  test/celeritas/em/RelativisticBrem.test.cc
  test/celeritas/em/SeltzerBerger.test.cc
  test/celeritas/ext/GeantImporter.test.cc
  test/celeritas/mat/ElementSelector.test.cc
  test/celeritas/mat/Material.test.cc
  test/celeritas/phys/CutoffParams.test.cc
  test/celeritas/phys/InteractorHostTestBase.cc
  test/celeritas/phys/Physics.test.cc
Labels: enhancement, physics

#837 Fix default `combined_brems` option to work with multiple-element materials
  app/celer-sim/RunnerInput.hh
Labels: bug, app

#838 Fix app/demo-geo-check test failure when using MPI
  app/demo-geo-check/CMakeLists.txt
Labels: bug

#836 Add `ScopedProfiling` to device actions
  src/celeritas/global/alongstep/AlongStepRZMapFieldMscAction.cu
  src/celeritas/global/alongstep/AlongStepUniformMscAction.cu
  src/celeritas/global/alongstep/detail/AlongStepKernels.cu
  src/celeritas/global/detail/ActionSequence.cc
Labels: enhancement

#834 Apply C++ core guidelines for copy/move assignment/construction
  doc/usage.rst
  src/accel/AlongStepFactory.hh
  src/celeritas/ext/GeantSetup.hh
  src/celeritas/ext/ScopedGeantExceptionHandler.hh
  src/celeritas/ext/ScopedGeantLogger.hh
  src/celeritas/ext/ScopedRootErrorHandler.hh
  src/celeritas/ext/detail/GeantBremsstrahlungProcess.cc
  src/celeritas/ext/detail/GeantBremsstrahlungProcess.hh
  src/celeritas/global/ActionInterface.hh
  src/celeritas/phys/Process.hh
  src/celeritas/user/StepCollector.cc
  src/celeritas/user/StepCollector.hh
  src/corecel/Macros.hh
  src/corecel/io/ScopedStreamFormat.hh
  src/corecel/io/ScopedStreamRedirect.hh
  src/corecel/io/ScopedTimeAndRedirect.hh
  src/corecel/io/ScopedTimeLog.hh
  src/corecel/io/detail/LoggerMessage.hh
  src/corecel/sys/ScopedMpiInit.hh
  src/corecel/sys/ScopedProfiling.cuda.cc
  src/corecel/sys/ScopedProfiling.hh
Labels: minor

#840 Add `screening_factor` to `ImportEmParameters`
  app/celer-dump-data.cc
  src/celeritas/ext/GeantImporter.cc
  src/celeritas/io/ImportParameters.hh
Labels: io, minor
