Repository celeritas-project/celeritas, pull requests merged in 2023-12, with the labels that each got.

#1040 Fix GeantSimpleCalo output when Celeritas is enabled
  app/celer-g4/ActionInitialization.cc
  app/celer-g4/DetectorConstruction.cc
  app/celer-g4/EventAction.cc
  app/celer-g4/ExceptionHandler.cc
  app/celer-g4/GeantDiagnostics.cc
  app/celer-g4/GlobalSetup.cc
  app/celer-g4/GlobalSetup.hh
  app/celer-g4/LocalLogger.cc
  app/celer-g4/RootIO.cc
  app/celer-g4/RootIO.hh
  app/celer-g4/RunAction.cc
  src/accel/GeantSimpleCalo.cc
  src/accel/SharedParams.cc
  src/accel/SharedParams.hh
Labels: bug, external

#1044 Support sorting tracks by particle types
  src/celeritas/Types.cc
  src/celeritas/Types.hh
  src/celeritas/track/SortTracksAction.cc
  src/celeritas/track/detail/TrackSortUtils.cu
  src/corecel/sys/KernelParamCalculator.device.hh
Labels: enhancement, core

#1043 Update cuda build instructions
  .github/pull_request_template.md
  README.md
  doc/main/installation.rst
  scripts/spack.yaml
Labels: core, minor

#1045 Improve JSON I/O for celer-g4/sim apps
  app/celer-g4/GlobalSetup.cc
  app/celer-g4/RunInputIO.json.cc
  app/celer-g4/celer-g4.cc
  app/celer-sim/RunnerInputIO.json.cc
  app/celer-sim/simple-driver.py
  src/accel/SharedParams.cc
  src/celeritas/ext/GeantPhysicsOptionsIO.json.cc
  src/celeritas/user/RootStepWriterIO.json.cc
  src/corecel/CMakeLists.txt
  src/corecel/io/JsonUtils.json.cc
  src/corecel/io/JsonUtils.json.hh
  src/corecel/sys/Version.cc
  src/corecel/sys/Version.hh
  src/orange/construct/OrangeInputIO.json.cc
Labels: enhancement, app

#1047 Refactor TrackSortUtils
  src/celeritas/track/detail/TrackSortUtils.cc
  src/celeritas/track/detail/TrackSortUtils.cu
  src/celeritas/track/detail/TrackSortUtils.hh
  src/corecel/sys/KernelParamCalculator.device.hh
Labels: core, minor

#1051 Uniquify ROOT file name when output is directed to stdout
  app/celer-g4/RootIO.cc
Labels: bug, app

#1049 Implement jump ahead for XORWOW RNG
  app/demo-interactor/KNDemoKernel.cu
  app/demo-interactor/KNDemoKernel.hh
  src/celeritas/CMakeLists.txt
  src/celeritas/global/CoreTrackView.hh
  src/celeritas/random/CuHipRngData.cc
  src/celeritas/random/CuHipRngData.hh
  src/celeritas/random/CuHipRngEngine.hh
  src/celeritas/random/CuHipRngParams.cc
  src/celeritas/random/CuHipRngParams.hh
  src/celeritas/random/XorwowRngData.hh
  src/celeritas/random/XorwowRngEngine.hh
  src/celeritas/random/XorwowRngParams.cc
  src/celeritas/random/XorwowRngParams.hh
  src/celeritas/random/detail/CuHipRngStateInit.cc
  src/celeritas/random/detail/CuHipRngStateInit.cu
  src/celeritas/random/detail/CuHipRngStateInit.hh
  test/celeritas/geo/HeuristicGeoExecutor.hh
  test/celeritas/random/RngEngine.test.cc
  test/celeritas/random/RngEngine.test.cu
  test/celeritas/random/RngEngine.test.hh
  test/celeritas/random/XorwowRngEngine.test.cc
Labels: enhancement, core

#1050 Implement offload to Celeritas from Geant4 using G4VTrackingManager hook
  doc/main/examples/geant4.rst
  example/accel/CMakeLists.txt
  example/accel/trackingmanager-offload.cc
  src/accel/CMakeLists.txt
  src/accel/TrackingManagerOffload.cc
  src/accel/TrackingManagerOffload.hh
Labels: enhancement, external

#1052 Update tests to pass with cuRAND
  test/celeritas/geo/HeuristicGeoTestBase.cc
  test/celeritas/global/AlongStep.test.cc
  test/celeritas/global/Stepper.test.cc
  test/celeritas/global/StepperTestBase.cc
  test/celeritas/global/StepperTestBase.hh
  test/celeritas/user/Diagnostic.test.cc
  test/celeritas/user/StepCollector.test.cc
Labels: documentation, minor

#1055 Release v0.4.1
  doc/appendix/release-history/v0.4.rst
  src/corecel/io/JsonUtils.json.cc
  src/corecel/io/JsonUtils.json.hh
Labels: documentation

#1053 Include documentation as mandatory CI
  .github/workflows/doc.yml
  .github/workflows/pr.yml
  cmake/CeleritasUtils.cmake
  doc/CMakeLists.txt
  doc/main/examples/geant4.rst
  src/CMakeLists.txt
  src/orange/surf/LocalSurfaceVisitor.hh
  src/orange/transform/TransformVisitor.hh
  src/orange/univ/TrackerVisitor.hh
Labels: documentation, minor

#1056 Warn and set default threads when OpenMP and Geant4 MT might collide
  src/accel/CMakeLists.txt
  src/accel/LocalTransporter.cc
Labels: enhancement, external

#1057 Fix celer-g4 primary generator MT reproducibility
  app/celer-g4/PGPrimaryGeneratorAction.cc
  app/celer-g4/PGPrimaryGeneratorAction.hh
  src/celeritas/phys/PrimaryGenerator.cc
  src/celeritas/phys/PrimaryGenerator.hh
  test/celeritas/phys/PrimaryGenerator.test.cc
Labels: bug, app

#1062 Remove extra constructor templates in device ActionLauncher
  src/celeritas/global/ActionLauncher.device.hh
Labels: core, minor

#1059 Insert SortTrackAction when sorting by particle type
  src/celeritas/global/CoreParams.cc
  src/celeritas/global/CoreState.cc
  src/celeritas/global/CoreState.hh
  src/celeritas/global/detail/CoreStateThreadOffsets.hh
  test/celeritas/track/TrackSort.test.cc
Labels: bug, performance

#1060 Add environment variable to kill Celeritas-supported tracks in Geant4
  app/celer-g4/TrackingAction.cc
  app/celer-g4/celer-g4.cc
  doc/main/usage.rst
  src/accel/SharedParams.cc
  src/accel/SharedParams.hh
  src/accel/SimpleOffload.cc
Labels: enhancement, app

#1064 Fix range constexpr
  src/corecel/cont/detail/RangeImpl.hh
  src/orange/BoundingBoxUtils.hh
  test/corecel/cont/Range.test.cc
Labels: bug, core

#1061 Ensure reproducibility when using MT Geant4 with Celeritas offloading
  app/celer-g4/EventAction.cc
  app/celer-g4/GeantDiagnostics.cc
  src/accel/LocalTransporter.cc
  src/accel/LocalTransporter.hh
  src/accel/SimpleOffload.cc
  src/celeritas/CMakeLists.txt
  src/celeritas/global/Stepper.cc
  src/celeritas/global/Stepper.hh
  src/celeritas/random/RngReseed.cc
  src/celeritas/random/RngReseed.cu
  src/celeritas/random/RngReseed.hh
  src/celeritas/random/XorwowRngData.hh
  src/celeritas/random/XorwowRngEngine.hh
  test/CMakeLists.txt
  test/celeritas/random/RngReseed.test.cc
  test/celeritas/random/XorwowRngEngine.test.cc
Labels: bug, external

#1066 Add additional documentation about fields
  .github/workflows/doc.yml
  doc/main/api/accel.rst
  doc/main/api/celeritas.rst
  doc/main/usage.rst
  src/celeritas/field/DormandPrinceStepper.hh
  src/celeritas/field/RZMapFieldInput.hh
  src/celeritas/field/RungeKuttaStepper.hh
  src/celeritas/field/UniformFieldData.hh
Labels: documentation

#1069 Fix conversion of boolean solids when the "left" solid is displaced
  src/celeritas/ext/g4vg/SolidConverter.cc
Labels: bug, external

#1071 Support Geant4-VecGeom conversion of parameterized volumes
  src/celeritas/ext/GeantGeoUtils.cc
  src/celeritas/ext/g4vg/Converter.cc
  test/CMakeLists.txt
  test/celeritas/data/znenv.gdml
  test/celeritas/ext/GeantGeo.test.cc
  test/celeritas/ext/Vecgeom.test.cc
Labels: enhancement, external

#1065 Save action times on multi-stream CPU celer-sim
  app/celer-sim/CMakeLists.txt
  app/celer-sim/Runner.cc
  app/celer-sim/Runner.hh
  app/celer-sim/RunnerInput.hh
  app/celer-sim/RunnerInputIO.json.cc
  app/celer-sim/RunnerOutput.hh
  app/celer-sim/Transporter.cc
  app/celer-sim/Transporter.hh
  app/celer-sim/celer-sim.cc
  scripts/cmake-presets/goldfinger.json
  src/celeritas/global/detail/ActionSequence.hh
  src/corecel/sys/Device.cc
Labels: enhancement, app

#1072 Automatically calculate number of events in apps
  app/celer-g4/ActionInitialization.cc
  app/celer-g4/ActionInitialization.hh
  app/celer-g4/GlobalSetup.cc
  app/celer-g4/GlobalSetup.hh
  app/celer-g4/RunInput.cc
  app/celer-g4/RunInput.hh
  app/celer-g4/RunInputIO.json.cc
  app/celer-g4/test-harness.py
  app/celer-sim/Runner.cc
  app/celer-sim/Runner.hh
  app/celer-sim/RunnerInput.hh
  app/celer-sim/RunnerInputIO.json.cc
  app/celer-sim/simple-driver.py
  src/accel/HepMC3PrimaryGenerator.cc
  src/celeritas/io/EventIOInterface.hh
  src/celeritas/io/EventReader.cc
  src/celeritas/io/EventReader.hh
  src/celeritas/io/RootEventReader.cc
  src/celeritas/io/RootEventReader.hh
  src/celeritas/phys/PrimaryGenerator.hh
  test/celeritas/io/EventIO.test.cc
  test/celeritas/io/RootEventIO.test.cc
  test/celeritas/phys/PrimaryGenerator.test.cc
Labels: enhancement, app

#1073 Use environment variables to control OpenMP behavior in `celer-sim`
  app/celer-sim/Runner.cc
  app/celer-sim/celer-sim.cc
Labels: bug, app

#1075 Add support for Geant4@11.2
  cmake/CeleritasUtils.cmake
  src/CMakeLists.txt
  src/accel/detail/TouchableUpdater.hh
  src/celeritas/ext/GeantGeoUtils.cc
  src/celeritas/ext/GeantGeoUtils.hh
  src/celeritas/ext/detail/GeantBremsstrahlungProcess.cc
  src/celeritas/ext/detail/GeantGeoNavCollection.cc
  src/celeritas/ext/detail/GeantGeoNavCollection.hh
  src/celeritas_sys_config.h.in
  test/celeritas/global/AlongStep.test.cc
Labels: bug, external
