Repository celeritas-project/celeritas, pull requests merged in 2024-07, with the labels that each got.

#1301 Add helper functions for sampling/calculating direction in interactors
  src/celeritas/em/interactor/BetheHeitlerInteractor.hh
  src/celeritas/em/interactor/CoulombScatteringInteractor.hh
  src/celeritas/em/interactor/EPlusGGInteractor.hh
  src/celeritas/em/interactor/KleinNishinaInteractor.hh
  src/celeritas/em/interactor/LivermorePEInteractor.hh
  src/celeritas/em/interactor/MollerBhabhaInteractor.hh
  src/celeritas/em/interactor/MuBetheBlochInteractor.hh
  src/celeritas/em/interactor/MuBremsstrahlungInteractor.hh
  src/celeritas/em/interactor/RayleighInteractor.hh
  src/celeritas/em/interactor/detail/BremFinalStateHelper.hh
  src/celeritas/phys/InteractionUtils.hh
  test/celeritas/CMakeLists.txt
  test/celeritas/phys/InteractionUtils.test.cc
Labels: physics, minor

#1294 Add new track status and support user "initialization"
  src/celeritas/Types.cc
  src/celeritas/Types.hh
  src/celeritas/em/model/MuBetheBlochModel.cc
  src/celeritas/global/KernelContextException.cc
  src/celeritas/global/alongstep/detail/MscApplier.hh
  src/celeritas/global/alongstep/detail/TrackUpdater.hh
  src/celeritas/optical/detail/CerenkovPreGenAction.hh
  src/celeritas/optical/detail/OpticalGenParams.hh
  src/celeritas/optical/detail/PreGenGatherAction.hh
  src/celeritas/optical/detail/ScintPreGenAction.hh
  src/celeritas/optical/detail/ScintPreGenExecutor.hh
  src/celeritas/phys/detail/PreStepExecutor.hh
  src/celeritas/track/SimData.hh
  src/celeritas/track/SimTrackView.hh
  src/celeritas/track/detail/ProcessPrimariesExecutor.hh
  src/celeritas/track/detail/ProcessSecondariesExecutor.hh
  src/celeritas/track/detail/TrackSortUtils.cc
  src/celeritas/track/detail/TrackSortUtils.cu
  src/celeritas/track/detail/TrackSortUtils.hh
  src/celeritas/user/StepDiagnostic.hh
  src/celeritas/user/detail/StepGatherAction.hh
  src/corecel/data/AuxStateData.hh
  test/celeritas/CMakeLists.txt
  test/celeritas/global/DummyAction.cc
  test/celeritas/global/DummyAction.hh
  test/celeritas/global/Stepper.test.cc
  test/celeritas/global/StepperGeant.test.cc
  test/celeritas/global/StepperTestBase.cc
  test/celeritas/global/StepperTestBase.hh
  test/celeritas/optical/OpticalTestBase.cc
  test/celeritas/track/TrackSort.test.cc
Labels: enhancement, physics

#1305 Hotfix: work around ROCm failures due to Node20 incompatibility
  .github/workflows/build-docker.yml
Labels: documentation

#1303 Add detailed error checking for action sequence behavior
  src/celeritas/CMakeLists.txt
  src/celeritas/Types.hh
  src/celeritas/global/ActionInterface.hh
  src/celeritas/global/ActionLauncher.device.hh
  src/celeritas/global/ActionLauncher.hh
  src/celeritas/global/CoreTrackView.hh
  src/celeritas/global/detail/ActionSequence.cc
  src/celeritas/global/detail/ActionSequence.hh
  src/celeritas/track/ExtendFromPrimariesAction.cc
  src/celeritas/track/ExtendFromSecondariesAction.cc
  src/celeritas/track/InitializeTracksAction.cc
  src/celeritas/track/SimTrackView.hh
  src/celeritas/track/StatusCheckData.hh
  src/celeritas/track/StatusChecker.cc
  src/celeritas/track/StatusChecker.cu
  src/celeritas/track/StatusChecker.hh
  src/celeritas/track/detail/StatusCheckExecutor.hh
  src/corecel/Assert.cc
  src/corecel/sys/MultiExceptionHandler.cc
  src/corecel/sys/MultiExceptionHandler.hh
  test/celeritas/CMakeLists.txt
  test/celeritas/GlobalTestBase.cc
  test/celeritas/GlobalTestBase.hh
  test/celeritas/track/StatusChecker.test.cc
Labels: enhancement, core

#1307 Fix device test failures
  test/celeritas/track/StatusChecker.test.cc
  test/celeritas/track/TrackSort.test.cc
  test/celeritas/user/Diagnostic.test.cc
Labels: documentation, minor

#1306 Add final state helper for ionization interactions
  src/celeritas/em/distribution/BhabhaEnergyDistribution.hh
  src/celeritas/em/distribution/MollerEnergyDistribution.hh
  src/celeritas/em/distribution/MuBBEnergyDistribution.hh
  src/celeritas/em/interactor/MollerBhabhaInteractor.hh
  src/celeritas/em/interactor/MuBetheBlochInteractor.hh
  src/celeritas/em/interactor/detail/BremFinalStateHelper.hh
  src/celeritas/em/interactor/detail/IoniFinalStateHelper.hh
Labels: physics, minor

#1304 Add debug output for track states
  src/celeritas/CMakeLists.txt
  src/celeritas/Types.cc
  src/celeritas/Types.hh
  src/celeritas/global/Debug.cc
  src/celeritas/global/Debug.hh
  src/celeritas/global/DebugIO.json.cc
  src/celeritas/global/DebugIO.json.hh
  src/celeritas/global/detail/ActionSequence.cc
Labels: enhancement, core

#1310 Add a helper function to copy a "collection group" back to the host
  src/corecel/data/Collection.hh
  src/corecel/data/CollectionAlgorithms.hh
  src/corecel/data/DeviceAllocation.cc
  src/corecel/data/DeviceAllocation.hh
  src/corecel/data/DeviceVector.hh
  src/corecel/data/Ref.hh
  src/corecel/data/detail/CollectionImpl.hh
  src/corecel/data/detail/DisabledStorage.hh
  test/celeritas/geo/HeuristicGeoTestBase.cc
  test/corecel/data/Collection.test.cc
  test/corecel/data/DeviceVector.test.cc
Labels: core, minor

#1315 Skip indirection array for sorted track slots
  src/celeritas/geo/detail/BoundaryExecutor.hh
  src/celeritas/global/CoreTrackData.cc
  src/celeritas/global/CoreTrackData.hh
  src/celeritas/global/CoreTrackView.hh
  src/celeritas/global/TrackExecutor.hh
  src/celeritas/global/alongstep/AlongStep.hh
  src/celeritas/global/alongstep/AlongStepGeneralLinearAction.cc
  src/celeritas/global/alongstep/AlongStepRZMapFieldMscAction.cc
  src/celeritas/global/alongstep/AlongStepUniformMscAction.cc
  src/celeritas/global/alongstep/detail/PropagationApplier.hh
  src/celeritas/phys/detail/TrackingCutExecutor.hh
  src/celeritas/track/SortTracksAction.cc
  src/celeritas/track/detail/InitTracksExecutor.hh
  test/celeritas/global/KernelContextException.test.cc
  test/celeritas/user/Diagnostic.test.cc
Labels: minor, performance

#1309 Add Bragg and ICRU73QO ionization models
  doc/main/api/celeritas.rst
  doc/main/overview.rst
  src/celeritas/CMakeLists.txt
  src/celeritas/Constants.hh
  src/celeritas/em/data/BraggICRU73QOData.hh
  src/celeritas/em/executor/BraggICRU73QOExecutor.hh
  src/celeritas/em/interactor/BraggICRU73QOInteractor.hh
  src/celeritas/em/interactor/detail/PhysicsConstants.hh
  src/celeritas/em/model/BraggModel.cc
  src/celeritas/em/model/BraggModel.cu
  src/celeritas/em/model/BraggModel.hh
  src/celeritas/em/model/ICRU73QOModel.cc
  src/celeritas/em/model/ICRU73QOModel.cu
  src/celeritas/em/model/ICRU73QOModel.hh
  test/celeritas/CMakeLists.txt
  test/celeritas/em/BraggICRU73QO.test.cc
Labels: enhancement, physics

#1318 Add environment variable to disable broken HIP asynchronous allocation
  .github/workflows/build-fast.yml
  .github/workflows/build-spack.yml
  doc/main/api/corecel.rst
  doc/main/usage.rst
  src/corecel/sys/DeviceIO.json.cc
  src/corecel/sys/Environment.cc
  src/corecel/sys/Environment.hh
  src/corecel/sys/Stream.cc
  src/corecel/sys/Stream.hh
  test/celeritas/track/StatusChecker.test.cc
  test/corecel/sys/Environment.test.cc
Labels: bug, core

#1319 Fix muon bremsstrahlung energy limits and sampling
  src/celeritas/em/data/MuBremsstrahlungData.hh
  src/celeritas/em/executor/MuBremsstrahlungExecutor.hh
  src/celeritas/em/interactor/BraggICRU73QOInteractor.hh
  src/celeritas/em/interactor/CombinedBremInteractor.hh
  src/celeritas/em/interactor/MuBremsstrahlungInteractor.hh
  src/celeritas/em/interactor/RelativisticBremInteractor.hh
  src/celeritas/em/interactor/SeltzerBergerInteractor.hh
  src/celeritas/em/interactor/detail/BremFinalStateHelper.hh
  src/celeritas/em/interactor/detail/PhysicsConstants.hh
  src/celeritas/em/model/MuBremsstrahlungModel.cc
  test/celeritas/em/MuBremsstrahlung.test.cc
Labels: bug, physics

#1316 Detect and gracefully handle ORANGE geometry errors during tracking
  src/celeritas/geo/detail/BoundaryExecutor.hh
  src/celeritas/track/detail/InitTracksExecutor.hh
  src/geocel/g4/GeantGeoTrackView.hh
  src/geocel/vg/VecgeomTrackView.hh
  src/orange/OrangeTrackView.hh
  src/orange/univ/SimpleUnitTracker.hh
  src/orange/univ/detail/Types.hh
  test/celeritas/global/Stepper.test.cc
Labels: enhancement, orange

#1320 Refactor muon bremsstrahlung differential cross section calculation and add documentation
  src/celeritas/em/interactor/MuBremsstrahlungInteractor.hh
  src/celeritas/em/xs/MuBremsDiffXsCalculator.hh
  test/celeritas/em/MuBremsstrahlung.test.cc
Labels: documentation, physics

#1321 Add release notes
  doc/appendix/release-history/v0.4.rst
Labels: documentation

#1324 Add Regula Falsi root solver
  src/corecel/math/Algorithms.hh
  src/corecel/math/RegulaFalsiRootFinder.hh
  test/corecel/CMakeLists.txt
  test/corecel/math/Algorithms.test.cc
  test/corecel/math/RegulaFalsiRootFinder.test.cc
Labels: enhancement, core

#1328 Remove celeritas include in corecel
  src/celeritas/Types.cc
  src/celeritas/Types.hh
  src/corecel/Types.cc
  src/corecel/Types.hh
  src/corecel/grid/Interpolator.hh
  src/corecel/sys/Stream.cc
Labels: core, minor

#1327 Refactor types to reduce duplication and cyclic dependencies
  src/celeritas/grid/GridIdFinder.hh
  src/corecel/OpaqueId.hh
  src/corecel/cont/Span.hh
  src/corecel/cont/detail/SpanImpl.hh
  src/corecel/data/LdgIterator.hh
  src/corecel/data/detail/CollectionImpl.hh
  src/corecel/data/detail/LdgIteratorImpl.hh
  src/corecel/data/detail/TypeTraits.hh
  src/corecel/math/Quantity.hh
  src/geocel/GeoParamsInterface.hh
  src/geocel/Types.hh
  src/geocel/rasterize/ImageData.hh
  src/orange/g4org/SolidConverter.cc
  src/orange/orangeinp/IntersectRegion.hh
  src/orange/orangeinp/PolySolid.cc
  src/orange/orangeinp/PolySolid.hh
  src/orange/orangeinp/detail/PolygonUtils.hh
  src/orange/univ/detail/InfixEvaluator.hh
  src/orange/univ/detail/LogicEvaluator.hh
  src/orange/univ/detail/RaggedRightIndexer.hh
  test/corecel/data/LdgIterator.test.cc
  test/geocel/rasterize/Image.test.cc
  test/orange/orangeinp/IntersectRegion.test.cc
  test/orange/orangeinp/PolySolid.test.cc
Labels: core, minor

#1326 Add cascade collider
  src/celeritas/CMakeLists.txt
  src/celeritas/grid/TwodGridBuilder.cc
  src/celeritas/grid/TwodGridBuilder.hh
  src/celeritas/neutron/data/NeutronInelasticData.hh
  src/celeritas/neutron/interactor/detail/CascadeCollider.hh
  src/celeritas/neutron/interactor/detail/CascadeParticle.hh
  src/celeritas/neutron/model/NeutronInelasticModel.cc
  src/celeritas/neutron/model/NeutronInelasticModel.hh
  src/celeritas/phys/FourVector.hh
  test/celeritas/CMakeLists.txt
  test/celeritas/neutron/NeutronInelastic.test.cc
  test/celeritas/phys/FourVector.test.cc
Labels: enhancement, physics

#1329 Add git pre-commit hook
  scripts/dev/install-commit-hooks.sh
  scripts/dev/pre-commit.validate-source
Labels: core, minor

#1330 Update frontier toolchain and backward compatibility
  app/celer-g4/RunInputIO.json.cc
  scripts/cmake-presets/frontier.json
  scripts/env/frontier.sh
  src/corecel/math/Algorithms.hh
Labels: core, minor

#1271 Support degenerate faces for "GenTrap" and rename to GenPrism
  src/orange/g4org/SolidConverter.cc
  src/orange/orangeinp/IntersectRegion.cc
  src/orange/orangeinp/IntersectRegion.hh
  src/orange/orangeinp/ObjectIO.json.cc
  src/orange/orangeinp/ObjectIO.json.hh
  src/orange/orangeinp/Shape.cc
  src/orange/orangeinp/Shape.hh
  src/orange/orangeinp/detail/PolygonUtils.hh
  test/orange/g4org/SolidConverter.test.cc
  test/orange/orangeinp/IntersectRegion.test.cc
  test/orange/orangeinp/UnitProto.test.cc
  test/orange/orangeinp/detail/PolygonUtils.test.cc
Labels: enhancement, orange

#1335 Add CUDA build instructions
  README.md
Labels: documentation, minor

#1323 Fix downstream CMake when using CUDA and not included at top level
  cmake/CeleritasConfig.cmake.in
  example/accel/CMakeLists.txt
  example/minimal/CMakeLists.txt
Labels: bug, documentation

#1338 Reduce string duplication from assertion messages
  src/corecel/Assert.cc
  src/corecel/Assert.hh
  test/celeritas/GeantTestBase.cc
Labels: core, minor

#1331 Add unit test function wrapper for diagnosing solver convergence
  test/corecel/math/BisectionRootFinder.test.cc
  test/corecel/math/DiagnosticRealFunc.hh
  test/corecel/math/IllinoisRootFinder.test.cc
  test/corecel/math/Integrator.test.cc
  test/corecel/math/RegulaFalsiRootFinder.test.cc
Labels: documentation, core

#1340 Fix HepMC3 tests to work with 3.3.0
  scripts/cmake-presets/goldfinger.json
  test/accel/HepMC3PrimaryGenerator.test.cc
  test/celeritas/data/event-novtx.hepmc3
  test/celeritas/io/EventIO.test.cc
Labels: documentation, external

#1336 Add color and PNG for future direct raytracing/rasterization
  CMakeLists.txt
  CMakePresets.json
  cmake/CeleritasConfig.cmake.in
  doc/main/installation.rst
  scripts/ci/spack.yaml
  scripts/cmake-presets/ci-centos-rocm.json
  scripts/cmake-presets/ci-ubuntu-cuda.json
  scripts/cmake-presets/ci-ubuntu-github.json
  scripts/cmake-presets/ci-windows-github.json
  scripts/spack.yaml
  src/corecel/Config.hh.in
  src/geocel/CMakeLists.txt
  src/geocel/rasterize/Color.cc
  src/geocel/rasterize/Color.hh
  src/geocel/rasterize/ImageWriter.hh
  src/geocel/rasterize/ImageWriter.libpng.cc
  test/corecel/data/DeviceAllocation.test.cc
  test/corecel/data/DeviceVector.test.cc
  test/geocel/CMakeLists.txt
  test/geocel/rasterize/Color.test.cc
  test/geocel/rasterize/ImageWriter.test.cc
Labels: enhancement, core

#1337 Fix GenPrism surface shapes to match Geant4
  src/orange/orangeinp/IntersectRegion.cc
  src/orange/orangeinp/IntersectRegion.hh
  test/orange/g4org/SolidConverter.test.cc
  test/orange/orangeinp/IntersectRegion.test.cc
Labels: enhancement, orange

#1341 Use spack-based workflow for address sanitizer
  .github/workflows/build-docker.yml
  .github/workflows/build-spack.yml
  scripts/cmake-presets/ci-centos-rocm.json
  scripts/cmake-presets/ci-ubuntu-github.json
Labels: documentation

#1295 Add involute surface to support HFIR simulation
  src/corecel/math/BisectionRootFinder.hh
  src/corecel/math/IllinoisRootFinder.hh
  src/corecel/math/RegulaFalsiRootFinder.hh
  src/orange/CMakeLists.txt
  src/orange/surf/Involute.cc
  src/orange/surf/Involute.hh
  src/orange/surf/SurfaceFwd.hh
  src/orange/surf/SurfaceIO.cc
  src/orange/surf/SurfaceIO.hh
  src/orange/surf/detail/InvolutePoint.hh
  src/orange/surf/detail/InvoluteSolver.hh
  test/orange/CMakeLists.txt
  test/orange/surf/Involute.test.cc
  test/orange/surf/detail/InvolutePoint.test.cc
  test/orange/surf/detail/InvoluteSolver.test.cc
Labels: enhancement, orange

#1314 Add optical sub-namespace
  src/celeritas/CMakeLists.txt
  src/celeritas/global/ActionInterface.hh
  src/celeritas/optical/CerenkovData.hh
  src/celeritas/optical/CerenkovDndxCalculator.hh
  src/celeritas/optical/CerenkovGenerator.hh
  src/celeritas/optical/CerenkovOffload.hh
  src/celeritas/optical/CerenkovParams.cc
  src/celeritas/optical/CerenkovParams.hh
  src/celeritas/optical/GeneratorDistributionData.hh
  src/celeritas/optical/MaterialPropertyData.hh
  src/celeritas/optical/MaterialPropertyParams.cc
  src/celeritas/optical/MaterialPropertyParams.hh
  src/celeritas/optical/OffloadData.hh
  src/celeritas/optical/OpticalCollector.cc
  src/celeritas/optical/OpticalCollector.hh
  src/celeritas/optical/Primary.hh
  src/celeritas/optical/ScintillationData.hh
  src/celeritas/optical/ScintillationGenerator.hh
  src/celeritas/optical/ScintillationOffload.hh
  src/celeritas/optical/ScintillationParams.cc
  src/celeritas/optical/ScintillationParams.hh
  src/celeritas/optical/TrackData.cc
  src/celeritas/optical/TrackData.hh
  src/celeritas/optical/detail/CerenkovOffloadAction.cc
  src/celeritas/optical/detail/CerenkovOffloadAction.cu
  src/celeritas/optical/detail/CerenkovOffloadAction.hh
  src/celeritas/optical/detail/CerenkovOffloadExecutor.hh
  src/celeritas/optical/detail/OffloadGatherAction.cc
  src/celeritas/optical/detail/OffloadGatherAction.cu
  src/celeritas/optical/detail/OffloadGatherAction.hh
  src/celeritas/optical/detail/OffloadGatherExecutor.hh
  src/celeritas/optical/detail/OffloadParams.cc
  src/celeritas/optical/detail/OffloadParams.hh
  src/celeritas/optical/detail/OpticalGenAlgorithms.cc
  src/celeritas/optical/detail/OpticalGenAlgorithms.cu
  src/celeritas/optical/detail/OpticalGenAlgorithms.hh
  src/celeritas/optical/detail/ScintOffloadAction.cc
  src/celeritas/optical/detail/ScintOffloadAction.cu
  src/celeritas/optical/detail/ScintOffloadAction.hh
  src/celeritas/optical/detail/ScintOffloadExecutor.hh
  test/celeritas/GlobalTestBase.hh
  test/celeritas/ImportedDataTestBase.cc
  test/celeritas/optical/Cerenkov.test.cc
  test/celeritas/optical/OpticalCollector.test.cc
  test/celeritas/optical/OpticalTestBase.hh
  test/celeritas/optical/Scintillation.test.cc
Labels: physics, minor

#1343 Fix minor compile error/warning with nvcc+clang
  src/celeritas/field/FieldPropagator.hh
  src/celeritas/global/ActionLauncher.device.hh
  src/corecel/Macros.hh
  test/celeritas/random/curand/CurandPerformance.test.cu
Labels: bug, minor
