Repository celeritas-project/celeritas, pull requests merged in 2024-12, with the labels that each got.

#1516 Stop CMake from cleaning root test data
  test/celeritas/CMakeLists.txt
Labels: core, minor

#1527 Trim export data for unit tests
  app/celer-export-geant.cc
  doc/development/style.rst
  src/celeritas/CMakeLists.txt
  src/celeritas/ext/RootInterfaceLinkDef.h
  src/celeritas/io/ImportData.cc
  src/celeritas/io/ImportData.hh
  src/celeritas/io/ImportDataTrimmer.cc
  src/celeritas/io/ImportDataTrimmer.hh
  src/celeritas/io/ImportOpticalMaterial.hh
  src/celeritas/io/ImportSBTable.hh
  test/celeritas/ext/RootJsonDumper.test.cc
Labels: documentation, physics

#1533 Rename Cerenkov to Cherenkov
  app/celer-sim/Runner.cc
  doc/implementation/optical-physics.rst
  src/celeritas/CMakeLists.txt
  src/celeritas/ext/GeantOpticalPhysicsOptions.hh
  src/celeritas/ext/GeantOpticalPhysicsOptionsIO.json.cc
  src/celeritas/ext/detail/CelerOpticalPhysics.cc
  src/celeritas/io/ImportOpticalMaterial.hh
  src/celeritas/optical/CherenkovData.hh
  src/celeritas/optical/CherenkovDndxCalculator.hh
  src/celeritas/optical/CherenkovGenerator.hh
  src/celeritas/optical/CherenkovOffload.hh
  src/celeritas/optical/CherenkovParams.cc
  src/celeritas/optical/CherenkovParams.hh
  src/celeritas/optical/OffloadData.hh
  src/celeritas/optical/OpticalCollector.cc
  src/celeritas/optical/OpticalCollector.hh
  src/celeritas/optical/detail/CherenkovGeneratorAction.cc
  src/celeritas/optical/detail/CherenkovGeneratorAction.cu
  src/celeritas/optical/detail/CherenkovGeneratorAction.hh
  src/celeritas/optical/detail/CherenkovGeneratorExecutor.hh
  src/celeritas/optical/detail/CherenkovOffloadAction.cc
  src/celeritas/optical/detail/CherenkovOffloadAction.cu
  src/celeritas/optical/detail/CherenkovOffloadAction.hh
  src/celeritas/optical/detail/CherenkovOffloadExecutor.hh
  test/celeritas/CMakeLists.txt
  test/celeritas/GlobalTestBase.hh
  test/celeritas/ImportedDataTestBase.cc
  test/celeritas/ImportedDataTestBase.hh
  test/celeritas/OnlyCoreTestBase.hh
  test/celeritas/data/lar-sphere.geant.json
  test/celeritas/optical/Cherenkov.test.cc
  test/celeritas/optical/OpticalCollector.test.cc
  test/celeritas/optical/OpticalTestBase.cc
Labels: physics, minor

#1518 Add muon pair production
  app/celer-export-geant.cc
  doc/implementation/em-physics.rst
  src/celeritas/CMakeLists.txt
  src/celeritas/em/data/MuPairProductionData.hh
  src/celeritas/em/distribution/MuAngularDistribution.hh
  src/celeritas/em/distribution/MuPPEnergyDistribution.hh
  src/celeritas/em/executor/MuPairProductionExecutor.hh
  src/celeritas/em/interactor/MuBremsstrahlungInteractor.hh
  src/celeritas/em/interactor/MuPairProductionInteractor.hh
  src/celeritas/em/model/MuPairProductionModel.cc
  src/celeritas/em/model/MuPairProductionModel.cu
  src/celeritas/em/model/MuPairProductionModel.hh
  src/celeritas/em/process/MuPairProductionProcess.cc
  src/celeritas/em/process/MuPairProductionProcess.hh
  src/celeritas/ext/detail/GeantProcessImporter.cc
  src/celeritas/grid/InverseCdfFinder.hh
  src/celeritas/io/ImportDataTrimmer.cc
  src/celeritas/io/ImportMuPairProductionTable.hh
  src/celeritas/phys/ProcessBuilder.cc
  src/celeritas/phys/ProcessBuilder.hh
  src/corecel/data/HyperslabIndexer.hh
  test/celeritas/CMakeLists.txt
  test/celeritas/data/four-steel-slabs.geant.json
  test/celeritas/data/four-steel-slabs.root
  test/celeritas/data/lar-sphere.root
  test/celeritas/data/simple-cms.root
  test/celeritas/em/MuPairProduction.test.cc
  test/celeritas/em/distribution/MuAngularDistribution.test.cc
  test/celeritas/ext/GeantImporter.test.cc
  test/celeritas/ext/RootImporter.test.cc
  test/celeritas/ext/RootJsonDumper.test.cc
  test/celeritas/phys/InteractorHostTestBase.cc
  test/celeritas/phys/InteractorHostTestBase.hh
  test/corecel/data/HyperslabIndexer.test.cc
Labels: enhancement, physics

#1532 Update Readme and Contributing doc
  CITATION.cff
  CONTRIBUTING.rst
  README.md
Labels: documentation

#1535 Fix hepmc3/macro initialization in celer-g4
  app/celer-g4/ActionInitialization.cc
  app/celer-g4/ActionInitialization.hh
  app/celer-g4/GlobalSetup.cc
  app/celer-g4/GlobalSetup.hh
  app/celer-g4/RunInput.hh
  app/celer-g4/celer-g4.cc
  doc/introduction/usage/app.rst
Labels: bug, app

#1531 Run clang-tidy on modified files only
  .github/workflows/build-spack.yml
Labels: documentation

#1536 Store a single process-integrated energy loss and range table per particle
  src/celeritas/alongstep/detail/FluctELoss.hh
  src/celeritas/alongstep/detail/MeanELoss.hh
  src/celeritas/em/msc/detail/UrbanMscHelper.hh
  src/celeritas/phys/Model.hh
  src/celeritas/phys/PhysicsData.hh
  src/celeritas/phys/PhysicsParams.cc
  src/celeritas/phys/PhysicsStepUtils.hh
  src/celeritas/phys/PhysicsTrackView.hh
  test/celeritas/em/MscTestBase.cc
  test/celeritas/phys/Physics.test.cc
  test/celeritas/phys/Physics.test.hh
  test/celeritas/phys/PhysicsStepUtils.test.cc
Labels: physics, minor

#1537 Add piecewise integrator and CDF utilities
  app/celer-sim/Runner.cc
  src/celeritas/grid/GenericCalculator.hh
  src/celeritas/optical/CherenkovParams.cc
  src/celeritas/optical/CherenkovParams.hh
  src/celeritas/optical/WavelengthShiftData.hh
  src/celeritas/optical/WavelengthShiftParams.cc
  src/celeritas/optical/interactor/WavelengthShiftInteractor.hh
  src/corecel/math/CdfUtils.hh
  test/celeritas/ImportedDataTestBase.cc
  test/celeritas/optical/Cherenkov.test.cc
  test/celeritas/optical/WavelengthShift.test.cc
  test/corecel/CMakeLists.txt
  test/corecel/math/CdfUtils.test.cc
Labels: physics, minor

#1479 Extend BIH capabilities for intersection operations
  src/orange/detail/BIHEnclosingVolFinder.hh
  src/orange/detail/BIHIntersectingVolFinder.hh
  test/orange/CMakeLists.txt
  test/orange/detail/BIHIntersectingVolFinder.test.cc
Labels: enhancement, orange

#1543 Remove curand performance test
  test/celeritas/CMakeLists.txt
  test/celeritas/random/curand/CurandPerformance.test.cc
  test/celeritas/random/curand/CurandPerformance.test.cu
  test/celeritas/random/curand/CurandPerformance.test.hh
Labels: removal

#1545 Add missing shell setup in README
  README.md
Labels: documentation

#1546 Enable optical stepping loop
  src/celeritas/optical/CoreTrackView.hh
  src/celeritas/optical/action/detail/PreStepExecutor.hh
  src/celeritas/optical/detail/OpticalLaunchAction.cc
  test/celeritas/optical/OpticalCollector.test.cc
Labels: enhancement, physics

#1547 Implement device bitset
  src/corecel/cont/Bitset.hh
  src/corecel/math/Algorithms.hh
  test/corecel/CMakeLists.txt
  test/corecel/cont/Bitset.test.cc
  test/corecel/math/Algorithms.test.cc
Labels: enhancement, core

#1551 Build VecGeom in weekly clang-tidy cron
  scripts/cmake-presets/ci-ubuntu-github.json
  src/celeritas/alongstep/detail/PropagationApplier.hh
  src/geocel/vg/VecgeomParams.hh
Labels: documentation

#1553 Document and slightly refactor Bethe-Heitler interactor
  src/celeritas/em/interactor/BetheHeitlerInteractor.hh
  src/celeritas/em/xs/LPMCalculator.hh
Labels: documentation, physics

#1554 Adapt bitset word size
  src/corecel/cont/Bitset.hh
  src/corecel/math/Algorithms.hh
Labels: core, minor
