Repository celeritas-project/celeritas, pull requests merged in 2024-09, with the labels that each got.

#1348 Implement physics constructor for OpticalPhysics
  src/celeritas/CMakeLists.txt
  src/celeritas/ext/GeantOpticalPhysicsOptions.cc
  src/celeritas/ext/GeantOpticalPhysicsOptions.hh
  src/celeritas/ext/GeantOpticalPhysicsOptionsIO.json.cc
  src/celeritas/ext/GeantOpticalPhysicsOptionsIO.json.hh
  src/celeritas/ext/GeantPhysicsOptions.hh
  src/celeritas/ext/GeantPhysicsOptionsIO.json.cc
  src/celeritas/ext/detail/CelerEmPhysicsList.cc
  src/celeritas/ext/detail/CelerFTFPBert.cc
  src/celeritas/ext/detail/CelerOpticalPhysics.cc
  src/celeritas/ext/detail/CelerOpticalPhysics.hh
  test/celeritas/ext/GeantImporter.test.cc
Labels: enhancement, physics

#1388 Address minor documentation, contract fixes in CelerOpticalPhysics
  src/celeritas/ext/GeantOpticalPhysicsOptions.hh
  src/celeritas/ext/detail/CelerOpticalPhysics.cc
Labels: minor

#1386 Add skeleton optical core params and launch action
  src/celeritas/CMakeLists.txt
  src/celeritas/optical/CoreParams.cc
  src/celeritas/optical/CoreParams.hh
  src/celeritas/optical/CoreState.cc
  src/celeritas/optical/CoreState.hh
  src/celeritas/optical/OpticalCollector.cc
  src/celeritas/optical/OpticalCollector.hh
  src/celeritas/optical/TrackData.cc
  src/celeritas/optical/TrackData.hh
  src/celeritas/optical/detail/OffloadParams.hh
  src/celeritas/optical/detail/OpticalLaunchAction.cc
  src/celeritas/optical/detail/OpticalLaunchAction.hh
  src/corecel/data/CollectionStateStore.hh
  test/celeritas/optical/OpticalCollector.test.cc
Labels: enhancement, physics

#1389 Add clang 18 and gcc 14 builds to CI
  .github/workflows/build-fast.yml
  src/celeritas/CMakeLists.txt
  src/corecel/CMakeLists.txt
  test/CMakeLists.txt
  test/celeritas/em/MscTestBase.hh
Labels: documentation

#1342 Integrate involute surface into ORANGE construction
  src/orange/OrangeTypes.cc
  src/orange/OrangeTypes.hh
  src/orange/detail/SurfacesRecordBuilder.cc
  src/orange/orangeinp/IntersectRegion.cc
  src/orange/orangeinp/IntersectRegion.hh
  src/orange/orangeinp/IntersectSurfaceBuilder.cc
  src/orange/orangeinp/ObjectIO.json.cc
  src/orange/orangeinp/ObjectIO.json.hh
  src/orange/orangeinp/detail/LocalSurfaceInserter.cc
  src/orange/orangeinp/detail/SurfaceHashPoint.hh
  src/orange/surf/FaceNamer.cc
  src/orange/surf/FaceNamer.hh
  src/orange/surf/Involute.cc
  src/orange/surf/Involute.hh
  src/orange/surf/SoftSurfaceEqual.cc
  src/orange/surf/SoftSurfaceEqual.hh
  src/orange/surf/SurfaceClipper.cc
  src/orange/surf/SurfaceClipper.hh
  src/orange/surf/SurfaceFwd.hh
  src/orange/surf/SurfaceIO.cc
  src/orange/surf/SurfaceIO.hh
  src/orange/surf/SurfaceTypeTraits.hh
  src/orange/surf/detail/AllSurfaces.hh
  src/orange/surf/detail/InvoluteSolver.hh
  src/orange/surf/detail/SurfaceTransformer.cc
  src/orange/surf/detail/SurfaceTransformer.hh
  src/orange/surf/detail/SurfaceTranslator.cc
  src/orange/surf/detail/SurfaceTranslator.hh
  test/orange/OrangeJson.test.cc
  test/orange/data/inputbuilder-involute-cw.org.json
  test/orange/data/inputbuilder-involute-fuel.org.json
  test/orange/data/inputbuilder-involute.org.json
  test/orange/orangeinp/IntersectRegion.test.cc
  test/orange/orangeinp/UnitProto.test.cc
  test/orange/surf/Involute.test.cc
  test/orange/surf/LocalSurfaceVisitor.test.cc
  test/orange/surf/SoftSurfaceEqual.test.cc
  test/orange/surf/detail/InvoluteSolver.test.cc
  test/orange/surf/detail/SurfaceTranslator.test.cc
Labels: enhancement, orange

#1394 Add separate configure option for on-device assertions
  .github/workflows/build-docker.yml
  .github/workflows/build-spack.yml
  CMakeLists.txt
  scripts/cmake-presets/ci-ubuntu-cuda.json
  src/corecel/Assert.hh
  src/corecel/Config.hh.in
Labels: enhancement, core

#1395 Extend Mott coefficients to include positrons and higher Z elements
  src/celeritas/em/data/WentzelOKVIData.hh
  src/celeritas/em/distribution/WentzelDistribution.hh
  src/celeritas/em/params/WentzelOKVIParams.cc
  src/celeritas/em/params/WentzelOKVIParams.hh
  src/celeritas/em/xs/MottRatioCalculator.hh
  test/celeritas/em/CoulombScattering.test.cc
Labels: enhancement, physics

#1392 Fix Geant4 setup when single Coulomb scattering is enabled
  src/celeritas/em/model/CoulombScatteringModel.cc
  src/celeritas/ext/detail/CelerEmStandardPhysics.cc
Labels: bug, physics

#1393 Refactor primaries as `aux` data
  app/celer-g4/ExceptionHandler.cc
  app/celer-g4/RunAction.cc
  app/celer-sim/RunnerOutput.cc
  app/celer-sim/Transporter.cc
  app/celer-sim/Transporter.hh
  src/celeritas/global/CoreParams.cc
  src/celeritas/global/CoreState.cc
  src/celeritas/global/CoreState.hh
  src/celeritas/global/Stepper.cc
  src/celeritas/global/Stepper.hh
  src/celeritas/optical/CoreState.cc
  src/celeritas/optical/CoreState.hh
  src/celeritas/track/CoreStateCounters.hh
  src/celeritas/track/ExtendFromPrimariesAction.cc
  src/celeritas/track/ExtendFromPrimariesAction.cu
  src/celeritas/track/ExtendFromPrimariesAction.hh
  src/celeritas/track/TrackInitParams.hh
  src/corecel/data/AuxStateVec.hh
  src/corecel/data/Copier.hh
  src/corecel/sys/ActionInterface.cc
  src/corecel/sys/ActionInterface.hh
  test/celeritas/GlobalTestBase.cc
  test/celeritas/GlobalTestBase.hh
  test/celeritas/global/AlongStepTestBase.cc
  test/celeritas/global/AlongStepTestBase.hh
  test/celeritas/global/Stepper.test.cc
  test/celeritas/track/StatusChecker.test.cc
  test/celeritas/track/TrackInit.test.cc
  test/celeritas/track/TrackSort.test.cc
  test/celeritas/user/Diagnostic.test.cc
Labels: physics, minor

#1405 Improve multithread GPU performance by removing subtle device sync
  src/celeritas/track/detail/TrackInitAlgorithms.cu
  src/corecel/data/Copier.hh
  test/corecel/data/Copier.test.cc
Labels: physics, performance

#1407 Work around GCC 12.3 compiler bugs
  app/celer-g4/celer-g4.cc
  test/corecel/data/DeviceVector.test.cc
Labels: bug, core

#1408 Fix documentation deployment
  .github/workflows/deploy-pages.yml
  .github/workflows/doc.yml
  doc/appendix/administration.rst
Labels: documentation

#1403 Change LocalTransporter deallocation semantics
  app/celer-g4/CMakeLists.txt
  app/celer-g4/DetectorConstruction.cc
  app/celer-g4/DetectorConstruction.hh
  app/celer-g4/GeantDiagnostics.cc
  app/celer-g4/GeantDiagnostics.hh
  app/celer-g4/LocalLogger.hh
  app/celer-g4/RunAction.cc
  app/celer-g4/test-harness.py
  src/accel/LocalTransporter.cc
  src/accel/LocalTransporter.hh
  src/accel/SharedParams.cc
  src/accel/SharedParams.hh
  src/accel/detail/HitManager.cc
  src/accel/detail/HitManager.hh
  src/accel/detail/HitProcessor.cc
  src/accel/detail/HitProcessor.hh
  src/celeritas/global/CoreState.cc
  src/celeritas/global/CoreState.hh
  src/celeritas/global/Stepper.cc
  src/celeritas/global/Stepper.hh
  src/celeritas/global/alongstep/detail/PropagationApplier.hh
  src/celeritas/phys/detail/TrackingCutExecutor.hh
  src/corecel/math/Quantity.hh
  src/geocel/g4/GeantGeoData.hh
  src/geocel/g4/detail/GeantGeoNavCollection.cc
  src/geocel/g4/detail/GeantGeoNavCollection.hh
  test/accel/detail/HitManager.test.cc
  test/accel/detail/HitProcessor.test.cc
  test/celeritas/global/Stepper.test.cc
Labels: minor, external

#1402 Store OBZ data during runtime
  src/orange/BoundingBoxUtils.hh
  src/orange/OrangeData.hh
  src/orange/OrangeInput.hh
  src/orange/OrangeTypes.hh
  src/orange/detail/OrientedBoundingZone.hh
  src/orange/detail/UnitInserter.cc
  src/orange/detail/UnitInserter.hh
  src/orange/orangeinp/UnitProto.cc
  src/orange/orangeinp/detail/BuildIntersectRegion.cc
  test/orange/BoundingBoxUtils.test.cc
  test/orange/Orange.test.cc
  test/orange/OrangeGeoTestBase.cc
  test/orange/detail/OrientedBoundingZone.test.cc
Labels: enhancement, orange

#1411 Add muon EM processes to Celeritas physics list and muon brems/ioni `Process` classes
  src/celeritas/CMakeLists.txt
  src/celeritas/em/model/ICRU73QOModel.cc
  src/celeritas/em/process/MuBremsstrahlungProcess.cc
  src/celeritas/em/process/MuBremsstrahlungProcess.hh
  src/celeritas/em/process/MuIonizationProcess.cc
  src/celeritas/em/process/MuIonizationProcess.hh
  src/celeritas/ext/GeantPhysicsOptions.hh
  src/celeritas/ext/GeantPhysicsOptionsIO.json.cc
  src/celeritas/ext/detail/CelerEmStandardPhysics.cc
  src/celeritas/ext/detail/CelerEmStandardPhysics.hh
  src/celeritas/ext/detail/MuHadEmStandardPhysics.hh
  src/celeritas/phys/ProcessBuilder.cc
  src/celeritas/phys/ProcessBuilder.hh
  test/celeritas/data/four-steel-slabs.geant.json
  test/celeritas/data/four-steel-slabs.root
  test/celeritas/data/simple-cms.root
  test/celeritas/ext/GeantImporter.test.cc
  test/celeritas/ext/RootImporter.test.cc
  test/celeritas/ext/RootJsonDumper.test.cc
  test/celeritas/phys/Particle.test.cc
  test/celeritas/phys/ProcessBuilder.test.cc
Labels: enhancement, physics

#1410 Refactor action sequence into action group plus extras
  app/celer-sim/Runner.cc
  app/celer-sim/Transporter.cc
  src/accel/CMakeLists.txt
  src/accel/LocalTransporter.cc
  src/celeritas/CMakeLists.txt
  src/celeritas/global/ActionGroups.cc
  src/celeritas/global/ActionGroups.hh
  src/celeritas/global/ActionInterface.hh
  src/celeritas/global/ActionSequence.cc
  src/celeritas/global/ActionSequence.hh
  src/celeritas/global/Stepper.cc
  src/celeritas/global/Stepper.hh
  src/celeritas/track/SortTracksAction.cc
  src/celeritas/track/SortTracksAction.hh
  src/corecel/sys/ActionGroups.hh
  src/corecel/sys/ActionGroups.t.hh
  src/corecel/sys/ActionInterface.hh
  src/corecel/sys/ActionRegistry.cc
  src/corecel/sys/ActionRegistry.hh
  test/accel/CMakeLists.txt
  test/celeritas/global/StepperTestBase.cc
  test/geocel/g4/GeantGeo.test.cc
Labels: physics, minor

#1414 Add action for generating scintillation photons from distributions
  src/celeritas/CMakeLists.txt
  src/celeritas/optical/OpticalCollector.cc
  src/celeritas/optical/OpticalCollector.hh
  src/celeritas/optical/ScintillationGenerator.hh
  src/celeritas/optical/detail/ScintGeneratorAction.cc
  src/celeritas/optical/detail/ScintGeneratorAction.cu
  src/celeritas/optical/detail/ScintGeneratorAction.hh
  src/celeritas/optical/detail/ScintGeneratorExecutor.hh
  test/celeritas/optical/OpticalCollector.test.cc
  test/celeritas/optical/Scintillation.test.cc
Labels: enhancement, physics

#1416 Define "static" concrete action for those with unique name/description
  src/celeritas/em/model/BetheHeitlerModel.cc
  src/celeritas/em/model/BetheHeitlerModel.hh
  src/celeritas/em/model/BraggModel.cc
  src/celeritas/em/model/BraggModel.hh
  src/celeritas/em/model/CombinedBremModel.cc
  src/celeritas/em/model/CombinedBremModel.hh
  src/celeritas/em/model/CoulombScatteringModel.cc
  src/celeritas/em/model/CoulombScatteringModel.hh
  src/celeritas/em/model/EPlusGGModel.cc
  src/celeritas/em/model/EPlusGGModel.hh
  src/celeritas/em/model/ICRU73QOModel.cc
  src/celeritas/em/model/ICRU73QOModel.hh
  src/celeritas/em/model/KleinNishinaModel.cc
  src/celeritas/em/model/KleinNishinaModel.hh
  src/celeritas/em/model/LivermorePEModel.cc
  src/celeritas/em/model/LivermorePEModel.hh
  src/celeritas/em/model/MollerBhabhaModel.cc
  src/celeritas/em/model/MollerBhabhaModel.hh
  src/celeritas/em/model/MuBetheBlochModel.cc
  src/celeritas/em/model/MuBetheBlochModel.hh
  src/celeritas/em/model/MuBremsstrahlungModel.cc
  src/celeritas/em/model/MuBremsstrahlungModel.hh
  src/celeritas/em/model/RayleighModel.cc
  src/celeritas/em/model/RayleighModel.hh
  src/celeritas/em/model/RelativisticBremModel.cc
  src/celeritas/em/model/RelativisticBremModel.hh
  src/celeritas/em/model/SeltzerBergerModel.cc
  src/celeritas/em/model/SeltzerBergerModel.hh
  src/celeritas/geo/detail/BoundaryAction.cc
  src/celeritas/geo/detail/BoundaryAction.hh
  src/celeritas/global/CoreParams.cc
  src/celeritas/neutron/model/ChipsNeutronElasticModel.cc
  src/celeritas/neutron/model/ChipsNeutronElasticModel.hh
  src/celeritas/neutron/model/NeutronInelasticModel.cc
  src/celeritas/neutron/model/NeutronInelasticModel.hh
  src/celeritas/phys/PhysicsParams.cc
  src/celeritas/phys/PhysicsParams.hh
  src/celeritas/phys/detail/DiscreteSelectAction.cc
  src/celeritas/phys/detail/DiscreteSelectAction.hh
  src/celeritas/phys/detail/PreStepAction.cc
  src/celeritas/phys/detail/PreStepAction.hh
  src/celeritas/phys/detail/TrackingCutAction.cc
  src/celeritas/phys/detail/TrackingCutAction.hh
  src/corecel/sys/ActionInterface.cc
  src/corecel/sys/ActionInterface.hh
  test/corecel/sys/ActionRegistry.test.cc
Labels: physics, minor

#1417 Add initial stepping loop to optical offload
  src/celeritas/CMakeLists.txt
  src/celeritas/optical/CoreParams.cc
  src/celeritas/optical/CoreParams.hh
  src/celeritas/optical/CoreState.hh
  src/celeritas/optical/TrackData.hh
  src/celeritas/optical/action/ActionGroups.cc
  src/celeritas/optical/action/ActionGroups.hh
  src/celeritas/optical/action/ActionInterface.hh
  src/celeritas/optical/action/BoundaryAction.cc
  src/celeritas/optical/action/BoundaryAction.cu
  src/celeritas/optical/action/BoundaryAction.hh
  src/celeritas/optical/detail/OpticalLaunchAction.cc
  src/celeritas/optical/detail/OpticalLaunchAction.hh
  src/celeritas/track/CoreStateCounters.hh
  src/celeritas/track/ExtendFromPrimariesAction.hh
  test/celeritas/optical/OpticalCollector.test.cc
  test/corecel/ScopedLogStorer.cc
  test/corecel/ScopedLogStorer.hh
Labels: enhancement, physics

#1420 Improve PRINT_EXPECTED formatting for long strings and vectors
  src/corecel/io/Repr.hh
  test/corecel/io/Repr.test.cc
Labels: core, minor

#1418 Support aliased nodes during CsgTree simplification
  src/orange/orangeinp/detail/DeMorganSimplifier.cc
  src/orange/orangeinp/detail/DeMorganSimplifier.hh
  test/orange/orangeinp/CsgTreeUtils.test.cc
Labels: minor, orange

#1419 Import muon pair production sampling table from Geant4
  app/celer-dump-data.cc
  src/celeritas/em/model/CombinedBremModel.hh
  src/celeritas/em/process/BremsstrahlungProcess.hh
  src/celeritas/ext/GeantImporter.cc
  src/celeritas/ext/RootInterfaceLinkDef.h
  src/celeritas/ext/detail/CelerEmStandardPhysics.cc
  src/celeritas/ext/detail/GeantProcessImporter.cc
  src/celeritas/ext/detail/GeantProcessImporter.hh
  src/celeritas/io/ImportData.hh
  src/celeritas/io/ImportMuPairProductionTable.hh
  src/celeritas/io/ImportPhysicsVector.cc
  src/celeritas/io/ImportPhysicsVector.hh
  src/celeritas/io/ImportSBTable.hh
  src/celeritas/io/ImportUnits.cc
  src/celeritas/io/ImportUnits.hh
  src/celeritas/phys/ProcessBuilder.hh
  test/celeritas/ext/GeantImporter.test.cc
  test/celeritas/ext/RootJsonDumper.test.cc
Labels: enhancement, external

#1421 Report and annotate test failures in CI
  .github/workflows/build-docker.yml
  .github/workflows/build-fast.yml
  .github/workflows/build-spack.yml
  .github/workflows/build-ultralite.yml
  .github/workflows/pull_request.yml
  .github/workflows/pull_request_completed.yml
  cmake/CeleritasAddTest.cmake
  scripts/cmake-presets/ci-ubuntu-github.json
  scripts/cmake-presets/ci-windows-github.json
  src/corecel/io/ColorUtils.cc
  test/corecel/math/HashUtils.test.cc
Labels: documentation, enhancement, core

#1423 Refactor action launcher components into kernel launcher
  src/celeritas/em/model/BetheHeitlerModel.cu
  src/celeritas/em/model/BraggModel.cu
  src/celeritas/em/model/CombinedBremModel.cu
  src/celeritas/em/model/EPlusGGModel.cu
  src/celeritas/em/model/ICRU73QOModel.cu
  src/celeritas/em/model/KleinNishinaModel.cu
  src/celeritas/em/model/LivermorePEModel.cu
  src/celeritas/em/model/MollerBhabhaModel.cu
  src/celeritas/em/model/MuBetheBlochModel.cu
  src/celeritas/em/model/MuBremsstrahlungModel.cu
  src/celeritas/em/model/RayleighModel.cu
  src/celeritas/em/model/RelativisticBremModel.cu
  src/celeritas/em/model/SeltzerBergerModel.cu
  src/celeritas/geo/detail/BoundaryAction.cu
  src/celeritas/global/ActionLauncher.device.hh
  src/celeritas/global/ActionLauncher.hh
  src/celeritas/global/CoreState.hh
  src/celeritas/global/CoreTrackView.hh
  src/celeritas/global/TrackExecutor.hh
  src/celeritas/global/alongstep/AlongStepNeutralAction.cu
  src/celeritas/global/alongstep/AlongStepRZMapFieldMscAction.cu
  src/celeritas/global/alongstep/AlongStepUniformMscAction.cu
  src/celeritas/global/alongstep/detail/AlongStepKernels.cu
  src/celeritas/global/alongstep/detail/PropagationApplier.hh
  src/celeritas/global/detail/CoreStateThreadOffsets.hh
  src/celeritas/neutron/model/ChipsNeutronElasticModel.cu
  src/celeritas/phys/InteractionApplier.hh
  src/celeritas/phys/detail/TrackingCutAction.cu
  src/celeritas/track/SimFunctors.hh
  src/celeritas/user/detail/SimpleCaloExecutor.hh
  src/celeritas/user/detail/SimpleCaloImpl.cu
  src/corecel/sys/KernelLauncher.device.hh
  src/corecel/sys/KernelParamCalculator.device.hh
  src/corecel/sys/KernelTraits.hh
  src/corecel/sys/detail/KernelLauncherImpl.device.hh
  src/corecel/sys/detail/KernelTraitsImpl.hh
  src/geocel/rasterize/RaytraceImager.device.t.hh
  src/geocel/vg/RaytraceImager.cu
  src/orange/RaytraceImager.cu
Labels: core, minor

#1424 Add optical core track view and launcher
  src/celeritas/CMakeLists.txt
  src/celeritas/optical/CoreParams.hh
  src/celeritas/optical/CoreState.hh
  src/celeritas/optical/CoreTrackData.cc
  src/celeritas/optical/CoreTrackData.hh
  src/celeritas/optical/CoreTrackDataFwd.hh
  src/celeritas/optical/CoreTrackView.hh
  src/celeritas/optical/TrackView.hh
  src/celeritas/optical/action/ActionLauncher.device.hh
  src/celeritas/optical/action/ActionLauncher.hh
  src/celeritas/optical/action/BoundaryAction.cc
  src/celeritas/optical/action/BoundaryAction.cu
  src/celeritas/optical/action/TrackSlotExecutor.hh
  src/celeritas/optical/action/detail/BoundaryExecutor.hh
  src/celeritas/optical/detail/CerenkovGeneratorAction.cc
  src/celeritas/optical/detail/ScintGeneratorAction.cc
  test/celeritas/optical/OpticalCollector.test.cc
Labels: enhancement, physics

#1429 Hotfix: untested CUDA code in #1424
  src/celeritas/optical/CoreTrackView.hh
  src/celeritas/optical/action/BoundaryAction.cu
Labels: documentation, minor

#1432 Add `total_energy` accessor to `ParticleTrackView`
  src/celeritas/em/distribution/MuBBEnergyDistribution.hh
  src/celeritas/em/interactor/CombinedBremInteractor.hh
  src/celeritas/em/interactor/RelativisticBremInteractor.hh
  src/celeritas/em/interactor/SeltzerBergerInteractor.hh
  src/celeritas/em/interactor/detail/RBEnergySampler.hh
  src/celeritas/em/interactor/detail/SBEnergySampler.hh
  src/celeritas/em/xs/RBDiffXsCalculator.hh
  src/celeritas/phys/ParticleTrackView.hh
  test/celeritas/em/RelativisticBrem.test.cc
  test/celeritas/phys/Particle.test.cc
Labels: physics, minor

#1409 Fix construction of single-volume Geant4 with ORANGE and activate examples
  .github/workflows/build-spack.yml
  example/accel/CMakeLists.txt
  scripts/ci/test-examples.sh
  src/accel/ExceptionConverter.cc
  src/corecel/Assert.cc
  src/corecel/io/StringUtils.cc
  src/corecel/io/StringUtils.hh
  src/orange/g4org/ProtoConstructor.cc
  test/accel/ExceptionConverter.test.cc
  test/celeritas/GeantTestBase.cc
  test/geocel/data/one-box.gdml
  test/orange/g4org/ProtoConstructor.test.cc
Labels: bug, orange

#1431 Fix intermittent CI failures due to corrupt XML
  .github/workflows/build-docker.yml
  .github/workflows/build-fast.yml
  .github/workflows/build-spack.yml
  .github/workflows/build-ultralite.yml
  .github/workflows/pull_request_completed.yml
  CMakeLists.txt
  cmake/CeleritasAddTest.cmake
  scripts/cmake-presets/ci-ubuntu-github.json
  scripts/cmake-presets/ci-windows-github.json
Labels: documentation, enhancement

#1433 Add `track_order` option to celer-g4 and default to partitioning by charge on GPU
  app/celer-g4/GlobalSetup.cc
  app/celer-g4/RunInput.hh
  app/celer-g4/RunInputIO.json.cc
  app/celer-sim/RunnerInput.hh
  app/celer-sim/RunnerInputIO.json.cc
  src/accel/SetupOptions.hh
  src/celeritas/TypesIO.hh
Labels: app, performance

#1426 Add slot particle diagnostic
  app/celer-g4/GeantDiagnostics.cc
  app/celer-g4/GlobalSetup.cc
  app/celer-g4/RunInput.hh
  app/celer-g4/RunInputIO.json.cc
  app/celer-g4/test-harness.py
  app/celer-sim/Runner.cc
  app/celer-sim/RunnerInput.hh
  app/celer-sim/RunnerInputIO.json.cc
  app/celer-sim/simple-driver.py
  doc/implementation/core-physics.rst
  doc/implementation/core-physics/diagnostics.rst
  scripts/user/.gitignore
  scripts/user/plot-slot-diagnostic.py
  src/accel/SetupOptions.hh
  src/accel/SetupOptionsMessenger.cc
  src/accel/SharedParams.cc
  src/celeritas/CMakeLists.txt
  src/celeritas/phys/ParticleParamsOutput.hh
  src/celeritas/track/ExtendFromPrimariesAction.cc
  src/celeritas/track/ExtendFromPrimariesAction.hh
  src/celeritas/user/ActionDiagnostic.cc
  src/celeritas/user/ActionDiagnostic.hh
  src/celeritas/user/SlotDiagnostic.cc
  src/celeritas/user/SlotDiagnostic.cu
  src/celeritas/user/SlotDiagnostic.hh
  src/celeritas/user/StepDiagnostic.cc
  src/celeritas/user/StepDiagnostic.hh
  src/celeritas/user/detail/SlotDiagnosticExecutor.hh
  src/corecel/data/AuxStateData.hh
  src/corecel/data/ObserverPtr.hh
  src/corecel/sys/ActionInterface.cc
  src/corecel/sys/ActionInterface.hh
  test/celeritas/CMakeLists.txt
  test/celeritas/user/CaloTestBase.hh
  test/celeritas/user/Diagnostic.test.cc
  test/celeritas/user/DiagnosticTestBase.cc
  test/celeritas/user/DiagnosticTestBase.hh
  test/celeritas/user/MctruthTestBase.hh
  test/celeritas/user/SimpleLoopTestBase.cc
  test/celeritas/user/SimpleLoopTestBase.hh
  test/celeritas/user/SlotDiagnostic.test.cc
  test/celeritas/user/StepCollector.test.cc
Labels: enhancement, user
