Repository celeritas-project/celeritas, pull requests merged in 2024-11, with the labels that each got.

#1475 Override and save Geant4 dataset variables at configure time
  CMakeLists.txt
  app/CMakeLists.txt
  test/CMakeLists.txt
  test/accel/CMakeLists.txt
  test/celeritas/CMakeLists.txt
Labels: enhancement, external

#1444 Implement spline interpolation for cross-section calculation
  src/celeritas/grid/SplineXsCalculator.hh
  test/celeritas/CMakeLists.txt
  test/celeritas/grid/CalculatorTestBase.cc
  test/celeritas/grid/SplineXsCalculator.test.cc
  test/celeritas/grid/XsCalculator.test.cc
Labels: enhancement, physics

#1477 Use kernel launchers instead of macros
  src/celeritas/random/CuHipRngData.cc
  src/celeritas/random/RngReseed.cc
  src/celeritas/random/RngReseed.cu
  src/celeritas/random/RngReseed.hh
  src/celeritas/random/detail/CuHipRngStateInit.cc
  src/celeritas/random/detail/CuHipRngStateInit.cu
  src/celeritas/random/detail/CuHipRngStateInit.hh
  src/celeritas/random/detail/RngReseedExecutor.hh
  src/corecel/sys/KernelLauncher.hh
  src/geocel/rasterize/RaytraceImager.t.hh
Labels: core, minor

#1480 Fix missing brace and refactor #1475
  .github/workflows/build-spack.yml
  CMakeLists.txt
  cmake/CeleritasUtils.cmake
Labels: core, minor

#1484 Fix build with latest Geant4 develop
  src/geocel/GeantGeoUtils.cc
Labels: minor, external

#1482 Improve logger when using either CUDA or MPI
  src/accel/Logger.cc
  src/corecel/io/Logger.cc
  src/corecel/io/Logger.hh
  src/corecel/io/detail/NullLoggerMessage.hh
  test/celeritas/ext/GeantVolumeMapper.test.cc
  test/corecel/io/Logger.test.cc
Labels: core, minor

#1481 Check VecGeom BVH device pointers at setup and run time
  CMakeLists.txt
  src/celeritas_cmake_strings.h
  src/celeritas_sys_config.h
  src/corecel/CMakeLists.txt
  src/corecel/device_runtime_api.h
  src/corecel/sys/KernelLauncher.device.hh
  src/geocel/CMakeLists.txt
  src/geocel/vg/VecgeomParams.cc
  src/geocel/vg/VecgeomParams.surface.cu
  src/geocel/vg/VecgeomParams.surface.hh
  src/geocel/vg/detail/BVHNavigator.hh
  src/geocel/vg/detail/VecgeomSetup.cu
  src/geocel/vg/detail/VecgeomSetup.hh
  test/geocel/CMakeLists.txt
Labels: bug, external

#1469 Implement optical Rayleigh model
  doc/implementation/optical-physics.rst
  src/celeritas/CMakeLists.txt
  src/celeritas/io/ImportOpticalMaterial.hh
  src/celeritas/optical/ImportedModelAdapter.cc
  src/celeritas/optical/MaterialParams.cc
  src/celeritas/optical/MaterialParams.hh
  src/celeritas/optical/model/RayleighMfpCalculator.hh
  src/celeritas/optical/model/RayleighModel.cc
  src/celeritas/optical/model/RayleighModel.cu
  src/celeritas/optical/model/RayleighModel.hh
  src/corecel/grid/NonuniformGrid.hh
  test/celeritas/CMakeLists.txt
  test/celeritas/optical/Absorption.test.cc
  test/celeritas/optical/MfpBuilder.test.cc
  test/celeritas/optical/MockImportedData.cc
  test/celeritas/optical/MockImportedData.hh
  test/celeritas/optical/MockValidation.test.cc
  test/celeritas/optical/Rayleigh.test.cc
  test/celeritas/optical/RayleighMfpCalculator.test.cc
  test/corecel/grid/NonuniformGrid.test.cc
Labels: enhancement, physics

#1487 Fix unnecessary linking when using VecGeom+CUDA
  cmake/CudaRdcUtils.cmake
Labels: bug, core

#1490 Fix dBVH memcpy size
  src/geocel/vg/detail/VecgeomSetup.cu
Labels: bug, minor

#1492 Use canonical loop form with OpenMP
  src/celeritas/global/ActionLauncher.hh
  src/celeritas/optical/action/ActionLauncher.hh
  src/celeritas/optical/action/InitializeTracksAction.cc
  src/celeritas/track/ExtendFromPrimariesAction.cc
  src/celeritas/track/InitializeTracksAction.cc
  src/celeritas/user/detail/SimpleCaloImpl.cc
  src/corecel/sys/KernelLauncher.hh
Labels: bug, core

#1491 Allow core and optical loops to have different numbers of track slots
  app/celer-sim/Runner.cc
  app/celer-sim/RunnerInput.hh
  app/celer-sim/RunnerInputIO.json.cc
  app/celer-sim/simple-driver.py
  src/celeritas/optical/OpticalCollector.cc
  src/celeritas/optical/OpticalCollector.hh
  src/celeritas/optical/action/detail/PreStepExecutor.hh
  src/celeritas/optical/detail/CerenkovGeneratorAction.cc
  src/celeritas/optical/detail/OpticalLaunchAction.cc
  src/celeritas/optical/detail/OpticalLaunchAction.hh
  src/celeritas/optical/detail/ScintGeneratorAction.cc
  test/celeritas/optical/OpticalCollector.test.cc
Labels: enhancement, physics

#1456 Add muon decay interactor
  doc/implementation/decay-physics.rst
  doc/index.rst
  src/celeritas/decay/data/MuDecayData.hh
  src/celeritas/decay/executor/MuDecayExecutor.hh
  src/celeritas/decay/interactor/MuDecayInteractor.hh
  src/celeritas/phys/FourVector.hh
  src/celeritas/phys/ParticleParams.hh
  test/celeritas/CMakeLists.txt
  test/celeritas/decay/MuDecay.test.cc
  test/celeritas/phys/InteractorHostTestBase.cc
Labels: enhancement, physics

#1489 Fix linking Athena with VecGeom+CUDA
  cmake/CudaRdcUtils.cmake
  cmake/FindVecGeom.cmake
Labels: bug, external

#1495 Reconstruct "touchable" using navigation hierarchy
  src/accel/CMakeLists.txt
  src/accel/SharedParams.cc
  src/accel/detail/HitManager.cc
  src/accel/detail/HitManager.hh
  src/accel/detail/HitProcessor.cc
  src/accel/detail/HitProcessor.hh
  src/accel/detail/LevelTouchableUpdater.cc
  src/accel/detail/LevelTouchableUpdater.hh
  src/accel/detail/NaviTouchableUpdater.cc
  src/accel/detail/NaviTouchableUpdater.hh
  src/accel/detail/TouchableUpdaterInterface.cc
  src/accel/detail/TouchableUpdaterInterface.hh
  src/geocel/g4vg/Converter.cc
  test/accel/CMakeLists.txt
  test/accel/detail/HitManager.test.cc
  test/accel/detail/HitProcessor.test.cc
  test/accel/detail/LevelTouchableUpdater.test.cc
  test/accel/detail/NaviTouchableUpdater.test.cc
  test/geocel/CMakeLists.txt
  test/geocel/vg/Vecgeom.test.cc
Labels: enhancement, external, user, geometry

#1498 Work around RDC-related link errors when +cuda+vecgeom~shared
  test/geocel/CMakeLists.txt
Labels: core, minor

#1499 Move `alongstep` directory to top level
  app/celer-sim/Runner.cc
  src/accel/AlongStepFactory.cc
  src/accel/AlongStepFactory.hh
  src/celeritas/CMakeLists.txt
  src/celeritas/alongstep/AlongStep.hh
  src/celeritas/alongstep/AlongStepGeneralLinearAction.cc
  src/celeritas/alongstep/AlongStepGeneralLinearAction.cu
  src/celeritas/alongstep/AlongStepGeneralLinearAction.hh
  src/celeritas/alongstep/AlongStepNeutralAction.cc
  src/celeritas/alongstep/AlongStepNeutralAction.cu
  src/celeritas/alongstep/AlongStepNeutralAction.hh
  src/celeritas/alongstep/AlongStepRZMapFieldMscAction.cc
  src/celeritas/alongstep/AlongStepRZMapFieldMscAction.cu
  src/celeritas/alongstep/AlongStepRZMapFieldMscAction.hh
  src/celeritas/alongstep/AlongStepUniformMscAction.cc
  src/celeritas/alongstep/AlongStepUniformMscAction.cu
  src/celeritas/alongstep/AlongStepUniformMscAction.hh
  src/celeritas/alongstep/detail/AlongStepKernels.cu
  src/celeritas/alongstep/detail/AlongStepKernels.hh
  src/celeritas/alongstep/detail/AlongStepNeutralImpl.hh
  src/celeritas/alongstep/detail/ElossApplier.hh
  src/celeritas/alongstep/detail/FluctELoss.hh
  src/celeritas/alongstep/detail/LinearPropagatorFactory.hh
  src/celeritas/alongstep/detail/MeanELoss.hh
  src/celeritas/alongstep/detail/MscApplier.hh
  src/celeritas/alongstep/detail/MscStepLimitApplier.hh
  src/celeritas/alongstep/detail/PropagationApplier.hh
  src/celeritas/alongstep/detail/RZMapFieldPropagatorFactory.hh
  src/celeritas/alongstep/detail/TimeUpdater.hh
  src/celeritas/alongstep/detail/TrackUpdater.hh
  src/celeritas/alongstep/detail/UniformFieldPropagatorFactory.hh
  src/celeritas/global/CoreParams.cc
  test/celeritas/GeantTestBase.cc
  test/celeritas/MockTestBase.cc
  test/celeritas/SimpleTestBase.cc
  test/celeritas/global/AlongStep.test.cc
  test/celeritas/global/AlongStepTestBase.cc
  test/celeritas/global/AlongStepTestBase.hh
  test/celeritas/global/Stepper.test.cc
  test/celeritas/global/StepperGeant.test.cc
  test/celeritas/optical/OpticalCollector.test.cc
  test/celeritas/user/Diagnostic.test.cc
  test/celeritas/user/StepCollector.test.cc
Labels: core, minor

#1500 Fix redundant move warning
  test/orange/g4org/ProtoConstructor.test.cc
Labels: core, minor

#1502 Fix documentation
  doc/CMakeLists.txt
  doc/implementation/decay-physics.rst
  doc/implementation/em-physics.rst
  doc/implementation/optical-physics.rst
  src/celeritas/decay/interactor/MuDecayInteractor.hh
  src/celeritas/io/ImportOpticalMaterial.hh
  src/orange/detail/BIHView.hh
Labels: bug, documentation

#1501 Default SD integration to "true"
  doc/implementation/geant4-interface.rst
  src/accel/SetupOptions.cc
  src/accel/SetupOptions.hh
  src/accel/detail/HitManager.cc
  test/accel/detail/HitManager.test.cc
Labels: enhancement, external

#1504 Add debugging information for app tests
  app/celer-g4/test-harness.py
  app/celer-geo/test-harness.py
  app/celer-sim/simple-driver.py
Labels: documentation, minor, app

#1509 Refactor muon bremsstrahlung angular distribution
  doc/implementation/em-physics.rst
  src/celeritas/em/distribution/MuBremsPPAngularDistribution.hh
  src/celeritas/em/interactor/MuBremsstrahlungInteractor.hh
  src/celeritas/em/model/SeltzerBergerModel.cc
  src/celeritas/em/model/SeltzerBergerModel.hh
  src/celeritas/em/model/detail/SBTableInserter.hh
  src/celeritas/grid/TwodGridBuilder.cc
  src/celeritas/grid/TwodGridBuilder.hh
  src/celeritas/io/ImportPhysicsVector.hh
  test/celeritas/CMakeLists.txt
  test/celeritas/em/BetheBloch.test.cc
  test/celeritas/em/MuBetheBloch.test.cc
  test/celeritas/em/distribution/MuBremsPPAngularDistribution.test.cc
Labels: documentation, physics, minor

#1510 Add FourVector helper functions
  src/celeritas/decay/interactor/MuDecayInteractor.hh
  src/celeritas/neutron/interactor/ChipsNeutronElasticInteractor.hh
  src/celeritas/neutron/interactor/detail/CascadeCollider.hh
  src/celeritas/neutron/interactor/detail/CascadeParticle.hh
  src/celeritas/phys/FourVector.hh
  src/celeritas/phys/ParticleTrackView.hh
  test/celeritas/neutron/NeutronElastic.test.cc
  test/celeritas/phys/FourVector.test.cc
Labels: physics, minor

#1513 Define hypotenuse function using fma
  src/celeritas/field/RZMapField.hh
  src/celeritas/neutron/interactor/detail/CascadeCollider.hh
  src/celeritas/phys/FourVector.hh
  src/corecel/math/Algorithms.hh
  src/corecel/math/ArrayUtils.hh
  src/orange/MatrixUtils.cc
  src/orange/surf/detail/InvoluteSolver.hh
  test/celeritas/field/CMSParameterizedField.hh
  test/corecel/math/Algorithms.test.cc
  test/orange/surf/Involute.test.cc
Labels: core, minor

#1511 Add a CI job for c++20
  .github/workflows/build-fast.yml
Labels: documentation

#1515 Fix celer-sim MC truth ROOT output file generation during tests
  app/celer-sim/CMakeLists.txt
  src/celeritas/user/RootStepWriter.cc
  src/celeritas/user/detail/StepParams.cc
Labels: bug, user

#1514 Split CeleritasUtils cmake and use VecGeom RDC if available
  CMakeLists.txt
  cmake/CeleritasAddTest.cmake
  cmake/CeleritasLibraryUtils.cmake
  cmake/CeleritasOptionUtils.cmake
  cmake/CeleritasUtils.cmake
  src/accel/CMakeLists.txt
  src/celeritas/CMakeLists.txt
  src/corecel/CMakeLists.txt
  src/geocel/CMakeLists.txt
  src/orange/CMakeLists.txt
  test/CMakeLists.txt
Labels: core, minor

#1521 Hotfix: Disable ROCm due to too-old CI image
  .github/workflows/build-docker.yml
Labels: documentation

#1523 Update post-PR workflow to `actions/download-artifact@v4`
  .github/workflows/pull_request_completed.yml
Labels: documentation, minor

#1525 Add a helper class for inverse transform sampling
  src/celeritas/grid/InverseCdfFinder.hh
  src/celeritas/neutron/interactor/detail/CascadeCollider.hh
  src/corecel/grid/TwodSubgridCalculator.hh
  test/celeritas/CMakeLists.txt
  test/celeritas/grid/InverseCdfFinder.test.cc
  test/corecel/grid/TwodGridCalculator.test.cc
Labels: physics, minor

#1524 Require clang-tidy in CI
  .clang-tidy
  .github/workflows/build-spack.yml
  app/celer-dump-data.cc
  app/celer-g4/DetectorConstruction.cc
  app/celer-g4/GeantDiagnostics.cc
  app/celer-g4/SensitiveHit.cc
  app/celer-geo/celer-geo.cc
  scripts/cmake-presets/ci-ubuntu-github.json
  src/accel/ExceptionConverter.cc
  src/accel/SharedParams.cc
  src/accel/detail/HitProcessor.cc
  src/celeritas/ext/detail/CelerOpticalPhysics.cc
  src/celeritas/global/CoreState.cc
  src/celeritas/mat/MaterialParams.cc
  src/celeritas/phys/ImportedProcessAdapter.cc
  src/celeritas/phys/PrimaryGenerator.cc
  src/celeritas/user/SimpleCalo.cc
  src/celeritas/user/SlotDiagnostic.cc
  src/corecel/data/CollectionMirror.hh
  src/corecel/io/ColorUtils.cc
  src/corecel/io/ExceptionOutput.cc
  src/corecel/io/LoggerTypes.cc
  src/corecel/io/detail/ReprImpl.cc
  src/corecel/sys/MultiExceptionHandler.cc
  src/corecel/sys/MultiExceptionHandler.hh
  src/corecel/sys/ScopedMem.cc
  src/corecel/sys/ScopedMem.hh
  src/corecel/sys/ScopedMpiInit.cc
  src/corecel/sys/ScopedSignalHandler.cc
  src/corecel/sys/Stream.cc
  src/corecel/sys/TracingSession.cc
  src/corecel/sys/TypeDemangler.cc
  src/geocel/GeoParamsInterface.hh
  src/geocel/GeoVolumeFinder.cc
  src/geocel/GeoVolumeFinder.hh
  src/geocel/ScopedGeantLogger.cc
  src/geocel/g4/GeantGeoParams.cc
  src/geocel/g4vg/Converter.cc
  src/geocel/g4vg/SolidConverter.cc
  src/geocel/rasterize/ImageWriter.libpng.cc
  src/geocel/vg/detail/VecgeomNavCollection.cc
  src/orange/OrangeParams.cc
  src/orange/OrangeParams.hh
  src/orange/OrangeTypes.cc
  src/orange/detail/OrangeInputIOImpl.json.cc
  src/orange/detail/UnitInserter.cc
  src/orange/detail/UniverseInserter.cc
  src/orange/g4org/PhysicalVolumeConverter.cc
  src/orange/g4org/ProtoConstructor.cc
  src/orange/g4org/SolidConverter.cc
  src/orange/orangeinp/InputBuilder.cc
  src/orange/orangeinp/IntersectRegion.cc
  src/orange/orangeinp/PolySolid.cc
  src/orange/surf/GeneralQuadric.cc
  src/orange/surf/GeneralQuadric.hh
  src/orange/surf/SimpleQuadric.cc
  src/orange/surf/SimpleQuadric.hh
Labels: documentation, core
