Repository celeritas-project/celeritas, pull requests merged in 2024-02, with the labels that each got.

#1094 Fix position check after propagating
  src/celeritas/global/alongstep/detail/PropagationApplier.hh
  test/CMakeLists.txt
  test/celeritas/LeadBoxTestBase.hh
  test/celeritas/data/lead-box.gdml
  test/celeritas/data/lead-box.org.json
  test/celeritas/data/lead-box.org.omn
  test/celeritas/global/AlongStep.test.cc
Labels: bug, field

#1097 Expand position check test and fix for other unit systems
  test/celeritas/global/AlongStep.test.cc
Labels: documentation, field

#1096 Prevent a PR with failed actions from being merged
  .github/workflows/pr.yml
Labels: documentation

#1093 Add bounding zone
  src/orange/BoundingBox.hh
  src/orange/CMakeLists.txt
  src/orange/Types.hh
  src/orange/orangeinp/detail/BoundingZone.cc
  src/orange/orangeinp/detail/BoundingZone.hh
  src/orange/surf/SurfaceClipper.cc
  src/orange/surf/SurfaceClipper.hh
  src/orange/surf/detail/SurfaceClipperImpl.cc
  src/orange/surf/detail/SurfaceClipperImpl.hh
  test/CMakeLists.txt
  test/orange/BoundingBox.test.cc
  test/orange/orangeinp/detail/BoundingZone.test.cc
  test/orange/surf/SurfaceClipper.test.cc
Labels: enhancement, orange

#1098 Fix non-sticky CMake options
  cmake/CeleritasUtils.cmake
Labels: core, minor

#1095 Refactor Geant4 utilities in preparation for g4vg
  src/celeritas/CMakeLists.txt
  src/celeritas/ext/GeantGeoParams.cc
  src/celeritas/ext/GeantGeoUtils.cc
  src/celeritas/ext/GeantGeoUtils.hh
  src/celeritas/ext/GeantImporter.cc
  src/celeritas/ext/GeantVolumeMapper.cc
  src/celeritas/ext/VisitGeantVolumes.hh
  src/celeritas/ext/detail/GeantVolumeVisitor.cc
  src/celeritas/ext/detail/GeantVolumeVisitor.hh
  src/celeritas/ext/g4vg/Converter.cc
  src/celeritas/ext/g4vg/LogicalVolumeConverter.cc
  test/CMakeLists.txt
  test/accel/detail/TouchableUpdater.test.cc
  test/celeritas/AllGeoTypedTestBase.hh
  test/celeritas/CheckedGeoTrackView.hh
  test/celeritas/CheckedGeoTrackView.t.hh
  test/celeritas/CoreGeoTestBase.hh
  test/celeritas/GenericGeoTestBase.cc
  test/celeritas/GenericGeoTestBase.hh
  test/celeritas/GenericGeoTestBase.t.hh
  test/celeritas/OrangeTestBase.cc
  test/celeritas/OrangeTestBase.hh
  test/celeritas/ext/GeantGeo.test.cc
  test/celeritas/ext/GeantGeoTestBase.cc
  test/celeritas/ext/GeantGeoTestBase.hh
  test/celeritas/ext/GeantGeoUtils.test.cc
  test/celeritas/ext/Vecgeom.test.cc
  test/celeritas/ext/VecgeomTestBase.cc
  test/celeritas/ext/VecgeomTestBase.hh
  test/celeritas/field/FieldPropagator.test.cc
  test/orange/OrangeGeoTestBase.hh
Labels: minor, external

#1101 Optimize log message code generation
  app/celer-g4/LocalLogger.cc
  app/celer-g4/LocalLogger.hh
  src/accel/Logger.cc
  src/corecel/io/Logger.cc
  src/corecel/io/Logger.hh
  src/corecel/io/LoggerTypes.hh
  src/corecel/io/detail/LoggerMessage.cc
  src/corecel/io/detail/LoggerMessage.hh
  test/corecel/ScopedLogStorer.cc
  test/corecel/ScopedLogStorer.hh
  test/corecel/io/Logger.test.cc
Labels: core, performance

#1100 Fix unit tests when using SI
  app/CMakeLists.txt
  app/demo-rasterizer/CMakeLists.txt
  app/demo-rasterizer/ImageIO.cc
  app/demo-rasterizer/RDemoKernel.hh
  app/demo-rasterizer/simple-driver.py
  scripts/cmake-presets/goldfinger.json
  src/celeritas/ext/GeantGeoTrackView.hh
  test/celeritas/Constants.test.cc
  test/celeritas/GenericGeoTestBase.t.hh
  test/celeritas/ext/GeantGeo.test.cc
  test/celeritas/global/AlongStep.test.cc
  test/celeritas/track/TrackSort.test.cc
Labels: documentation, external

#1102 Fix CMake for linking CUDA RDC for executables
  cmake/CeleritasLibrary.cmake
Labels: bug, core

#1105 Fix CTest names
  test/celeritas/CMakeLists.txt
  test/corecel/CMakeLists.txt
  test/orange/CMakeLists.txt
Labels: documentation, minor

#1106 Rename ORANGE construction files
  app/orange-update.cc
  doc/main/usage.rst
  src/orange/CMakeLists.txt
  src/orange/OrangeData.hh
  src/orange/OrangeInput.hh
  src/orange/OrangeInputIO.json.cc
  src/orange/OrangeInputIO.json.hh
  src/orange/OrangeParams.cc
  src/orange/OrangeParamsOutput.cc
  src/orange/detail/BIHData.hh
  src/orange/detail/BIHTraverser.hh
  src/orange/detail/DepthCalculator.cc
  src/orange/detail/DepthCalculator.hh
  src/orange/detail/OrangeInputIOImpl.json.cc
  src/orange/detail/OrangeInputIOImpl.json.hh
  src/orange/detail/RectArrayInserter.cc
  src/orange/detail/RectArrayInserter.hh
  src/orange/detail/TransformRecordInserter.hh
  src/orange/detail/UnitInserter.cc
  src/orange/detail/UnitInserter.hh
  src/orange/orangeinp/CsgTree.cc
  src/orange/orangeinp/CsgTree.hh
  src/orange/orangeinp/CsgTreeIO.json.cc
  src/orange/orangeinp/CsgTreeIO.json.hh
  src/orange/orangeinp/CsgTreeUtils.cc
  src/orange/orangeinp/CsgTreeUtils.hh
  src/orange/orangeinp/CsgTypes.cc
  src/orange/orangeinp/CsgTypes.hh
  src/orange/orangeinp/detail/CsgUnit.hh
  src/orange/orangeinp/detail/CsgUnitBuilder.cc
  src/orange/orangeinp/detail/CsgUnitBuilder.hh
  src/orange/orangeinp/detail/LocalSurfaceInserter.cc
  src/orange/orangeinp/detail/LocalSurfaceInserter.hh
  src/orange/orangeinp/detail/NodeReplacementInserter.hh
  src/orange/orangeinp/detail/NodeSimplifier.cc
  src/orange/orangeinp/detail/NodeSimplifier.hh
  src/orange/orangeinp/detail/PostfixLogicBuilder.hh
  test/celeritas/ext/GeantVolumeMapper.test.cc
  test/orange/CMakeLists.txt
  test/orange/Orange.test.cc
  test/orange/Orange.test.cu
  test/orange/OrangeGeoTestBase.cc
  test/orange/OrangeTestBase.cc
  test/orange/orangeinp/CsgTestUtils.cc
  test/orange/orangeinp/CsgTestUtils.hh
  test/orange/orangeinp/CsgTree.test.cc
  test/orange/orangeinp/CsgTreeUtils.test.cc
  test/orange/orangeinp/detail/CsgUnitBuilder.test.cc
  test/orange/orangeinp/detail/LocalSurfaceInserter.test.cc
  test/orange/surf/LocalSurfaceVisitor.test.cc
Labels: minor, orange

#1110 Add missing <algorithm> include needed in GCC 14
  src/celeritas/phys/PrimaryGeneratorOptions.hh
Labels: core, minor

#1109 Reduce number of Geant4 libraries linked in G4VG and elsewhere
  app/celer-g4/CMakeLists.txt
  cmake/CeleritasUtils.cmake
  src/accel/CMakeLists.txt
  src/celeritas/CMakeLists.txt
  src/geocel/CMakeLists.txt
  src/geocel/g4vg/SolidConverter.cc
Labels: enhancement, external

#1111 Release v0.4.2
  .github/pull_request_template.release.md
  doc/appendix/administration.rst
  doc/appendix/release-history/v0.4.rst
  src/celeritas/phys/PrimaryGeneratorOptions.hh
Labels: documentation

#1112 Add deduplicating transform inserter
  src/corecel/math/HashUtils.hh
  src/orange/CMakeLists.txt
  src/orange/orangeinp/detail/CsgUnit.hh
  src/orange/orangeinp/detail/TransformInserter.cc
  src/orange/orangeinp/detail/TransformInserter.hh
  src/orange/transform/NoTransformation.hh
  src/orange/transform/SignedPermutation.hh
  src/orange/transform/TransformHasher.cc
  src/orange/transform/TransformHasher.hh
  src/orange/transform/Transformation.hh
  src/orange/transform/Translation.hh
  src/orange/transform/VariantTransform.hh
  test/orange/CMakeLists.txt
  test/orange/orangeinp/detail/TransformInserter.test.cc
  test/orange/transform/VariantTransform.test.cc
Labels: enhancement, orange

#1116 Add Wentzel OK&VI transport cross section calculator
  src/celeritas/em/distribution/WentzelDistribution.hh
  src/celeritas/em/interactor/WentzelInteractor.hh
  src/celeritas/em/xs/WentzelHelper.hh
  src/celeritas/em/xs/WentzelTransportXsCalculator.hh
  test/celeritas/em/Wentzel.test.cc
Labels: enhancement, physics

#1118 Disable ROCm builds because of constant failures
  .jenkins
Labels: minor

#1117 Fix ORANGE namespaces
  .clang-format
  .git-blame-ignore-revs
  src/orange/OrangeParams.cc
  src/orange/OrangeTrackView.hh
  src/orange/detail/DepthCalculator.cc
  src/orange/detail/DepthCalculator.hh
  src/orange/detail/LevelStateAccessor.hh
  src/orange/orangeinp/CsgTree.cc
  src/orange/orangeinp/CsgTreeUtils.cc
  src/orange/orangeinp/detail/CsgUnitBuilder.hh
  src/orange/orangeinp/detail/LocalSurfaceInserter.cc
  src/orange/orangeinp/detail/LocalSurfaceInserter.hh
  src/orange/orangeinp/detail/NodeReplacementInserter.hh
  src/orange/orangeinp/detail/NodeSimplifier.cc
  src/orange/orangeinp/detail/NodeSimplifier.hh
  src/orange/orangeinp/detail/PostfixLogicBuilder.hh
  test/orange/orangeinp/detail/LocalSurfaceInserter.test.cc
  test/orange/univ/SimpleUnitTracker.test.cc
  test/orange/univ/SimpleUnitTracker.test.hh
Labels: minor, orange

#1113 Add convex surface builder
  src/orange/CMakeLists.txt
  src/orange/orangeinp/ConvexSurfaceBuilder.cc
  src/orange/orangeinp/ConvexSurfaceBuilder.hh
  src/orange/orangeinp/detail/BoundingZone.cc
  src/orange/orangeinp/detail/BoundingZone.hh
  src/orange/orangeinp/detail/ConvexSurfaceState.hh
  src/orange/orangeinp/detail/NegatedSurfaceClipper.hh
  src/orange/surf/FaceNamer.cc
  src/orange/surf/FaceNamer.hh
  src/orange/surf/RecursiveSimplifier.hh
  src/orange/surf/SimpleQuadric.hh
  src/orange/surf/SurfaceClipper.cc
  src/orange/surf/SurfaceClipper.hh
  src/orange/surf/detail/RecursiveSimplifierImpl.hh
  test/orange/CMakeLists.txt
  test/orange/orangeinp/ConvexSurfaceBuilder.test.cc
  test/orange/orangeinp/CsgTestUtils.cc
  test/orange/orangeinp/CsgTestUtils.hh
  test/orange/surf/FaceNamer.test.cc
  test/orange/surf/SurfaceClipper.test.cc
Labels: enhancement, orange

#1108 Add Cerenkov pre-generator
  src/celeritas/optical/CerenkovPreGenerator.hh
  src/celeritas/optical/OpticalDistributionData.hh
  test/celeritas/CMakeLists.txt
  test/celeritas/optical/Cerenkov.test.cc
  test/celeritas/optical/OpticalTestBase.cc
  test/celeritas/optical/OpticalTestBase.hh
Labels: enhancement, physics

#1124 Fix missing explicit instantiations in ORANGE CSB
  src/orange/orangeinp/ConvexSurfaceBuilder.cc
Labels: minor, orange

#1122 Workaround missing G4persistency target bug in Geant4 11.2
  cmake/CeleritasUtils.cmake
Labels: bug, external

#1123 Add compile-time consistency check for Celeritas and Geant4 versions
  src/geocel/GeantGeoUtils.cc
Labels: minor, external

#1121 Add infix string builder
  src/orange/orangeinp/CsgTreeUtils.cc
  src/orange/orangeinp/CsgTreeUtils.hh
  src/orange/orangeinp/detail/InfixStringBuilder.hh
  test/orange/orangeinp/CsgTreeUtils.test.cc
Labels: enhancement, orange

#1119 Implement convex regions
  src/orange/BoundingBoxUtils.hh
  src/orange/CMakeLists.txt
  src/orange/orangeinp/ConvexRegion.cc
  src/orange/orangeinp/ConvexRegion.hh
  src/orange/orangeinp/ConvexSurfaceBuilder.cc
  src/orange/orangeinp/ConvexSurfaceBuilder.hh
  src/orange/orangeinp/detail/ConvexSurfaceState.cc
  src/orange/orangeinp/detail/ConvexSurfaceState.hh
  src/orange/surf/SurfaceClipper.cc
  test/geocel/BoundingBox.test.cc
  test/orange/BoundingBoxUtils.test.cc
  test/orange/CMakeLists.txt
  test/orange/orangeinp/ConvexRegion.test.cc
  test/orange/orangeinp/CsgTestUtils.cc
  test/orange/orangeinp/detail/CsgUnitBuilder.test.cc
Labels: enhancement, orange

#1125 Implement second-order convex regions
  src/orange/MatrixUtils.hh
  src/orange/orangeinp/ConvexRegion.cc
  src/orange/orangeinp/ConvexRegion.hh
  src/orange/orangeinp/ConvexSurfaceBuilder.hh
  src/orange/surf/detail/QuadricConeConverter.hh
  src/orange/surf/detail/QuadricCylConverter.hh
  src/orange/surf/detail/QuadricSphereConverter.hh
  test/orange/orangeinp/ConvexRegion.test.cc
Labels: enhancement, orange

#1126 Add shape and volume builder
  scripts/user/orange-csg-to-dot.py
  src/orange/CMakeLists.txt
  src/orange/orangeinp/ConvexSurfaceBuilder.cc
  src/orange/orangeinp/CsgTree.cc
  src/orange/orangeinp/CsgTree.hh
  src/orange/orangeinp/ObjectInterface.hh
  src/orange/orangeinp/Shape.cc
  src/orange/orangeinp/Shape.hh
  src/orange/orangeinp/detail/CsgUnit.hh
  src/orange/orangeinp/detail/CsgUnitBuilder.cc
  src/orange/orangeinp/detail/CsgUnitBuilder.hh
  src/orange/orangeinp/detail/VolumeBuilder.cc
  src/orange/orangeinp/detail/VolumeBuilder.hh
  test/orange/CMakeLists.txt
  test/orange/orangeinp/ConvexRegion.test.cc
  test/orange/orangeinp/ConvexSurfaceBuilder.test.cc
  test/orange/orangeinp/CsgTestUtils.cc
  test/orange/orangeinp/CsgTree.test.cc
  test/orange/orangeinp/CsgTreeUtils.test.cc
  test/orange/orangeinp/Shape.test.cc
  test/orange/orangeinp/detail/CsgUnitBuilder.test.cc
Labels: enhancement, orange

#1127 Transform refactoring
  src/corecel/io/StreamableVariant.hh
  src/orange/orangeinp/ConvexSurfaceBuilder.cc
  src/orange/orangeinp/detail/CsgUnit.hh
  src/orange/orangeinp/detail/CsgUnitBuilder.cc
  src/orange/orangeinp/detail/CsgUnitBuilder.hh
  src/orange/orangeinp/detail/VolumeBuilder.cc
  src/orange/orangeinp/detail/VolumeBuilder.hh
  test/orange/CMakeLists.txt
  test/orange/orangeinp/ConvexRegion.test.cc
  test/orange/orangeinp/ConvexSurfaceBuilder.test.cc
  test/orange/orangeinp/CsgTestUtils.cc
  test/orange/orangeinp/CsgTestUtils.hh
  test/orange/orangeinp/ObjectTestBase.cc
  test/orange/orangeinp/ObjectTestBase.hh
  test/orange/orangeinp/Shape.test.cc
  test/orange/orangeinp/detail/CsgUnitBuilder.test.cc
Labels: minor, orange
