Repository celeritas-project/celeritas, pull requests merged in 2024-08, with the labels that each got.

#1352 Fix clang-tidy checks, including some use-after-move
  .clang-tidy
  src/accel/LocalTransporter.cc
  src/celeritas/global/Stepper.cc
  src/celeritas/global/Stepper.hh
  src/celeritas/grid/ValueGridBuilder.cc
  src/celeritas/io/detail/ImportDataConverter.cc
  src/corecel/io/OutputRegistry.cc
  src/geocel/ScopedGeantLogger.cc
  src/orange/orangeinp/Solid.cc
  src/orange/orangeinp/detail/ProtoBuilder.cc
  src/orange/orangeinp/detail/ProtoBuilder.hh
Labels: minor

#1350 Automatically build and deploy github documentation
  .github/workflows/deploy-pages.yml
  .github/workflows/doc.yml
  doc/appendix/administration.rst
  doc/appendix/development.rst
  doc/appendix/release-history/v0.1.rst
  doc/appendix/release-history/v0.2.rst
  doc/appendix/release-history/v0.3.rst
  doc/appendix/release-history/v0.4.rst
  doc/main/api/celeritas.rst
  src/celeritas/global/detail/ParamsTraits.hh
  src/celeritas/neutron/interactor/detail/CascadeCollider.hh
  src/celeritas/optical/detail/OpticalGenAlgorithms.cc
  src/celeritas/optical/detail/OpticalGenAlgorithms.cu
  src/orange/surf/Involute.cc
  src/orange/surf/Involute.hh
Labels: documentation

#1354 Refactor rejection sampling using a helper class
  .github/workflows/push.yml
  doc/main/api/celeritas.rst
  src/celeritas/em/distribution/BhabhaEnergyDistribution.hh
  src/celeritas/em/distribution/MollerEnergyDistribution.hh
  src/celeritas/em/distribution/MuBBEnergyDistribution.hh
  src/celeritas/em/distribution/SBEnergyDistribution.hh
  src/celeritas/em/distribution/WentzelDistribution.hh
  src/celeritas/em/interactor/BraggICRU73QOInteractor.hh
  src/celeritas/em/interactor/detail/RBEnergySampler.hh
  src/celeritas/em/interactor/detail/SBEnergySampler.hh
  src/celeritas/em/xs/WentzelHelper.hh
  src/celeritas/random/distribution/RejectionSampler.hh
  test/celeritas/CMakeLists.txt
  test/celeritas/em/CoulombScattering.test.cc
  test/celeritas/random/distribution/NormalDistribution.test.cc
  test/celeritas/random/distribution/RejectionSampler.test.cc
Labels: physics, minor

#1358 Add optical physics documentation
  doc/main/api/celeritas.rst
  src/celeritas/optical/CerenkovOffload.hh
  src/celeritas/optical/GeneratorDistributionData.hh
  src/celeritas/optical/ScintillationGenerator.hh
  src/celeritas/optical/ScintillationOffload.hh
  src/celeritas/optical/detail/OffloadGatherExecutor.hh
  src/celeritas/random/distribution/ExponentialDistribution.hh
Labels: documentation, physics

#1359 Automatically add Zotero publications to project site
  .github/workflows/deploy-pages.yml
  .github/workflows/doc.yml
Labels: documentation

#1361 Add Mermaid CSG tree output
  scripts/user/orange-csg-to-dot.py
Labels: documentation, orange

#1360 Add documentation for config options, improve unit docs, and use doxygen todos
  .github/workflows/deploy-pages.yml
  app/celer-g4/RootIO.cc
  app/celer-g4/RunAction.cc
  app/celer-geo/celer-geo.cc
  app/celer-sim/Runner.cc
  app/celer-sim/RunnerInput.hh
  doc/CMakeLists.txt
  doc/main/api/celeritas.rst
  doc/main/api/corecel.rst
  doc/main/installation.rst
  src/accel/LocalTransporter.cc
  src/accel/SetupOptionsMessenger.cc
  src/accel/detail/HitProcessor.cc
  src/celeritas/Constants.hh
  src/celeritas/Quantities.hh
  src/celeritas/UnitTypes.hh
  src/celeritas/Units.hh
  src/celeritas/em/distribution/WentzelDistribution.hh
  src/celeritas/em/interactor/BraggICRU73QOInteractor.hh
  src/celeritas/em/interactor/CoulombScatteringInteractor.hh
  src/celeritas/em/interactor/LivermorePEInteractor.hh
  src/celeritas/em/interactor/detail/SBPositronXsCorrector.hh
  src/celeritas/em/model/MollerBhabhaModel.cc
  src/celeritas/em/model/SeltzerBergerModel.cc
  src/celeritas/em/params/WentzelOKVIParams.cc
  src/celeritas/field/MakeMagFieldPropagator.hh
  src/celeritas/field/RZMapFieldInputIO.json.cc
  src/celeritas/neutron/interactor/ChipsNeutronElasticInteractor.hh
  src/celeritas/optical/Types.hh
  src/celeritas/phys/PDGNumber.hh
  src/celeritas/phys/PhysicsStepUtils.hh
  src/celeritas/random/Selector.hh
  src/celeritas/random/XorwowRngData.hh
  src/celeritas/random/XorwowRngParams.hh
  src/celeritas/track/ExtendFromSecondariesAction.cc
  src/celeritas/track/detail/ProcessSecondariesExecutor.hh
  src/celeritas/track/detail/StatusCheckExecutor.hh
  src/corecel/Constants.hh
  src/corecel/data/StackAllocator.hh
  src/corecel/sys/KernelRegistry.hh
  src/geocel/vg/VecgeomParams.cc
  src/orange/MatrixUtils.hh
  src/orange/OrangeData.hh
  src/orange/OrangeParamsOutput.cc
  src/orange/detail/BIHBuilder.cc
  src/orange/detail/TransformRecordInserter.hh
  src/orange/orangeinp/IntersectRegion.cc
  src/orange/orangeinp/PolySolid.cc
  src/orange/orangeinp/UnitProto.cc
  src/orange/orangeinp/detail/CsgUnitBuilder.cc
  src/orange/orangeinp/detail/NodeSimplifier.cc
  src/orange/orangeinp/detail/SenseEvaluator.cc
  src/orange/surf/SurfaceClipper.cc
  src/orange/surf/SurfaceSimplifier.cc
  src/orange/univ/SimpleUnitTracker.hh
  test/Test.hh
Labels: documentation

#1365 Add separate developer doc section to user manual
  app/celer-sim/Runner.cc
  doc/CMakeLists.txt
  doc/development/coding.rst
  doc/development/contributing.rst
  doc/development/style.rst
  doc/development/testing.rst
  doc/example/celer-g4.rst
  doc/example/celer-geo.rst
  doc/example/celer-sim.rst
  doc/example/geant4.rst
  doc/example/minimal.rst
  doc/implementation/optical-physics.rst
  doc/index.rst
  doc/introduction/usage/app.rst
  scripts/dev/celerlldb.py
  src/celeritas/io/ImportData.hh
  src/celeritas/io/ImportElement.hh
  src/celeritas/io/ImportMaterial.hh
  src/celeritas/io/ImportModel.hh
  src/celeritas/io/ImportParticle.hh
  src/celeritas/io/ImportProcess.hh
  src/celeritas/mat/IsotopeView.hh
  src/celeritas/mat/MaterialData.hh
  src/celeritas/mat/MaterialView.hh
  src/celeritas/optical/MaterialPropertyParams.hh
  src/celeritas/optical/OffloadData.hh
  src/celeritas/optical/OpticalCollector.hh
  src/celeritas/optical/TrackData.hh
  src/celeritas/optical/detail/OffloadGatherAction.hh
  src/celeritas/optical/detail/OffloadGatherExecutor.hh
  src/celeritas/random/distribution/RejectionSampler.hh
  test/Test.hh
Labels: documentation

#1367 Properly clear state counters and data for reuse
  app/celer-sim/Transporter.cc
  src/celeritas/CMakeLists.txt
  src/celeritas/global/CoreState.cc
  src/celeritas/global/CoreState.hh
  src/celeritas/global/CoreTrackData.cc
  src/celeritas/global/Stepper.hh
  src/celeritas/global/detail/TrackSlotUtils.cc
  src/celeritas/global/detail/TrackSlotUtils.cu
  src/celeritas/global/detail/TrackSlotUtils.hh
  src/celeritas/optical/TrackData.cc
  src/celeritas/track/SimData.hh
  src/celeritas/track/TrackInitData.hh
  src/celeritas/track/detail/TrackSortUtils.cc
  src/celeritas/track/detail/TrackSortUtils.cu
  src/celeritas/track/detail/TrackSortUtils.hh
  src/corecel/data/CollectionAlgorithms.hh
  test/celeritas/track/Sim.test.cc
  test/corecel/data/Collection.test.cc
Labels: bug, app

#1369 Fix initialization of geometry state when inserting multiple sets of primaries
  src/celeritas/track/ExtendFromPrimariesAction.cc
  src/celeritas/track/detail/InitTracksExecutor.hh
  src/corecel/data/detail/Filler.cu
  src/corecel/data/detail/Filler.hh
  test/celeritas/global/StepperGeant.test.cc
Labels: bug, physics

#1366 Accept single CsgTree from stdin
  scripts/user/orange-csg-to-dot.py
Labels: bug, minor

#1368 Add inverse helpers to generic calculator
  src/celeritas/em/data/LivermorePEData.hh
  src/celeritas/grid/GenericCalculator.hh
  src/celeritas/grid/GenericGridBuilder.hh
  src/celeritas/grid/GenericGridData.hh
  src/celeritas/grid/GenericGridInserter.hh
  src/celeritas/neutron/data/NeutronElasticData.hh
  src/celeritas/neutron/data/NeutronInelasticData.hh
  src/celeritas/neutron/xs/NeutronInelasticMicroXsCalculator.hh
  src/celeritas/neutron/xs/NucleonNucleonXsCalculator.hh
  src/celeritas/optical/CerenkovData.hh
  src/celeritas/optical/CerenkovDndxCalculator.hh
  src/celeritas/optical/MaterialPropertyData.hh
  src/celeritas/optical/ScintillationData.hh
  src/corecel/cont/detail/RangeImpl.hh
  src/corecel/data/Collection.hh
  src/corecel/grid/NonuniformGrid.hh
  test/celeritas/grid/GenericCalculator.test.cc
  test/celeritas/grid/GenericGridBuilder.test.cc
  test/celeritas/grid/GenericGridInserter.test.cc
  test/celeritas/neutron/NeutronInelastic.test.cc
  test/corecel/cont/Range.test.cc
Labels: enhancement, core

#1371 Allow normal distribution to preserve spare value
  src/celeritas/random/distribution/NormalDistribution.hh
  test/celeritas/random/distribution/NormalDistribution.test.cc
Labels: core, minor

#1370 Define optical MaterialView and rename MaterialParams
  app/celer-sim/Runner.cc
  scripts/cmake-presets/goldfinger.json
  src/celeritas/CMakeLists.txt
  src/celeritas/io/ImportData.hh
  src/celeritas/optical/CerenkovDndxCalculator.hh
  src/celeritas/optical/CerenkovGenerator.hh
  src/celeritas/optical/CerenkovOffload.hh
  src/celeritas/optical/CerenkovParams.cc
  src/celeritas/optical/CerenkovParams.hh
  src/celeritas/optical/MaterialData.hh
  src/celeritas/optical/MaterialParams.cc
  src/celeritas/optical/MaterialParams.hh
  src/celeritas/optical/MaterialView.hh
  src/celeritas/optical/OffloadData.hh
  src/celeritas/optical/OpticalCollector.cc
  src/celeritas/optical/OpticalCollector.hh
  src/celeritas/optical/ScintillationOffload.hh
  src/celeritas/optical/detail/CerenkovOffloadAction.cc
  src/celeritas/optical/detail/CerenkovOffloadAction.cu
  src/celeritas/optical/detail/CerenkovOffloadAction.hh
  src/celeritas/optical/detail/CerenkovOffloadExecutor.hh
  src/celeritas/optical/detail/OffloadGatherExecutor.hh
  test/celeritas/GlobalTestBase.hh
  test/celeritas/ImportedDataTestBase.cc
  test/celeritas/ImportedDataTestBase.hh
  test/celeritas/OnlyCoreTestBase.hh
  test/celeritas/optical/Cerenkov.test.cc
  test/celeritas/optical/OpticalCollector.test.cc
  test/celeritas/optical/Scintillation.test.cc
Labels: physics, minor

#1364 Improve sincospi availability and implementation
  CMakeLists.txt
  cmake/try-sincospi.cc
  doc/CMakeLists.txt
  src/CMakeLists.txt
  src/celeritas_cmake_strings.h
  src/celeritas_config.h.in
  src/celeritas_sys_config.h
  src/celeritas_version.h
  src/corecel/CMakeLists.txt
  src/corecel/Config.hh.in
  src/corecel/math/Algorithms.hh
  src/corecel/math/Turn.hh
  src/corecel/math/detail/MathImpl.hh
  src/corecel/math/detail/Sincospi.hh
Labels: enhancement, core

#1373 Sample cerenkov photons one at a time using rejection
  src/celeritas/optical/CerenkovGenerator.hh
  src/celeritas/optical/detail/OpticalUtils.hh
  test/DiagnosticRngEngine.hh
  test/celeritas/optical/Cerenkov.test.cc
  test/celeritas/optical/Scintillation.test.cc
Labels: physics, minor

#1362 Add oriented bounding zone class to be used for safety distance calculations
  src/orange/OrangeData.hh
  src/orange/detail/OrientedBoundingZone.hh
  test/orange/CMakeLists.txt
  test/orange/detail/OrientedBoundingZone.test.cc
Labels: enhancement, orange

#1317 Add optical absorption and Rayleigh interactors
  src/celeritas/optical/Interaction.hh
  src/celeritas/optical/TrackView.hh
  src/celeritas/optical/interactor/AbsorptionInteractor.hh
  src/celeritas/optical/interactor/RayleighInteractor.hh
  test/celeritas/CMakeLists.txt
  test/celeritas/optical/Absorption.test.cc
  test/celeritas/optical/InteractorHostTestBase.cc
  test/celeritas/optical/InteractorHostTestBase.hh
  test/celeritas/optical/Rayleigh.test.cc
Labels: enhancement, physics

#1377 Clear along-step action when track is marked as errored
  src/celeritas/global/CoreTrackView.hh
  src/celeritas/global/alongstep/detail/FluctELoss.hh
  src/celeritas/global/alongstep/detail/MeanELoss.hh
  src/celeritas/global/alongstep/detail/TimeUpdater.hh
  src/celeritas/global/alongstep/detail/TrackUpdater.hh
  src/corecel/io/LoggerTypes.hh
  test/celeritas/CMakeLists.txt
  test/celeritas/global/AlongStep.test.cc
  test/celeritas/global/StepperGeant.test.cc
  test/celeritas/global/StepperTestBase.cc
  test/geocel/data/lead-box.gdml
Labels: bug, physics

#1380 Replace SWIG with JSON (via ROOT export) for data exploration
  CMakeLists.txt
  CMakePresets.json
  app/celer-export-geant.cc
  cmake/CeleritasConfig.cmake.in
  doc/introduction/installation.rst
  doc/introduction/usage/app.rst
  interface/CMakeLists.txt
  interface/celeritas.i
  interface/detail/macros.i
  scripts/ci/spack.yaml
  scripts/cmake-presets/bede.json
  scripts/cmake-presets/ci-centos-rocm.json
  scripts/cmake-presets/ci-ubuntu-cuda.json
  scripts/cmake-presets/ci-ubuntu-github.json
  scripts/cmake-presets/ci-windows-github.json
  scripts/cmake-presets/esseivaj.json
  scripts/cmake-presets/exalearn4.json
  scripts/cmake-presets/frontier.json
  scripts/cmake-presets/gilgamesh.json
  scripts/cmake-presets/goldfinger.json
  scripts/cmake-presets/gondolin.json
  scripts/cmake-presets/omnia.json
  scripts/cmake-presets/perlmutter.json
  scripts/cmake-presets/stognini.json
  scripts/cmake-presets/voskhod.json
  scripts/cmake-presets/wildstyle.json
  scripts/cmake-presets/zeus.json
  scripts/dev/celeritas-gen.py
  scripts/docker/dev/jammy-cuda11.yaml
  scripts/docker/interactive/spack.yaml
  scripts/spack.yaml
  src/celeritas/CMakeLists.txt
  src/celeritas/ext/RootExporter.cc
  src/celeritas/ext/RootImporter.cc
  src/celeritas/ext/RootJsonDumper.cc
  src/celeritas/ext/RootJsonDumper.hh
  src/celeritas/io/ImportModel.hh
  src/celeritas/io/ImportOpticalMaterial.hh
  src/celeritas/io/ImportParameters.hh
  src/celeritas/phys/PDGNumber.hh
  src/corecel/Types.hh
  src/corecel/sys/Version.hh
  test/celeritas/CMakeLists.txt
  test/celeritas/ext/RootImporter.test.cc
  test/celeritas/ext/RootJsonDumper.test.cc
Labels: enhancement, core

#1322 Optimize track vector data layout for particle types
  src/celeritas/Types.cc
  src/celeritas/Types.hh
  src/celeritas/global/ActionLauncher.device.hh
  src/celeritas/global/CoreParams.cc
  src/celeritas/global/CoreTrackData.cc
  src/celeritas/random/distribution/InverseSquareDistribution.hh
  src/celeritas/random/distribution/RejectionSampler.hh
  src/celeritas/random/distribution/UniformRealDistribution.hh
  src/celeritas/track/InitializeTracksAction.cc
  src/celeritas/track/TrackInitData.hh
  src/celeritas/track/TrackInitParams.hh
  src/celeritas/track/detail/InitTracksExecutor.hh
  src/celeritas/track/detail/LocateAliveExecutor.hh
  src/celeritas/track/detail/ProcessSecondariesExecutor.hh
  src/celeritas/track/detail/TrackInitAlgorithms.cc
  src/celeritas/track/detail/TrackInitAlgorithms.cu
  src/celeritas/track/detail/TrackInitAlgorithms.hh
  src/celeritas/track/detail/Utils.hh
  test/celeritas/track/TrackSort.test.cc
Labels: physics, performance

#1379 Count number of optical primaries to be generated from distributions
  src/celeritas/optical/OffloadData.hh
  src/celeritas/optical/detail/CerenkovOffloadAction.cc
  src/celeritas/optical/detail/CerenkovOffloadAction.hh
  src/celeritas/optical/detail/OffloadGatherAction.hh
  src/celeritas/optical/detail/OpticalGenAlgorithms.cc
  src/celeritas/optical/detail/OpticalGenAlgorithms.cu
  src/celeritas/optical/detail/OpticalGenAlgorithms.hh
  src/celeritas/optical/detail/ScintOffloadAction.cc
  src/celeritas/optical/detail/ScintOffloadAction.hh
  test/celeritas/global/StepperGeant.test.cc
  test/celeritas/optical/OpticalCollector.test.cc
Labels: physics, minor

#1378 Add volume-to-material mapping and change import data
  app/celer-dump-data.cc
  app/celer-export-geant.cc
  app/celer-sim/Runner.cc
  doc/implementation/core-physics/import.rst
  doc/implementation/optical-physics.rst
  src/accel/SharedParams.cc
  src/celeritas/Types.hh
  src/celeritas/ext/GeantImporter.cc
  src/celeritas/ext/GeantImporter.hh
  src/celeritas/geo/GeoMaterialParams.hh
  src/celeritas/io/ImportData.hh
  src/celeritas/io/ImportElement.hh
  src/celeritas/io/ImportMaterial.hh
  src/celeritas/io/ImportOpticalMaterial.hh
  src/celeritas/io/ImportVolume.hh
  src/celeritas/io/detail/ImportDataConverter.cc
  src/celeritas/mat/MaterialData.hh
  src/celeritas/mat/MaterialParams.cc
  src/celeritas/mat/MaterialParams.hh
  src/celeritas/optical/MaterialData.hh
  src/celeritas/optical/MaterialParams.cc
  src/celeritas/optical/MaterialParams.hh
  src/celeritas/optical/MaterialView.hh
  src/celeritas/optical/ScintillationParams.cc
  src/celeritas/optical/Types.hh
  test/celeritas/CMakeLists.txt
  test/celeritas/ImportedDataTestBase.cc
  test/celeritas/ext/GeantImporter.test.cc
  test/celeritas/ext/RootJsonDumper.test.cc
  test/celeritas/mat/Material.test.cc
  test/celeritas/optical/Cerenkov.test.cc
Labels: enhancement, physics

#1381 Fix warnings on updated Cray/ROCm toolchain
  src/celeritas/random/CuHipRngData.hh
Labels: core, minor

#1289 Implement operation to simplify negated join on CsgTree
  src/orange/CMakeLists.txt
  src/orange/orangeinp/CsgTree.hh
  src/orange/orangeinp/CsgTreeIO.json.cc
  src/orange/orangeinp/CsgTreeUtils.cc
  src/orange/orangeinp/CsgTreeUtils.hh
  src/orange/orangeinp/UnitProto.cc
  src/orange/orangeinp/detail/CsgUnit.hh
  src/orange/orangeinp/detail/CsgUnitBuilder.cc
  src/orange/orangeinp/detail/DeMorganSimplifier.cc
  src/orange/orangeinp/detail/DeMorganSimplifier.hh
  test/orange/g4org/SolidConverter.test.cc
  test/orange/orangeinp/CsgTestUtils.cc
  test/orange/orangeinp/CsgTreeUtils.test.cc
Labels: enhancement, orange

#1383 Add always-on celer-sim diagnostic to count total number of tracks
  app/celer-sim/RunnerOutput.cc
  app/celer-sim/Transporter.cc
  app/celer-sim/Transporter.hh
  src/corecel/data/CollectionAlgorithms.hh
Labels: enhancement, app

#1382 Allow sim params without looping
  src/celeritas/global/CoreTrackData.cc
  src/celeritas/optical/TrackData.cc
  src/celeritas/optical/TrackData.hh
  src/celeritas/track/SimData.hh
  src/celeritas/track/SimParams.cc
  src/celeritas/track/SimParams.hh
  src/celeritas/track/SimTrackView.hh
  src/celeritas/track/TrackInitData.hh
  test/celeritas/em/MscTestBase.cc
  test/celeritas/optical/OpticalTestBase.cc
  test/celeritas/track/Sim.test.cc
Labels: physics, minor

#1384 Reduce default maximum substeps in field propagator
  src/celeritas/field/FieldDriverOptions.hh
  test/celeritas/field/FieldPropagator.test.cc
  test/celeritas/global/AlongStep.test.cc
  test/celeritas/track/Sim.test.cc
  test/celeritas/user/Diagnostic.test.cc
Labels: field, performance
