Repository celeritas-project/celeritas, pull requests merged in 2024-01, with the labels that each got.

#1081 Rename `GenericXsCalculator`
  src/celeritas/em/data/LivermorePEData.hh
  src/celeritas/em/interactor/LivermorePEInteractor.hh
  src/celeritas/em/xs/LivermorePEMicroXsCalculator.hh
  src/celeritas/grid/GenericCalculator.hh
  src/celeritas/grid/GenericGridData.hh
  src/celeritas/grid/ValueGridInserter.hh
  src/celeritas/grid/XsGridData.hh
  test/CMakeLists.txt
  test/celeritas/grid/GenericCalculator.test.cc
Labels: core, minor

#1082 Add algorithm for difference of squares and move `is_monotonic_increasing()` to utils
  src/celeritas/em/msc/detail/UrbanMscScatter.hh
  src/celeritas/grid/ValueGridBuilder.cc
  src/celeritas/grid/VectorUtils.cc
  src/celeritas/grid/VectorUtils.hh
  src/corecel/math/Algorithms.hh
  test/celeritas/grid/VectorUtils.test.cc
  test/corecel/math/Algorithms.test.cc
Labels: core, minor

#1080 Add Cerenkov distribution and generator
  src/celeritas/CMakeLists.txt
  src/celeritas/Types.hh
  src/celeritas/grid/GenericCalculator.hh
  src/celeritas/optical/CerenkovData.hh
  src/celeritas/optical/CerenkovDistributionData.hh
  src/celeritas/optical/CerenkovDndxCalculator.hh
  src/celeritas/optical/CerenkovGenerator.hh
  src/celeritas/optical/CerenkovParams.cc
  src/celeritas/optical/CerenkovParams.hh
  src/celeritas/optical/OpticalPrimary.hh
  src/celeritas/optical/OpticalPropertyData.hh
  test/CMakeLists.txt
  test/celeritas/optical/Cerenkov.test.cc
Labels: enhancement, physics

#1077 Add specialized "permutation" transform
  src/corecel/cont/EnumArray.hh
  src/corecel/math/Turn.hh
  src/orange/CMakeLists.txt
  src/orange/MatrixUtils.cc
  src/orange/transform/SignedPermutation.cc
  src/orange/transform/SignedPermutation.hh
  src/orange/transform/Transformation.hh
  test/CMakeLists.txt
  test/corecel/math/Quantity.test.cc
  test/orange/MatrixUtils.test.cc
  test/orange/transform/SignedPermutation.test.cc
Labels: enhancement, orange

#1089 Remove unused data from ImportElement/Material
  interface/celeritas.i
  src/celeritas/CMakeLists.txt
  src/celeritas/ext/GeantImporter.cc
  src/celeritas/io/ImportElement.hh
  src/celeritas/io/ImportMaterial.cc
  src/celeritas/io/ImportMaterial.hh
  test/celeritas/ext/GeantImporter.test.cc
Labels: minor, external

#1079 Add CSG unit and unit builder
  src/celeritas/Types.hh
  src/celeritas/mat/MaterialData.hh
  src/corecel/cont/VariantUtils.hh
  src/orange/CMakeLists.txt
  src/orange/Types.hh
  src/orange/orangeinp/detail/CsgUnit.hh
  src/orange/orangeinp/detail/CsgUnitBuilder.cc
  src/orange/orangeinp/detail/CsgUnitBuilder.hh
  src/orange/surf/LocalSurfaceVisitor.hh
  src/orange/transform/TransformIO.cc
  src/orange/transform/TransformIO.hh
  src/orange/transform/TransformVisitor.hh
  src/orange/univ/TrackerVisitor.hh
  test/CMakeLists.txt
  test/orange/CsgTestUtils.cc
  test/orange/CsgTestUtils.hh
  test/orange/construct/CsgTree.test.cc
  test/orange/orangeinp/detail/CsgUnitBuilder.test.cc
  test/orange/transform/Transformation.test.cc
  test/orange/transform/Translation.test.cc
Labels: enhancement, orange

#1042 Fix link errors in edge cases and restore HIP testing
  .jenkins
  CMakeLists.txt
  CMakePresets.json
  example/accel/CMakeLists.txt
  example/minimal/CMakeLists.txt
  scripts/cmake-presets/ci-ubuntu-cuda.json
  src/celeritas/CMakeLists.txt
Labels: core, minor

#1090 Change propagation fatal error to be recoverable
  src/celeritas/global/alongstep/detail/PropagationApplier.hh
Labels: bug, field

#1088 Define unit traits and support arbitrary RZ field map units
  src/celeritas/Types.cc
  src/celeritas/Types.hh
  src/celeritas/UnitTypes.hh
  src/celeritas/field/RZMapFieldInput.hh
  src/celeritas/field/RZMapFieldInputIO.json.cc
  src/celeritas/field/RZMapFieldParams.hh
  src/corecel/cont/Array.hh
  test/celeritas/UnitUtils.hh
  test/celeritas/Units.test.cc
  test/celeritas/field/Fields.test.cc
Labels: enhancement, field

#1086 Add ScintillationGenerator and related data structures
  src/celeritas/CMakeLists.txt
  src/celeritas/optical/CerenkovGenerator.hh
  src/celeritas/optical/OpticalDistributionData.hh
  src/celeritas/optical/OpticalPrimary.hh
  src/celeritas/optical/ScintillationData.hh
  src/celeritas/optical/ScintillationGenerator.hh
  src/celeritas/optical/ScintillationParams.cc
  src/celeritas/optical/ScintillationParams.hh
  test/CMakeLists.txt
  test/celeritas/optical/Cerenkov.test.cc
  test/celeritas/optical/ScintillationGenerator.test.cc
Labels: enhancement, physics

#1092 Add bounding box utilities for output and upcoming ORANGE work
  src/orange/BoundingBox.hh
  src/orange/BoundingBoxUtils.cc
  src/orange/BoundingBoxUtils.hh
  test/orange/BoundingBox.test.cc
  test/orange/BoundingBoxUtils.test.cc
Labels: enhancement, orange
