Repository celeritas-project/celeritas, pull requests merged in 2025-01, with the labels that each got.

#1557 Fix accel examples and related CI issues
  .clang-tidy
  .github/workflows/build-spack.yml
  .github/workflows/build-ultralite.yml
  .github/workflows/doc.yml
  doc/implementation/geant4-interface.rst
  example/accel/fastsim-offload.cc
  example/accel/simple-offload.cc
  example/accel/trackingmanager-offload.cc
  scripts/ci/test-examples.sh
  scripts/cmake-presets/ci-ubuntu-github.json
  src/celeritas/em/data/CommonCoulombData.hh
  src/celeritas/em/distribution/MuAngularDistribution.hh
  src/celeritas/em/distribution/WentzelDistribution.hh
  src/celeritas/em/xs/NuclearFormFactors.hh
  src/celeritas/em/xs/WentzelHelper.hh
  src/celeritas/random/RngReseed.cu
  src/celeritas/random/RngReseed.hh
  test/celeritas/global/AlongStepTestBase.hh
Labels: documentation

#1559 Prepare to update copyrights
  .git-blame-ignore-revs
  .github/pull_request_template.md
  COPYRIGHT
  scripts/dev/celeritas-gen.py
Labels: documentation

#1555 Update docker and Spack CI
  .github/workflows/build-docker.yml
  .github/workflows/build-spack.yml
  .github/workflows/build-ultralite.yml
  .github/workflows/clear-cache.yml
  .github/workflows/cron_weekly.yml
  .github/workflows/deploy-pages.yml
  .github/workflows/doc.yml
  .github/workflows/merge_group.yml
  .github/workflows/pull_request.yml
  .github/workflows/pull_request_completed.yml
  .github/workflows/push.yml
  .jenkins
  CMakePresets.json
  README.md
  scripts/ci/spack.yaml
  scripts/cmake-presets/ci-rocky-cuda.json
  scripts/cmake-presets/ci-ubuntu-github.json
  scripts/cmake-presets/ci-ubuntu-rocm.json
  scripts/cmake-presets/frontier.json
  scripts/docker/README.md
  scripts/docker/build.sh
  scripts/docker/ci/Dockerfile
  scripts/docker/dev/Dockerfile
  scripts/docker/dev/bionic-minimal.yaml
  scripts/docker/dev/centos7-rocm5.yaml
  scripts/docker/dev/rocky-cuda12.yaml
  scripts/docker/dev/ubuntu-rocm6.yaml
  scripts/spack.yaml
  test/celeritas/geo/Geometry.test.cc
  test/geocel/CMakeLists.txt
  test/geocel/vg/Vecgeom.test.cc
Labels: documentation

#1561 Enable more dependencies in clang-tidy checks
  .clang-tidy
  .github/workflows/build-spack.yml
  app/celer-g4/RootIO.cc
  scripts/cmake-presets/ci-ubuntu-github.json
  src/celeritas/alongstep/detail/PropagationApplier.hh
  src/celeritas/ext/detail/CelerOpticalPhysics.cc
  src/celeritas/user/SlotDiagnostic.cc
  src/corecel/cont/EnumArray.hh
  src/corecel/cont/Span.hh
  src/corecel/data/Collection.hh
  src/corecel/data/CollectionStateStore.hh
  src/corecel/data/ParamsDataInterface.hh
  src/corecel/io/StringEnumMapper.hh
  src/corecel/sys/ScopedMem.cc
  src/corecel/sys/ScopedMpiInit.cc
  src/corecel/sys/ScopedMpiInit.hh
  src/geocel/rasterize/RaytraceImager.hh
  src/orange/orangeinp/InputBuilder.cc
  src/orange/surf/GeneralQuadric.cc
  src/orange/surf/SimpleQuadric.cc
Labels: documentation

#1550 Reduce `celer-sim` memory usage and improve its `CELER_LOG` transport output
  app/celer-sim/Runner.cc
  app/celer-sim/RunnerInput.hh
  app/celer-sim/RunnerInputIO.json.cc
  app/celer-sim/Transporter.cc
  app/celer-sim/Transporter.hh
  app/celer-sim/celer-sim.cc
Labels: enhancement, app

#1539 Lazily evaluate senses
  src/corecel/math/Algorithms.hh
  src/orange/OrangeData.hh
  src/orange/OrangeTrackView.hh
  src/orange/OrangeTypes.cc
  src/orange/OrangeTypes.hh
  src/orange/SenseUtils.hh
  src/orange/orangeinp/detail/InfixStringBuilder.hh
  src/orange/surf/ConeAligned.hh
  src/orange/surf/CylAligned.hh
  src/orange/surf/CylCentered.hh
  src/orange/surf/GeneralQuadric.hh
  src/orange/surf/Plane.hh
  src/orange/surf/PlaneAligned.hh
  src/orange/surf/SimpleQuadric.hh
  src/orange/surf/Sphere.hh
  src/orange/surf/SphereCentered.hh
  src/orange/univ/SimpleUnitTracker.hh
  src/orange/univ/detail/InfixEvaluator.hh
  src/orange/univ/detail/LazySenseCalculator.hh
  src/orange/univ/detail/LogicEvaluator.hh
  src/orange/univ/detail/SenseCalculator.hh
  src/orange/univ/detail/Types.hh
  test/orange/OrangeGeoTestBase.cc
  test/orange/OrangeGeoTestBase.hh
  test/orange/surf/LocalSurfaceVisitor.test.hh
  test/orange/univ/RectArrayTracker.test.cc
  test/orange/univ/SimpleUnitTracker.test.cc
  test/orange/univ/SimpleUnitTracker.test.hh
  test/orange/univ/TrackerVisitor.test.cc
  test/orange/univ/detail/LogicEvaluator.test.cc
  test/orange/univ/detail/SenseCalculator.test.cc
Labels: enhancement, orange

#1530 Support building infix logic representation
  src/orange/CMakeLists.txt
  src/orange/orangeinp/UnitProto.cc
  src/orange/orangeinp/detail/BuildLogicUtils.hh
  src/orange/orangeinp/detail/PostfixLogicBuilder.cc
  src/orange/orangeinp/detail/PostfixLogicBuilder.hh
  test/orange/orangeinp/CsgTreeUtils.test.cc
Labels: enhancement, orange

#1563 Update CMake policy
  CMakeLists.txt
  README.md
  test/celeritas/CMakeLists.txt
Labels: documentation

#1564 Add 'LogicalTrue' functor
  src/celeritas/ext/detail/GeantOpticalModelImporter.cc
  src/celeritas/ext/detail/GeantProcessImporter.cc
  src/celeritas/optical/MaterialParams.cc
  src/celeritas/phys/ImportedProcessAdapter.cc
  src/celeritas/phys/PhysicsParams.cc
  src/celeritas/phys/PrimaryGeneratorOptions.hh
  src/celeritas/user/StepCollector.cc
  src/corecel/math/Algorithms.hh
  src/geocel/GeantGeoUtils.cc
  src/orange/detail/UnitInserter.cc
  src/orange/orangeinp/CsgObject.cc
  src/orange/orangeinp/UnitProto.cc
  test/corecel/math/Algorithms.test.cc
Labels: core, minor

#1567 Fix Doxygen member group formatting
  app/celer-g4/TimerOutput.hh
  src/accel/GeantSimpleCalo.hh
  src/accel/GeantStepDiagnostic.hh
  src/accel/SetupOptions.hh
  src/celeritas/ext/GeantOpticalPhysicsOptions.hh
  src/celeritas/ext/GeantPhysicsOptions.hh
  src/celeritas/global/KernelContextException.hh
  src/celeritas/io/ImportElement.hh
  src/celeritas/mat/MaterialParams.hh
  src/celeritas/optical/CoreParams.hh
  src/celeritas/optical/detail/OffloadParams.hh
  src/celeritas/optical/detail/OpticalLaunchAction.hh
  src/celeritas/track/ExtendFromPrimariesAction.hh
  src/celeritas/track/ExtendFromSecondariesAction.hh
  src/celeritas/track/StatusChecker.hh
  src/celeritas/user/ActionDiagnostic.hh
  src/celeritas/user/SimpleCalo.hh
  src/celeritas/user/SlotDiagnostic.hh
  src/celeritas/user/StepDiagnostic.hh
  src/celeritas/user/detail/StepParams.hh
  src/corecel/cont/Array.hh
  src/orange/orangeinp/IntersectSurfaceBuilder.hh
  src/orange/orangeinp/detail/BuildLogicUtils.hh
  src/orange/orangeinp/detail/InfixStringBuilder.hh
  src/orange/orangeinp/detail/InternalSurfaceFlagger.hh
  src/orange/orangeinp/detail/IntersectSurfaceState.hh
  src/orange/orangeinp/detail/SenseEvaluator.hh
  src/orange/surf/detail/InvolutePoint.hh
Labels: documentation

#1568 Fix unnecessary use of inline constexpr
  src/accel/SetupOptionsMessenger.cc
  src/celeritas/field/FieldDriverOptions.hh
  src/celeritas/io/ImportMaterial.hh
  src/celeritas/io/ImportVolume.hh
  src/celeritas/track/StatusCheckData.hh
  src/celeritas/user/RootStepWriter.hh
  src/corecel/cont/InitializedValue.hh
  src/corecel/data/Collection.hh
  src/corecel/math/BisectionRootFinder.hh
  src/corecel/math/IllinoisRootFinder.hh
  src/corecel/math/RegulaFalsiRootFinder.hh
  src/corecel/sys/TracingSession.hh
  src/geocel/GeoTraits.hh
  src/geocel/g4/GeantGeoTraits.hh
  src/geocel/vg/VecgeomGeoTraits.hh
  src/orange/OrangeData.hh
  src/orange/OrangeGeoTraits.hh
  test/orange/surf/FaceNamer.test.cc
Labels: core, minor

#1486 Replace "volid" with "vol_id" throughout ORANGE
  src/orange/OrangeData.hh
  src/orange/OrangeInput.hh
  src/orange/OrangeInputIO.json.cc
  src/orange/OrangeTrackView.hh
  src/orange/OrangeTypes.hh
  src/orange/detail/BIHBuilder.cc
  src/orange/detail/BIHData.hh
  src/orange/detail/BIHEnclosingVolFinder.hh
  src/orange/detail/BIHIntersectingVolFinder.hh
  src/orange/detail/BIHView.hh
  src/orange/detail/DepthCalculator.cc
  src/orange/detail/DepthCalculator.hh
  src/orange/detail/OrientedBoundingZone.hh
  src/orange/detail/RectArrayInserter.cc
  src/orange/detail/UnitInserter.cc
  src/orange/orangeinp/CsgTreeIO.json.cc
  src/orange/orangeinp/InputBuilder.cc
  src/orange/orangeinp/UnitProto.cc
  src/orange/orangeinp/detail/CsgUnit.hh
  src/orange/orangeinp/detail/CsgUnitBuilder.cc
  src/orange/orangeinp/detail/ProtoBuilder.cc
  src/orange/orangeinp/detail/ProtoBuilder.hh
  src/orange/orangeinp/detail/ProtoMap.cc
  src/orange/orangeinp/detail/ProtoMap.hh
  src/orange/transform/TransformVisitor.hh
  src/orange/univ/RectArrayTracker.hh
  src/orange/univ/SimpleUnitTracker.hh
  src/orange/univ/TrackerVisitor.hh
  test/orange/Orange.test.cc
  test/orange/OrangeGeoTestBase.cc
  test/orange/OrangeGeoTestBase.hh
  test/orange/detail/BIHBuilder.test.cc
  test/orange/detail/BIHEnclosingVolFinder.test.cc
  test/orange/orangeinp/CsgTestUtils.cc
  test/orange/univ/RectArrayTracker.test.cc
Labels: minor, orange

#1558 Add support for Geant4 navigator through offload interface
  .github/workflows/build-spack.yml
  app/celer-g4/CMakeLists.txt
  src/accel/LocalTransporter.cc
  src/accel/detail/HitManager.cc
Labels: enhancement, external

#1580 Hotfix: fetch tags manually to fix CI
  .github/workflows/build-docker.yml
  .github/workflows/build-spack.yml
Labels: documentation

#1581 Import and use muon+hadron EM physics parameters
  app/celer-dump-data.cc
  app/celer-sim/Runner.cc
  src/accel/SharedParams.cc
  src/celeritas/alongstep/detail/ElossApplier.hh
  src/celeritas/alongstep/detail/FluctELoss.hh
  src/celeritas/alongstep/detail/MeanELoss.hh
  src/celeritas/em/msc/UrbanMsc.hh
  src/celeritas/em/msc/detail/UrbanMscMinimalStepLimit.hh
  src/celeritas/em/msc/detail/UrbanMscSafetyStepLimit.hh
  src/celeritas/ext/GeantImporter.cc
  src/celeritas/ext/GeantPhysicsOptions.hh
  src/celeritas/ext/GeantPhysicsOptionsIO.json.cc
  src/celeritas/ext/detail/CelerEmStandardPhysics.cc
  src/celeritas/global/CoreTrackView.hh
  src/celeritas/io/ImportParameters.hh
  src/celeritas/phys/ParticleTrackView.hh
  src/celeritas/phys/PhysicsData.hh
  src/celeritas/phys/PhysicsParams.cc
  src/celeritas/phys/PhysicsParams.hh
  src/celeritas/phys/PhysicsParamsOutput.cc
  src/celeritas/phys/PhysicsTrackView.hh
  src/celeritas/track/detail/ProcessSecondariesExecutor.hh
  test/celeritas/data/four-steel-slabs.root
  test/celeritas/em/MscTestBase.cc
  test/celeritas/em/UrbanMsc.test.cc
  test/celeritas/ext/GeantImporter.test.cc
  test/celeritas/ext/RootJsonDumper.test.cc
  test/celeritas/phys/Particle.test.cc
  test/celeritas/phys/Physics.test.cc
  test/celeritas/phys/Physics.test.cu
  test/celeritas/phys/Physics.test.hh
  test/celeritas/phys/PhysicsStepUtils.test.cc
Labels: enhancement, physics

#1587 Update Perlmutter env
  scripts/cmake-presets/perlmutter.json
  scripts/env/perlmutter.sh
Labels: documentation, minor

#1585 Add ARM runner to CI
  .github/workflows/build-fast.yml
  README.md
Labels: documentation

#1578 Require less ancient CUDA architecture and OpenMP implementation
  CMakeLists.txt
  app/celer-sim/celer-sim.cc
  cmake/CeleritasOptionUtils.cmake
  scripts/cmake-presets/ci-windows-github.json
  src/corecel/math/Atomics.hh
Labels: core, removal

#1575 Propagate code citations into user manual
  CONTRIBUTING.rst
  doc/CMakeLists.txt
  doc/_static/celeritas.bib
  doc/_static/references.bib
  doc/_static/zotero.bib
  doc/backmatter/references.rst
  doc/conf.py
  doc/development/administration.rst
  doc/development/coding.rst
  doc/implementation/core-physics/rng.rst
  doc/implementation/core-physics/stepping.rst
  doc/implementation/em-physics.rst
  doc/implementation/units-constants.rst
  doc/index.rst
  scripts/dev/better-bibtex-prefs.json
  src/celeritas/Constants.hh
  src/celeritas/em/data/WentzelOKVIData.hh
  src/celeritas/em/distribution/EnergyLossHelper.hh
  src/celeritas/em/distribution/SBEnergyDistribution.hh
  src/celeritas/em/distribution/TsaiUrbanDistribution.hh
  src/celeritas/em/distribution/WentzelDistribution.hh
  src/celeritas/em/interactor/SeltzerBergerInteractor.hh
  src/celeritas/em/interactor/detail/PhysicsConstants.hh
  src/celeritas/em/xs/MottRatioCalculator.hh
  src/celeritas/em/xs/NuclearFormFactors.hh
  src/celeritas/em/xs/WentzelHelper.hh
  src/celeritas/neutron/interactor/detail/MomentumTransferSampler.hh
  src/celeritas/neutron/model/NeutronInelasticModel.cc
  src/celeritas/neutron/model/NeutronInelasticModel.hh
  src/celeritas/optical/action/detail/TrackInitAlgorithms.cc
  src/celeritas/phys/PDGNumber.hh
  src/celeritas/phys/PhysicsStepUtils.hh
  src/celeritas/random/XorwowRngEngine.hh
  src/celeritas/random/distribution/GammaDistribution.hh
  src/orange/detail/BIHBuilder.hh
Labels: documentation

#1574 Extend Coulomb scattering to support additional particle types
  app/celer-sim/Runner.cc
  src/accel/SharedParams.cc
  src/celeritas/em/data/CommonCoulombData.hh
  src/celeritas/em/data/UrbanMscData.hh
  src/celeritas/em/data/WentzelOKVIData.hh
  src/celeritas/em/data/WentzelVIMscData.hh
  src/celeritas/em/msc/UrbanMsc.hh
  src/celeritas/em/msc/detail/UrbanMscHelper.hh
  src/celeritas/em/msc/detail/UrbanMscSafetyStepLimit.hh
  src/celeritas/em/msc/detail/UrbanMscScatter.hh
  src/celeritas/em/params/UrbanMscParams.cc
  src/celeritas/em/params/WentzelOKVIParams.cc
  src/celeritas/em/params/WentzelOKVIParams.hh
  src/celeritas/em/params/WentzelVIMscParams.cc
  src/celeritas/em/params/detail/MscParamsHelper.cc
  src/celeritas/em/params/detail/MscParamsHelper.hh
  src/celeritas/em/xs/WentzelHelper.hh
  src/celeritas/ext/GeantPhysicsOptions.hh
  src/celeritas/ext/GeantPhysicsOptionsIO.json.cc
  src/celeritas/ext/detail/CelerEmStandardPhysics.cc
  test/celeritas/ImportedDataTestBase.cc
  test/celeritas/SimpleTestBase.cc
  test/celeritas/data/four-steel-slabs.root
  test/celeritas/data/lar-sphere.geant.json
  test/celeritas/em/CoulombScattering.test.cc
  test/celeritas/em/UrbanMsc.test.cc
  test/celeritas/em/WentzelVIMsc.test.cc
  test/celeritas/ext/GeantImporter.test.cc
Labels: enhancement, physics

#1576 Use lazy sense calculator
  src/orange/univ/SimpleUnitTracker.hh
  src/orange/univ/detail/LazySenseCalculator.hh
  test/orange/univ/detail/SenseCalculator.test.cc
Labels: orange, performance

#1577 Release v0.5.1
  CMakeLists.txt
  doc/appendix/release-history/v0.5.rst
  doc/conf.py
  doc/config.json.in
Labels: documentation

#1588 Improve and fix documentation
  doc/CMakeLists.txt
  doc/_static/macros.tex
  doc/_static/zotero.bib
  doc/implementation/core-physics/diagnostics.rst
  doc/implementation/corecel.rst
  doc/implementation/data-model.rst
  doc/implementation/orange.rst
  doc/implementation/units-constants.rst
  doc/index.rst
  doc/introduction/overview.rst
  doc/introduction/usage.rst
  doc/introduction/usage/app.rst
  doc/usage/execution.rst
  doc/usage/execution/applications.rst
  doc/usage/execution/environment.rst
  doc/usage/execution/profiling.rst
  doc/usage/execution/utilities.rst
  doc/usage/installation.rst
  doc/usage/integration.rst
  scripts/README.md
  src/celeritas/Constants.hh
  src/celeritas/Quantities.hh
  src/celeritas/Units.hh
  src/celeritas/mat/MaterialParams.hh
  src/celeritas/phys/PDGNumber.hh
  src/celeritas/phys/ParticleParams.hh
  src/celeritas/phys/PhysicsParams.hh
  src/corecel/Assert.hh
  src/corecel/OpaqueId.hh
  src/corecel/Types.hh
  src/corecel/cont/Span.hh
  src/corecel/data/AuxInterface.hh
  src/corecel/data/AuxParamsRegistry.hh
  src/corecel/data/AuxStateData.hh
  src/corecel/data/Collection.hh
  src/corecel/math/Algorithms.hh
  src/corecel/math/ArraySoftUnit.hh
  src/corecel/math/ArrayUtils.hh
  src/corecel/math/NumericLimits.hh
  src/corecel/math/Quantity.hh
  src/corecel/math/SoftEqual.hh
  src/orange/OrangeTrackView.hh
  src/orange/orangeinp/CsgObject.cc
  src/orange/orangeinp/IntersectRegion.hh
Labels: documentation

#1589 Improve diagnostic output when offloading
  src/accel/LocalTransporter.cc
  src/accel/LocalTransporter.hh
  src/accel/SetupOptions.hh
  src/accel/SharedParams.cc
  src/accel/SimpleOffload.cc
Labels: enhancement, external

#1520 Add optical model importer and refactor imported optical materials
  src/celeritas/CMakeLists.txt
  src/celeritas/optical/ImportedMaterials.cc
  src/celeritas/optical/ImportedMaterials.hh
  src/celeritas/optical/MaterialData.hh
  src/celeritas/optical/MaterialParams.cc
  src/celeritas/optical/MaterialParams.hh
  src/celeritas/optical/MaterialView.hh
  src/celeritas/optical/ModelImporter.cc
  src/celeritas/optical/ModelImporter.hh
  src/celeritas/optical/Types.hh
  src/celeritas/optical/model/AbsorptionModel.cc
  src/celeritas/optical/model/AbsorptionModel.hh
  src/celeritas/optical/model/RayleighModel.cc
  src/celeritas/optical/model/RayleighModel.hh
  test/celeritas/CMakeLists.txt
  test/celeritas/optical/Cherenkov.test.cc
  test/celeritas/optical/ImportedMaterials.test.cc
  test/celeritas/optical/ImportedModelAdapter.test.cc
  test/celeritas/optical/ModelImporter.test.cc
  test/celeritas/optical/OpticalMockTestBase.cc
  test/celeritas/optical/OpticalRootImport.test.cc
  test/celeritas/optical/Rayleigh.test.cc
  test/celeritas/optical/RayleighMfpCalculator.test.cc
Labels: enhancement, physics

#1573 Add example offloading template
  .github/workflows/build-spack.yml
  CMakeLists.txt
  doc/example/geant4.rst
  example/offload-template/.gitignore
  example/offload-template/CMakeLists.txt
  example/offload-template/README.rst
  example/offload-template/main.cc
  example/offload-template/src/ActionInitialization.cc
  example/offload-template/src/ActionInitialization.hh
  example/offload-template/src/Celeritas.cc
  example/offload-template/src/Celeritas.hh
  example/offload-template/src/DetectorConstruction.cc
  example/offload-template/src/DetectorConstruction.hh
  example/offload-template/src/EventAction.cc
  example/offload-template/src/EventAction.hh
  example/offload-template/src/PrimaryGeneratorAction.cc
  example/offload-template/src/PrimaryGeneratorAction.hh
  example/offload-template/src/RunAction.cc
  example/offload-template/src/RunAction.hh
  example/offload-template/src/SensitiveDetector.cc
  example/offload-template/src/SensitiveDetector.hh
  scripts/ci/test-examples.sh
Labels: documentation

#1591 Output diagnostic information about core sizes
  app/celer-sim/Runner.cc
  app/celer-sim/Transporter.cc
  app/celer-sim/Transporter.hh
  src/accel/LocalTransporter.cc
  src/accel/SharedParams.cc
  src/celeritas/global/CoreParams.cc
  src/celeritas/global/CoreParams.hh
  src/celeritas/global/CoreState.cc
  src/celeritas/global/CoreState.hh
  src/celeritas/global/Stepper.cc
  src/celeritas/global/Stepper.hh
  src/celeritas/global/detail/CoreSizes.json.hh
  src/celeritas/optical/Model.hh
  src/celeritas/optical/ModelImporter.hh
  src/celeritas/optical/Types.hh
  src/celeritas/optical/model/AbsorptionModel.cc
  src/celeritas/optical/model/RayleighModel.cc
Labels: enhancement, app

#1593 Change PrimaryGeneratorAction to be a wrapper
  app/celer-g4/ActionInitialization.cc
  app/celer-g4/PGPrimaryGeneratorAction.cc
  app/celer-g4/PGPrimaryGeneratorAction.hh
  src/celeritas/ext/GeantImporter.cc
  src/celeritas/ext/GeantImporter.hh
  src/celeritas/phys/ParticleParams.cc
  src/celeritas/phys/ParticleParams.hh
  src/celeritas/phys/PrimaryGenerator.cc
  src/celeritas/phys/PrimaryGenerator.hh
Labels: minor, app

#1590 Simplify and add to system config diagnostics
  src/corecel/CMakeLists.txt
  src/corecel/io/BuildOutput.cc
  src/corecel/io/StringUtils.cc
  src/corecel/io/StringUtils.hh
  test/corecel/io/StringUtils.test.cc
Labels: enhancement, core

#1595 Set step length and other data in reconstructed tracks
  src/accel/SetupOptions.cc
  src/accel/SetupOptions.hh
  src/accel/detail/HitManager.cc
  src/accel/detail/HitProcessor.cc
  src/celeritas/inp/Scoring.hh
  test/accel/SimpleSensitiveDetector.cc
  test/accel/SimpleSensitiveDetector.hh
  test/accel/detail/HitProcessor.test.cc
Labels: bug, external

#1583 Refactor primary generator using new `inp`
  app/celer-g4/ActionInitialization.cc
  app/celer-g4/PGPrimaryGeneratorAction.cc
  app/celer-g4/PGPrimaryGeneratorAction.hh
  src/celeritas/phys/PrimaryGenerator.cc
  src/celeritas/phys/PrimaryGenerator.hh
  src/celeritas/phys/PrimaryGeneratorOptions.cc
  src/celeritas/phys/PrimaryGeneratorOptions.hh
  test/celeritas/phys/PrimaryGenerator.test.cc
Labels: physics, minor

#1596 Add hit manager output diagnostic
  src/accel/CMakeLists.txt
  src/accel/SharedParams.cc
  src/accel/detail/HitManager.hh
  src/accel/detail/HitManagerOutput.cc
  src/accel/detail/HitManagerOutput.hh
  src/accel/detail/SensDetInserter.cc
  test/accel/detail/HitManager.test.cc
Labels: enhancement

#1598 Update core advisors
  .github/workflows/doc.yml
  doc/_static/ornltm-header-celeritas.tex
  doc/conf.py
  doc/development/administration.rst
Labels: documentation

#1592 Always select at-rest process for stopped tracks
  src/celeritas/alongstep/detail/ElossApplier.hh
  src/celeritas/alongstep/detail/PropagationApplier.hh
  src/celeritas/em/process/BremsstrahlungProcess.hh
  src/celeritas/em/process/ComptonProcess.hh
  src/celeritas/em/process/CoulombScatteringProcess.hh
  src/celeritas/em/process/EIonizationProcess.hh
  src/celeritas/em/process/EPlusAnnihilationProcess.cc
  src/celeritas/em/process/EPlusAnnihilationProcess.hh
  src/celeritas/em/process/GammaConversionProcess.hh
  src/celeritas/em/process/MuBremsstrahlungProcess.hh
  src/celeritas/em/process/MuIonizationProcess.hh
  src/celeritas/em/process/MuPairProductionProcess.hh
  src/celeritas/em/process/PhotoelectricProcess.hh
  src/celeritas/em/process/RayleighProcess.hh
  src/celeritas/ext/detail/GeantProcessImporter.cc
  src/celeritas/io/ImportProcess.hh
  src/celeritas/neutron/process/NeutronElasticProcess.hh
  src/celeritas/neutron/process/NeutronInelasticProcess.hh
  src/celeritas/phys/ImportedProcessAdapter.hh
  src/celeritas/phys/PhysicsData.hh
  src/celeritas/phys/PhysicsParams.cc
  src/celeritas/phys/PhysicsStepUtils.hh
  src/celeritas/phys/PhysicsTrackView.hh
  src/celeritas/phys/Process.hh
  src/celeritas/phys/ProcessBuilder.cc
  test/celeritas/MockTestBase.cc
  test/celeritas/data/four-steel-slabs.root
  test/celeritas/ext/GeantImporter.test.cc
  test/celeritas/ext/RootJsonDumper.test.cc
  test/celeritas/global/AlongStep.test.cc
  test/celeritas/global/StepperGeant.test.cc
  test/celeritas/optical/OpticalCollector.test.cc
  test/celeritas/phys/MockProcess.cc
  test/celeritas/phys/MockProcess.hh
  test/celeritas/phys/Physics.test.cc
  test/celeritas/track/TrackSort.test.cc
  test/celeritas/user/Diagnostic.test.cc
  test/celeritas/user/SlotDiagnostic.test.cc
Labels: enhancement, physics, performance

#1582 Add postfix to infix conversion utility
  src/orange/CMakeLists.txt
  src/orange/OrangeInputIO.json.cc
  src/orange/OrangeTypes.hh
  src/orange/detail/LogicUtils.cc
  src/orange/detail/LogicUtils.hh
  src/orange/detail/OrangeInputIOImpl.json.cc
  src/orange/orangeinp/UnitProto.cc
  src/orange/orangeinp/detail/CsgLogicUtils.hh
  test/orange/CMakeLists.txt
  test/orange/detail/LogicUtils.test.cc
  test/orange/orangeinp/CsgTreeUtils.test.cc
Labels: minor, orange

#1597 Write out optical size diagnostic
  app/celer-export-geant.cc
  app/celer-sim/CMakeLists.txt
  app/celer-sim/RunnerInput.hh
  app/celer-sim/RunnerInputIO.json.cc
  app/celer-sim/simple-driver.py
  app/data/gamma-4evt-15prim.hepmc3
  src/accel/detail/HitManagerOutput.cc
  src/celeritas/Types.cc
  src/celeritas/global/CoreParams.cc
  src/celeritas/optical/TrackInitParams.hh
  src/celeritas/optical/detail/OpticalLaunchAction.cc
  src/celeritas/optical/detail/OpticalLaunchAction.hh
  src/celeritas/optical/detail/OpticalSizes.json.hh
Labels: enhancement, app

#1603 Move physics lists out of details and rename tracking offload
  app/celer-g4/celer-g4.cc
  example/accel/trackingmanager-offload.cc
  example/offload-template/src/ActionInitialization.cc
  example/offload-template/src/Celeritas.cc
  src/accel/CMakeLists.txt
  src/accel/TrackingManager.cc
  src/accel/TrackingManager.hh
  src/accel/TrackingManagerOffload.hh
  src/celeritas/CMakeLists.txt
  src/celeritas/ext/EmPhysicsList.cc
  src/celeritas/ext/EmPhysicsList.hh
  src/celeritas/ext/FtfpBertPhysicsList.cc
  src/celeritas/ext/FtfpBertPhysicsList.hh
  src/celeritas/ext/GeantPhysicsOptions.hh
  src/celeritas/ext/GeantSetup.cc
  src/celeritas/ext/detail/EmStandardPhysics.cc
  src/celeritas/ext/detail/EmStandardPhysics.hh
  src/celeritas/ext/detail/OpticalPhysics.cc
  src/celeritas/ext/detail/OpticalPhysics.hh
  src/celeritas/ext/detail/PhysicsListUtils.hh
Labels: minor, external
