Repository celeritas-project/celeritas, pull requests merged in 2025-08, with the labels that each got.

#1891 Work around spurious -Wmaybe-uninitialized warning with GCC
  src/orange/g4org/ProtoConstructor.cc
Labels: minor

#1905 Add global VolumeParams and rename geant_geo->global_geant_geo
  app/celer-geo/Runner.cc
  src/accel/GeantSimpleCalo.cc
  src/accel/SharedParams.cc
  src/celeritas/ext/GeantImporter.cc
  src/celeritas/ext/GeantSetup.cc
  src/celeritas/ext/GeantVolumeMapper.cc
  src/celeritas/ext/detail/GeantSurfacePhysicsHelper.cc
  src/celeritas/setup/FrameworkInput.cc
  src/celeritas/setup/Model.cc
  src/geocel/GeantGeoParams.cc
  src/geocel/GeantGeoParams.hh
  src/geocel/VolumeParams.cc
  src/geocel/VolumeParams.hh
  src/geocel/vg/VecgeomParams.cc
  src/orange/OrangeParams.cc
  test/celeritas/GeantTestBase.cc
  test/celeritas/GlobalTestBase.cc
  test/geocel/GeantImportVolumeResult.cc
  test/geocel/GenericGeoTestInterface.cc
Labels: minor, geometry

#1909 Make surface model its own hierarchy and add default surface
  src/celeritas/CMakeLists.txt
  src/celeritas/phys/SurfaceModel.cc
  src/celeritas/phys/SurfaceModel.hh
  src/celeritas/phys/SurfacePhysicsMapBuilder.cc
  src/celeritas/phys/SurfacePhysicsMapBuilder.hh
  src/celeritas/phys/SurfacePhysicsMapData.hh
  src/celeritas/phys/SurfacePhysicsMapView.hh
  test/celeritas/phys/SurfacePhysicsMap.test.cc
Labels: physics, minor

#1915 Only warn when imported particle data is larger than user-defined offload list
  src/accel/SharedParams.cc
Labels: minor, external

#1896 Add smear and Gaussian surface roughness calculators
  doc/CMakeLists.txt
  doc/implementation/optical-physics.rst
  src/celeritas/optical/surface/GaussianRoughnessSampler.hh
  src/celeritas/optical/surface/SmearRoughnessSampler.hh
  src/celeritas/optical/surface/SurfacePhysicsUtils.hh
  src/celeritas/optical/surface/VolumeSurfaceSelector.hh
  src/corecel/random/distribution/NormalDistribution.hh
  test/AssertionHelper.cc
  test/celeritas/CMakeLists.txt
  test/celeritas/optical/RoughnessCalculator.test.cc
  test/corecel/random/HistogramSampler.hh
  test/testdetail/TestMacrosImpl.hh
Labels: enhancement, physics

#1917 Update particle speed calculation to be more robust against round-off error
  src/celeritas/alongstep/detail/TimeUpdater.hh
  src/celeritas/phys/ParticleTrackView.hh
  test/celeritas/global/AlongStep.test.cc
  test/celeritas/phys/Particle.test.cc
Labels: physics, minor

#1801 Add optical surface physics
  src/celeritas/CMakeLists.txt
  src/celeritas/Types.hh
  src/celeritas/ext/GeantImporter.cc
  src/celeritas/ext/RootInterfaceLinkDef.h
  src/celeritas/ext/detail/GeantSurfacePhysicsHelper.hh
  src/celeritas/ext/detail/GeantSurfacePhysicsLoader.cc
  src/celeritas/inp/SurfacePhysics.hh
  src/celeritas/io/ImportDataTrimmer.cc
  src/celeritas/io/ImportDataTrimmer.hh
  src/celeritas/optical/CoreParams.cc
  src/celeritas/optical/CoreParams.hh
  src/celeritas/optical/CoreTrackData.cc
  src/celeritas/optical/CoreTrackData.hh
  src/celeritas/optical/CoreTrackView.hh
  src/celeritas/optical/Types.cc
  src/celeritas/optical/Types.hh
  src/celeritas/optical/action/detail/PropagateExecutor.hh
  src/celeritas/optical/surface/SurfaceModel.hh
  src/celeritas/optical/surface/SurfacePhysicsData.hh
  src/celeritas/optical/surface/SurfacePhysicsParams.cc
  src/celeritas/optical/surface/SurfacePhysicsParams.hh
  src/celeritas/optical/surface/SurfacePhysicsView.hh
  src/celeritas/optical/surface/SurfaceSteppingAction.cc
  src/celeritas/optical/surface/SurfaceSteppingAction.hh
  src/celeritas/optical/surface/detail/InitBoundaryExecutor.hh
  src/celeritas/phys/SurfaceModel.hh
  src/celeritas/phys/SurfacePhysicsMapBuilder.cc
  src/celeritas/phys/SurfacePhysicsMapBuilder.hh
  src/celeritas/phys/SurfacePhysicsMapData.hh
  src/celeritas/phys/SurfacePhysicsMapView.hh
  src/celeritas/setup/Problem.cc
  test/celeritas/CMakeLists.txt
  test/celeritas/GlobalTestBase.cc
  test/celeritas/GlobalTestBase.hh
  test/celeritas/ImportedDataTestBase.cc
  test/celeritas/ImportedDataTestBase.hh
  test/celeritas/OnlyCoreTestBase.hh
  test/celeritas/data/four-steel-slabs.root
  test/celeritas/data/four-steel-slabs.root-dump.json
  test/celeritas/data/lar-sphere.root
  test/celeritas/data/simple-cms.root
  test/celeritas/ext/GeantImporter.test.cc
  test/celeritas/ext/RootJsonDumper.test.cc
  test/celeritas/optical/ImportedMaterials.test.cc
  test/celeritas/optical/ImportedModelAdapter.test.cc
  test/celeritas/optical/ModelImporter.test.cc
  test/celeritas/optical/OpticalMockModels.hh
  test/celeritas/optical/OpticalMockTestBase.hh
  test/celeritas/optical/Physics.test.cc
  test/celeritas/optical/SurfacePhysics.test.cc
  test/celeritas/phys/SurfacePhysicsMap.test.cc
  test/geocel/GeoTests.cc
  test/geocel/data/optical-surfaces.gdml
Labels: enhancement, physics

#1927 Fix failing celer-sim unit test with simple calo
  app/celer-sim/simple-driver.py
Labels: documentation, user
