Repository celeritas-project/celeritas, pull requests merged in 2025-07, with the labels that each got.

#1842 Add a helper function for launching a CPU kernel with an arbitrary number of threads
  src/celeritas/global/ActionLauncher.hh
  src/celeritas/optical/action/ActionLauncher.hh
  src/celeritas/optical/action/InitializeTracksAction.cc
  src/celeritas/track/ExtendFromPrimariesAction.cc
  src/celeritas/track/InitializeTracksAction.cc
  src/celeritas/user/detail/SimpleCaloImpl.cc
Labels: core, minor

#1841 Add null pointer checks for Geant4 surfaces
  src/geocel/GeantGeoParams.cc
Labels: bug, external

#1845 Update build script and user presets
  CMakePresets.json
  README.md
  scripts/build.sh
  scripts/cmake-presets/_dev_.json
  scripts/cmake-presets/ci-ubuntu-github.json
  scripts/cmake-presets/goldfinger.json
  scripts/cmake-presets/voskhod.json
  scripts/cmake-presets/wildstyle.json
Labels: documentation

#1847 Add track weight propagation to secondaries track
  src/accel/LocalTransporter.cc
  src/celeritas/ext/detail/HitProcessor.cc
  src/celeritas/phys/InteractionApplier.hh
  src/celeritas/phys/Primary.hh
  src/celeritas/phys/Secondary.hh
  src/celeritas/track/SimData.hh
  src/celeritas/track/SimTrackView.hh
  src/celeritas/user/DetectorSteps.hh
  test/celeritas/track/Sim.test.cc
Labels: enhancement, physics

#1856 Hotfix: revert accidental changes from #1839
  src/orange/OrangeData.hh
  src/orange/OrangeTrackView.hh
Labels: minor, orange

#1857 Fix counters in optical generator action
  src/celeritas/optical/OpticalCollector.cc
  src/celeritas/optical/gen/detail/GeneratorAction.cc
  src/celeritas/optical/gen/detail/GeneratorAction.hh
  test/celeritas/optical/OpticalCollector.test.cc
Labels: bug, physics

#1846 Add volume params to core
  CMakePresets.json
  scripts/cmake-presets/goldfinger.json
  src/celeritas/CMakeLists.txt
  src/celeritas/global/CoreParams.cc
  src/celeritas/global/CoreParams.hh
  src/celeritas/setup/Model.cc
  src/celeritas/setup/Model.hh
  src/celeritas/setup/Problem.cc
  src/celeritas/setup/Problem.hh
  src/corecel/cont/LabelIdMultiMap.hh
  src/geocel/GeantGeoParams.hh
  src/geocel/SurfaceData.hh
  src/geocel/SurfaceParams.cc
  src/geocel/SurfaceParams.hh
  src/geocel/VolumeParams.cc
  src/geocel/VolumeParams.hh
  src/geocel/vg/VecgeomParams.cc
  src/orange/OrangeParams.cc
  src/orange/OrangeParams.hh
  test/celeritas/GlobalTestBase.cc
  test/celeritas/GlobalTestBase.hh
  test/celeritas/ImportedDataTestBase.cc
  test/celeritas/ImportedDataTestBase.hh
  test/celeritas/MockTestBase.cc
  test/celeritas/MockTestBase.hh
  test/celeritas/OnlyGeoTestBase.hh
  test/celeritas/SimpleTestBase.cc
  test/celeritas/SimpleTestBase.hh
  test/celeritas/optical/OpticalMockTestBase.hh
  test/geocel/Surface.test.cc
  test/geocel/Volume.test.cc
Labels: minor, geometry

#1853 Update HitProcessor test to support non unit weights
  src/celeritas/user/DetectorSteps.cc
  src/celeritas/user/DetectorSteps.cu
  src/celeritas/user/DetectorSteps.hh
  src/celeritas/user/StepData.hh
  src/celeritas/user/detail/StepGatherExecutor.hh
  src/celeritas/user/detail/StepScratchCopyExecutor.hh
  test/celeritas/ext/SimpleSensitiveDetector.cc
  test/celeritas/ext/detail/HitProcessor.test.cc
  test/celeritas/user/DetectorSteps.test.cc
Labels: enhancement, physics

#1852 Add surface physics map
  src/celeritas/CMakeLists.txt
  src/celeritas/phys/SurfaceModel.hh
  src/celeritas/phys/SurfacePhysicsMapBuilder.cc
  src/celeritas/phys/SurfacePhysicsMapBuilder.hh
  src/celeritas/phys/SurfacePhysicsMapData.hh
  src/celeritas/phys/SurfacePhysicsMapView.hh
  test/celeritas/CMakeLists.txt
  test/celeritas/phys/SurfacePhysicsMap.test.cc
  test/geocel/CMakeLists.txt
  test/geocel/Surface.test.cc
  test/geocel/SurfaceTestBase.cc
  test/geocel/SurfaceTestBase.hh
Labels: physics, minor

#1861 Begin exposing Cherenkov/optical loop outside of the optical collector
  app/celer-sim/Runner.hh
  app/celer-sim/Transporter.cc
  src/accel/SharedParams.cc
  src/accel/SharedParams.hh
  src/celeritas/optical/OpticalCollector.cc
  src/celeritas/optical/OpticalCollector.hh
  src/celeritas/optical/gen/CherenkovGenerator.hh
  src/celeritas/optical/gen/CherenkovOffload.hh
  src/celeritas/optical/gen/detail/CherenkovOffloadExecutor.hh
  src/celeritas/optical/gen/detail/OffloadAction.hh
  test/celeritas/optical/Cherenkov.test.cc
  test/celeritas/optical/OpticalCollector.test.cc
Labels: physics, minor

#1859 Add VolumeSurfaceSelector
  src/celeritas/optical/CoreTrackView.hh
  src/celeritas/optical/surface/VolumeSurfaceSelector.hh
  test/celeritas/CMakeLists.txt
  test/celeritas/optical/VolumeSurfaceSelector.test.cc
Labels: enhancement, physics

#1864 Refactor geometry construction to use static methods and shared pointers
  app/celer-geo/Runner.cc
  app/celer-geo/Runner.hh
  src/accel/GeantSimpleCalo.cc
  src/accel/SharedParams.cc
  src/celeritas/ext/GeantImporter.cc
  src/celeritas/ext/GeantSetup.cc
  src/celeritas/ext/GeantVolumeMapper.cc
  src/celeritas/setup/FrameworkInput.cc
  src/celeritas/setup/Model.cc
  src/celeritas/setup/StandaloneInput.cc
  src/geocel/GeantGeoParams.cc
  src/geocel/GeantGeoParams.hh
  src/geocel/GeantGeoUtils.cc
  src/geocel/GeoTraits.hh
  src/geocel/g4/GeantGeoTraits.hh
  src/geocel/vg/VecgeomGeoTraits.hh
  src/geocel/vg/VecgeomParams.cc
  src/geocel/vg/VecgeomParams.hh
  src/orange/OrangeGeoTraits.hh
  src/orange/OrangeParams.cc
  src/orange/OrangeParams.hh
  test/PersistentSP.hh
  test/accel/HepMC3PrimaryGenerator.test.cc
  test/celeritas/GeantTestBase.cc
  test/celeritas/GeantTestBase.hh
  test/celeritas/GlobalGeoTestBase.cc
  test/celeritas/GlobalGeoTestBase.hh
  test/celeritas/GlobalTestBase.cc
  test/celeritas/ext/GeantVolumeMapper.test.cc
  test/celeritas/ext/detail/LevelTouchableUpdater.test.cc
  test/celeritas/field/FieldPropagator.test.cc
  test/geocel/GeantImportVolumeResult.cc
  test/geocel/GenericGeoTestBase.hh
  test/geocel/GenericGeoTestBase.t.hh
  test/geocel/GenericGeoTestInterface.cc
  test/geocel/LazyGeoManager.cc
  test/geocel/LazyGeoManager.hh
  test/geocel/data/simple-cms.gdml
  test/geocel/data/simple-cms.org.json
  test/geocel/data/simple-cms.org.omn
  test/geocel/data/two-boxes.org.json
  test/geocel/vg/Vecgeom.test.cc
  test/orange/OrangeGeant.test.cc
  test/orange/OrangeGeoTestBase.cc
  test/orange/OrangeTestBase.hh
  test/orange/g4org/GeantLoadTestBase.cc
Labels: minor, geometry

#1865 Move generators into optical namespace and refactor track generation utilities
  doc/implementation/optical-physics.rst
  src/celeritas/CMakeLists.txt
  src/celeritas/optical/OpticalCollector.cc
  src/celeritas/optical/OpticalCollector.hh
  src/celeritas/optical/Types.hh
  src/celeritas/optical/gen/CherenkovGenerator.hh
  src/celeritas/optical/gen/CherenkovOffload.hh
  src/celeritas/optical/gen/GeneratorAction.cc
  src/celeritas/optical/gen/GeneratorAction.cu
  src/celeritas/optical/gen/GeneratorAction.hh
  src/celeritas/optical/gen/GeneratorBase.cc
  src/celeritas/optical/gen/GeneratorBase.hh
  src/celeritas/optical/gen/GeneratorData.hh
  src/celeritas/optical/gen/OffloadAction.cc
  src/celeritas/optical/gen/OffloadAction.cu
  src/celeritas/optical/gen/OffloadAction.hh
  src/celeritas/optical/gen/OffloadGatherAction.cc
  src/celeritas/optical/gen/OffloadGatherAction.cu
  src/celeritas/optical/gen/OffloadGatherAction.hh
  src/celeritas/optical/gen/PrimaryGenerator.hh
  src/celeritas/optical/gen/PrimaryGeneratorAction.cc
  src/celeritas/optical/gen/PrimaryGeneratorAction.cu
  src/celeritas/optical/gen/PrimaryGeneratorAction.hh
  src/celeritas/optical/gen/ScintillationGenerator.hh
  src/celeritas/optical/gen/ScintillationOffload.hh
  src/celeritas/optical/gen/detail/CherenkovOffloadExecutor.hh
  src/celeritas/optical/gen/detail/GeneratorAlgorithms.cc
  src/celeritas/optical/gen/detail/GeneratorAlgorithms.cu
  src/celeritas/optical/gen/detail/GeneratorAlgorithms.hh
  src/celeritas/optical/gen/detail/GeneratorExecutor.hh
  src/celeritas/optical/gen/detail/GeneratorTraits.hh
  src/celeritas/optical/gen/detail/OffloadAlgorithms.cc
  src/celeritas/optical/gen/detail/OffloadAlgorithms.cu
  src/celeritas/optical/gen/detail/OffloadAlgorithms.hh
  src/celeritas/optical/gen/detail/OffloadTraits.hh
  src/celeritas/optical/gen/detail/OpticalGenAlgorithms.cu
  src/celeritas/optical/gen/detail/PrimaryGeneratorExecutor.hh
  src/celeritas/optical/gen/detail/ScintOffloadExecutor.hh
  src/celeritas/optical/gen/detail/UpdateSumExecutor.hh
  src/celeritas/track/Utils.hh
  src/celeritas/track/detail/InitTracksExecutor.hh
  src/celeritas/track/detail/LocateAliveExecutor.hh
  src/celeritas/track/detail/ProcessPrimariesExecutor.hh
  src/celeritas/track/detail/TrackInitAlgorithms.cc
  src/celeritas/track/detail/TrackInitAlgorithms.cu
  src/celeritas/track/detail/TrackInitAlgorithms.hh
  src/corecel/math/Algorithms.hh
  test/celeritas/optical/Cherenkov.test.cc
  test/celeritas/optical/OpticalLaunchAction.test.cc
  test/celeritas/optical/OpticalUtils.test.cc
  test/celeritas/optical/Scintillation.test.cc
  test/corecel/math/Algorithms.test.cc
Labels: physics, minor

#1866 Reconstruct G4VTrackUserInfo and G4VProcess
  app/celer-g4/TrackingAction.cc
  src/accel/FastSimulationModel.cc
  src/accel/LocalTransporter.cc
  src/accel/LocalTransporter.hh
  src/celeritas/ext/detail/HitProcessor.cc
  src/celeritas/ext/detail/HitProcessor.hh
Labels: enhancement, external

#1872 Rename LogicalFalse and LogicalTrue
  src/celeritas/ext/detail/GeantOpticalModelImporter.cc
  src/celeritas/ext/detail/GeantProcessImporter.cc
  src/celeritas/optical/MaterialParams.cc
  src/celeritas/optical/gen/detail/OffloadAlgorithms.cc
  src/celeritas/optical/gen/detail/OffloadAlgorithms.cu
  src/celeritas/phys/ImportedProcessAdapter.cc
  src/celeritas/phys/PhysicsParams.cc
  src/celeritas/phys/PrimaryGenerator.cc
  src/celeritas/phys/PrimaryGeneratorOptions.hh
  src/celeritas/track/detail/TrackInitAlgorithms.cc
  src/celeritas/track/detail/TrackInitAlgorithms.cu
  src/celeritas/user/StepCollector.cc
  src/corecel/math/Algorithms.hh
  src/geocel/GeantGeoUtils.cc
  src/orange/orangeinp/CsgObject.cc
  src/orange/orangeinp/UnitProto.cc
  test/corecel/math/Algorithms.test.cc
Labels: core, minor

#1870 Support single-precision Geant4->ORANGE conversion
  .github/workflows/build-spack.yml
  example/offload-template/.gitignore
  example/offload-template/src/StepDiagnosticData.hh
  src/orange/CMakeLists.txt
  src/orange/OrangeParams.cc
  src/orange/g4org/Converter.hh
  src/orange/g4org/Scaler.hh
  src/orange/g4org/SolidConverter.cc
  src/orange/g4org/Transformer.hh
  src/orange/orangeinp/detail/LocalSurfaceInserter.cc
  test/PersistentSP.hh
  test/celeritas/GeantTestBase.cc
  test/geocel/GeoTests.cc
  test/geocel/GeoTests.hh
  test/orange/CMakeLists.txt
  test/orange/OrangeGeant.test.cc
  test/orange/g4org/PhysicalVolumeConverter.test.cc
  test/orange/g4org/ProtoConstructor.test.cc
  test/orange/g4org/SolidConverter.test.cc
  test/orange/g4org/Transformer.test.cc
Labels: enhancement, orange

#1869 Add TrackProcessor class for reconstructing Geant4 tracks
  src/accel/LocalTransporter.cc
  src/celeritas/CMakeLists.txt
  src/celeritas/ext/detail/HitProcessor.cc
  src/celeritas/ext/detail/HitProcessor.hh
  src/celeritas/ext/detail/TrackProcessor.cc
  src/celeritas/ext/detail/TrackProcessor.hh
  test/celeritas/CMakeLists.txt
  test/celeritas/ext/detail/TrackProcessor.test.cc
Labels: enhancement, external

#1840 Add RevolvedSpecialTrapezoid as a first step towards G4GenericPolycone
  scripts/dev/codespell-fixes.txt
  src/corecel/math/SoftEqual.hh
  src/orange/orangeinp/CsgTypes.cc
  src/orange/orangeinp/CsgTypes.hh
  src/orange/orangeinp/IntersectRegion.cc
  src/orange/orangeinp/IntersectRegion.hh
  src/orange/orangeinp/ObjectIO.json.cc
  src/orange/orangeinp/ObjectIO.json.hh
  src/orange/orangeinp/detail/PolygonUtils.hh
  test/corecel/math/SoftEqual.test.cc
  test/orange/orangeinp/IntersectRegion.test.cc
  test/orange/orangeinp/detail/PolygonUtils.test.cc
Labels: enhancement, orange

#1878 Fix volume params construction in model setup
  src/celeritas/setup/Model.cc
  src/celeritas/setup/Problem.cc
Labels: bug, physics

#1874 Add volume params visitor
  src/celeritas/user/detail/StepParams.cc
  src/geocel/CMakeLists.txt
  src/geocel/GeantGeoParams.cc
  src/geocel/GeantGeoParams.hh
  src/geocel/GeoParamsInterface.hh
  src/geocel/GeoParamsOutput.cc
  src/geocel/VolumeParams.cc
  src/geocel/VolumeParams.hh
  src/geocel/VolumeToString.cc
  src/geocel/VolumeToString.hh
  src/geocel/VolumeVisitor.hh
  src/geocel/g4/VisitVolumes.hh
  src/geocel/inp/Model.hh
  src/geocel/vg/VecgeomParams.cc
  src/geocel/vg/VecgeomParams.hh
  src/geocel/vg/VisitVolumes.hh
  src/orange/OrangeParams.hh
  test/celeritas/geo/Geometry.test.cc
  test/geocel/GenericGeoResults.cc
  test/geocel/GenericGeoResults.hh
  test/geocel/GeoTests.cc
  test/geocel/Volume.test.cc
  test/geocel/g4/GeantGeo.test.cc
  test/geocel/g4/VisitVolumes.test.cc
  test/geocel/vg/Vecgeom.test.cc
Labels: minor, geometry

#1875 Refactor optical params and stepping loop for optical-only mode
  src/celeritas/CMakeLists.txt
  src/celeritas/inp/Physics.hh
  src/celeritas/optical/OpticalCollector.cc
  src/celeritas/optical/OpticalCollector.hh
  src/celeritas/optical/Transporter.cc
  src/celeritas/optical/Transporter.hh
  src/celeritas/optical/detail/OpticalLaunchAction.cc
  src/celeritas/optical/detail/OpticalLaunchAction.hh
  src/celeritas/setup/Problem.cc
  test/celeritas/CMakeLists.txt
  test/celeritas/GlobalTestBase.cc
  test/celeritas/GlobalTestBase.hh
  test/celeritas/ImportedDataTestBase.cc
  test/celeritas/ImportedDataTestBase.hh
  test/celeritas/LArSphereBase.hh
  test/celeritas/optical/OpticalCollector.test.cc
  test/celeritas/optical/Physics.test.cc
  test/celeritas/optical/PrimaryGenerator.test.cc
Labels: physics, minor

#1882 Delete IPAContextException
  src/celeritas/phys/ImportedProcessAdapter.cc
  src/celeritas/phys/ImportedProcessAdapter.hh
Labels: physics, minor

#1880 Add volume test base
  test/celeritas/optical/VolumeSurfaceSelector.test.cc
  test/celeritas/phys/SurfacePhysicsMap.test.cc
  test/geocel/CMakeLists.txt
  test/geocel/Surface.test.cc
  test/geocel/SurfaceTestBase.cc
  test/geocel/SurfaceTestBase.hh
  test/geocel/SurfaceUtils.hh
  test/geocel/Volume.test.cc
  test/geocel/VolumeTestBase.cc
  test/geocel/VolumeTestBase.hh
  test/geocel/g4/VisitVolumes.test.cc
Labels: documentation, geometry

#1885 Prevent splitting during ROOT I/O to reduce file size
  src/celeritas/ext/RootExporter.cc
  test/celeritas/data/four-steel-slabs.root
  test/celeritas/data/lar-sphere.root
  test/celeritas/data/simple-cms.root
Labels: external
