Repository celeritas-project/celeritas, pull requests merged in 2025-04, with the labels that each got.

#1710 Remove macro setup from celer-g4
  app/celer-g4/celer-g4.cc
  doc/usage/execution/_usage/celer-g4.txt
Labels: app, removal

#1711 Allow G4 applications to query celeritas offload mode
  example/accel/simple-offload.cc
  src/accel/IntegrationBase.cc
  src/accel/IntegrationBase.hh
  src/accel/SharedParams.hh
  src/accel/Types.hh
Labels: enhancement, external

#1709 Fix sampling of angle in Urban MSC model
  src/celeritas/em/msc/detail/UrbanMscScatter.hh
  test/celeritas/em/UrbanMsc.test.cc
  test/celeritas/global/AlongStep.test.cc
  test/celeritas/global/StepperGeant.test.cc
  test/celeritas/optical/OpticalCollector.test.cc
  test/celeritas/user/Diagnostic.test.cc
  test/celeritas/user/SlotDiagnostic.test.cc
  test/celeritas/user/StepCollector.test.cc
Labels: bug, physics

#1704 Fix OBZ bugs
  src/orange/BoundingBoxUtils.hh
  src/orange/detail/OrientedBoundingZone.hh
  test/orange/BoundingBoxUtils.test.cc
  test/orange/detail/OrientedBoundingZone.test.cc
Labels: bug, orange, geometry

#1712 Update Geant4 version to 11.3 in CI build
  .github/workflows/build-docker.yml
  .github/workflows/build-spack.yml
  test/celeritas/GeantTestBase.cc
  test/celeritas/global/AlongStep.test.cc
  test/celeritas/global/StepperGeant.test.cc
  test/celeritas/user/Diagnostic.test.cc
  test/celeritas/user/SlotDiagnostic.test.cc
  test/celeritas/user/StepCollector.test.cc
Labels: documentation, physics

#1718 Remove dependency of orange test on celeritas
  src/geocel/random/IsotropicDistribution.hh
  src/geocel/random/UniformBoxDistribution.hh
  test/orange/CMakeLists.txt
  test/orange/Orange.test.cc
  test/orange/OrangeGeoTestBase.hh
  test/orange/OrangeJson.test.cc
  test/orange/OrangeShift.test.cc
  test/orange/detail/BIHBuilder.test.cc
  test/orange/detail/BIHEnclosingVolFinder.test.cc
  test/orange/detail/OrientedBoundingZone.test.cc
  test/orange/detail/UniverseIndexer.test.cc
  test/orange/orangeinp/CsgTestUtils.hh
  test/orange/univ/RectArrayTracker.test.cc
  test/orange/univ/SimpleUnitTracker.test.cc
Labels: core, minor

#1717 Add histogram helper class to simplify distribution tests
  test/celeritas/em/BetheBloch.test.cc
  test/celeritas/em/BraggICRU73QO.test.cc
  test/celeritas/em/MuBetheBloch.test.cc
  test/celeritas/em/MuPairProduction.test.cc
  test/corecel/CMakeLists.txt
  test/corecel/random/Histogram.cc
  test/corecel/random/Histogram.hh
  test/corecel/random/distribution/ExponentialDistribution.test.cc
  test/corecel/random/distribution/GammaDistribution.test.cc
  test/corecel/random/distribution/InverseSquareDistribution.test.cc
  test/corecel/random/distribution/NormalDistribution.test.cc
  test/corecel/random/distribution/PoissonDistribution.test.cc
  test/corecel/random/distribution/RadialDistribution.test.cc
  test/corecel/random/distribution/ReciprocalDistribution.test.cc
  test/corecel/random/distribution/RejectionSampler.test.cc
  test/corecel/random/distribution/UniformRealDistribution.test.cc
  test/orange/BoundingBoxUtils.test.cc
Labels: documentation, core

#1719 Add string simplifier helper class for testing
  .github/workflows/build-fast.yml
  .github/workflows/build-ultralite.yml
  test/Test.cc
  test/Test.hh
  test/celeritas/CMakeLists.txt
  test/celeritas/field/FieldPropagator.test.cc
  test/celeritas/geo/Geometry.test.cc
  test/celeritas/global/AlongStep.test.cc
  test/celeritas/global/Stepper.test.cc
  test/corecel/CMakeLists.txt
  test/corecel/ScopedLogStorer.cc
  test/corecel/ScopedLogStorer.hh
  test/corecel/StringSimplifier.cc
  test/corecel/StringSimplifier.hh
  test/corecel/StringSimplifier.test.cc
  test/geocel/CheckedGeoTrackView.t.hh
  test/geocel/vg/Vecgeom.test.cc
  test/orange/g4org/ProtoConstructor.test.cc
  test/orange/orangeinp/CsgTestUtils.cc
Labels: documentation, core

#1715 Improve messages when multiple tracks fail in flight
  src/celeritas/global/DebugIO.json.cc
  src/celeritas/global/KernelContextException.cc
  src/corecel/io/LogContextException.cc
  src/corecel/io/detail/LoggerMessage.hh
  src/corecel/sys/MultiExceptionHandler.cc
  test/celeritas/global/KernelContextException.test.cc
  test/celeritas/global/Stepper.test.cc
  test/corecel/sys/MultiExceptionHandler.test.cc
Labels: enhancement, core

#1721 Update to CudaRdcUtils v12 -
  cmake/external/CudaRdcUtils.cmake
Labels: enhancement, core

#1722 Estimate scintillation wavelength distribution parameters from tabulated values when only the latter is provided
  src/celeritas/ext/GeantImporter.cc
  src/celeritas/ext/detail/GeantMaterialPropertyGetter.hh
  src/celeritas/ext/detail/GeantOpticalModelImporter.cc
  src/celeritas/optical/CherenkovParams.cc
  src/celeritas/optical/WavelengthShiftParams.cc
  src/corecel/math/PdfUtils.hh
  test/celeritas/data/lar-sphere.root
  test/celeritas/ext/GeantImporter.test.cc
  test/corecel/CMakeLists.txt
  test/corecel/math/PdfUtils.test.cc
  test/geocel/data/lar-sphere.gdml
Labels: enhancement, physics

#1724 Fix field map usage from accel
  src/celeritas/inp/Field.hh
  src/celeritas/setup/Problem.cc
Labels: bug, app

#1723 Improve MSC test code coverage
  src/celeritas/phys/Interaction.hh
  src/corecel/random/distribution/PoissonDistribution.hh
  test/celeritas/CMakeLists.txt
  test/celeritas/em/BetheBloch.test.cc
  test/celeritas/em/BraggICRU73QO.test.cc
  test/celeritas/em/MuBetheBloch.test.cc
  test/celeritas/em/MuPairProduction.test.cc
  test/celeritas/em/UrbanMsc.test.cc
  test/corecel/random/Histogram.cc
  test/corecel/random/Histogram.hh
  test/corecel/random/distribution/PoissonDistribution.test.cc
Labels: documentation, physics

#1725 Add quick-start documentation for integrating
  README.md
  doc/implementation/geant4-interface/setup.rst
  doc/usage/integration.rst
  example/accel/add-celer.diff
  example/accel/fastsim-offload.cc
  example/accel/simple-offload.cc
  example/accel/trackingmanager-offload.cc
  scripts/ci/test-examples.sh
Labels: documentation

#1734 Remove per-process switch for integral cross section method
  src/celeritas/em/process/BremsstrahlungProcess.hh
  src/celeritas/em/process/ComptonProcess.hh
  src/celeritas/em/process/CoulombScatteringProcess.cc
  src/celeritas/em/process/CoulombScatteringProcess.hh
  src/celeritas/em/process/EIonizationProcess.cc
  src/celeritas/em/process/EIonizationProcess.hh
  src/celeritas/em/process/EPlusAnnihilationProcess.cc
  src/celeritas/em/process/EPlusAnnihilationProcess.hh
  src/celeritas/em/process/GammaConversionProcess.hh
  src/celeritas/em/process/MuBremsstrahlungProcess.cc
  src/celeritas/em/process/MuBremsstrahlungProcess.hh
  src/celeritas/em/process/MuIonizationProcess.hh
  src/celeritas/em/process/MuPairProductionProcess.cc
  src/celeritas/em/process/MuPairProductionProcess.hh
  src/celeritas/em/process/PhotoelectricProcess.hh
  src/celeritas/em/process/RayleighProcess.hh
  src/celeritas/inp/PhysicsProcess.hh
  src/celeritas/neutron/process/NeutronElasticProcess.hh
  src/celeritas/neutron/process/NeutronInelasticProcess.hh
  src/celeritas/phys/PhysicsParams.cc
  src/celeritas/phys/Process.hh
  src/celeritas/phys/ProcessBuilder.cc
  src/celeritas/phys/ProcessBuilder.hh
  src/celeritas/setup/Problem.cc
  test/celeritas/MockTestBase.cc
  test/celeritas/global/StepperGeant.test.cc
  test/celeritas/phys/MockProcess.cc
  test/celeritas/phys/MockProcess.hh
  test/celeritas/phys/Physics.test.cc
Labels: physics, removal

#1729 Simplify Geant4 user application interface
  .github/workflows/build-spack.yml
  README.md
  cmake/CeleritasConfig.cmake.in
  doc/example/geant4.rst
  doc/usage/integration.rst
  example/accel/add-celer.diff
  example/geant4/.gitignore
  example/geant4/CMakeLists.txt
  example/geant4/add-celer.diff
  example/geant4/fastsim-offload.cc
  example/geant4/simple-offload.cc
  example/geant4/trackingmanager-offload.cc
  example/offload-template/CMakeLists.txt
  example/offload-template/README.rst
  example/offload-template/src/ActionInitialization.cc
  scripts/ci/test-examples.sh
  src/CMakeLists.txt
  src/CeleritasG4.hh
  src/accel/AlongStepFactory.cc
  src/accel/AlongStepFactory.hh
  src/accel/FastSimulationIntegration.hh
  src/accel/IntegrationBase.cc
  src/accel/IntegrationBase.hh
  src/accel/SetupOptions.hh
  src/accel/TrackingManagerIntegration.hh
  src/accel/UserActionIntegration.hh
Labels: minor, external

#1694 Add ExtThrust for more explicit dependencies
  CMakeLists.txt
  scripts/cmake-presets/perlmutter.json
  src/CMakeLists.txt
  src/accel/CMakeLists.txt
  src/celeritas/CMakeLists.txt
  src/corecel/CMakeLists.txt
  test/celeritas/CMakeLists.txt
  test/corecel/CMakeLists.txt
  test/geocel/CMakeLists.txt
Labels: core, minor

#1736 Add utilities to stabilize downstream use of ORANGE
  CMakeLists.txt
  src/corecel/sys/Device.cc
  src/orange/BoundingBoxUtils.hh
  src/orange/CMakeLists.txt
  src/orange/LevelStateAccessor.hh
  src/orange/OrangeTrackView.hh
  src/orange/detail/UnitInserter.cc
  src/orange/orangeinp/ScaleUtils.cc
  src/orange/orangeinp/ScaleUtils.hh
  src/orange/orangeinp/detail/CsgLogicUtils.hh
  src/orange/orangeinp/detail/NegatedSurfaceClipper.hh
  src/orange/surf/SurfaceClipper.cc
  src/orange/surf/SurfaceClipper.hh
  test/orange/univ/SimpleUnitTracker.test.cc
  test/orange/univ/SimpleUnitTracker.test.hh
Labels: enhancement, orange

#1737 Rename field integration interfaces: Stepper→Integrators, Driver→Substepper
  .git-blame-ignore-revs
  doc/_static/zotero.bib
  doc/implementation/core-physics/propagation.rst
  src/celeritas/alongstep/AlongStepCylMapFieldMscAction.cu
  src/celeritas/alongstep/AlongStepUniformMscAction.cu
  src/celeritas/alongstep/detail/CylMapFieldPropagatorFactory.hh
  src/celeritas/alongstep/detail/RZMapFieldPropagatorFactory.hh
  src/celeritas/alongstep/detail/UniformFieldPropagatorFactory.hh
  src/celeritas/field/CylMapFieldData.hh
  src/celeritas/field/DormandPrinceIntegrator.hh
  src/celeritas/field/FieldDriverOptions.hh
  src/celeritas/field/FieldPropagator.hh
  src/celeritas/field/FieldSubstepper.hh
  src/celeritas/field/MakeMagFieldPropagator.hh
  src/celeritas/field/RZMapFieldData.hh
  src/celeritas/field/RungeKuttaIntegrator.hh
  src/celeritas/field/Types.hh
  src/celeritas/field/ZHelixIntegrator.hh
  test/celeritas/CMakeLists.txt
  test/celeritas/field/DiagnosticIntegrator.hh
  test/celeritas/field/FieldPropagator.test.cc
  test/celeritas/field/FieldSubstepper.test.cc
  test/celeritas/field/Integrators.test.cc
  test/celeritas/field/MagFieldTraits.hh
Labels: field, minor

#1740 Remove celer-dump-data app
  .github/workflows/build-docker.yml
  .github/workflows/build-spack.yml
  app/CMakeLists.txt
  app/celer-dump-data.cc
  doc/usage/execution/_usage/celer-dump-data.txt
  doc/usage/execution/utilities.rst
Labels: app, removal

#1739 Add uniform grid input and continue to simplify grid construction
  doc/usage/input/grid.rst
  src/celeritas/em/params/detail/MscParamsHelper.cc
  src/celeritas/ext/RootInterfaceLinkDef.h
  src/celeritas/ext/detail/GeantMicroXsCalculator.cc
  src/celeritas/ext/detail/GeantMicroXsCalculator.hh
  src/celeritas/ext/detail/GeantModelImporter.cc
  src/celeritas/ext/detail/GeantProcessImporter.cc
  src/celeritas/ext/detail/GeantProcessImporter.hh
  src/celeritas/field/RZMapFieldParams.cc
  src/celeritas/grid/NonuniformGridInserter.hh
  src/celeritas/grid/RangeGridCalculator.cc
  src/celeritas/grid/RangeGridCalculator.hh
  src/celeritas/grid/UniformGridInserter.cc
  src/celeritas/grid/UniformGridInserter.hh
  src/celeritas/grid/ValueGridBuilder.cc
  src/celeritas/grid/ValueGridBuilder.hh
  src/celeritas/grid/XsGridInserter.cc
  src/celeritas/grid/XsGridInserter.hh
  src/celeritas/inp/Grid.hh
  src/celeritas/io/ImportDataTrimmer.cc
  src/celeritas/io/ImportDataTrimmer.hh
  src/celeritas/io/ImportModel.hh
  src/celeritas/io/ImportPhysicsTable.hh
  src/celeritas/io/detail/ImportDataConverter.cc
  src/celeritas/optical/CherenkovParams.cc
  src/celeritas/optical/WavelengthShiftParams.cc
  src/celeritas/optical/model/RayleighModel.cc
  src/celeritas/phys/ImportedModelAdapter.cc
  src/celeritas/phys/ImportedProcessAdapter.cc
  src/celeritas/phys/ImportedProcessAdapter.hh
  src/celeritas/phys/PhysicsParams.cc
  src/corecel/Types.hh
  src/corecel/grid/UniformGridData.hh
  src/geocel/Types.hh
  test/celeritas/SimpleTestBase.cc
  test/celeritas/data/four-steel-slabs.root
  test/celeritas/data/lar-sphere.root
  test/celeritas/data/simple-cms.root
  test/celeritas/ext/GeantImporter.test.cc
  test/celeritas/ext/RootJsonDumper.test.cc
  test/celeritas/grid/CalculatorTestBase.cc
  test/celeritas/grid/CalculatorTestBase.hh
  test/celeritas/grid/GridInserter.test.cc
  test/celeritas/grid/InverseRangeCalculator.test.cc
  test/celeritas/grid/NonuniformGridInserter.test.cc
  test/celeritas/grid/RangeCalculator.test.cc
  test/celeritas/grid/RangeGridCalculator.test.cc
  test/celeritas/grid/SplineCalculator.test.cc
  test/celeritas/grid/UniformLogGridCalculator.test.cc
  test/celeritas/grid/ValueGridBuilder.test.cc
  test/celeritas/grid/XsCalculator.test.cc
  test/celeritas/optical/OpticalMockModels.hh
  test/celeritas/optical/Physics.test.cc
  test/celeritas/phys/MockModel.cc
  test/celeritas/phys/MockProcess.cc
  test/corecel/grid/FindInterp.test.cc
  test/corecel/grid/UniformGrid.test.cc
Labels: physics, minor

#1633 Expand support for spline interpolation
  app/celer-g4/GlobalSetup.cc
  app/celer-g4/RunInput.cc
  app/celer-g4/RunInput.hh
  app/celer-g4/RunInputIO.json.cc
  app/celer-sim/RunnerInput.cc
  app/celer-sim/RunnerInput.hh
  app/celer-sim/RunnerInputIO.json.cc
  app/celer-sim/simple-driver.py
  src/accel/SetupOptions.cc
  src/accel/SetupOptions.hh
  src/celeritas/TypesIO.json.cc
  src/celeritas/TypesIO.json.hh
  src/celeritas/alongstep/detail/FluctELoss.hh
  src/celeritas/em/model/detail/LivermoreXsInserter.hh
  src/celeritas/em/msc/detail/UrbanMscHelper.hh
  src/celeritas/ext/GeantImporter.cc
  src/celeritas/ext/GeantImporter.hh
  src/celeritas/ext/detail/GeantProcessImporter.cc
  src/celeritas/ext/detail/GeantProcessImporter.hh
  src/celeritas/grid/InverseRangeCalculator.hh
  src/celeritas/grid/NonuniformGridBuilder.cc
  src/celeritas/grid/NonuniformGridBuilder.hh
  src/celeritas/grid/RangeCalculator.hh
  src/celeritas/grid/RangeGridCalculator.cc
  src/celeritas/grid/SplineCalculator.hh
  src/celeritas/grid/UniformGridInserter.cc
  src/celeritas/grid/UniformGridInserter.hh
  src/celeritas/grid/XsGridInserter.cc
  src/celeritas/grid/XsGridInserter.hh
  src/celeritas/grid/detail/GridUtils.hh
  src/celeritas/inp/Physics.hh
  src/celeritas/io/LivermorePEReader.cc
  src/celeritas/io/LivermorePEReader.hh
  src/celeritas/phys/ImportedModelAdapter.cc
  src/celeritas/phys/PhysicsData.hh
  src/celeritas/phys/PhysicsParams.cc
  src/celeritas/phys/PhysicsParams.hh
  src/celeritas/phys/PhysicsParamsOutput.cc
  src/celeritas/phys/PhysicsStepUtils.hh
  src/celeritas/phys/PhysicsTrackView.hh
  src/celeritas/phys/ProcessBuilder.cc
  src/celeritas/setup/Problem.cc
  src/corecel/grid/NonuniformGridData.hh
  src/corecel/grid/SplineDerivCalculator.cc
  src/corecel/grid/SplineDerivCalculator.hh
  src/corecel/grid/detail/GridAccessor.hh
  test/celeritas/MockTestBase.cc
  test/celeritas/MockTestBase.hh
  test/celeritas/em/LivermorePE.test.cc
  test/celeritas/grid/CalculatorTestBase.cc
  test/celeritas/grid/CalculatorTestBase.hh
  test/celeritas/grid/InverseRangeCalculator.test.cc
  test/celeritas/grid/UniformLogGridCalculator.test.cc
  test/celeritas/phys/MockProcess.hh
  test/celeritas/phys/Physics.test.cc
  test/celeritas/phys/PhysicsStepUtils.test.cc
Labels: enhancement, physics

#1754 Release v0.5.3
  doc/appendix/release-history/v0.5.rst
  scripts/dev/cloc-to-numbers.py
  scripts/dev/run-cloc.sh
Labels: documentation

#1755 Fix ROCTX find: hip not cuda
  CMakeLists.txt
Labels: core, minor

#1747 Add authorship guidelines
  .github/pull_request_template.release.md
  CONTRIBUTING.rst
  doc/_static/zotero.bib
  doc/backmatter/acknowledgments.rst
  doc/conf.py
  doc/development/administration.rst
  scripts/release/orcid.json
  scripts/release/users.json
Labels: documentation

#1714 Simplify MSC angular sampling
  doc/CMakeLists.txt
  doc/_static/macros.tex
  doc/conf.py
  doc/implementation/core-physics/rng.rst
  doc/implementation/em-physics/coulomb.rst
  scripts/cmake-presets/goldfinger.json
  src/celeritas/alongstep/AlongStepUniformMscAction.cu
  src/celeritas/em/data/UrbanMscData.hh
  src/celeritas/em/data/WentzelVIMscData.hh
  src/celeritas/em/distribution/UrbanLargeAngleDistribution.hh
  src/celeritas/em/distribution/WentzelDistribution.hh
  src/celeritas/em/msc/UrbanMsc.hh
  src/celeritas/em/msc/detail/MscStepFromGeo.hh
  src/celeritas/em/msc/detail/MscStepToGeo.hh
  src/celeritas/em/msc/detail/UrbanMscHelper.hh
  src/celeritas/em/msc/detail/UrbanMscMinimalStepLimit.hh
  src/celeritas/em/msc/detail/UrbanMscSafetyStepLimit.hh
  src/celeritas/em/msc/detail/UrbanMscScatter.hh
  src/corecel/random/distribution/BernoulliDistribution.hh
  src/corecel/random/distribution/GenerateCanonical.hh
  src/corecel/random/distribution/PowerDistribution.hh
  src/corecel/random/distribution/UniformRealDistribution.hh
  src/corecel/random/engine/CachedRngEngine.hh
  src/corecel/random/engine/CuHipRngEngine.hh
  src/corecel/random/engine/XorwowRngEngine.hh
  test/celeritas/em/UrbanMsc.test.cc
  test/corecel/CMakeLists.txt
  test/corecel/random/CachedRngEngine.test.cc
  test/corecel/random/Histogram.cc
  test/corecel/random/Histogram.hh
  test/corecel/random/SequenceEngine.hh
  test/corecel/random/XorwowRngEngine.test.cc
  test/corecel/random/distribution/PowerDistribution.test.cc
  test/corecel/random/distribution/UniformRealDistribution.test.cc
Labels: physics, minor

#1741 Unify perfetto usage
  app/celer-g4/RunInput.cc
  app/celer-g4/RunInput.hh
  app/celer-g4/celer-g4.cc
  doc/usage/execution/profiling.rst
  scripts/docker/interactive/scheduling.cfg
  src/celeritas/setup/Problem.cc
  src/corecel/io/BuildOutput.cc
  src/corecel/sys/detail/TrackEvent.perfetto.hh
Labels: performance

#1744 Add cartesian magnetic field using Covfie
  .github/workflows/build-spack.yml
  CMakeLists.txt
  cmake/CeleritasConfig.cmake.in
  cmake/Findcovfie.cmake
  doc/implementation/core-physics/propagation.rst
  external/CMakeLists.txt
  scripts/cmake-presets/ci-rocky-cuda.json
  scripts/cmake-presets/ci-ubuntu-github.json
  src/CMakeLists.txt
  src/accel/AlongStepFactory.cc
  src/accel/AlongStepFactory.hh
  src/accel/SetupOptions.cc
  src/celeritas/CMakeLists.txt
  src/celeritas/alongstep/AlongStepCartMapFieldMscAction.cc
  src/celeritas/alongstep/AlongStepCartMapFieldMscAction.cu
  src/celeritas/alongstep/AlongStepCartMapFieldMscAction.hh
  src/celeritas/alongstep/detail/CartMapFieldPropagatorFactory.hh
  src/celeritas/field/CartMapField.covfie.hh
  src/celeritas/field/CartMapField.hh
  src/celeritas/field/CartMapFieldData.covfie.hh
  src/celeritas/field/CartMapFieldData.hh
  src/celeritas/field/CartMapFieldInput.hh
  src/celeritas/field/CartMapFieldParams.covfie.cc
  src/celeritas/field/CartMapFieldParams.hh
  src/celeritas/field/detail/CovfieFieldTraits.hh
  src/celeritas/field/detail/NotImplementedField.hh
  src/celeritas/inp/Field.hh
  src/celeritas/setup/Problem.cc
  src/corecel/CMakeLists.txt
  src/corecel/Config.hh.in
  src/corecel/io/BuildOutput.cc
  test/celeritas/CMakeLists.txt
  test/celeritas/field/Fields.test.cc
Labels: enhancement, field

#1761 Fix missing header and typo
  external/CMakeLists.txt
  src/accel/TrackingManagerIntegration.cc
Labels: minor

#1759 Add helper for accumulating histograms
  test/AssertionHelper.cc
  test/AssertionHelper.hh
  test/CMakeLists.txt
  test/TestMacros.hh
  test/TestMacros.test.cc
  test/celeritas/em/BetheBloch.test.cc
  test/celeritas/em/UrbanMsc.test.cc
  test/celeritas/em/distribution/EnergyLossHelper.test.cc
  test/celeritas/em/distribution/MuAngularDistribution.test.cc
  test/celeritas/em/distribution/TsaiUrbanDistribution.test.cc
  test/corecel/CMakeLists.txt
  test/corecel/random/Histogram.hh
  test/corecel/random/HistogramSampler.cc
  test/corecel/random/HistogramSampler.hh
  test/geocel/GenericGeoTestInterface.cc
  test/geocel/GenericGeoTestInterface.hh
  test/testdetail/TestMacrosImpl.hh
Labels: documentation
