Repository celeritas-project/celeritas, pull requests merged in 2025-03, with the labels that each got.

#1646 Increase ccache size for asanlite job
  .github/workflows/build-spack.yml
Labels: documentation, minor

#1643 Update cmake-git-version
  cmake/CgvFindVersion.cmake
Labels: core, minor

#1636 Refactor log handlers for better reuse
  app/celer-g4/LocalLogger.cc
  app/celer-g4/LocalLogger.hh
  src/corecel/CMakeLists.txt
  src/corecel/io/LogHandlers.cc
  src/corecel/io/LogHandlers.hh
  src/corecel/io/Logger.cc
  src/corecel/io/detail/LoggerMessage.cc
Labels: core, minor

#1649 Support sensitive detectors in replica/parameterized volumes
  src/celeritas/ext/detail/LevelTouchableUpdater.cc
  src/celeritas/ext/detail/LevelTouchableUpdater.hh
  src/geocel/GeantGeoUtils.cc
  src/geocel/GeantGeoUtils.hh
  src/geocel/GeoParamsInterface.hh
  src/geocel/detail/MakeLabelVector.hh
  src/geocel/g4/GeantGeoParams.cc
  src/geocel/g4/GeantGeoParams.hh
  src/geocel/g4/GeantGeoTrackView.hh
  src/geocel/vg/VecgeomParams.cc
  src/geocel/vg/VecgeomParams.hh
  src/orange/OrangeParams.hh
  test/celeritas/CMakeLists.txt
  test/celeritas/ext/detail/LevelTouchableUpdater.test.cc
  test/celeritas/ext/detail/NaviTouchableUpdater.test.cc
  test/celeritas/user/ExampleInstanceCalo.cc
  test/celeritas/user/StepCollector.test.cc
  test/geocel/CMakeLists.txt
  test/geocel/CmseGeoTest.hh
  test/geocel/GeantGeoUtils.test.cc
  test/geocel/GenericGeoTestBase.hh
  test/geocel/GenericGeoTestBase.t.hh
  test/geocel/GenericGeoTestInterface.cc
  test/geocel/GenericGeoTestInterface.hh
  test/geocel/GeoTests.cc
  test/geocel/GeoTests.hh
  test/geocel/ReplicaGeoTest.hh
  test/geocel/data/replica.gdml
  test/geocel/g4/GeantGeo.test.cc
  test/geocel/vg/Vecgeom.test.cc
Labels: enhancement, external, geometry

#1642 Add support for elliptical cylinders and elliptical cones in orange and g4org
  src/orange/g4org/SolidConverter.cc
  src/orange/orangeinp/IntersectRegion.cc
  src/orange/orangeinp/IntersectRegion.hh
  src/orange/orangeinp/ObjectIO.json.cc
  src/orange/orangeinp/ObjectIO.json.hh
  test/orange/g4org/SolidConverter.test.cc
  test/orange/orangeinp/IntersectRegion.test.cc
Labels: enhancement, orange

#1655 Hotfix: prevent vecgeom 2.0 in regular builds
  .github/workflows/build-spack.yml
  cmake/CgvFindVersion.cmake
  scripts/docker/interactive/spack.yaml
  scripts/spack.yaml
Labels: documentation

#1653 Support post-step touchable location and step status
  src/accel/SetupOptions.cc
  src/accel/SetupOptions.hh
  src/celeritas/ext/GeantSd.cc
  src/celeritas/ext/GeantSd.hh
  src/celeritas/ext/detail/HitProcessor.cc
  src/celeritas/ext/detail/HitProcessor.hh
  src/celeritas/ext/detail/LevelTouchableUpdater.cc
  src/celeritas/ext/detail/LevelTouchableUpdater.hh
  src/celeritas/ext/detail/NaviTouchableUpdater.cc
  src/celeritas/ext/detail/NaviTouchableUpdater.hh
  src/celeritas/ext/detail/TouchableUpdaterInterface.hh
  src/celeritas/inp/Scoring.hh
  src/celeritas/user/detail/StepGatherExecutor.hh
  src/geocel/GeantGeoUtils.cc
  test/celeritas/ext/GeantSd.test.cc
  test/celeritas/ext/SimpleSensitiveDetector.cc
  test/celeritas/ext/SimpleSensitiveDetector.hh
  test/celeritas/ext/detail/HitProcessor.test.cc
  test/celeritas/ext/detail/LevelTouchableUpdater.test.cc
  test/geocel/GeantGeoUtils.test.cc
Labels: enhancement, external

#1422 Support surface-based VecGeom 2.x navigator
  .github/workflows/build-spack.yml
  scripts/cmake-presets/ci-ubuntu-github.json
  scripts/cmake-presets/wildstyle.json
  src/celeritas/field/FieldDriver.hh
  src/celeritas/field/FieldPropagator.hh
  src/celeritas/field/ZHelixStepper.hh
  src/celeritas/inp/Field.hh
  src/corecel/CMakeLists.txt
  src/corecel/Config.hh.in
  src/geocel/vg/VecgeomData.hh
  src/geocel/vg/VecgeomParams.cc
  src/geocel/vg/VecgeomTrackView.hh
  src/geocel/vg/detail/BVHNavigator.hh
  src/geocel/vg/detail/SurfNavigator.hh
  src/geocel/vg/detail/VecgeomSetup.hh
  src/orange/g4org/SolidConverter.cc
  test/celeritas/CMakeLists.txt
  test/celeritas/em/UrbanMsc.test.cc
  test/celeritas/field/FieldPropagator.test.cc
  test/celeritas/geo/Geometry.test.cc
  test/celeritas/geo/HeuristicGeoData.hh
  test/celeritas/geo/HeuristicGeoExecutor.hh
  test/celeritas/geo/HeuristicGeoTestBase.cc
  test/celeritas/geo/HeuristicGeoTestBase.hh
  test/celeritas/global/StepperGeant.test.cc
  test/celeritas/user/SlotDiagnostic.test.cc
  test/celeritas/user/StepCollector.test.cc
  test/geocel/CMakeLists.txt
  test/geocel/CheckedGeoTrackView.t.hh
  test/geocel/CmseGeoTest.hh
  test/geocel/GeoTests.cc
  test/geocel/UnitUtils.hh
  test/geocel/g4/GeantGeo.test.cc
  test/geocel/vg/Vecgeom.test.cc
Labels: enhancement, external

#1654 Approximate G4Torus using inner/outer bounding cylinders
  src/orange/g4org/SolidConverter.cc
  test/orange/g4org/SolidConverter.test.cc
Labels: enhancement, orange, geometry

#1656 Refactor geometry tests into common file
  src/geocel/g4/GeantGeoTrackView.hh
  test/geocel/CMakeLists.txt
  test/geocel/CmsEeBackDeeGeoTest.cc
  test/geocel/CmsEeBackDeeGeoTest.hh
  test/geocel/CmseGeoTest.hh
  test/geocel/FourLevelsGeoTest.cc
  test/geocel/FourLevelsGeoTest.hh
  test/geocel/GeoTests.cc
  test/geocel/GeoTests.hh
  test/geocel/MultiLevelGeoTest.cc
  test/geocel/MultiLevelGeoTest.hh
  test/geocel/ReplicaGeoTest.hh
  test/geocel/SolidsGeoTest.cc
  test/geocel/SolidsGeoTest.hh
  test/geocel/TransformedBoxGeoTest.cc
  test/geocel/TransformedBoxGeoTest.hh
  test/geocel/ZnenvGeoTest.hh
  test/geocel/g4/GeantGeo.test.cc
  test/geocel/vg/Vecgeom.test.cc
  test/orange/OrangeGeant.test.cc
  test/orange/OrangeGeoTestBase.cc
  test/orange/OrangeGeoTestBase.hh
  test/testdetail/TestMacrosImpl.hh
Labels: minor, geometry

#1659 Support volume-specific uniform field
  app/celer-g4/DetectorConstruction.cc
  doc/implementation/core-physics/propagation.rst
  src/accel/AlongStepFactory.cc
  src/accel/AlongStepFactory.hh
  src/accel/SetupOptions.cc
  src/celeritas/CMakeLists.txt
  src/celeritas/alongstep/AlongStepUniformMscAction.cc
  src/celeritas/alongstep/AlongStepUniformMscAction.cu
  src/celeritas/alongstep/AlongStepUniformMscAction.hh
  src/celeritas/alongstep/detail/FieldFunctors.hh
  src/celeritas/alongstep/detail/UniformFieldPropagatorFactory.hh
  src/celeritas/field/UniformFieldData.hh
  src/celeritas/field/UniformFieldParams.cc
  src/celeritas/field/UniformFieldParams.hh
  src/celeritas/global/TrackExecutor.hh
  src/celeritas/inp/Field.hh
  src/celeritas/optical/action/TrackSlotExecutor.hh
  src/celeritas/setup/Problem.cc
  src/celeritas/track/TrackFunctors.hh
  test/celeritas/CMakeLists.txt
  test/celeritas/global/AlongStep.test.cc
  test/celeritas/global/AlongStepTestBase.cc
  test/celeritas/global/StepperGeant.test.cc
  test/celeritas/optical/OpticalCollector.test.cc
  test/celeritas/user/Diagnostic.test.cc
  test/celeritas/user/StepCollector.test.cc
Labels: enhancement, field

#1661 Fix link errors with CUDA RDC and `--as-needed` flag
  cmake/CudaRdcUtils.cmake
  src/corecel/CMakeLists.txt
Labels: bug, core

#1660 Use CLI11 for front end command line parsing
  CMakeLists.txt
  app/CMakeLists.txt
  app/CliUtils.cc
  app/CliUtils.hh
  app/celer-dump-data.cc
  app/celer-export-geant.cc
  app/celer-g4/GlobalSetup.cc
  app/celer-geo/CMakeLists.txt
  app/celer-geo/celer-geo.cc
  app/celer-sim/CMakeLists.txt
  app/celer-sim/celer-sim.cc
  app/orange-update.cc
  cmake/FindCLI11.cmake
  doc/usage/execution/_usage/celer-dump-data.txt
  doc/usage/execution/_usage/celer-export-geant.txt
  doc/usage/execution/_usage/celer-g4.txt
  doc/usage/execution/_usage/celer-geo.txt
  doc/usage/execution/_usage/celer-sim.txt
  doc/usage/execution/_usage/orange-update.txt
  doc/usage/execution/_usage/regenerate.sh
  doc/usage/execution/applications.rst
  doc/usage/execution/utilities.rst
  doc/usage/installation.rst
  external/CMakeLists.txt
  scripts/cmake-presets/ci-ubuntu-github.json
  scripts/cmake-presets/goldfinger.json
  scripts/docker/dev/rocky-cuda12.yaml
  scripts/docker/dev/ubuntu-rocm6.yaml
  scripts/docker/interactive/spack.yaml
  scripts/spack.yaml
  src/celeritas/ext/RootJsonDumper.cc
  src/celeritas/ext/RootJsonDumper.hh
  src/corecel/Assert.cc
  src/corecel/CMakeLists.txt
  src/corecel/io/FileOrConsole.hh
  src/corecel/io/Repr.hh
  src/corecel/io/detail/ReprImpl.cc
  src/corecel/io/detail/ReprImpl.hh
  src/corecel/sys/MpiCommunicator.hh
  test/celeritas/ext/RootJsonDumper.test.cc
  test/corecel/Assert.test.cc
Labels: minor, app

#1663 Move offload template into a celeritas::example namespace
  example/offload-template/main.cc
  example/offload-template/src/ActionInitialization.cc
  example/offload-template/src/ActionInitialization.hh
  example/offload-template/src/DetectorConstruction.cc
  example/offload-template/src/DetectorConstruction.hh
  example/offload-template/src/MakeCelerOptions.cc
  example/offload-template/src/MakeCelerOptions.hh
  example/offload-template/src/PrimaryGeneratorAction.cc
  example/offload-template/src/PrimaryGeneratorAction.hh
  example/offload-template/src/RunAction.cc
  example/offload-template/src/RunAction.hh
  scripts/dev/celeritas-gen.py
Labels: documentation, minor

#1668 Update frontier toolchain for Feb 2025
  scripts/env/frontier.sh
Labels: minor

#1667 Remove 'default_stream' option
  app/celer-g4/GlobalSetup.cc
  app/celer-g4/RunInput.cc
  app/celer-g4/RunInput.hh
  app/celer-g4/RunInputIO.json.cc
  app/celer-sim/RunnerInput.cc
  app/celer-sim/RunnerInputIO.json.cc
  app/celer-sim/celer-sim.cc
  src/accel/SetupOptions.cc
  src/accel/SetupOptions.hh
  src/accel/SetupOptionsMessenger.cc
  src/accel/SharedParams.cc
  src/celeritas/inp/Control.hh
Labels: core, removal

#1669 Default downstream CUDA/HIP architectures
  .github/workflows/build-spack.yml
  CMakeLists.txt
  cmake/CeleritasConfig.cmake.in
  scripts/ci/test-examples.sh
Labels: enhancement, core

#1664 Add an example user action for gathering statistics on GPU
  .github/workflows/build-docker.yml
  .github/workflows/build-spack.yml
  example/offload-template/CMakeLists.txt
  example/offload-template/README.rst
  example/offload-template/main.cc
  example/offload-template/src/ActionInitialization.cc
  example/offload-template/src/EventAction.cc
  example/offload-template/src/EventAction.hh
  example/offload-template/src/MakeCelerOptions.cc
  example/offload-template/src/PrimaryGeneratorAction.cc
  example/offload-template/src/StepDiagnostic.cc
  example/offload-template/src/StepDiagnostic.cu
  example/offload-template/src/StepDiagnostic.hh
  example/offload-template/src/StepDiagnosticData.hh
  example/offload-template/src/StepDiagnosticExecutor.hh
  src/accel/IntegrationBase.cc
  src/accel/IntegrationBase.hh
  src/accel/LocalTransporter.cc
  src/accel/LocalTransporter.hh
  src/accel/SetupOptions.cc
  src/accel/SetupOptions.hh
  src/accel/SharedParams.cc
  src/accel/SharedParams.hh
  src/accel/TrackingManagerIntegration.cc
  src/celeritas/global/CoreState.hh
  src/celeritas/inp/Diagnostics.hh
  src/celeritas/track/CoreStateCounters.hh
  src/celeritas/user/SlotDiagnostic.cc
  src/celeritas/user/SlotDiagnostic.cu
  src/celeritas/user/SlotDiagnostic.hh
  src/celeritas/user/detail/StepParams.cc
  src/corecel/cont/Span.hh
  src/corecel/data/AuxStateData.hh
  src/corecel/data/CollectionAlgorithms.hh
Labels: documentation, enhancement, external

#1675 Add quantity support to FindInterp and template Turn
  doc/implementation/units-constants.rst
  src/corecel/grid/FindInterp.hh
  src/corecel/math/Quantity.hh
  src/corecel/math/Turn.hh
  src/orange/g4org/SolidConverter.cc
  test/corecel/CMakeLists.txt
  test/corecel/grid/FindInterp.test.cc
  test/corecel/grid/TwodGridCalculator.test.cc
  test/corecel/math/Quantity.test.cc
Labels: enhancement, core

#1676 By default load CudaRdcUtils and print config message
  CMakeLists.txt
  cmake/CeleritasConfig.cmake.in
  doc/example/minimal.rst
  doc/usage/integration.rst
  example/FindCeleritas.cmake
  example/accel/CMakeLists.txt
  example/minimal/CMakeLists.txt
  example/offload-template/CMakeLists.txt
Labels: enhancement, core

#1674 Support VecGeom 2.0
  .github/workflows/build-spack.yml
  CMakeLists.txt
  app/celer-g4/test-harness.py
  cmake/CeleritasConfig.cmake.in
  scripts/ci/spack.yaml
  scripts/cmake-presets/ci-ubuntu-github.json
  scripts/cmake-presets/wildstyle.json
  src/corecel/CMakeLists.txt
  src/corecel/Config.hh.in
  src/corecel/cont/detail/SpanImpl.hh
  src/corecel/io/BuildOutput.cc
  src/geocel/vg/VecgeomData.hh
  src/geocel/vg/VecgeomParams.cc
  src/geocel/vg/VecgeomTrackView.hh
  src/geocel/vg/detail/VecgeomNavCollection.hh
  src/geocel/vg/detail/VecgeomSetup.cu
  src/geocel/vg/detail/VecgeomSetup.hh
  src/geocel/vg/detail/VecgeomVersion.hh
  test/celeritas/em/UrbanMsc.test.cc
Labels: enhancement, external, geometry

#1677 Fix bremsstrahlung process construction when using only a single model
  src/celeritas/em/process/BremsstrahlungProcess.cc
  src/celeritas/em/process/BremsstrahlungProcess.hh
  src/celeritas/phys/ProcessBuilder.cc
  src/celeritas/phys/ProcessBuilder.hh
  src/celeritas/setup/Problem.cc
Labels: bug, physics

#1666 Lazily fetch volumes for UniformAlongStepFactory
  src/accel/AlongStepFactory.cc
  src/accel/AlongStepFactory.hh
  src/accel/SetupOptions.cc
Labels: bug, field

#1644 Remove G4EmExtraPhysics from FtfpBertPhysicsList
  src/celeritas/ext/FtfpBertPhysicsList.cc
Labels: physics, minor

#1673 Define dependency helper targets and reorganize CMakeLists
  .github/workflows/build-docker.yml
  .github/workflows/build-fast.yml
  .github/workflows/build-ultralite.yml
  CMakeLists.txt
  app/CMakeLists.txt
  app/celer-geo/CMakeLists.txt
  app/celer-sim/CMakeLists.txt
  cmake/CeleritasConfig.cmake.in
  cmake/CeleritasLibrary.cmake
  cmake/CeleritasLibraryUtils.cmake
  cmake/external/CudaRdcUtils.cmake
  doc/usage/integration.rst
  external/CMakeLists.txt
  scripts/ci/test-examples.sh
  src/CMakeLists.txt
  src/accel/CMakeLists.txt
  src/celeritas/CMakeLists.txt
  src/corecel/CMakeLists.txt
  src/corecel/sys/Device.cc
  src/geocel/CMakeLists.txt
  test/CMakeLists.txt
  test/celeritas/CMakeLists.txt
  test/geocel/CMakeLists.txt
  test/orange/CMakeLists.txt
Labels: core, minor

#1679 Update CudaRdcUtils to v3
  cmake/external/CudaRdcUtils.cmake
Labels: core, minor

#1678 Add Celeritas cmake command wrappers for downstream code
  CMakeLists.txt
  cmake/CeleritasConfig.cmake.in
  cmake/CeleritasLibrary.cmake
  cmake/CeleritasLibraryUtils.cmake
  cmake/FindCLI11.cmake
  doc/usage/integration.rst
  example/accel/CMakeLists.txt
  example/minimal/CMakeLists.txt
  example/offload-template/CMakeLists.txt
  scripts/cmake-presets/ci-ubuntu-github.json
  src/CMakeLists.txt
  src/corecel/CMakeLists.txt
Labels: enhancement, core

#1680 Fix static builds and CI reporting
  .github/workflows/build-docker.yml
  .github/workflows/build-fast.yml
  .github/workflows/build-spack.yml
  .github/workflows/build-ultralite.yml
  .github/workflows/clear-cache.yml
  .github/workflows/doc.yml
  CMakeLists.txt
  cmake/CeleritasConfig.cmake.in
  cmake/FindPerfetto.cmake
  external/CMakeLists.txt
  scripts/cmake-presets/ci-ubuntu-github.json
  scripts/cmake-presets/ci-windows-github.json
  scripts/cmake-presets/wildstyle.json
  scripts/dev/analyze-cmake-trace.py
  src/CMakeLists.txt
  src/corecel/CMakeLists.txt
  src/corecel/io/BuildOutput.cc
  src/corecel/sys/TracingSession.perfetto.cc
Labels: bug, core

#1682 Enable optical GPU tests
  app/celer-dump-data.cc
  app/celer-export-geant.cc
  app/celer-sim/celer-sim.cc
  doc/usage/execution/_usage/celer-dump-data.txt
  doc/usage/execution/_usage/celer-export-geant.txt
  doc/usage/execution/_usage/celer-sim.txt
  test/celeritas/CMakeLists.txt
  test/celeritas/optical/OpticalCollector.test.cc
  test/celeritas/optical/OpticalUtils.test.cc
Labels: documentation, app

#1687 Update ROOT data and tests with Geant4 version 11.3.0
  .github/workflows/build-spack.yml
  test/celeritas/data/four-steel-slabs.root
  test/celeritas/data/lar-sphere.root
  test/celeritas/data/simple-cms.root
  test/celeritas/em/MuPairProduction.test.cc
  test/celeritas/em/UrbanMsc.test.cc
  test/celeritas/ext/RootJsonDumper.test.cc
  test/celeritas/phys/ProcessBuilder.test.cc
Labels: documentation, physics

#1690 Change default field substeps in accel
  src/accel/SetupOptions.hh
Labels: minor, external

#1686 Make SB energy limit configurable and partially fix failures when using a single brems model
  app/celer-dump-data.cc
  src/celeritas/em/data/RelativisticBremData.hh
  src/celeritas/em/data/SeltzerBergerData.hh
  src/celeritas/em/interactor/CombinedBremInteractor.hh
  src/celeritas/em/interactor/RelativisticBremInteractor.hh
  src/celeritas/em/interactor/SeltzerBergerInteractor.hh
  src/celeritas/em/interactor/detail/PhysicsConstants.hh
  src/celeritas/em/model/CombinedBremModel.cc
  src/celeritas/em/model/RelativisticBremModel.cc
  src/celeritas/em/model/SeltzerBergerModel.cc
  src/celeritas/ext/GeantPhysicsOptions.hh
  src/celeritas/ext/GeantPhysicsOptionsIO.json.cc
  src/celeritas/ext/detail/EmStandardPhysics.cc
  src/celeritas/ext/detail/GeantBremsstrahlungProcess.cc
  src/celeritas/ext/detail/GeantBremsstrahlungProcess.hh
  src/celeritas/ext/detail/GeantModelImporter.cc
  src/celeritas/io/ImportModel.hh
  src/celeritas/phys/ImportedModelAdapter.cc
  src/celeritas/phys/ImportedModelAdapter.hh
  src/celeritas/phys/PhysicsParams.cc
  test/celeritas/data/four-steel-slabs.root
  test/celeritas/data/lar-sphere.root
  test/celeritas/data/simple-cms.root
  test/celeritas/em/CombinedBrem.test.cc
  test/celeritas/em/CoulombScattering.test.cc
  test/celeritas/em/Rayleigh.test.cc
  test/celeritas/em/RelativisticBrem.test.cc
  test/celeritas/em/SeltzerBerger.test.cc
  test/celeritas/ext/GeantImporter.test.cc
  test/celeritas/ext/RootJsonDumper.test.cc
  test/celeritas/phys/InteractorHostTestBase.cc
  test/celeritas/phys/InteractorHostTestBase.hh
Labels: bug, enhancement, physics

#1693 Add timers to accel integration classes
  app/celer-g4/CMakeLists.txt
  app/celer-g4/EventAction.cc
  app/celer-g4/GeantDiagnostics.cc
  app/celer-g4/GeantDiagnostics.hh
  app/celer-g4/RunAction.cc
  src/accel/CMakeLists.txt
  src/accel/FastSimulationIntegration.cc
  src/accel/IntegrationBase.cc
  src/accel/SharedParams.cc
  src/accel/SharedParams.hh
  src/accel/TimeOutput.cc
  src/accel/TimeOutput.hh
  src/accel/TrackingManagerIntegration.cc
  src/accel/UserActionIntegration.cc
  src/accel/UserActionIntegration.hh
  src/accel/detail/IntegrationSingleton.cc
  src/accel/detail/IntegrationSingleton.hh
Labels: enhancement, external

#1691 Remove deprecations for v0.6
  app/celer-g4/GlobalSetup.cc
  app/celer-g4/GlobalSetup.hh
  app/celer-g4/RunInputIO.json.cc
  cmake/CeleritasConfig.cmake.in
  src/accel/SetupOptions.hh
  src/accel/SharedParams.cc
  src/celeritas/global/ActionInterface.hh
  src/corecel/cont/LabelIdMultiMap.hh
  src/corecel/io/LoggerTypes.hh
  src/geocel/GeoParamsInterface.hh
  src/orange/OrangeParams.hh
Labels: removal

#1689 Fix out-of-bounds memory access in `CylMapField`
  src/celeritas/field/CylMapField.hh
  src/celeritas/field/CylMapFieldParams.cc
  test/corecel/math/Algorithms.test.cc
Labels: bug, field

#1684 Use float for field interpolation
  src/accel/CylMapMagneticField.cc
  src/accel/CylMapMagneticField.hh
  src/celeritas/field/CylMapField.hh
  src/celeritas/field/CylMapFieldData.hh
  src/celeritas/field/CylMapFieldInput.hh
  src/celeritas/field/CylMapFieldParams.cc
  src/celeritas/field/CylMapFieldParams.hh
  test/celeritas/field/Fields.test.cc
Labels: enhancement, field

#1696 CUDA RDC: Improve handling of object library and CUDA_RUNTIME_LIBRARY
  cmake/external/CudaRdcUtils.cmake
Labels: enhancement, core

#1697 Allow some "required" SetupOptions to be set via Geant4 UI
  example/offload-template/CMakeLists.txt
  example/offload-template/run-offload.cc
  example/offload-template/run.mac
  example/offload-template/src/MakeCelerOptions.cc
  src/accel/SetupOptionsMessenger.cc
  src/accel/SetupOptionsMessenger.hh
  src/accel/detail/IntegrationSingleton.cc
Labels: enhancement, external

#1699 CUDA RDC: fix static builds
  cmake/external/CudaRdcUtils.cmake
  src/geocel/GeantGeoUtils.hh
Labels: core, minor

#1700 Update and fix G4VG external integration
  external/CMakeLists.txt
  src/corecel/CMakeLists.txt
  src/corecel/io/BuildOutput.cc
Labels: minor, external

#1698 Split EM physics and Geant4 interface into sub-files
  doc/implementation/core-physics.rst
  doc/implementation/core-physics/limits.rst
  doc/implementation/core-physics/propagation.rst
  doc/implementation/em-physics.rst
  doc/implementation/em-physics/annihilation.rst
  doc/implementation/em-physics/brems.rst
  doc/implementation/em-physics/coulomb.rst
  doc/implementation/em-physics/ionization.rst
  doc/implementation/em-physics/pair-production.rst
  doc/implementation/em-physics/photon-interaction.rst
  doc/implementation/em-physics/slowing-down.rst
  doc/implementation/geant4-interface.rst
  doc/implementation/geant4-interface/details.rst
  doc/implementation/geant4-interface/high-level.rst
  doc/implementation/geant4-interface/low-level.rst
  doc/implementation/geant4-interface/setup.rst
Labels: documentation, minor

#1701 Improve doc generation and brems-related documentation
  CMakeLists.txt
  doc/CMakeLists.txt
  doc/_static/macros.tex
  doc/_static/zotero.bib
  doc/conf.py
  doc/implementation/em-physics/brems.rst
  scripts/release/orcid.json
  src/celeritas/em/interactor/BetheHeitlerInteractor.hh
  src/celeritas/em/interactor/detail/RBEnergySampler.hh
  src/celeritas/em/msc/detail/MscStepFromGeo.hh
  src/celeritas/em/msc/detail/UrbanMscMinimalStepLimit.hh
  src/celeritas/em/msc/detail/UrbanMscSafetyStepLimit.hh
  src/celeritas/em/msc/detail/UrbanMscScatter.hh
  src/celeritas/em/xs/LPMCalculator.hh
  src/celeritas/em/xs/RBDiffXsCalculator.hh
  src/corecel/Constants.hh
  test/corecel/math/NumericLimits.test.cu
Labels: documentation

#1706 Release v0.5.2
  doc/appendix/release-history/v0.1.rst
  doc/appendix/release-history/v0.2.rst
  doc/appendix/release-history/v0.3.rst
  doc/appendix/release-history/v0.5.rst
  scripts/env/frontier.sh
Labels: documentation
