Repository celeritas-project/celeritas, pull requests merged in 2025-09, with the labels that each got.

#1918 Modularize and expose physics lists and PG generator
  app/celer-g4/ActionInitialization.cc
  app/celer-g4/CMakeLists.txt
  doc/CMakeLists.txt
  doc/implementation/core-physics/problem-def.rst
  doc/implementation/geant4-interface/details.rst
  doc/implementation/geant4-interface/low-level.rst
  src/accel/CMakeLists.txt
  src/accel/PGPrimaryGeneratorAction.cc
  src/accel/PGPrimaryGeneratorAction.hh
  src/celeritas/CMakeLists.txt
  src/celeritas/ext/EmPhysicsList.cc
  src/celeritas/ext/EmPhysicsList.hh
  src/celeritas/ext/FtfpBertPhysicsList.cc
  src/celeritas/ext/GeantPhysicsOptions.hh
  src/celeritas/ext/detail/EmStandardPhysics.cc
  src/celeritas/ext/detail/EmStandardPhysics.hh
  src/celeritas/ext/detail/MuHadEmStandardPhysics.cc
  src/celeritas/ext/detail/MuHadEmStandardPhysics.hh
  src/celeritas/g4/SupportedEmStandardPhysics.cc
  src/celeritas/g4/SupportedEmStandardPhysics.hh
  src/celeritas/g4/SupportedOpticalPhysics.cc
  src/celeritas/g4/SupportedOpticalPhysics.hh
  src/celeritas/g4/detail/GeantBremsstrahlungProcess.cc
  src/celeritas/g4/detail/GeantBremsstrahlungProcess.hh
  src/celeritas/inp/Events.hh
  src/celeritas/optical/gen/PrimaryGeneratorAction.cc
  src/celeritas/phys/PrimaryGenerator.cc
  src/celeritas/phys/PrimaryGeneratorOptions.cc
  test/celeritas/optical/PrimaryGenerator.test.cc
  test/celeritas/phys/PrimaryGenerator.test.cc
Labels: minor, external

#1924 Refactor Geant4 launching macros into a reusable script
  CMakeLists.txt
  app/CMakeLists.txt
  cmake/CeleritasG4Tests.cmake
  cmake/CeleritasUtils.cmake
  example/geant4/CMakeLists.txt
  test/CMakeLists.txt
Labels: documentation, external

#1912 Fix volume instance IDs for background volumes in ORANGE
  src/orange/OrangeInput.hh
  src/orange/OrangeInputIO.json.cc
  src/orange/OrangeInputIO.json.hh
  src/orange/OrangeTrackView.hh
  src/orange/detail/UnitInserter.cc
  src/orange/detail/UniverseInserter.cc
  src/orange/detail/UniverseInserter.hh
  src/orange/g4org/Converter.cc
  src/orange/g4org/ProtoConstructor.cc
  src/orange/g4org/ProtoConstructor.hh
  src/orange/g4org/Volume.hh
  src/orange/orangeinp/InputBuilder.hh
  src/orange/orangeinp/UnitProto.cc
  src/orange/orangeinp/UnitProto.hh
  test/geocel/GenericGeoTestBase.t.hh
  test/geocel/GeoTests.cc
  test/geocel/g4/GeantGeo.test.cc
  test/orange/OrangeGeant.test.cc
  test/orange/OrangeJson.test.cc
  test/orange/data/inputbuilder-bgspheres.org.json
  test/orange/data/inputbuilder-globalspheres.org.json
  test/orange/data/inputbuilder-hierarchy.org.json
  test/orange/data/inputbuilder-incomplete-bb.org.json
  test/orange/data/inputbuilder-involute-cw.org.json
  test/orange/data/inputbuilder-involute-fuel.org.json
  test/orange/data/inputbuilder-involute.org.json
  test/orange/data/inputbuilder-universe-union-boundary.org.json
  test/orange/data/inputbuilder-universes.org.json
  test/orange/g4org/Converter.test.cc
  test/orange/g4org/ProtoConstructor.test.cc
  test/orange/orangeinp/UnitProto.test.cc
Labels: bug, orange

#1935 IWYU on some files
  src/celeritas/inp/Events.hh
  src/celeritas/optical/detail/OpticalLaunchAction.hh
  src/celeritas/phys/PrimaryGeneratorOptions.hh
  src/corecel/data/AuxParamsRegistry.hh
  src/orange/orangeinp/IntersectRegion.hh
Labels: core, minor

#1938 Allow multiple "activate device" calls if not modifying device
  src/corecel/sys/Device.cc
  test/accel/CMakeLists.txt
Labels: enhancement, core

#1937 Use environment variable values if set
  doc/usage/execution/environment.rst
  src/accel/ExceptionConverter.cc
  src/accel/SharedParams.cc
  src/corecel/sys/Device.cc
  src/corecel/sys/KernelRegistry.cc
Labels: enhancement, core

#1936 Fix edge case where imported lambda and lambda prime tables have overlapping range
  src/celeritas/ext/detail/GeantProcessImporter.cc
  src/celeritas/phys/ImportedProcessAdapter.cc
  test/accel/IntegrationTestBase.cc
Labels: bug, external

#1939 Use double-precision energy for input energy distributions
  src/celeritas/inp/Events.hh
  src/celeritas/phys/PrimaryGeneratorOptions.cc
  src/corecel/math/Quantity.hh
  test/accel/IntegrationTestBase.cc
  test/corecel/math/Quantity.test.cc
Labels: minor, app

#1940 Fix weight reconstruction for GeantSd
  src/celeritas/ext/GeantSd.cc
  test/accel/IntegrationTestBase.cc
Labels: bug, user

#1934 Implement Geant4 geometry normals and refactor/add tests
  doc/implementation/geometry/geant4.rst
  doc/implementation/geometry/interfaces.rst
  doc/implementation/geometry/orange.rst
  doc/implementation/geometry/vecgeom.rst
  src/geocel/g4/GeantGeoTrackView.hh
  src/geocel/vg/VecgeomParams.cc
  test/geocel/GenericGeoResults.cc
  test/geocel/GenericGeoResults.hh
  test/geocel/GenericGeoTestBase.hh
  test/geocel/GenericGeoTestBase.t.hh
  test/geocel/GenericGeoTestInterface.cc
  test/geocel/GenericGeoTestInterface.hh
  test/geocel/GeoTests.cc
  test/geocel/GeoTests.hh
  test/geocel/g4/GeantGeo.test.cc
  test/geocel/vg/Vecgeom.test.cc
  test/geocel/vg/VecgeomTestBase.hh
  test/orange/OrangeGeant.test.cc
  test/orange/OrangeJson.test.cc
Labels: enhancement, geometry

#1943 Use JSON reference for CSG tree
  scripts/dev/update-reference-json.py
  test/orange/orangeinp/CsgTreeUtils.test.cc
  test/testdetail/TestMacrosImpl.cc
Labels: documentation, orange

#1942 Fix ORANGE surface normal calculation on boundary of daughter universes
  src/orange/OrangeTrackView.hh
  test/geocel/GeoTests.cc
  test/orange/OrangeGeant.test.cc
  test/orange/OrangeJson.test.cc
Labels: bug, orange

#1949 Create placeholder SDs when loading GeantGeoParams from GDML
  src/geocel/CMakeLists.txt
  src/geocel/GeantGeoParams.cc
  src/geocel/GeantGeoParams.hh
  test/geocel/g4/GeantGeo.test.cc
Labels: enhancement, geometry

#1922 Add surface normal state to optical surface physics
  src/celeritas/optical/surface/SurfacePhysicsData.hh
  src/celeritas/optical/surface/SurfacePhysicsUtils.hh
  src/celeritas/optical/surface/SurfacePhysicsView.hh
  src/celeritas/optical/surface/detail/InitBoundaryExecutor.hh
  src/celeritas/phys/SurfacePhysicsMapView.hh
  src/geocel/vg/VecgeomTrackView.hh
  test/celeritas/CMakeLists.txt
  test/celeritas/optical/SurfacePhysics.test.cc
Labels: enhancement, physics

#1948 Add shell detectors around lAr sphere test problem
  test/accel/IntegrationTestBase.cc
  test/celeritas/CMakeLists.txt
  test/celeritas/data/lar-sphere.geant.json
  test/celeritas/data/lar-sphere.root
  test/celeritas/ext/GeantImporter.test.cc
  test/celeritas/optical/OpticalRootImport.test.cc
  test/geocel/GeoTests.cc
  test/geocel/GeoTests.hh
  test/geocel/data/lar-sphere.gdml
  test/geocel/g4/GeantGeo.test.cc
  test/geocel/vg/Vecgeom.test.cc
  test/orange/OrangeGeant.test.cc
  test/orange/g4org/Converter.test.cc
  test/orange/g4org/ProtoConstructor.test.cc
Labels: documentation, geometry

#1959 Fix data selection in `SetupOptions` -> `FrameworkInput` conversion
  src/accel/SetupOptions.cc
Labels: bug, user

#1960 Release v0.6.1
  doc/release-history/v0.6.rst
  doc/usage/execution/profiling.rst
  src/celeritas/em/data/UrbanMscData.hh
  src/celeritas/phys/GeneratorRegistry.hh
  src/corecel/random/distribution/NormalDistribution.hh
  src/geocel/detail/MakeLabelVector.hh
  test/geocel/Volume.test.cc
Labels: documentation

#1963 Skip wavelength shift model without data during optical model import
  scripts/release/users.json
  src/celeritas/optical/ModelImporter.cc
  src/celeritas/optical/PhysicsParams.cc
Labels: enhancement, physics

#1969 Work around another spurious -Wmaybe-uninitialized warning with GCC
  src/orange/g4org/ProtoConstructor.cc
Labels: minor, orange

#1971 Warn user when running large problems on debug build
  src/accel/LocalTransporter.cc
  src/accel/LocalTransporter.hh
  src/celeritas/optical/CoreState.hh
  src/celeritas/optical/OpticalCollector.cc
  src/celeritas/optical/OpticalCollector.hh
Labels: enhancement, external

#1966 Add documentation and use flag for CELER_USE_PROFILING
  doc/implementation/corecel.rst
  doc/usage/execution/profiling.rst
  example/offload-template/README.rst
  example/offload-template/src/EventAction.cc
  example/offload-template/src/EventAction.hh
  src/corecel/sys/Environment.cc
  src/corecel/sys/Environment.hh
  src/corecel/sys/ScopedProfiling.cc
  src/corecel/sys/ScopedProfiling.hh
  src/corecel/sys/TracingSession.hh
  src/corecel/sys/TracingSession.perfetto.cc
  src/corecel/sys/detail/NvtxUtils.cc
  test/Test.hh
  test/accel/IntegrationTestBase.cc
  test/accel/IntegrationTestBase.hh
  test/corecel/sys/Environment.test.cc
  test/testdetail/TestMainImpl.cc
Labels: documentation, core

#1973 Fix a few testing issues
  test/accel/CMakeLists.txt
  test/celeritas/optical/OpticalCollector.test.cc
  test/orange/OrangeJson.test.cc
Labels: documentation

#1979 Fix cache clearing
  .github/workflows/clear-cache.yml
Labels: documentation, minor

#1985 Remove `weight` field from `Secondary`
  src/celeritas/phys/InteractionApplier.hh
  src/celeritas/phys/Secondary.hh
Labels: core, minor

#1986 Add `CELER_` prefix to G4 material property names specific to Celeritas
  app/data/lar-sphere.gdml
  doc/implementation/geometry/geant4.rst
  doc/implementation/optical-physics.rst
  src/celeritas/ext/GeantImporter.cc
  test/celeritas/ext/GeantImporter.test.cc
  test/geocel/data/lar-sphere.gdml
Labels: physics, minor

#1987 Support G4MultiUnion in ORANGE
  src/orange/g4org/SolidConverter.cc
  src/orange/g4org/SolidConverter.hh
  test/orange/g4org/SolidConverter.test.cc
Labels: enhancement, orange

#1989 Fix setting CUDA heapSize through G4UI
  src/celeritas/setup/System.cc
Labels: bug, minor

#1992 Update CMake requirements
  CMakeLists.txt
  cmake/CeleritasConfig.cmake.in
  cmake/CgvFindVersion.cmake
  example/geant4/CMakeLists.txt
  example/minimal/CMakeLists.txt
  example/offload-template/CMakeLists.txt
  scripts/ci/test-examples.sh
  scripts/cmake-presets/goldfinger.json
  scripts/spack.yaml
Labels: core, minor

#1994 Split corecel docs into multiple pages
  doc/implementation/corecel.rst
  doc/implementation/corecel/fundamentals.rst
  doc/implementation/corecel/numerics.rst
  doc/implementation/corecel/stdlib.rst
  doc/implementation/corecel/system.rst
  src/corecel/math/BisectionRootFinder.hh
  src/corecel/math/IllinoisRootFinder.hh
  src/corecel/math/RegulaFalsiRootFinder.hh
  src/corecel/math/TridiagonalSolver.hh
Labels: documentation, minor

#1996 Move loading of celer-g4 setup options to after run manager construction
  app/celer-g4/celer-g4.cc
Labels: bug, app
