Repository celeritas-project/celeritas, pull requests merged in 2025-02, with the labels that each got.

#1599 Use BIH to accelerate background_intersect
  src/orange/BoundingBoxUtils.hh
  src/orange/detail/BIHBuilder.cc
  src/orange/detail/BIHBuilder.hh
  src/orange/detail/BIHIntersectingVolFinder.hh
  src/orange/detail/UnitInserter.cc
  src/orange/univ/SimpleUnitTracker.hh
  src/orange/univ/detail/SurfaceFunctors.hh
  test/orange/OrangeJson.test.cc
  test/orange/detail/BIHBuilder.test.cc
  test/orange/detail/BIHEnclosingVolFinder.test.cc
  test/orange/detail/BIHIntersectingVolFinder.test.cc
Labels: enhancement, orange

#1608 Update perfetto to v49.0
  external/CMakeLists.txt
  src/corecel/sys/TraceCounter.perfetto.cc
Labels: core, minor

#1605 Use external G4VG
  .github/workflows/build-spack.yml
  CMakeLists.txt
  cmake/CeleritasLibraryUtils.cmake
  cmake/CgvFindVersion.cmake
  cmake/FindG4VG.cmake
  doc/implementation/geant4-interface.rst
  external/CMakeLists.txt
  scripts/ci/spack.yaml
  scripts/docker/dev/rocky-cuda12.yaml
  scripts/docker/interactive/spack.yaml
  scripts/spack.yaml
  src/geocel/CMakeLists.txt
  src/geocel/g4vg/Converter.cc
  src/geocel/g4vg/Converter.hh
  src/geocel/g4vg/LogicalVolumeConverter.cc
  src/geocel/g4vg/LogicalVolumeConverter.hh
  src/geocel/g4vg/Scaler.hh
  src/geocel/g4vg/SolidConverter.cc
  src/geocel/g4vg/SolidConverter.hh
  src/geocel/g4vg/Transformer.hh
  src/geocel/vg/VecgeomParams.cc
Labels: minor, external

#1606 Add TrackingManagerConstructor and SharedParams::GetMode
  CMakeLists.txt
  app/celer-g4/CMakeLists.txt
  app/celer-g4/EventAction.cc
  app/celer-g4/ExceptionHandler.cc
  app/celer-g4/ExceptionHandler.hh
  app/celer-g4/GeantDiagnostics.cc
  app/celer-g4/RunAction.cc
  app/celer-g4/RunInput.cc
  app/celer-g4/TrackingAction.cc
  app/celer-g4/celer-g4.cc
  example/accel/CMakeLists.txt
  example/accel/fastsim-offload.cc
  example/accel/simple-offload.cc
  example/accel/trackingmanager-offload.cc
  example/offload-template/main.cc
  example/offload-template/src/ActionInitialization.cc
  example/offload-template/src/EventAction.cc
  example/offload-template/src/RunAction.cc
  src/accel/CMakeLists.txt
  src/accel/LocalTransporter.cc
  src/accel/LocalTransporter.hh
  src/accel/Logger.hh
  src/accel/SharedParams.cc
  src/accel/SharedParams.hh
  src/accel/SimpleOffload.cc
  src/accel/SimpleOffload.hh
  src/accel/TrackingManager.cc
  src/accel/TrackingManagerConstructor.cc
  src/accel/TrackingManagerConstructor.hh
Labels: minor, external

#1610 Move `PolyEvaluator` to corecel/math
  src/celeritas/em/interactor/BetheHeitlerInteractor.hh
  src/celeritas/em/interactor/LivermorePEInteractor.hh
  src/celeritas/em/msc/detail/UrbanMscSafetyStepLimit.hh
  src/celeritas/em/msc/detail/UrbanMscScatter.hh
  src/celeritas/em/params/UrbanMscParams.cc
  src/celeritas/em/xs/EPlusGGMacroXsCalculator.hh
  src/celeritas/em/xs/LPMCalculator.hh
  src/celeritas/em/xs/LivermorePEMicroXsCalculator.hh
  src/celeritas/em/xs/MottRatioCalculator.hh
  src/celeritas/neutron/xs/NucleonNucleonXsCalculator.hh
  src/corecel/math/PolyEvaluator.hh
  test/celeritas/CMakeLists.txt
  test/corecel/CMakeLists.txt
  test/corecel/math/PolyEvaluator.test.cc
Labels: physics, minor

#1611 Add JLSE CMake preset and a few small fixes
  README.md
  scripts/build.sh
  scripts/cmake-presets/jlse.json
  src/celeritas/random/distribution/NormalDistribution.hh
  src/corecel/io/Label.hh
  test/celeritas/random/distribution/NormalDistribution.test.cc
Labels: documentation, minor

#1612 Fix multiple `release()` calls to ensure nullptr is not used in process construction
  src/celeritas/ext/detail/OpticalPhysics.cc
Labels: bug, external

#1607 Implement cubic spline interpolation
  doc/_static/zotero.bib
  src/celeritas/CMakeLists.txt
  src/celeritas/grid/SplineDerivCalculator.cc
  src/celeritas/grid/SplineDerivCalculator.hh
  src/celeritas/grid/XsCalculator.hh
  src/celeritas/grid/XsGridData.hh
  src/celeritas/grid/detail/GridAccessor.hh
  src/corecel/CMakeLists.txt
  src/corecel/grid/SplineInterpolator.hh
  src/corecel/math/TridiagonalSolver.cc
  src/corecel/math/TridiagonalSolver.hh
  test/celeritas/CMakeLists.txt
  test/celeritas/grid/CalculatorTestBase.cc
  test/celeritas/grid/CalculatorTestBase.hh
  test/celeritas/grid/SplineDerivCalculator.test.cc
  test/celeritas/grid/XsCalculator.test.cc
  test/corecel/CMakeLists.txt
  test/corecel/grid/SplineInterpolator.test.cc
  test/corecel/math/TridiagonalSolver.test.cc
Labels: enhancement, physics

#1621 Rename `EXTERNAL` CMake variable
  CMakeLists.txt
  cmake/CeleritasOptionUtils.cmake
  external/CMakeLists.txt
  scripts/cmake-presets/goldfinger.json
  src/geocel/vg/VecgeomParams.cc
Labels: core, minor

#1614 Add safety visualization tool
  app/celer-geo/celer-geo.cc
  src/geocel/CMakeLists.txt
  src/geocel/g4/SafetyImager.cc
  src/geocel/rasterize/ImageData.hh
  src/geocel/rasterize/SafetyImager.hh
  src/geocel/rasterize/SafetyImager.t.hh
  src/geocel/rasterize/detail/SafetyCalculator.hh
  src/geocel/vg/SafetyImager.cc
  src/orange/CMakeLists.txt
  src/orange/SafetyImager.cc
  test/geocel/CMakeLists.txt
  test/geocel/data/pincell.gdml
  test/geocel/g4/GeantGeo.test.cc
  test/geocel/vg/Vecgeom.test.cc
  test/orange/CMakeLists.txt
  test/orange/OrangeGeant.test.cc
Labels: enhancement, geometry

#1625 Support spline interpolation on a nonuniform grid
  src/celeritas/grid/NonuniformGridBuilder.cc
  src/celeritas/grid/NonuniformGridBuilder.hh
  src/celeritas/grid/NonuniformGridCalculator.hh
  src/corecel/grid/NonuniformGridData.hh
  test/celeritas/grid/NonuniformGridCalculator.test.cc
Labels: enhancement, physics

#1627 Fix crash in multithreaded celer-g4
  app/celer-g4/DetectorConstruction.cc
  app/celer-g4/PGPrimaryGeneratorAction.cc
  app/celer-g4/PGPrimaryGeneratorAction.hh
  src/celeritas/phys/PrimaryGenerator.cc
  src/celeritas/phys/PrimaryGenerator.hh
  src/celeritas/phys/PrimaryGeneratorOptions.cc
  src/orange/detail/OrangeInputIOImpl.json.cc
Labels: bug, app

#1626 Fix loading of GDML files with reflection
  app/celer-g4/DetectorConstruction.cc
  app/celer-g4/DetectorConstruction.hh
  doc/implementation/geant4-interface.rst
  src/accel/SharedParams.cc
  src/celeritas/ext/GeantSetup.cc
  src/geocel/CMakeLists.txt
  src/geocel/GeantGdmlLoader.cc
  src/geocel/GeantGdmlLoader.hh
  src/geocel/GeantGeoUtils.cc
  src/geocel/GeantGeoUtils.hh
  src/geocel/ScopedGeantLogger.cc
  src/geocel/g4/GeantGeoParams.cc
  src/orange/OrangeParams.cc
  test/accel/detail/LevelTouchableUpdater.test.cc
  test/geocel/CMakeLists.txt
  test/geocel/GeantGdmlLoader.test.cc
  test/geocel/GeantGeoUtils.test.cc
  test/geocel/data/cms-ee-back-dee.gdml
  test/geocel/data/four-levels.gdml
  test/geocel/data/solids.gdml
  test/geocel/vg/Vecgeom.test.cc
  test/orange/CMakeLists.txt
  test/orange/g4org/Converter.test.cc
  test/orange/g4org/GeantLoadTestBase.cc
  test/orange/g4org/GeantLoadTestBase.hh
  test/orange/g4org/PhysicalVolumeConverter.test.cc
  test/orange/g4org/ProtoConstructor.test.cc
Labels: bug, external

#1623 Add generic geometry test interface to reduce duplication
  src/corecel/io/Label.cc
  src/corecel/io/Label.hh
  src/corecel/io/Repr.hh
  src/geocel/GeoTraits.hh
  src/geocel/g4/GeantGeoParams.hh
  src/geocel/g4/GeantGeoTrackView.hh
  src/geocel/g4/GeantGeoTraits.hh
  src/geocel/vg/VecgeomGeoTraits.hh
  src/geocel/vg/VecgeomParams.cc
  src/orange/OrangeGeoTraits.hh
  test/geocel/CMakeLists.txt
  test/geocel/CmseGeoTest.hh
  test/geocel/FourLevelsGeoTest.cc
  test/geocel/FourLevelsGeoTest.hh
  test/geocel/GeantImportVolumeResult.cc
  test/geocel/GeantImportVolumeResult.hh
  test/geocel/GenericGeoParameterizedTest.hh
  test/geocel/GenericGeoTestBase.hh
  test/geocel/GenericGeoTestBase.t.hh
  test/geocel/GenericGeoTestInterface.cc
  test/geocel/GenericGeoTestInterface.hh
  test/geocel/MultiLevelGeoTest.cc
  test/geocel/MultiLevelGeoTest.hh
  test/geocel/SolidsGeoTest.cc
  test/geocel/SolidsGeoTest.hh
  test/geocel/TransformedBoxGeoTest.cc
  test/geocel/TransformedBoxGeoTest.hh
  test/geocel/ZnenvGeoTest.hh
  test/geocel/g4/GeantGeo.test.cc
  test/geocel/g4/GeantGeoTestBase.hh
  test/geocel/g4/VisitVolumes.test.cc
  test/geocel/vg/Vecgeom.test.cc
  test/orange/OrangeGeant.test.cc
  test/orange/OrangeGeoTestBase.cc
  test/orange/OrangeGeoTestBase.hh
Labels: documentation, geometry

#1628 Bump VecGeom minimum version to 1.2.10
  CMakeLists.txt
  scripts/docker/dev/rocky-cuda12.yaml
  scripts/docker/interactive/spack.yaml
  scripts/spack.yaml
Labels: bug, external

#1630 Flush perfetto TrackEvents
  app/celer-sim/celer-sim.cc
  scripts/docker/interactive/CMakeUserPresets.json
  scripts/docker/interactive/Dockerfile
  scripts/docker/interactive/spack.yaml
  src/corecel/sys/TracingSession.cc
  src/corecel/sys/TracingSession.hh
Labels: core, minor

#1631 Move Geant4 SD integration into celeritas/ext
  doc/implementation/geant4-interface.rst
  doc/usage/input/scoring.rst
  src/accel/CMakeLists.txt
  src/accel/LocalTransporter.cc
  src/accel/SetupOptions.cc
  src/accel/SetupOptions.hh
  src/accel/SharedParams.cc
  src/accel/SharedParams.hh
  src/celeritas/CMakeLists.txt
  src/celeritas/ext/GeantSd.cc
  src/celeritas/ext/GeantSd.hh
  src/celeritas/ext/GeantSdOutput.cc
  src/celeritas/ext/GeantSdOutput.hh
  src/celeritas/ext/detail/HitProcessor.cc
  src/celeritas/ext/detail/HitProcessor.hh
  src/celeritas/ext/detail/LevelTouchableUpdater.cc
  src/celeritas/ext/detail/LevelTouchableUpdater.hh
  src/celeritas/ext/detail/NaviTouchableUpdater.cc
  src/celeritas/ext/detail/NaviTouchableUpdater.hh
  src/celeritas/ext/detail/SensDetInserter.cc
  src/celeritas/ext/detail/SensDetInserter.hh
  src/celeritas/ext/detail/TouchableUpdaterInterface.cc
  src/celeritas/ext/detail/TouchableUpdaterInterface.hh
  src/celeritas/inp/Scoring.hh
  test/accel/CMakeLists.txt
  test/celeritas/CMakeLists.txt
  test/celeritas/ext/GeantSd.test.cc
  test/celeritas/ext/SDTestBase.cc
  test/celeritas/ext/SDTestBase.hh
  test/celeritas/ext/SimpleSensitiveDetector.cc
  test/celeritas/ext/SimpleSensitiveDetector.hh
  test/celeritas/ext/detail/HitProcessor.test.cc
  test/celeritas/ext/detail/LevelTouchableUpdater.test.cc
  test/celeritas/ext/detail/NaviTouchableUpdater.test.cc
Labels: minor, external

#1634 Add perfetto track counters to accel LocalTransporter
  src/accel/LocalTransporter.cc
  src/corecel/sys/TraceCounter.perfetto.cc
  src/corecel/sys/TracingSession.cc
  src/corecel/sys/TracingSession.hh
Labels: core, minor

#1635 Fix reading and writing HepMC3 events
  src/accel/HepMC3PrimaryGenerator.cc
  src/celeritas/io/EventReader.cc
  src/celeritas/io/EventWriter.cc
  test/accel/HepMC3PrimaryGenerator.test.cc
  test/celeritas/data/event-novtx.hepmc3
  test/celeritas/io/EventIO.test.cc
  test/celeritas/io/EventIOTestBase.cc
Labels: bug, external

#1639 Improve testing and documentation for VecGeom
  .github/workflows/build-spack.yml
  app/celer-geo/CMakeLists.txt
  doc/_static/zotero.bib
  src/celeritas/field/DormandPrinceStepper.hh
  src/celeritas/track/detail/StatusCheckExecutor.hh
  src/celeritas/user/detail/StepGatherExecutor.hh
  src/geocel/CMakeLists.txt
  test/accel/HepMC3PrimaryGenerator.test.cc
  test/geocel/CMakeLists.txt
  test/geocel/CmsEeBackDeeGeoTest.cc
  test/geocel/CmseGeoTest.hh
  test/geocel/FourLevelsGeoTest.cc
  test/geocel/GenericGeoTestInterface.cc
  test/geocel/GenericGeoTestInterface.hh
  test/geocel/MultiLevelGeoTest.cc
  test/geocel/TransformedBoxGeoTest.cc
  test/geocel/vg/Vecgeom.test.cc
Labels: documentation, core

#1638 Add support for Z cuts when converting G4Solids
  src/orange/g4org/SolidConverter.cc
  src/orange/orangeinp/IntersectRegion.cc
  src/orange/orangeinp/IntersectRegion.hh
  src/orange/orangeinp/ObjectIO.json.cc
  src/orange/orangeinp/ObjectIO.json.hh
  src/orange/orangeinp/Solid.cc
  src/orange/orangeinp/Solid.hh
  test/orange/g4org/SolidConverter.test.cc
  test/orange/orangeinp/IntersectRegion.test.cc
  test/orange/orangeinp/Solid.test.cc
Labels: enhancement, external, orange, geometry

#1641 Update externals and enforce G4VG version
  .github/workflows/build-spack.yml
  CMakeLists.txt
  cmake/CgvFindVersion.cmake
  external/CMakeLists.txt
  scripts/cmake-presets/ci-windows-github.json
Labels: minor, external

#1645 Add ORCID to citation
  CITATION.cff
Labels: documentation
